### ISSUE TITLE
客户端调用bert_serving服务遇到 IndexError: list index out of range错误

### ISSUE THREAD

**Issue by bigpo** [PaddlePaddle/PaddleFormers#1023]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
> 服务端：paddlehub Version: 1.8.3,  paddlepaddle-gpu Version: 1.8.5.post107
> 客户端：paddlehub Version: 1.8.3 ,  paddlepaddle Version: 1.8.5

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> 服务端：docker镜像 hub.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7， python=3.7
> 客服端：ubuntu18.04， python=3.7

- 复现信息：如为报错，请给出复现环境、复现步骤

在docker容器内运行demo不会报错，在客户端运行demo则报错
运行脚本如下：
```python
import numpy as np
from paddlehub.serving.bert_serving import bs_client
bc = bs_client.BSClient(module_name="ernie_tiny", server="localhost:8867") #端口已做映射
input_text = [["西"], ["白发多"], ["醉后"], ["星河"]]

result = bc.get_result(input_text=input_text)
res = np.array(result)
print(res.shape)
```

错误信息如下：
```bash
[2020-11-17 15:06:00,331] [    INFO] - Installing ernie_tiny module
[2020-11-17 15:06:00,332] [    INFO] - Module ernie_tiny already installed in /home/xxx/.paddlehub/modules/ernie_tiny
[2020-11-17 15:06:01,628] [    INFO] - Dataset is None or it has not any labels, label map = {}
[2020-11-17 15:06:01,679] [ WARNING] - Infer Error with server localhost:9000 : [Errno 111] Connection refused
[2020-11-17 15:06:01,679] [    INFO] - Try to connect another servers
Traceback (most recent call last):
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 114, in request_server
    self.serving_list[self.con_index])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/prj/demo_bert.py", line 6, in <module>
    result = bc.get_result(input_text=input_text)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/paddlehub/serving/bert_serving/bs_client.py", line 21, in get_result
    return self.bs.encode(input_text)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 231, in encode
    response_msg = self.request_server(request_msg)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 126, in request_server
    self.serving_list[self.con_index], err))
IndexError: list index out of rang
```

**Comment by bigpo** [comment]
额外还有一个疑问是，不清楚为什么客户端也需要安装paddle，paddlehub这些，难道不是只调用服务端的环境就好了吗？像hub serving这种就可以直接通过 requests.post() 的方式来调用，而不需要依赖paddle，paddlehub。

不知道确实是否是这样，如若不是还请指正，感谢！

**Comment by T-baby** [comment]
我自己试过它错误提示有问题。。应该是 Connection refused。

而且它端口设置有问题，要把我们设置的端口和 9000 端口一起打开才行。

**Comment by T-baby** [comment]
我把问题的代码解析放到我的 issue 里面。。

https://github.com/PaddlePaddle/PaddleHub/issues/1030#issuecomment-730971288
