### ISSUE TITLE
加载fine-tuned模型获取句子embedding报错，求解哦

### ISSUE THREAD

**Issue by BossRobin** [PaddlePaddle/PaddleFormers#1048]
我想使用微调之后的模型生产句子的embedding向量，我首先按照https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/finetuned_model_to_module.md
做了一个module，具体代码如下：
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

import numpy as np
from paddlehub.common.logger import logger
from paddlehub.module.module import moduleinfo, serving
import paddlehub as hub


@moduleinfo(
    name="ernie_crf_finetuned_embedding",
    version="1.2.0",
    summary="ERNIE CRF which was fine-tuned on the own dataset.",
    author="robin",
    author_email="",
    type="nlp/semantic_model")
class ERNIECRFFinetuned(hub.module.nlp_module.TransformerModule):
    def _initialize(self,
                    ckpt_dir="../ckpt_20201123203922",
                    num_class=3,
                    max_seq_len=256,
                    use_gpu=True,
                    batch_size=1):
        self.ckpt_dir = os.path.join(self.directory, ckpt_dir)
        self.num_class = num_class
        self.MAX_SEQ_LEN = max_seq_len
        self.label_dict = {0: "O", 1: "B-ORG", 2: "I-ORG"}

        # Load Paddlehub ERNIE Tiny pretrained model
        self.module = hub.Module(name="ernie")
        inputs, outputs, program = self.module.context(
            trainable=True, max_seq_len=max_seq_len)

        self.vocab_path = self.module.get_vocab_path()

        metrics_choices = ["f1"]

        reader = hub.reader.SequenceLabelReader(
            vocab_path=self.module.get_vocab_path(),
            max_seq_len=max_seq_len,
            sp_model_path=self.module.get_spm_path(),
            word_dict_path=self.module.get_word_dict_path())
        sequence_output = outputs["sequence_output"]

        feed_list = [
            inputs["input_ids"].name,
            inputs["position_ids"].name,
            inputs["segment_ids"].name,
            inputs["input_mask"].name,
        ]
        config = hub.RunConfig(
            use_data_parallel=False,
            use_cuda=use_gpu,
            batch_size=batch_size,
            checkpoint_dir=self.ckpt_dir,
            strategy=hub.AdamWeightDecayStrategy())

        self.seq_label_task = hub.SequenceLabelTask(
            data_reader=reader,
            feature=sequence_output,
            feed_list=feed_list,
            max_seq_len=max_seq_len,
            num_classes=self.num_class,
            config=config,
            metrics_choices=metrics_choices,
            add_crf=True)

    @serving
    def predict(self, data, return_result=False, accelerate_mode=True):
        """
        Get prediction results
        """
        tmp_data = []
        for example in data:
            formatted = []
            for sentence in example:
                formatted.append('\x02'.join(list(sentence)))
            tmp_data.append(formatted)
        data = tmp_data
        labels = self.seq_label_task.predict(data=data, return_result=return_result, accelerate_mode=accelerate_mode)
        results = [run_state.run_results for run_state in labels]
        prediction = []
        for batch_result in results:
            prediction.append([self.label_dict[res[0]] for res in batch_result[0][1:-1]])
        return prediction


if __name__ == "__main__":
    ernie_crf = ERNIECRFFinetuned(
        ckpt_dir="../ckpt_20201123203922", num_class=3)

    data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["采购人单位名称齐齐哈尔市公安局交通警察支队单位地址齐齐哈尔市及"],
            ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]

    predictions = ernie_crf.predict(data=data)
    for index, text in enumerate(data):
        print("%s\tpredict=%s" % (data[index][0], predictions[index]))
```

然后使用https://www.paddlepaddle.org.cn/hubdetail?name=ERNIE&en_category=SemanticModel这里的例子获取embedding时报错了，代码如下：
```
import paddlehub as hub

module = hub.Module(name="ernie_crf_finetuned_embedding")
inputs, outputs, program = module.context(trainable=True, max_seq_len=256)

input_ids = inputs["input_ids"]
position_ids = inputs["position_ids"]
segment_ids = inputs["segment_ids"]
input_mask = inputs["input_mask"]

pooled_output = outputs["pooled_output"]

sequence_output = outputs["sequence_output"]

embedding_result = module.get_embedding(texts=[["Sample1_text_a"],["Sample2_text_a","Sample2_text_b"]], use_gpu=True)

params_layer = module.get_params_layer()
strategy = hub.finetune.strategy.ULMFiTStrategy(params_layer=params_layer)
```
错误信息：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/likai/envs/ernie-crf/lib/python3.6/site-packages/paddlehub/module/nlp_module.py", line 363, in context
    pooled_output, sequence_output = self.net(
  File "/data/likai/envs/ernie-crf/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 370, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ERNIECRFFinetuned' object has no attribute 'net'

paddlehub==1.8.3
paddlepaddle-gpu==1.7.0.post107
paddle-ernie==0.0.4.dev1
python==3.6.9

**Comment by Steffy-zxf** [comment]
你好！你是想要获取 finetune后的ernie模型 句子embedding 还是 finetune后 ernie+crf模型对于数据预测的序列标签呢？

如果是想要获取finetune后 ernie+crf模型对于数据预测的序列标签， 定义finetune后的module，继承`hub.Module`即可，如`class ERNIECRFFinetuned(hub.Module)`。参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/finetuned_model_to_module.md

如果是想要获取finetune后 ernie模型 句子embedding，  有两种方法：

1. 将本地的ernie module文件夹下的 预训练参数替换成 finetune后的参数。ernie module 存放在`$HUB_HOME/.paddlehub/modules`。关于`$HUB_HOME`参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7
**NOTE:** 保持目录层级一致

2. 定义finetune后的module，继承`hub.TransformerModule`，如 `class ERNIECRFFinetuned(hub.TransformerModule)`，之后还需要实现`def net()`方法。可以参考：
ernie module实现：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/hub_module/modules/text/semantic_model/ernie
`hub.TransformerModule`实现：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/paddlehub/module/nlp_module.py#L245

**Comment by BossRobin** [comment]
我是想要获取finetune后的ernie模型的字/句子embedding。多谢🙏，我试一下。
