### ISSUE TITLE
Windows系统下安装多个模型报错

### ISSUE THREAD

**Issue by whuter** [PaddlePaddle/PaddleFormers#1055]
1）PaddleHub和PaddlePaddle版本：
paddlehub                         2.0.0b0
paddlepaddle-gpu                  2.0.0rc0.post100

2）系统环境：Windows 10，python 3.7

hub install lac

d:\program files\python3\lib\site-packages\jinja2\utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
d:\program files\python3\lib\site-packages\jinja2\runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/lac_2.2.0.tar.gz
[##################################################] 100.00%
Decompress C:\Users\QuickJack\.paddlehub\tmp\tmp37kjnhk_\lac_2.2.0.tar.gz
[##################################################] 100.00%
Traceback (most recent call last):
  File "d:\program files\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python3\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\program files\python3\lib\site-packages\paddlehub\commands\utils.py", line 69, in execute
    return com['_entry']().execute(sys.argv[idx:])
  File "d:\program files\python3\lib\site-packages\paddlehub\commands\install.py", line 44, in execute
    manager.install(name=name, version=version)
  File "d:\program files\python3\lib\site-packages\paddlehub\module\manager.py", line 188, in install
    return self._install_from_name(name, version)
  File "d:\program files\python3\lib\site-packages\paddlehub\module\manager.py", line 263, in _install_from_name
    return self._install_from_url(item['url'])
  File "d:\program files\python3\lib\site-packages\paddlehub\module\manager.py", line 256, in _install_from_url
    return self._install_from_archive(file)
  File "d:\program files\python3\lib\site-packages\paddlehub\module\manager.py", line 358, in _install_from_archive
    return self._install_from_directory(directory)
  File "d:\program files\python3\lib\site-packages\paddlehub\module\manager.py", line 322, in _install_from_directory
    module_info = HubModule.load_module_info(directory)
  File "d:\program files\python3\lib\site-packages\paddlehub\module\module.py", line 233, in load_module_info
    pycode = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 17844: illegal multibyte sequence

**Comment by haoyuying** [comment]
请修改编码方式为utf-8格式

**Comment by whuter** [comment]
> 请修改编码方式为utf-8格式

请问如何修改？

**Comment by haoyuying** [comment]
尝试将你本地代码中报错的“"d:\program files\python3\lib\site-packages\paddlehub\module\module.py”的232行改成 with open(module_file, 'r', encoding='utf-8') as file:

**Comment by whuter** [comment]
可以了，谢谢，可以在源码里加上

**Comment by haoyuying** [comment]
paddlehub现在已经更新，您的问题已经修复，欢迎体验新版paddlehub
