### ISSUE TITLE
paddlehub文本分类finetuned的模型预测时候报错：Shape not matching

### ISSUE THREAD

**Issue by geekChinaMaster** [PaddlePaddle/PaddleFormers#1059]
mac系统
paddlehub版本：1.8.3
paddlepaddle版本：1.8.5
python版本：3.7.9
paddlehub文本分类finetuned的模型预测时候报错：Shape not matching
代码如下：
import paddlehub as hub
import numpy as np
ernie_tiny = hub.Module(name="ernie_tiny_finetuned")
# Data to be prdicted
data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
        ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]

predictions = ernie_tiny.predict(data=data)
for index, text in enumerate(data):
    print("%s\tpredict=%s" % (data[index][0], predictions[index]))
报错：
RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((1024, 52)), while the loaded parameter (namely [ cls_out_w ]) has a shape of  ((768, 52)).

**Comment by Steffy-zxf** [comment]
你好！在用PaddleHub fine-tune文本分类时，用的module 是ernie_tiny？ 预测使用的ckpt保存的finetune后module 必须和 finetune时使用的module一致。

**Comment by geekChinaMaster** [comment]
> 你好！在用PaddleHub fine-tune文本分类时，用的module 是ernie_tiny？ 预测使用的ckpt保存的finetune后module 必须和 finetune时使用的module一致。

好的，谢谢，这个已经解决；

**Comment by geekChinaMaster** [comment]
> 你好！在用PaddleHub fine-tune文本分类时，用的module 是ernie_tiny？ 预测使用的ckpt保存的finetune后module 必须和 finetune时使用的module一致。

不过在将我的模型一键部署以后，开启服务调用报错了，
Traceback (most recent call last):
  File "/home/www/.conda/envs/event_label/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 42, in predict_v2_advanced
    output = serving_method(**predict_args)
  File "/home/www/.conda/envs/event_label/lib/python3.7/site-packages/paddlehub/module/module.py", line 72, in _wrapper
    return func(*args, **kwargs)
  File "/home/www/.paddlehub/modules/ernie_tiny_finetuned/module.py", line 104, in predict
    batch_result = np.argmax(batch_result, axis=2)[0]
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/www/.conda/envs/event_label/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/www/.conda/envs/event_label/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/www/.conda/envs/event_label/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/home/www/.conda/envs/event_label/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (52) into shape (1)

我的请求代码是：
import requests
import json


# 待预测文本
texts = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
        ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]
# key为'data', 对应着预测接口predict的参数data
data = {'data': texts}

# 指定模型为ernie_tiny_finetuned并发送post请求，且请求的headers为application/json方式
url = "http://127.0.0.1:8866/predict/ernie_tiny_finetuned"
headers = {"Content-Type": "application/json"}
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(json.dumps(r.json(), indent=4, ensure_ascii=False))

**Comment by geekChinaMaster** [comment]
一键部署之后调用出现异常
import paddlehub as hub
import numpy as np

ernie_tiny = hub.Module(name="ernie_tiny_finetuned")

# Data to be prdicted
data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
        ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]

predictions = ernie_tiny.predict(data=data)
for index, text in enumerate(data):
    print("%s\tpredict=%s" % (data[index][0], predictions[index]))



[2020-12-02 01:26:36,192] [    INFO] - Installing ernie_tiny_finetuned module
[2020-12-02 01:26:41,834] [   ERROR] - Can't find module ernie_tiny_finetuned, please check your spelling.
Traceback (most recent call last):
  File "/data/work/nlp_task/cheng/jz_git/event_label/event_label_formal.py", line 9, in <module>
    ernie_tiny = hub.Module(name="ernie_tiny_finetuned")
  File "/home/www/.conda/envs/nlp_env/lib/python3.7/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/home/www/.conda/envs/nlp_env/lib/python3.7/site-packages/paddlehub/module/module.py", line 174, in init_with_name
    raise RuntimeError(tips)
RuntimeError: Can't find module ernie_tiny_finetuned, please check your spelling.

Process finished with exit code 1
