### ISSUE TITLE
 No module named 'paddle.utils.download'

### ISSUE THREAD

**Issue by czcz1024** [PaddlePaddle/PaddleFormers#1070]
win10
python3.8.5
paddlepaddle 1.8.5
paddlehub 2.0.0b0

import paddlehub

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..\paddlehub\__init__.py", line 25, in <module>
    from paddlehub.utils import download as _download
  File "..\paddlehub\utils\download.py", line 19, in <module>
    from paddle.utils.download import get_path_from_url
ModuleNotFoundError: No module named 'paddle.utils.download'

**Comment by Rayn-liuwei** [comment]
重新安装 paddleaddle=1.8.5 就能解决。

pip install paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple

pip3 install paddlehub==1.8.3

**Comment by ZeyuChen** [comment]
@czcz1024 
这个错误是因为paddle没有使用最新的2.0-rc版本
GPU的话这样安装
pip install paddlepaddle-gpu==2.0.0rc0 -f https://paddlepaddle.org.cn/whl/stable.html

CPU的话这样安装
pip install paddlepaddle==2.0.0rc0 -i https://mirror.baidu.com/pypi/simple
