### ISSUE TITLE
Error: Attribute output_padding is not found in proto conv2d_transpose

### ISSUE THREAD

**Issue by Rayn-liuwei** [PaddlePaddle/PaddleFormers#1072]
# 1. 运行环境：

    Windows 10
    16G RAM
    1T Disk
    Intel(R) Core(TM) i7-8565U CPU

# 2. 测试代码

```python
import datetime
import time

import paddlehub as hub
import cv2

ocr = hub.Module(name="chinese_ocr_db_crnn_server", enable_mkldnn=True)

if __name__ == "__main__":

    occr = ChineseOCRDBCRNNServer()

    image_path = "E:/test/test.jpg"
        for i in range(0, 1000):
        start = datetime.datetime.now()

        result = ocr.recognize_text(images=[cv2.imread(image_path)])

        cost = datetime.datetime.now() - start
        print("耗时: ", cost, "Result :", result)

    pass
```

# 3.错误信息：

    [2020-12-02 18:07:18,728] [    INFO] - Installing chinese_ocr_db_crnn_server module
    [2020-12-02 18:07:18,898] [    INFO] - Module chinese_ocr_db_crnn_server already installed in C:\Users\ytkj-yfb\.paddlehub\modules\chinese_ocr_db_crnn_server
    e[37m---    fused 0 scale with matmule[0m
    e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
    e[37m---    fused 0 scale with matmule[0m
    e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
    [2020-12-02 18:07:19,780] [    INFO] - Installing chinese_text_detection_db_server module-1.0.2
    [2020-12-02 18:07:19,781] [    INFO] - Module chinese_text_detection_db_server-1.0.2 already installed in C:\Users\ytkj-yfb\.paddlehub\modules\chinese_text_detection_db_server
    Traceback (most recent call last):
      File "D:\anaconda3-bin\envs\pytorch-envs\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-2-9690880bf687>", line 1, in <module>
        runfile('E:/python_workspace/secneter/src/ocr_example/ocr_paddlehub.py', wdir='E:/python_workspace/secneter/src/ocr_example')
      File "D:\Program Files\JetBrains\PyCharm 2019.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
        pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
      File "D:\Program Files\JetBrains\PyCharm 2019.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
        exec(compile(contents+"\n", file, 'exec'), glob, loc)
      File "E:/python_workspace/secneter/src/ocr_example/ocr_paddlehub.py", line 29, in <module>
        result = ocr.recognize_text(images=[cv2.imread(image_path)])
      File "C:\Users\ytkj-yfb\.paddlehub\modules\chinese_ocr_db_crnn_server\module.py", line 247, in recognize_text
        detection_results = self.text_detector_module.detect_text(
      File "C:\Users\ytkj-yfb\.paddlehub\modules\chinese_ocr_db_crnn_server\module.py", line 112, in text_detector_module
        version='1.0.2')
      File "D:\anaconda3-bin\envs\pytorch-envs\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
        name=name, version=version, **kwargs)
      File "D:\anaconda3-bin\envs\pytorch-envs\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
        return cls.init_with_directory(directory=module_dir[0], **kwargs)
      File "D:\anaconda3-bin\envs\pytorch-envs\lib\site-packages\paddlehub\module\module.py", line 200, in init_with_directory
        user_module = _item(directory=directory, **kwargs)
      File "D:\anaconda3-bin\envs\pytorch-envs\lib\site-packages\paddlehub\module\module.py", line 146, in __init__
        self._initialize(**kwargs)
      File "C:\Users\ytkj-yfb\.paddlehub\modules\chinese_text_detection_db_server\module.py", line 47, in _initialize
        self._set_config()
      File "C:\Users\ytkj-yfb\.paddlehub\modules\chinese_text_detection_db_server\module.py", line 84, in _set_config
        self.predictor = create_paddle_predictor(config)
    paddle.fluid.core_avx.EnforceNotMet: 
    --------------------------------------------
    C++ Call Stacks (More useful to developers):
    --------------------------------------------
    Windows not support stack backtrace yet.
    ----------------------
    Error Message Summary:
    ----------------------
    Error: Attribute output_padding is not found in proto conv2d_transpose at (D:\1.8.5\paddle\paddle\fluid\framework\op_desc.cc:521)

# 4. 说明

在测试中，不增加 enable_mkldnn=True 参数，可正常运行。

**Comment by chenboo** [comment]
我也是这个问题。

**Comment by lpj0711** [comment]
楼主解决了吗 我也是相同的问题，是不是跟paddle版本有关系啊
