### ISSUE TITLE
报错 ModuleNotFoundError: No module named 'paddle.utils'

### ISSUE THREAD

**Issue by fanyangfanyang** [PaddlePaddle/PaddleFormers#1082]
PaddleHub       2.0.0b0
PaddlePaddle   2.0.0rc0
paddle             1.0.2
paddleocr        1.1.1
Ubuntu            18.04.4
python             3.6.9
    最初在安装PaddlePaddle和PaddleHub，之后，运行hub ocr模型时提示缺少paddle包；
    后来安装paddle包后运行，提示缺少“paddle.utils”
Traceback (most recent call last):
  File "/home/ubgpu/.local/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/home/ubgpu/.local/lib/python3.6/site-packages/paddlehub/__init__.py", line 25, in <module>
    from paddlehub.utils import download as _download
  File "/home/ubgpu/.local/lib/python3.6/site-packages/paddlehub/utils/download.py", line 19, in <module>
    from paddle.utils.download import get_path_from_url
ModuleNotFoundError: No module named 'paddle.utils'

**Comment by haoyuying** [comment]
请安装paddlehub2.0.0b1， pip install paddlehub==2.0.0b1

**Comment by cfy42584125** [comment]
![企业微信截图_16306427472169](https://user-images.githubusercontent.com/62530854/131949902-60758320-8fd1-4cf7-99ef-f00883bb3676.png)
安装了这个pip install paddlehub==2.0.0b1，还是报No module named 'paddle.utils.cpp_extension'这个错误
