### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 9759: illegal multibyte sequence

### ISSUE THREAD

**Issue by jurimengs** [PaddlePaddle/PaddleFormers#1084]
Win10 
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
运行窗口： 命令提示符（cmd）

pip install paddlepaddle==2.0.0rc
pip install paddlehub==2.0.0b
hub install senta_bilstm
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/senta_bilstm_1.2.0.tar.gz
[##################################################] 100.00%
Decompress C:\Users\A37\.paddlehub\tmp\tmpd1lk73yb\senta_bilstm_1.2.0.tar.gz
[##################################################] 100.00%
Traceback (most recent call last):
  File "d:\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python36\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\python\python36\lib\site-packages\paddlehub\commands\utils.py", line 69, in execute
    return com['_entry']().execute(sys.argv[idx:])
  File "d:\python\python36\lib\site-packages\paddlehub\commands\install.py", line 44, in execute
    manager.install(name=name, version=version)
  File "d:\python\python36\lib\site-packages\paddlehub\module\manager.py", line 188, in install
    return self._install_from_name(name, version)
  File "d:\python\python36\lib\site-packages\paddlehub\module\manager.py", line 263, in _install_from_name
    return self._install_from_url(item['url'])
  File "d:\python\python36\lib\site-packages\paddlehub\module\manager.py", line 256, in _install_from_url
    return self._install_from_archive(file)
  File "d:\python\python36\lib\site-packages\paddlehub\module\manager.py", line 358, in _install_from_archive
    return self._install_from_directory(directory)
  File "d:\python\python36\lib\site-packages\paddlehub\module\manager.py", line 322, in _install_from_directory
    module_info = HubModule.load_module_info(directory)
  File "d:\python\python36\lib\site-packages\paddlehub\module\module.py", line 233, in load_module_info
    pycode = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 9759: illegal multibyte sequence

定位到  d:\python\python36\lib\site-packages\paddlehub\module\module.py 233 行，加了个字符后OK，截图如下：

![图片](https://user-images.githubusercontent.com/10648133/101015613-a1c5c900-35a2-11eb-8254-3d7b51969baa.png)

**Comment by nepeplwu** [comment]
@jurimengs 感谢反馈，这个问题是因为编码原因导致的，我们已经在2.0.0-beta1版本中修复了，你可以通过
```cmd
pip install paddlehub==2.0.0b1
```
来更新
