### ISSUE TITLE
centos上执行hub命令报错，请问哪里的问题

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleFormers#1090]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
系统：centos
python：3.7
paddlepaddle: 1.8.2
padlehub: 1.7.1
paddlepaddle和paddlehub用最新版本我也尝试了，不好用
执行hub serving start -m chinese_ocr_db_crnn_mobile报错如下：
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle/bin/hub", line 5, in <module>
    from paddlehub.commands.hub import main
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/__init__.py", line 27, in <module>
    from . import module
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/__init__.py", line 16, in <module>
    from . import module
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 31, in <module>
    from paddlehub.common import utils
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/common/__init__.py", line 16, in <module>
    from . import utils
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/common/utils.py", line 30, in <module>
    import cv2
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by ShenYuhan** [comment]
您可以参考这里解决https://blog.csdn.net/qingfengxd1/article/details/108203954

```shell
yum install mesa-libGL.x86_64
```

**Comment by Sunyingbin** [comment]
非常感谢

**Comment by 60999** [comment]
debian 10 下参考：
sudo apt update
sudo apt install libgl1-mesa-glx

docker里面使用

apt update
apt install libgl1-mesa-glx
