### ISSUE TITLE
hub show / list  运行模型好慢啊  花费时间： 36.00005912780762

### ISSUE THREAD

**Issue by y455471846b** [PaddlePaddle/PaddleFormers#1095]
运行环境：
   win7 64  python 3.6.4  paddlepaddle==2.0.0rc0  paddlehub==1.8.3
D:\Program Files\python3.6\Lib\site-packages\scipy\stats\morestats.py:12: DeprecationWarning: Importing from numpy.testing.decorators is deprecated since numpy 1.15.0, import from numpy.testing instead.
  from numpy.testing.decorators import setastest
D:\Program Files\python3.6\Lib\site-packages\jinja2\filters.py:24: DeprecationWarning: Flags not at the start of the expression '\\w+(?u)'
  _word_re = re.compile(r'\w+(?u)')
D:\Program Files\python3.6\Lib\site-packages\paddle\fluid\layers\math_op_patch.py:278: UserWarning: D:\hub-model-collection\.paddlehub\modules\ernie\model\ernie.py:111
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
D:\Program Files\python3.6\Lib\site-packages\paddle\fluid\layers\math_op_patch.py:278: UserWarning: D:\hub-model-collection\.paddlehub\modules\ernie\model\ernie.py:112
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
D:\Program Files\python3.6\Lib\site-packages\paddle\fluid\layers\math_op_patch.py:278: UserWarning: D:\hub-model-collection\.paddlehub\modules\ernie\model\transformer_encoder.py:118
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
D:\Program Files\python3.6\Lib\site-packages\paddle\fluid\layers\math_op_patch.py:278: UserWarning: D:\hub-model-collection\.paddlehub\modules\ernie\model\transformer_encoder.py:206
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
花费时间： 36.00005912780762

**Comment by haoyuying** [comment]
请安装paddlehub升级版本pip install paddlehub==2.0.0b1

**Comment by y455471846b** [comment]
File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\module\manager.py", line 340, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\module\module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\utils\utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "d:\program files\python3.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Program Files\python3.6\Lib\site-packages\ernie\__init__.py", line 21, in <module>
    paddle_version = [int(i) for i in paddle.__version__.split('.')]
  File "D:\Program Files\python3.6\Lib\site-packages\ernie\__init__.py", line 21, in <listcomp>
    paddle_version = [int(i) for i in paddle.__version__.split('.')]
ValueError: invalid literal for int() with base 10: '0-rc0'

又报了这个错误，paddle-ernie 已经pip install paddle-ernie -U到最新版了，paddle-ernie==0.0.4dev1

**Comment by y455471846b** [comment]
paddlepaddle==2.0.0rc0 也是最新版 ，训练模型时用的是：paddlepaddle==2.0.0rc0 + paddlehub==1.8.3，如果降低版本的话，训练时都会报错的

**Comment by ShenYuhan** [comment]
尝试升级到2.0.0b1的paddlehub，这块性能我们做了优化

**Comment by y455471846b** [comment]
没有优化啊，你第一次回复后我就用2.0.0b1的paddlehub了，刚卸载又从新安装，还是一样的报错，这个版本是不支持paddlepaddle==2.0.0rc0吗？

**Comment by y455471846b** [comment]
Successfully installed paddlepaddle-1.8.5

C:\Users\Administrator>hub serving start --modules resume_parse
Traceback (most recent call last):
  File "d:\program files\python3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\python3.6\Scripts\hub.exe\__main__.py", line 5, in <module>
  File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\__init__.py", line 24, in <module>
    from paddlehub import datasets
  File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\datasets\__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas
  File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\datasets\canvas.py", line 23, in <module>
    from paddlehub.vision.utils import get_img_file
  File "D:\Program Files\python3.6\Lib\site-packages\paddlehub\vision\utils.py", line 159, in <module>
    def subtract_imagenet_mean_batch(batch: paddle.Tensor) -> paddle.Tensor:
AttributeError: module 'paddle' has no attribute 'Tensor'

2.0.0b1的paddlehub与paddlepaddle==1.8.5 版本也不适配
