### ISSUE TITLE
windows下PaddleHub2.0.0启动hub serving报"ModuleNotFoundError: No module named 'zmq'"错误

### ISSUE THREAD

**Issue by fzbird** [PaddlePaddle/PaddleFormers#1116]
win10系统下，paddlepaddle-gpu 2.0.0rc0，先安装的paddlehub 1.8.3，后又安装了paddlehub 2.0.0b0，执行服务器检查正常，如下：
--------------------------
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub
>>> paddlehub.server_check()
[2020-12-14 10:44:58,134] [    INFO] - Request Hub-Server successfully.
True
-----------------------------------
但在运行hub serving时，报'zmq'错误，如下：
-----------------------------------
(paddle) C:\Users\Administrator>hub serving start --modules deeplabv3p_xception65_humanseg --use_gpu
c:\users\administrator\envs\paddle\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
c:\users\administrator\envs\paddle\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Administrator\Envs\paddle\Lib\site-packages\paddlehub\serving\worker.py", line 16, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
 * Serving Flask app "paddlehub.serving.http_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
--------------------------------
服务启动了但无响应，也无法CTRL+C退出
系统里已经安装了
pyzmq 20.0.0
zmq 0.0.0
之前使用paddlehub 1.8.3的时候hub serving没有问题，现在不行了，不知道是哪里的问题？zmq版本的问题吗？请帮忙给解决一下。

**Comment by ShenYuhan** [comment]
您好，确认下是否hub执行环境没有pyzmq，我这边做了尝试，在win10机器上可以正常使用

**Comment by fzbird** [comment]
我用的virtualenv-wrapper，创建的虚拟环境下是包含pyzmq20.0.0的，我也尝试过卸载pyzmq重新安装，依然不行。比较奇怪，第一次遇到明明有模块却显示找不到模块的情况。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ShenYuhan"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午5:36
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;; 
抄送: "闪/li闪"<36178831@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleHub] windows下PaddleHub2.0.0启动hub serving报&quot;ModuleNotFoundError: No module named &#39;zmq&#39;&quot;错误 (#1116)





 
您好，确认下是否hub执行环境没有pyzmq，我这边做了尝试，在win10机器上可以正常使用

**Comment by fzbird** [comment]
我是之前 安装的hub 1.8.3，一直很正常，后来为了测试user_guided_colorization，然后又安装的hub 2.0.0b0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ShenYuhan"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午5:36
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;; 
抄送: "闪/li闪"<36178831@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleHub] windows下PaddleHub2.0.0启动hub serving报&quot;ModuleNotFoundError: No module named &#39;zmq&#39;&quot;错误 (#1116)





 
您好，确认下是否hub执行环境没有pyzmq，我这边做了尝试，在win10机器上可以正常使用

**Comment by ShenYuhan** [comment]
可以试试直接import zmq，如果直接在python脚本中import zmq都失败的话，明显就是环境问题了

**Comment by fzbird** [comment]
下午测试了，在环境下import zmq是没问题的，可以使用help查看模块相关信息。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ShenYuhan"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 晚上7:12
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;; 
抄送: "闪/li闪"<36178831@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleHub] windows下PaddleHub2.0.0启动hub serving报&quot;ModuleNotFoundError: No module named &#39;zmq&#39;&quot;错误 (#1116)





 
可以试试直接import zmq，如果直接在python脚本中import zmq都失败的话，明显就是环境问题了

**Comment by fzbird** [comment]
晚上重新创建虚拟环境从头开始安装了一遍，这次没有安装paddlehub1.8.5，直接安装的paddlehub2.0.0b，就没了这个问题了。不过两次安装paddlehub2.0.0b都遇到了import git错误：ImportError: Failed to initialize: Bad git executable.将lib\site-packages\paddlehub\server\git_source.py中的import git 之前添加上os.environ["GIT_PYTHON_REFRESH"] = "quiet"就可以了。

在些谢谢ShenYuhan的回复。

**Comment by fzbird** [comment]
安装了user_guided_colorization，并成功启动了serving，但是发送请求后有错误，后来又安装上deeplabv3p_xception65_humanseg，运行hub serving start --modules deeplabv3p_xception65_humanseg --use_gpu就又出现了“zmq”模块的问题，依然没法Ctrl+C退出：
——————————————
(paddle20) C:\Users\Administrator>hub install deeplabv3p_xception65_humanseg
e:\python\envs\paddle20\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
e:\python\envs\paddle20\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/deeplabv3p_xception65_humanseg_1.1.1.tar.gz
[##################################################] 100.00%
Decompress E:\paddleHub\tmp\tmp_kkklpoe\deeplabv3p_xception65_humanseg_1.1.1.tar.gz
[##################################################] 100.00%
[2020-12-14 22:06:00,878] [    INFO] - Successfully installed deeplabv3p_xception65_humanseg-1.1.1

(paddle20) C:\Users\Administrator>hub serving start --modules deeplabv3p_xception65_humanseg --use_gpu
e:\python\envs\paddle20\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
e:\python\envs\paddle20\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
Traceback (most recent call last):
  File "E:\python\Envs\paddle20\Lib\site-packages\paddlehub\serving\worker.py", line 16, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
 * Serving Flask app "paddlehub.serving.http_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)

**Comment by ShenYuhan** [comment]
paddle20这个环境是你验证是否安装zmq的环境吗，如果能够成功import，按理说应该不会突然无法找不到模块的；另外不同的模型并不影响paddlehub及环境

**Comment by fzbird** [comment]
@ShenYuhan ：模型不影响paddlehub及环境的问题，今天我在1.8.3版本下就遇到了，win10+paddlepaddle-gpu 2.0.0rc0+paddlehub 1.8.3，安装了realsr模型，此环境下默认只能安装realsr 1.0.0，结果就hub serving就不行了，运行其他的也出错，这个时候竟然hub list、hub uninstall也不行了！
卸载了paddlehub又重新安装，发现还是不行，感觉应该与这个realsr有关，改了模块下文件夹的名字，提示另外的错误，后来发现paddlehub下的paddlehub\module\manager.py会对模块进行检测，最后只能删除了模块目录下的realsr目录，hub list再终于恢复正常。
从这一点上，说明安装的模型有问题也可能会影响到paddlehub环境，1.8.3 版本的paddlehub\module\manager.py需要修正一下。
-----------------------------------
(paddlehub185) C:\Users\Administrator>hub list
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\python\Envs\paddlehub185\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\commands\list.py", line 38, in execute
    all_modules = default_module_manager.all_modules()
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\manager.py", line 71, in check_module_valid
    _module = importlib.import_module(
  File "c:\program files\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\paddleHub\.paddlehub\modules\realsr\module.py", line 36, in <module>
    class RealSRPredictor(nn.Layer):
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\module.py", line 80, in _wrapper
    raise RuntimeError
RuntimeError

(paddlehub185) C:\Users\Administrator>hub uninstall realsr
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\python\Envs\paddlehub185\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\commands\uninstall.py", line 48, in execute
    result, tips = default_module_manager.uninstall_module(
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\manager.py", line 235, in uninstall_module
    self.all_modules(update=True)
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\manager.py", line 71, in check_module_valid
    _module = importlib.import_module(
  File "c:\program files\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\paddleHub\.paddlehub\modules\realsr\module.py", line 36, in <module>
    class RealSRPredictor(nn.Layer):
  File "e:\python\envs\paddlehub185\lib\site-packages\paddlehub\module\module.py", line 80, in _wrapper
    raise RuntimeError
RuntimeError

(paddlehub185) C:\Users\Administrator>hub config
The current configuration is shown below.
{
    "server_url": [
        "http://paddlepaddle.org.cn/paddlehub"
    ],
    "resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
    "debug": false,
    "log_level": "DEBUG",
    "hub_name": "a1f14459d0d36bc5729d4c4d0fd507c7-1607674047"
}

(paddlehub185) C:\Users\Administrator>hub config reset
Set success! The current configuration is shown below.
{
    "server_url": [
        "http://paddlepaddle.org.cn/paddlehub"
    ],
    "resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
    "debug": false,
    "log_level": "DEBUG",
    "hub_name": "a1f14459d0d36bc5729d4c4d0fd507c7-1608100478"
}

**Comment by fzbird** [comment]
windows下PaddleHub2.0.0启动hub serving报"ModuleNotFoundError: No module named 'zmq'"错误的解决：
经过这几天的折腾，最终通过在import zmq前加上了下面这句，这个问题出的原因不清楚，好像与python环境有关：
import sys
sys.path.append('d:\python\Envs\paddle20\Lib\site-packages')

**Comment by fzbird** [comment]
我的paddlehub2.0.1在启动hub serving时还是报错，我把serving下的worker.py中在import zmq前增加了sys.path.append('xxx\Envs\paddle20\Lib\site-packages')后，不再报zmp模块无法导入的错误了，服务也可以执行访问，但是仍然不能使用Ctrl+C中止任务。另外，我在测试的时候，使用&nbsp;deeplabv3p_xception65_humanseg模型，返回的json数据，data结果列表竟然不在'results'key下，而是在'msg'键值下，如下面这种格式：
{'msg': [{‘data':'xxxx'},{'data':'xxxxx'}], 'results': '', 'status': '000'}
不知道为何会产生这种结果？
相同的机器我在padddlehub1.8.3下测试&nbsp;deeplabv3p_xception65_humanseg模型，返回的json数据是正常。
因为刚刚接触paddlepaddle，所以很多地方不太清楚是怎么回事，请指教！

**Comment by suntao2015005848** [comment]
同样的问题，为什么结果会跑到msg中，而且一个模型执行hub serving start -m xxx  --port  --use_gpu 会启动多次，一个模型tmd同一个端口，在显卡上同时跑了3次，导致显存直接*3，本来2个G的显存占用，占用到6个G。离谱啊。  
![image](https://user-images.githubusercontent.com/49387197/125053510-c73a2880-e0d7-11eb-9904-5bb172ea16ab.png)
