### ISSUE TITLE
realsr进行视频超分时gpu显存溢出，请问如何优化？

### ISSUE THREAD

**Issue by jindongyi011039** [PaddlePaddle/PaddleFormers#1118]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub2.0，PaddlePaddle2.0
2）系统环境：Windows10，python版本3.6
- 复现信息：如为报错，请给出复现环境、复现步骤
- module = hub.Module(name="realsr")
- module.predict('****.mp4')
- device: Nvidia GTX1060, CUDA Capability: 61, Driver API Version: 11.2, Runtime API Version: 10.2, cuDNN Version: 7.6.
-出错信息：
Traceback (most recent call last):
  File "testpaddle.py", line 17, in <module>
    resvideo = module.predict('***.mp4')
  File "\.paddlehub\modules\realsr\module.py", line 124, in predict
    return self.run_video(input)
  File "\.paddlehub\modules\realsr\module.py", line 104, in run_video
    pred_img = self.run_image(frame)
  File "\.paddlehub\modules\realsr\module.py", line 77, in run_image
    out = self.model(x)

ResourceExhaustedError:
Out of memory error on GPU 0. Cannot allocate 1.563721GB memory on GPU 0, available memory is only 1.022400GB.

**Comment by haoyuying** [comment]
这个模型本身比较大，而且是四倍超分，所以给您的建议是，可以选择小的超分模型edvr https://www.paddlepaddle.org.cn/hubdetail?name=edvr&en_category=VideoRestoration，或者使用分辨率较低的视频数据。

**Comment by haoyuying** [comment]
这个模型本身比较大，而且是四倍超分，所以给您的建议是，可以选择小的超分模型edvr https://www.paddlepaddle.org.cn/hubdetail?name=edvr&en_category=VideoRestoration
，或者使用分辨率较低的视频数据。
