### ISSUE TITLE
[已解决] win10-cpu版-无法使用PaddleHub

### ISSUE THREAD

**Issue by TingsongYu** [PaddlePaddle/PaddleFormers#1119]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
paddlehub          1.8.3
paddlepaddle       2.0.0rc0

2）系统环境：请您描述系统类型，例如
win10 64bit, python 3.7.9

- 复现信息：如为报错，请给出复现环境、复现步骤
初始化任何模型都会报错，报错信息没有明确提示是什么错误。

复现代码：
import paddlehub as hub
object_detector = hub.Module(name="yolov3_darknet53_coco2017")

错误信息：
[2020-12-16 16:18:35,487] [    INFO] - Installing yolov3_darknet53_coco2017 module
Traceback (most recent call last):
  File "F:/pytorch_quick_start/src/pdd.py", line 32, in <module>
    object_detector = hub.Module(name="yolov3_darknet53_coco2017")
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 171, in init_with_name
    module_name=name, module_version=version, extra=extra)
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\manager.py", line 127, in install_module
    self.all_modules(update=True)
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\manager.py", line 72, in check_module_valid
    "{}.module".format(basename))
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\yts32\.paddlehub\modules\realsr\module.py", line 36, in <module>
    class RealSRPredictor(nn.Layer):
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 80, in _wrapper
    raise RuntimeError
RuntimeError

Process finished with exit code 1

**Comment by chunzhang-hub** [comment]
建议您这边升级paddlehub到2.0版本，再试试 
pip install paddlehub==2.0.0b

**Comment by fzbird** [comment]
realsr 1.0.0在win10+python3.8.6+paddlepaddle 2.0.0rc+paddlehub1.8.3下也不行。

**Comment by TingsongYu** [comment]
> realsr 1.0.0在win10+python3.8.6+paddlepaddle 2.0.0rc+paddlehub1.8.3下也不行。

我的也是realsr，也不行，报错还是上面那个错误。
最开始安装了gpu版，能运行，但是由于gpu显存不够，所以打算安装cpu版来跑，可现在发现cpu版报错，无法运行

**Comment by TingsongYu** [comment]
> 建议您这边升级paddlehub到2.0版本，再试试
> pip install paddlehub==2.0.0b

尝试更新为paddlepaddle 2.0.0b，但仍旧报相同的错误：

`[2020-12-16 17:26:11,264] [    INFO] - Installing realsr module
Downloading realsr
[==================================================] 100.00%
Uncompress C:\Users\yts32\.paddlehub\tmp\tmp9rh6a8nb\realsr
[==================================================] 100.00%
[2020-12-16 17:26:57,733] [    INFO] - Successfully installed realsr-1.0.0
Traceback (most recent call last):
  File "F:/pytorch_quick_start/src/pdd.py", line 7, in <module>
    model = hub.Module(name='realsr')
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\yts32\.paddlehub\modules\realsr\module.py", line 36, in <module>
    class RealSRPredictor(nn.Layer):
  File "D:\Anaconda_data\envs\pd_2_cpu\lib\site-packages\paddlehub\module\module.py", line 80, in _wrapper
    raise RuntimeError
RuntimeError

Process finished with exit code 1
`

**Comment by chunzhang-hub** [comment]
@TingsongYu @fzbird realsr这个module依赖需要paddlepaddle >= 2.0.0rc，paddlehub >= 2.0.0。需要升级下paddlehub，再试试看还有问题嘛

**Comment by TingsongYu** [comment]
> @TingsongYu @fzbird realsr这个module依赖需要paddlepaddle >= 2.0.0rc，paddlehub >= 2.0.0。需要升级下paddlehub，再试试看还有问题嘛

感谢，升级了paddlehub==2.0.0b，可以运行了

**Comment by TingsongYu** [comment]
> realsr 1.0.0在win10+python3.8.6+paddlepaddle 2.0.0rc+paddlehub1.8.3下也不行。

把paddlehub升级，就可以了（注意是paddlehub不是paddlepaddle，嘿嘿）
