### ISSUE TITLE
use_multiprocess参数问题

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/PaddleFormers#1120]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

老师好，我在使用hub serving start启动服务时，不启用--use_multiprocess参数，服务正常，但是使用--use_multiprocess时调用服务就一直报超时错误，如下：
Traceback (most recent call last):
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\zhaoyi-036\Miniconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\zhaoyi-036\Miniconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\zhaoyi-036\Miniconda3\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\zhaoyi-036\Miniconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\zhaoyi-036\Miniconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\zhaoyi-036\Miniconda3\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logoDetect_test.py", line 29, in <module>
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\zhaoyi-036\Miniconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

1）PaddleHub和PaddlePaddle版本：PaddleHub1.8.3，PaddlePaddle1.8.4，paddlex1.2.8
2）系统环境：Linux，python3.7
3）CPU信息如下：
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2400.480
CPU max MHz:           3000.0000
CPU min MHz:           800.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              11264K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31

**Comment by ShenYuhan** [comment]
是cpu和gpu共用吗，如果是纯cpu的话，开启use_multiprocess后试试设置下--workers，设置小一点看看

**Comment by YasinZhao** [comment]
> 是cpu和gpu共用吗，如果是纯cpu的话，开启use_multiprocess后试试设置下--workers，设置小一点看
老师，你好，我有设置--workers参数，从8降到2，服务还是报上述错误，不设置--use_multiprocess --workers时就没问题，模型是用GPU训练的，部署打算采用纯CPU方式

**Comment by YasinZhao** [comment]
> 是cpu和gpu共用吗，如果是纯cpu的话，开启use_multiprocess后试试设置下--workers，设置小一点看看

老师，你好，我有设置--workers参数，从8降到2，服务还是报上述错误，不设置--use_multiprocess --workers时就没问题，模型是用GPU训练的，部署打算采用纯CPU方式

**Comment by ShenYuhan** [comment]
使用的是哪个模型，贴一下完整的命令，我这边试一下

**Comment by YasinZhao** [comment]
> 使用的是哪个模型，贴一下完整的命令，我这边试一下

老师，你好，使用的是自己一个logo数据集，然后基于paddlex1.2.8训练的pp-yolo模型，经paddlex转换成paddlehub支持的模式，服务启动的命令如下：
无错误：hub serving start -m logoDetect -p 8866
有错误：hub serving start -m logoDetect -p 8866  --use_multiprocess --workers 4

**Comment by tintinxue1** [comment]
遇到同样的错误，multiprocess设了workers后就会各种remote connection问题然后worker reboot,根本没办法用， 单线程的没问题

**Comment by YasinZhao** [comment]
请问这么久了，这个多线程问题官方解决了吗，我用最新的paddlepaddle，paddlehub还是有问题啊

**Comment by 934453938** [comment]
这个问题解决了吗？我的还是CPU只能使用单线程，不能使用use_multiprocess这个参数
