### ISSUE TITLE
2.0执行!hub search seg报错

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleFormers#1125]
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\utils.py", line 69, in execute
    return com['_entry']().execute(sys.argv[idx:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\search.py", line 39, in execute
    table.append(result['name'], result['version'], result['summary'])
KeyError: 'summary'

调整为hub search segment正常

**Comment by ShenYuhan** [comment]
您好，感谢您的意见，此问题已经修复，下次版本升级将解决，目前您可以通过search模型全名来避免此问题
