### ISSUE TITLE
Runtimeerror问题

### ISSUE THREAD

**Issue by Ether-Fish** [PaddlePaddle/PaddleFormers#1127]
1）PaddleHub和PaddlePaddle版本：PaddlePaddle2.0.0
2）系统环境：- Ubuntu18.04
- 复现信息：如为报错，请给出复现环境、复现步骤
### 代码
```

  1 # !/usr/bin/env python                                                                                                                                                                                   
  2 # coding=utf-8
  3 import cv2
  4 import paddlehub as hub
  5 
  6 model = hub.Module(name='photo_restoration', visualization=True)
  7 im = cv2.imread('1.jpeg')
  8 res = model.run_image(im)
```
### 报错
```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "res.py", line 6, in <module>
    model = hub.Module(name='photo_restoration', visualization=True)
  File "/home/ether/.local/lib/python3.6/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/home/ether/.local/lib/python3.6/site-packages/paddlehub/module/module.py", line 171, in init_with_name
    module_name=name, module_version=version, extra=extra)
  File "/home/ether/.local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 127, in install_module
    self.all_modules(update=True)
  File "/home/ether/.local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "/home/ether/.local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 72, in check_module_valid
    "{}.module".format(basename))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ether/.paddlehub/modules/photo_restoration/module.py", line 32, in <module>
    class PhotoRestoreModel(nn.Layer):
  File "/home/ether/.local/lib/python3.6/site-packages/paddlehub/module/module.py", line 80, in _wrapper
    raise RuntimeError
RuntimeError
```

**Comment by haoyuying** [comment]
请安装ffmpeg， conda install x264=='1!152.20180717' ffmpeg=4.0.2 -c conda-forge

**Comment by Ether-Fish** [comment]
> 请安装ffmpeg， conda install x264=='1!152.20180717' ffmpeg=4.0.2 -c conda-forge

我因为没有使用Anaconda，所以使用pip3 install ffmpeg下载ffmpeg. 但是仍然无法解决上述问题。请问是否需要下载某一特定版本的ffmpeg，此外可以解释出现Runtimeerror的问题原因吗。

**Comment by haoyuying** [comment]
runtimeerror存在的问题可能有两个，第一个没有安装photorestoration最新版hub install photo_restoration==1.0.1，这个问题是由于 photo_restoration最初适配的paddlehub版本为1.8导致的，最有可能的是ffmpeg导致的，该模型对ffmpeg和x264编码均有要求，pip 这种方式安装的ffmpeg并不能满足要求。或者你可以尝试pip install imageio-ffmpeg来安装，我这边重新试了下模型，没有出现您说的问题。

**Comment by Ether-Fish** [comment]
我尝试了pip install imagio-ffmpeg 并没有成功解决问题。我之后用旧版本的Paddlehub尝试重新下载模型吧，谢谢

**Comment by juzuo** [comment]
@haoyuying 你好，我也遇到这个runtime error问题。而且我用命令conda install x264=='1!152.20180717' ffmpeg=4.0.2 -c conda-forge安装了ffmpeg

**Comment by haoyuying** [comment]
paddle,paddlehub,和具体的hub模型都用的什么版本呢，方便我们复现问题。

**Comment by juzuo** [comment]
@haoyuying 你好，问题解决了，应该是paddlepaddle和paddlehub的版本问题，改成2.0就没这个问题了，但是有新问题：
1. 在我的机器上，安装cpu版的paddlepaddle，按照文档运行photo_restoration，会停在这：
load pretrained checkpoint success
load pretrained checkpoint success

 Colorization model proccess start..

 SuperResolution model proccess start..
然后等好久会显示Killed.
2. 于是我在aistudio.baidu.com上创建了一个项目，打算在这里跑GPU，会遇到这个问题：
---------------------------------------------------------------------------SystemError                               Traceback (most recent call last)<ipython-input-7-125bd72a90ad> in <module>
      2 import paddlehub as hub
      3 
----> 4 model = hub.Module(name='photo_restoration', visualization=True)
      5 im = cv2.imread('1.jpg')
      6 res = model.run_image(im)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, version, source, update, branch, **kwargs)
    170             if name:
    171                 module = cls.init_with_name(
--> 172                     name=name, version=version, source=source, update=update, branch=branch, **kwargs)
    173                 CacheUpdater("update_cache", module=name, version=version).start()
    174             elif directory:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, source, update, branch, **kwargs)
    279 
    280         user_module_cls.directory = directory
--> 281         return user_module_cls(**kwargs)
    282 
    283     @classmethod
~/.paddlehub/modules/photo_restoration/module.py in __init__(self, visualization)
     40     def __init__(self, visualization: bool = False):
     41         super(PhotoRestoreModel, self).__init__()
---> 42         self.deoldify = hub.Module(name='deoldify')
     43         self.realsr = hub.Module(name='realsr')
     44         self.visualization = visualization
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, version, source, update, branch, **kwargs)
    170             if name:
    171                 module = cls.init_with_name(
--> 172                     name=name, version=version, source=source, update=update, branch=branch, **kwargs)
    173                 CacheUpdater("update_cache", module=name, version=version).start()
    174             elif directory:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, source, update, branch, **kwargs)
    279 
    280         user_module_cls.directory = directory
--> 281         return user_module_cls(**kwargs)
    282 
    283     @classmethod
~/.paddlehub/modules/deoldify/module.py in __init__(self, render_factor, output_path, load_checkpoint)
     38     def __init__(self, render_factor: int = 32, output_path: int = 'output', load_checkpoint: str = None):
     39         super(DeOldifyPredictor, self).__init__()
---> 40         self.model = build_model()
     41         self.render_factor = render_factor
     42         self.output = os.path.join(output_path, 'DeOldify')
~/.paddlehub/modules/deoldify/base_module.py in build_model()
    471                      norm_type='Spectral',
    472                      self_attention=True,
--> 473                      nf_factor=2)
    474     return model
~/.paddlehub/modules/deoldify/base_module.py in __init__(self, encoder, n_classes, blur, blur_final, self_attention, y_range, last_cross, bottle, norm_type, nf_factor, **kwargs)
     66                               ni * 2,
     67                               norm_type=norm_type,
---> 68                               extra_bn=extra_bn),
     69             custom_conv_layer(ni * 2,
     70                               ni,
~/.paddlehub/modules/deoldify/base_module.py in custom_conv_layer(ni, nf, ks, stride, padding, bias, is_1d, norm_type, use_activ, leaky, transpose, self_attention, extra_bn, **kwargs)
    144                      bias_attr=bias,
    145                      stride=stride,
--> 146                      padding=padding)
    147     if norm_type == 'Weight':
    148         conv = nn.utils.weight_norm(conv)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py in __init__(self, in_channels, out_channels, kernel_size, stride, padding, dilation, groups, padding_mode, weight_attr, bias_attr, data_format)
    621             weight_attr=weight_attr,
    622             bias_attr=bias_attr,
--> 623             data_format=data_format)
    624 
    625     def forward(self, x):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py in __init__(self, in_channels, out_channels, kernel_size, transposed, dims, stride, padding, padding_mode, output_padding, dilation, groups, weight_attr, bias_attr, data_format)
    134             shape=filter_shape,
    135             attr=self._param_attr,
--> 136             default_initializer=_get_default_param_initializer())
    137         self.bias = self.create_parameter(
    138             attr=self._bias_attr, shape=[self._out_channels], is_bias=True)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in create_parameter(self, shape, attr, dtype, is_bias, default_initializer)
    388             temp_attr = None
    389         return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
--> 390                                              default_initializer)
    391 
    392     @deprecated(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py in create_parameter(self, attr, shape, dtype, is_bias, default_initializer, stop_gradient, type)
    370                 type=type,
    371                 stop_gradient=stop_gradient,
--> 372                 **attr._to_kwargs(with_initializer=True))
    373         else:
    374             self.startup_program.global_block().create_parameter(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in create_parameter(self, *args, **kwargs)
   2805                 pass
   2806             else:
-> 2807                 initializer(param, self)
   2808         return param
   2809 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/initializer.py in __call__(self, var, block)
    362                 "use_mkldnn": False
    363             },
--> 364             stop_gradient=True)
    365 
    366         if var.dtype == VarDesc.VarType.FP16:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in _prepend_op(self, *args, **kwargs)
   2921                                        kwargs.get("outputs", {}), attrs
   2922                                        if attrs else {},
-> 2923                                        kwargs.get("stop_gradient", False))
   2924         else:
   2925             op_desc = self.desc._prepend_op()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     43         self.trace(type, inputs, outputs, attrs,
     44                    framework._current_expected_place(), self._has_grad and
---> 45                    not stop_gradient)
     46 
     47     def train_mode(self):
SystemError: (Fatal) Operator gaussian_random raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 288.000244MB memory on GPU 0, available memory is only 140.750000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
. (at /paddle/paddle/fluid/imperative/tracer.cc:98)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

提示说GPU0没显存了，但是我在GPU0上就运行了这一个项目啊。。。

**Comment by juzuo** [comment]
![error](https://user-images.githubusercontent.com/49368764/104256647-8d84be00-54b6-11eb-9ee5-d72efda9d115.png)
请看截图。

**Comment by haoyuying** [comment]
是这样，超分网络是超四倍的， 本身占用内存非常大，所以如果显存不足够大的话，最好找小的分辨率的视频进行超分，并且超分合成速度较慢。在v100gpu上运行的话， 原始图像的分辨最好不要超过800*800

**Comment by juzuo** [comment]
明白了，多谢多谢！

**Comment by juzuo** [comment]
刚才在aistudio.baidu.com上测了一下，超过300*400的图就跑不起来了，32G的显存会占满。请问这个正常吗？有没有优化的方法？
@haoyuying

**Comment by haoyuying** [comment]
是正常的，这个模型本身很耗资源，而且比较慢。

**Comment by juzuo** [comment]
好吧。多谢了。
