### ISSUE TITLE
模型运行报错：operands could not be broadcast together with remapped shapes

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleFormers#1128]
Traceback (most recent call last):

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/datasets/dataset.py", line 166, in _read_into_queue
    six.reraise(*sys.exc_info())

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/datasets/dataset.py", line 158, in _read_into_queue
    result = mapper(sample[0], sample[1], sample[2])

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/seg_transforms.py", line 152, in __call__
    outputs = op(im, im_info, label)

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/seg_transforms.py", line 759, in __call__
    self.label_padding_value))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 1172, in pad
    pad_width = _as_pairs(pad_width, narray.ndim, as_index=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 953, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 129, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (3,2)

**Comment by haoyuying** [comment]
请问是paddlehub的模型吗，如果是，请给出具体的运行脚本，运行环境等信息，方便我们复现问题。
