### ISSUE TITLE
/demo/text_classification/train.py 无法使用

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleFormers#1134]
1）PaddleHub和PaddlePaddle版本：PaddlePaddle2.0.0rc1, paddlehub==2.0.0b
2）系统环境：Windows10 python3.7
- 复现信息：如为报错，请给出复现环境、复现步骤
Traceback (most recent call last):
  File ".\测试.py", line 30, in <module>
    trainer.train(train_dataset, epochs=3, batch_size=32, eval_dataset=dev_dataset, save_interval=1)
  File "D:\conda\envs\work_hub2\lib\site-packages\paddlehub\finetune\trainer.py", line 199, in train
    loss, metrics = self.training_step(batch, batch_idx)
  File "D:\conda\envs\work_hub2\lib\site-packages\paddlehub\finetune\trainer.py", line 336, in training_step
    result = self.model.training_step(batch, batch_idx)
  File "C:\Users\zkj\.paddlehub\modules\ernie_tiny\module.py", line 122, in training_step
    predictions, avg_loss, acc = self(input_ids=batch[0], token_type_ids=batch[1], labels=batch[2])
  File "D:\conda\envs\work_hub2\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\zkj\.paddlehub\modules\ernie_tiny\module.py", line 72, in forward
    loss = self.criterion(logits, labels)
  File "D:\conda\envs\work_hub2\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\conda\envs\work_hub2\lib\site-packages\paddle\nn\layer\loss.py", line 249, in forward
    name=self.name)
  File "D:\conda\envs\work_hub2\lib\site-packages\paddle\nn\functional\loss.py", line 1220, in cross_entropy
    axis=axis)
  File "D:\conda\envs\work_hub2\lib\site-packages\paddle\fluid\layers\loss.py", line 1264, in softmax_with_cross_entropy
    axis)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\2.0.0rc1\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < softmax_with_cross_entropy > error]
使用demo源代码报错,怀疑是paddlepaddle问题,

**Comment by KPatr1ck** [comment]
测试后发现在win10环境下会出现相同的报错，需要继续排查。
一个临时的解决方法，可以尝试将labels的tensor类型强转成int64。

**Comment by KPatr1ck** [comment]
> 测试后发现在win10环境下会出现相同的报错，需要继续排查。
> 一个临时的解决方法，可以尝试将labels的tensor类型强转成int64。

[paddlehub/datasets/base_nlp_dataset.py, line 250](
https://github.com/PaddlePaddle/PaddleHub/blob/47895a938004a84fa794de918cc8b63cc4de49e8/paddlehub/datasets/base_nlp_dataset.py#L250)

label在这里转一下numpy的dtype可以暂时解决，paddlehub 2.0rc版本将修复这个问题。
```python
return np.array(record['input_ids']), np.array(record['segment_ids']), np.array(record['label'], dtype=np.int64)
```
