### ISSUE TITLE
edvr模型推理报错

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleFormers#1135]
环境:linux aistudio
```shell
python --version
Python 3.7.4

nvidia-smi 
Tue Dec 22 15:29:01 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   40C    P0    40W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
Stepping:              7
CPU MHz:               2599.994
BogoMIPS:              5199.98
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0-23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs ibpb fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 arat
```

运行代码

```shell
import paddlehub as hub

model = hub.Module(name='edvr')
model.predict('./test.mp4')
```

报错
```shell
python test.py 
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/nltk/decorators.py:68: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  regargs, varargs, varkwargs, defaults, formatvalue=lambda value: ""
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/nltk/lm/counter.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence, defaultdict
[2020-12-22 15:26:37,776] [    INFO] - Installing edvr module
[2020-12-22 15:26:37,778] [    INFO] - Module edvr already installed in /home/aistudio/.paddlehub/modules/edvr
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = hub.Module(name='edvr')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 146, in __init__
    self._initialize(**kwargs)
  File "/home/aistudio/.paddlehub/modules/edvr/module.py", line 70, in _initialize
    self.build_inference_model()
  File "/home/aistudio/.paddlehub/modules/edvr/module.py", line 90, in build_inference_model
    params_filename=param_file)
TypeError: load_inference_model() missing 1 required positional argument: 'path_prefix'
```
aistudio 公开项目地址
https://aistudio.baidu.com/aistudio/projectdetail/1353034

**Comment by haoyuying** [comment]
模型加载参数缺失导致的，建议先卸载edvr，hub uninstall edvr,然后重新安装edvr，hub install edvr。并且这个模型要安装ffmpeg，可以尝试使用conda install x264=='1!152.20180717' ffmpeg=4.0.2 -c conda-forge 或者pip install imageio-ffmpeg安装要求比较高。

**Comment by haoyuying** [comment]
还有个问题，我看了你test的文件，没打开，但是太大了，这个模型是超分四倍的模型，如果单张图片分辨率过高，会导致内存或显存不足报错。

**Comment by linhandev** [comment]
抱歉才看到，我研究研究

**Comment by linhandev** [comment]
应该是视频分辨率的问题，换了视频解决了。谢谢大佬

**Comment by linhandev** [comment]
感觉看起来是模型加载的代码有问题，是paddle的api报的缺参数的错误。

这个是api的文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/api/paddle/static/load_inference_model_cn.html#load-inference-model

代码里面调用的时候接口是
![image](https://user-images.githubusercontent.com/29757093/105354854-1ecd0080-5c2c-11eb-918c-68335168348a.png)
格式应该是有问题

**Comment by linhandev** [comment]
应该就是这个问题，第一个参数改成 path_prefix 就能执行了
