### ISSUE TITLE
进行finetune训练时报错：ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by xct-xct** [PaddlePaddle/PaddleFormers#1156]
1）PaddleHub1.8.0，PaddlePaddle1.8.5-CPU版本
2）系统环境：Windows10-anaconda3，python3.7.9
3）pointwise文本匹配任务，finetune代码如下;
`CKPT_DIR="./ckpt_embedding_pointwise_matching"

python -u embedding_pointwise_matching.py \
            --batch_size=1 \
            --checkpoint_dir=${CKPT_DIR} \
            --learning_rate=5e-2 \
            --max_seq_len=256 \
            --num_epoch=3 \
            --network=lstm`

`import argparse
import ast
import paddlehub as hub

# yapf: disable
parser = argparse.ArgumentParser(__doc__)
parser.add_argument("--num_epoch", type=int, default=3, help="Number of epoches for fine-tuning.")
parser.add_argument("--learning_rate", type=float, default=5e-5, help="Learning rate used to train with warmup.")
parser.add_argument("--checkpoint_dir", type=str, default=None, help="Directory to model checkpoint")
parser.add_argument("--max_seq_len", type=int, default=512, help="Number of words of the longest seqence.")
parser.add_argument("--batch_size", type=int, default=32, help="Total examples' number in batch for training.")
parser.add_argument("--network", type=str, default=None, help="Pre-defined network which was connected after module.")
args = parser.parse_args()

jieba_paddle = hub.Module(name='jieba_paddle')

def cut(text):
    res = jieba_paddle.cut(text, use_paddle=False)
    return res

if __name__ == '__main__':

    module = hub.Module(name="word2vec_skipgram")

    inputs, outputs, program = module.context(
        trainable=True, max_seq_len=args.max_seq_len, num_slots=2)

    tokenizer = hub.CustomTokenizer(
        vocab_file=module.get_vocab_path(),
        tokenize_chinese_chars=True,
        cut_function=cut
    )

    dataset = hub.dataset.LCQMC(
        tokenizer=tokenizer, max_seq_len=args.max_seq_len)

    query = outputs["emb"]
    title = outputs['emb_2']

    strategy = hub.DefaultStrategy(
        optimizer_name="sgd", learning_rate=args.learning_rate)

    config = hub.RunConfig(
        eval_interval=300,
        use_data_parallel=False,
        use_cuda=False,
        num_epoch=args.num_epoch,
        batch_size=args.batch_size,
        checkpoint_dir=args.checkpoint_dir,
        strategy=strategy)

    matching_task = hub.PointwiseTextMatchingTask(
        dataset=dataset,
        query_feature=query,
        title_feature=title,
        tokenizer=tokenizer,
        network=args.network,
        config=config)

    matching_task.finetune_and_eval()`

4）报错信息如下：
`[2020-12-30 17:08:25,593] [   TRAIN] - step 80 / 716205: loss=0.70985 acc=0.50000 f1=0.66667 precision=0.50000 recall=1.00000 [                     step/sec: 106.67]
[2020-12-30 17:08:25,685] [   TRAIN] - step 90 / 716205: loss=0.71690 acc=0.10000 f1=0.18182 precision=0.14286 recall=0.25000 [                     step/sec: 110.15]
[2020-12-30 17:08:25,779] [   TRAIN] - step 100 / 716205: loss=0.69809 acc=0.60000 f1=0.75000 precision=0.60000 recall=1.00000                      [step/sec: 107.81]
[2020-12-30 17:08:25,879] [   TRAIN] - step 110 / 716205: loss=0.70668 acc=0.50000 f1=0.66667 precision=0.50000 recall=1.00000                      [step/sec: 100.27]
[2020-12-30 17:08:25,972] [   TRAIN] - step 120 / 716205: loss=0.70090 acc=0.40000 f1=0.25000 precision=0.20000 recall=0.33333                      [step/sec: 109.00]
[2020-12-30 17:08:26,066] [   TRAIN] - step 130 / 716205: loss=0.70716 acc=0.50000 f1=0.00000 precision=0.00000 recall=0.00000                      [step/sec: 107.81]
[2020-12-30 17:08:26,165] [   TRAIN] - step 140 / 716205: loss=0.70787 acc=0.40000 f1=0.00000 precision=0.00000 recall=0.00000                      [step/sec: 101.28]
[2020-12-30 17:08:26,263] [   TRAIN] - step 150 / 716205: loss=0.67597 acc=0.70000 f1=0.00000 precision=0.00000 recall=0.00000                      [step/sec: 102.24]
[2020-12-30 17:08:26,358] [   TRAIN] - step 160 / 716205: loss=0.72892 acc=0.30000 f1=0.46154 precision=0.60000 recall=0.37500                      [step/sec: 107.78]
[2020-12-30 17:08:26,452] [   TRAIN] - step 170 / 716205: loss=0.69535 acc=0.50000 f1=0.66667 precision=0.55556 recall=0.83333                      [step/sec: 107.78]
[2020-12-30 17:08:26,549] [   TRAIN] - step 180 / 716205: loss=0.69153 acc=0.60000 f1=0.75000 precision=0.60000 recall=1.00000                      [step/sec: 105.55]
[2020-12-30 17:08:26,638] [   TRAIN] - step 190 / 716205: loss=0.62224 acc=0.80000 f1=0.88889 precision=0.80000 recall=1.00000                      [step/sec: 112.66]
Traceback (most recent call last):
  File "embedding_pointwise_matching.py", line 60, in <module>
    matching_task.finetune_and_eval()
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\finetune\task\base_task.py", line 945, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\finetune\task\base_task.py", line 966, in finetune
    run_states = self._run(do_eval=do_eval)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1219, in _run
    step_run_state.update()
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\finetune\task\base_task.py", line 72, in update
    self.run_speed = self.run_step / self.run_time_used
ZeroDivisionError: float division by zero`

**Comment by AlexDish** [comment]
Me too.
I am running the finetune on windows10.
The program will raise ZeroDivisionError ramdomly.
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    ret = task.predict(data=data,return_result=True) #使用PaddleHub提供的API实现一键结果预测，return_result默认结果是False
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1139, in predict
    run_states = self._run_with_predictor()
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1082, in _run_with_predictor
    step_run_state.update()
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\finetune\task\base_task.py", line 72, in update
    self.run_speed = self.run_step / self.run_time_used
ZeroDivisionError: float division by zero

I found it OK in the morning, but in the afternoon it occured this problem.

**Comment by xct-xct** [comment]
通过修改...\paddlehub\finetune\task.base_task中第71行代码，目前不会有该报错，但不清楚此修改会有什么影响。
![image](https://user-images.githubusercontent.com/54756702/103389761-cc785280-4b4b-11eb-9c98-f93ac60e827f.png)

**Comment by KPatr1ck** [comment]
> 通过修改...\paddlehub\finetune\task.base_task中第71行代码，目前不会有该报错，但不清楚此修改会有什么影响。
> ![image](https://user-images.githubusercontent.com/54756702/103389761-cc785280-4b4b-11eb-9c98-f93ac60e827f.png)

目前这个报错在你的环境里是必现的吗？
我尝试设置相同的配置，跑同一个训练脚本没出能复现。
这个时间信息目前只用于计算和展示训练速度，你这个修改不会影响模型参数的训练。
如果有能稳定复现的方法请在issue内继续回复，感谢~

**Comment by xct-xct** [comment]
> > 通过修改...\paddlehub\finetune\task.base_task中第71行代码，目前不会有该报错，但不清楚此修改会有什么影响。
> > ![image](https://user-images.githubusercontent.com/54756702/103389761-cc785280-4b4b-11eb-9c98-f93ac60e827f.png)
> 
> 目前这个报错在你的环境里是必现的吗？
> 我尝试设置相同的配置，跑同一个训练脚本没出能复现。
> 这个时间信息目前只用于计算和展示训练速度，你这个修改不会影响模型参数的训练。
> 如果有能稳定复现的方法请在issue内继续回复，感谢~

感谢回复！
此报错不是必现的，只在训练过程中偶尔出现，目前修改后就没出现过该问题了，训练也正常。
后续有能稳定复现的方式会再次回复，感谢~
