### ISSUE TITLE
senta_demo 执行有问题

### ISSUE THREAD

**Issue by Magiclemond** [PaddlePaddle/PaddleFormers#117]
用的1.5.1的paddlepaddle及1.1.0的paddlehub，显示报错：
AttributeError: module 'paddle' has no attribute 'batch'
查询版本更新里面并没有这方面的改动…想知道哪边出了问题

**Comment by Steffy-zxf** [comment]
感谢反馈！运行环境是 windows/linux, python2/python3 ? 方便贴下错误信息堆栈的调用情况吗？

**Comment by Magiclemond** [comment]
不好意思刚看到，环境windows,python3
执行 results = senta.sentiment_classify(data=input_dict) 语句时出现的问题
具体信息：
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Python3.6\lib\site-packages\paddlehub\module\module.py", line 476, in __call__
    sign_name=sign_name, data_dict=data)
  File "xxx\.paddlehub\modules\senta_bilstm\python\97503482545a556bf2f6e699392af4b0.py", line 62, in preprocess
    processed = self.lac.lexical_analysis(data=data_dict)
  File "D:\Python3.6\lib\site-packages\paddlehub\module\module.py", line 479, in __call__
    reader = paddle.batch(reader, batch_size=batch_size)
AttributeError: module 'paddle' has no attribute 'batch'

**Comment by Steffy-zxf** [comment]
检查下，paddle的版本以及有没有batch这个属性

```python
import paddle

print(paddle.__version__)
print(paddle.__dict__)
```

正常的话，可以看到‘batch‘这个属性

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
