### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'Tensor'

### ISSUE THREAD

**Issue by yancccc** [PaddlePaddle/PaddleFormers#1175]
ocr = hub.Module(name="chinese_ocr_db_crnn_mobile") #加载移动端预训练模型
这句会报错：
Traceback (most recent call last):
  File "1.py", line 19, in <module>
    import paddlehub as hub
  File "/home/ycc/PaddleHub-release-v2.0.0-rc/paddlehub/__init__.py", line 24, in <module>
    from paddlehub import datasets
  File "/home/ycc/PaddleHub-release-v2.0.0-rc/paddlehub/datasets/__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas
  File "/home/ycc/PaddleHub-release-v2.0.0-rc/paddlehub/datasets/canvas.py", line 23, in <module>
    from paddlehub.vision.utils import get_img_file
  File "/home/ycc/PaddleHub-release-v2.0.0-rc/paddlehub/vision/utils.py", line 159, in <module>
    def subtract_imagenet_mean_batch(batch: paddle.Tensor) -> paddle.Tensor:
AttributeError: module 'paddle' has no attribute 'Tensor'

**Comment by haoyuying** [comment]
请安装paddlepaddle2.0版本
