### ISSUE TITLE
pyramidbox_lite_server_mask在某些图片检测时会出现ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by gardenofever** [PaddlePaddle/PaddleFormers#1187]
在对某些图像进行人脸检测时，如果使用use_multi_scale=True，就会出现错误，具体如下
```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-98907cf19a25>", line 1, in <module>
    runfile('F:/Model/venv/PaddleHub.py', wdir='F:/Model/venv')
  File "D:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/Model/venv/PaddleHub.py", line 43, in <module>
    results = module.face_detection(images=imgs, batch_size=1, use_multi_scale=True, shrink=1, visualization=False, output_dir='detection_result', use_gpu=True)
  File "C:\Users\garde\.paddlehub\modules\pyramidbox_lite_server_mask\module.py", line 127, in face_detection
    images, paths, use_gpu, use_multi_scale):
  File "C:\Users\garde\.paddlehub\modules\pyramidbox_lite_server_mask\data_feed.py", line 183, in reader
    scale_res = np.row_stack(scale_res)
  File "<__array_function__ internals>", line 6, in vstack
  File "D:\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```
但是在进行其他图像处理的时候，就不会出错，一开始以为是因为图像中检测不出人脸，但是后来专门选了一个没有人脸的景色图像处理了一下，发现没有bug。很奇怪。

测试图像
```
链接：https://pan.baidu.com/s/1RYIAK1Vj6AmiowrcBrx8Zg 
提取码：ysep 
复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V2的分享
```

**Comment by haoyuying** [comment]
您好，感谢您的反馈，我们将会近期修复这个问题，感谢您的贡献。

**Comment by gardenofever** [comment]
我发现了，是如果图像中完全没有人脸，如果使用use_multi_scale的话，就会出错。
在data_feed.py中，如果使用了multi-scale，就会np.row_stack(scale_res)一下，但是如果没有检测出来人脸，这里scale_res就是空的，于是就会出错。请修正一下。
之前景物的图像居然也被误检出一个人脸，所以没发现问题。
