### ISSUE TITLE
安装语音合成包 transformer_tts_ljspeech 报错提示ImportError: cannot import name 'DataFormatError'

### ISSUE THREAD

**Issue by dongzitai** [PaddlePaddle/PaddleFormers#1197]
操作系统：Linux
发行版：CentOS Linux release 7.9.2009 (Core)
python: Python 3.6.8 (default, Nov 16 2020, 16:55:22)
paddle：
paddlehub           2.0.0rc0
paddlenlp           2.0.0b2
paddlepaddle        2.0.0rc1

安装命令：
hub install transformer_tts_ljspeech==1.0.0
报错信息：
==================================================
Record at 2021-01-18 13:09:22
==================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/manager.py", line 222, in search
    module = self._local_modules[name] = HubModule.load(module_dir)
  File "/usr/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/usr/local/lib/python3.6/site-packages/paddlehub/utils/utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/transformer_tts_ljspeech/module.py", line 26, in <module>
    from paddlehub.module.nlp_module import DataFormatError
ImportError: cannot import name 'DataFormatError'

**Comment by KPatr1ck** [comment]
你好，由于包的目录结构改变，`DataFormatError`这个类的import路径需要更改，transformer_tts_ljspeech 1.0.0的module目前暂未升级到动态图，在之后的升级会修复该问题

> File "/root/.paddlehub/modules/transformer_tts_ljspeech/module.py", line 26, in
from paddlehub.module.nlp_module import DataFormatError
ImportError: cannot import name 'DataFormatError'

可以先改成下面的import路径再试一次
> from paddlehub.compat.module.nlp_module import DataFormatError

**Comment by dongzitai** [comment]
> 你好，由于包的目录结构改变，`DataFormatError`这个类的import路径需要更改，transformer_tts_ljspeech 1.0.0的module目前暂未升级到动态图，在之后的升级会修复该问题
> 
> > File "/root/.paddlehub/modules/transformer_tts_ljspeech/module.py", line 26, in
> > from paddlehub.module.nlp_module import DataFormatError
> > ImportError: cannot import name 'DataFormatError'
> 
> 可以先改成下面的import路径再试一次
> 
> > from paddlehub.compat.module.nlp_module import DataFormatError

paddlehub的这个版本是基于Parakeet的release/v0.1开发的，和0.2在结构上差异太大，安装的过程出现的问题太多了。。暂时没法用了
