### ISSUE TITLE
paddlehub 2.0 版本安装出现错误，怎么解决

### ISSUE THREAD

**Issue by pby231** [PaddlePaddle/PaddleFormers#1201]
[2021-01-19 16:43:40,561] [ WARNING] - An error was encountered while loading ernie_gen_couplet. Detailed error information can be found in the /home/pby231/.paddlehub/log/20210119.log.
[2021-01-19 16:43:40,562] [ WARNING] - An error was encountered while loading ernie_gen_couplet. Detailed error information can be found in the /home/pby231/.paddlehub/log/20210119.log.
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/ernie_gen_couplet.tar.gz
[##################################################] 100.00%
Decompress /home/pby231/.paddlehub/tmp/tmpfuaqj0eg/ernie_gen_couplet.tar.gz
[##################################################] 100.00%
[2021-01-19 16:44:48,797] [    INFO] - Successfully uninstalled ernie_gen_couplet
Traceback (most recent call last):
  File "anli.py", line 28, in <module>
    module_similar = hub.Module(name="ernie_gen_couplet") # 调用对联生成的模型
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/module.py", line 171, in __new__
    module = cls.init_with_name(
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/module.py", line 263, in init_with_name
    user_module_cls = manager.install(name=name, version=version, source=source, update=update, branch=branch)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 188, in install
    return self._install_from_name(name, version)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 263, in _install_from_name
    return self._install_from_url(item['url'])
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 256, in _install_from_url
    return self._install_from_archive(file)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 361, in _install_from_archive
    return self._install_from_directory(directory)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 345, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/utils/utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pby231/.paddlehub/modules/ernie_gen_couplet/module.py", line 21, in <module>
    from paddlehub.module.nlp_module import DataFormatError
ImportError: cannot import name 'DataFormatError' from 'paddlehub.module.nlp_module' (/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/nlp_module.py)

**Comment by pby231** [comment]
能帮忙解决一下吗？比较着急

**Comment by Cy6er7um** [comment]
你安装的命令是什么？Python的环境？Paddlepaddle版本什么的都发一下
