### ISSUE TITLE
hub install ernie_gen_poetry==1.0.2 安装报错

### ISSUE THREAD

**Issue by pby231** [PaddlePaddle/PaddleFormers#1205]
hub install ernie_gen_lover_words==1.0.1
/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/ernie_gen_lover_words.tar.gz
[##################################################] 100.00%
Decompress /home/pby231/.paddlehub/tmp/tmprh4y_s4_/ernie_gen_lover_words.tar.gz
[##################################################] 100.00%
Traceback (most recent call last):
  File "/opt/anaconda3/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/commands/utils.py", line 69, in execute
    return com['_entry']().execute(sys.argv[idx:])
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/commands/install.py", line 44, in execute
    manager.install(name=name, version=version)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 188, in install
    return self._install_from_name(name, version)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 263, in _install_from_name
    return self._install_from_url(item['url'])
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 256, in _install_from_url
    return self._install_from_archive(file)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 361, in _install_from_archive
    return self._install_from_directory(directory)
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/manager.py", line 345, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/opt/anaconda3/lib/python3.8/site-packages/paddlehub/utils/utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pby231/.paddlehub/modules/ernie_gen_lover_words/module.py", line 21, in <module>
    from paddlehub.module.nlp_module import DataFormatError
ImportError: cannot import name 'DataFormatError' from 'paddlehub.module.nlp_module' (/opt/anaconda3/lib/python3.8/site-packages/paddlehub/module/nlp_module.py)

怎么解决呢

**Comment by KPatr1ck** [comment]
你好，你的问题和[#1197](https://github.com/PaddlePaddle/PaddleHub/issues/1197#issuecomment-762680403)类似，可以参考解决。之后paddlehub和module更新将修复这个问题~
