### ISSUE TITLE
AttributeError: module 'paddlehub' has no attribute 'Module'

### ISSUE THREAD

**Issue by quarechen** [PaddlePaddle/PaddleFormers#1233]
运行demo失败
`import paddlehub as hub`
`module = hub.Module(name="deeplabv3p_xception65_humanseg")  `
`res = module.segmentation(paths = ["./test.jpg"], visualization=True, output_dir='humanseg_output') `
- 版本、环境信息
1）PaddleHub-2.0.0rc0 和PaddlePaddle-gpu-2.2.0rc1
2）Windows10，python-3.7

> D:\software\anaconda\python.exe D:/project/learnPaddle/paddle.py
Traceback (most recent call last):
  File "D:/project/learnPaddle/paddle.py", line 1, in <module>
    import paddlehub as hub   # 导入PaddleHub代码库
  File "D:\software\anaconda\lib\site-packages\paddlehub\__init__.py", line 24, in <module>
    from paddlehub import datasets
  File "D:\software\anaconda\lib\site-packages\paddlehub\datasets\__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas
  File "D:\software\anaconda\lib\site-packages\paddlehub\datasets\canvas.py", line 19, in <module>
    import paddle
  File "D:\project\learnPaddle\paddle.py", line 2, in <module>
    module = hub.Module(name="deeplabv3p_xception65_humanseg")    # 指定模型名称
AttributeError: module 'paddlehub' has no attribute 'Module'

**Comment by Cy6er7um** [comment]
你的hub可能有、问题

**Comment by haoyuying** [comment]
您好，建议您将hub卸载后重新安装。

**Comment by quarechen** [comment]
解决了。。。不小心把文件命名为paddle.py了，改名字就好了

**Comment by nanli2018** [comment]
哈喽，哪个文件改名字

**Comment by quarechen** [comment]
> 哈喽，哪个文件改名字

就是自己写的运行这个项目的名字
