### ISSUE TITLE
hub serving start multiprocess workers 问题

### ISSUE THREAD

**Issue by tintinxue1** [PaddlePaddle/PaddleFormers#1239]
1）PaddleHub和PaddlePaddle版本：2.0.0
2）MacOS, python 3.7.9

paddleocr用hub serving start -m ocr_det 加上 --use_multiprocess --workers 4 的话，server会一直boot新的worker, 然后client方一会儿就会connection error,试过好多次都是这样。用了Docker的镜像打包serving的。client方面的错误如下：
```
Traceback (most recent call last):
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_hubserving.py", line 117, in <module>
    main(server_url, image_path)
  File "test_hubserving.py", line 87, in main
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bxue/Applications/anaconda/anaconda3/envs/paddleocr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
server方面一直看到booting新的worker.

**Comment by NATHAN76543217** [comment]
Hi, I have the same issue, how did you do for make it work?

**Comment by YasinZhao** [comment]
同样的问题，请问楼主怎么解决的

**Comment by tintinxue1** [comment]
> 同样的问题，请问楼主怎么解决的

是docker的RAM分配不足，它不会报错，只会重启worker, 我给docker多分配了RAM就可以了。



> Hi, I have the same issue, how did you do for make it work?

so basically docker used limited resources that's why it kept rebooting the worker. I assigned more RAM to docker and it's resolved.

**Comment by YasinZhao** [comment]
> > 同样的问题，请问楼主怎么解决的
> 
> 是docker的RAM分配不足，它不会报错，只会重启worker, 我给docker多分配了RAM就可以了。
> 
> > Hi, I have the same issue, how did you do for make it work?
> 
> so basically docker used limited resources that's why it kept rebooting the worker. I assigned more RAM to docker and it's resolved.

感谢楼主，我去试一下

**Comment by xiachaoxulu** [comment]
macos  本机 使用use_multiprocess， 怎么解决这个楼主的这个问题？
