### ISSUE TITLE
请给一个含paddlehub的docker

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/PaddleFormers#1252]
请给一个含paddlehub的docker。
我自己装的老是缺少缺那，跑不起来。

 File "/usr/local/python3/lib/python3.8/site-packages/paddlehub/utils/utils.py", line 18, in <module>
    import cv2
  File "/usr/local/python3/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by KPatr1ck** [comment]
你好，目前paddlehub没有提供docker的安装方式。
目前你具体安装的paddlepaddle和paddlehub的版本分别是多少呢？然后你是用哪个module的时候跑不起来？

**Comment by 60999** [comment]
出现了同样问题 pp2.0.1 paddlehub-2.0.4

#hub install abc.zip 

/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/datasets/__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/datasets/canvas.py", line 24, in <module>
    from paddlehub.utils.download import download_data
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/utils/download.py", line 22, in <module>
    from paddlehub.utils import log, utils, xarfile
  File "/usr/local/lib/python3.7/dist-packages/paddlehub/utils/utils.py", line 18, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by 60999** [comment]
解决参考  #1090
