### ISSUE TITLE
deeplabv3p_xception65_humanseg

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/PaddleFormers#1253]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

为社么这个模块现在不稳定？
import os
import paddlehub as hub
import cv2
humanseg = hub.Module(name="deeplabv3p_xception65_humanseg")
path = 'E:/项目/image/'
files = os.listdir(path)
imgs = []
for i in files:
    imgs.append(path+i)
results = humanseg.segmentation(data = {'image':imgs})

[2021-02-23 21:13:48,583] [    INFO] - Installing deeplabv3p_xception65_humanseg module
[2021-02-23 21:13:48,628] [    INFO] - Module deeplabv3p_xception65_humanseg already installed in C:\Users\lenovo\.paddlehub\modules\deeplabv3p_xception65_humanseg
Traceback (most recent call last):
  File "E:/项目/unit3/predict_module/demo2.py", line 15, in <module>
    results = humanseg.segmentation(data = {'image':imgs})
  File "C:\Users\lenovo\.paddlehub\modules\deeplabv3p_xception65_humanseg\module.py", line 95, in segmentation
    for yield_data in reader(images, paths):
  File "C:\Users\lenovo\.paddlehub\modules\deeplabv3p_xception65_humanseg\data_feed.py", line 31, in reader
    im = cv2.imread(im_path).astype('float32')
AttributeError: 'NoneType' object has no attribute 'astype'
E:/项目/image/22 .jpg

Process finished with exit code 1

**Comment by haoyuying** [comment]
这个报错出现在im_path传入又问题，可能是由于path中有中文字符导致的，建议更换im_path的地址。
