### ISSUE TITLE
TypeError: 'property' object is not callable

### ISSUE THREAD

**Issue by Andy546** [PaddlePaddle/PaddleFormers#1264]
- 版本、环境信息
1）paddlehub          2.0.0
paddlepaddle       2.0.0rc0
2）系统环境：MacOS，python3.7

报错信息：TypeError: 'property' object is not callable
在执行
`hub run lac --input_text "今天是个好日子"`
时报错。全部报错信息如下：
`/Users/andy/anaconda3/envs/python37/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/Users/andy/anaconda3/envs/python37/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
Traceback (most recent call last):
  File "/Users/andy/anaconda3/envs/python37/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/Users/andy/anaconda3/envs/python37/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/Users/andy/anaconda3/envs/python37/lib/python3.7/site-packages/paddlehub/commands/run.py", line 56, in execute
    result = module._run_func(argv[1:])
TypeError: 'property' object is not callable`

**Comment by KPatr1ck** [comment]
你好，检查一下lac模块是否正确安装了。

以下是我本地的测试环境和情况，可以正常执行的。
```
paddlepaddle     2.0.0
paddlehub        2.0.0
```
```
$ hub run lac --input_text "今天是个好日子" 
[{'word': ['今天', '是', '个', '好日子'], 'tag': ['TIME', 'v', 'q', 'n']}]
```

**Comment by Andy546** [comment]
> 你好，检查一下lac模块是否正确安装了。
> 
> 以下是我本地的测试环境和情况，可以正常执行的。
> 
> ```
> paddlepaddle     2.0.0
> paddlehub        2.0.0
> ```
> 
> ```
> $ hub run lac --input_text "今天是个好日子" 
> [{'word': ['今天', '是', '个', '好日子'], 'tag': ['TIME', 'v', 'q', 'n']}]
> ```

你好，第一次执行时报的错，lac模块还没下载下来就报错了。修改Paddlehub以前版本可以正常执行了。
目前版本为：
`paddlehub 1.8.3`

**Comment by 1084667371** [comment]
不需要降低版本，你换一个目录运行命令行的命令即可，你那是因为安装和运行命令在一个目录了
