### ISSUE TITLE
DataLoader reader thread raised an exception

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/PaddleFormers#1267]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub2.0.0，PaddlePaddle2.0
2）系统环境：MacOS，python 3.8

运行PaddleHub-release-v2.0/demo/sequence_labeling 报错

```
/Users/rai/opt/anaconda3/envs/paddle/bin/python /Users/rai/PycharmProjects/med_entity/PaddleHub-release-v2.0/demo/sequence_labeling/train.py
/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
[2021-02-26 16:58:56,987] [    INFO] - Already cached /Users/rai/.paddlenlp/models/ernie-tiny/ernie_tiny.pdparams
/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for classifier.weight. classifier.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1263: UserWarning: Skip loading for classifier.bias. classifier.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
[2021-02-26 16:59:05,411] [    INFO] - Found /Users/rai/.paddlenlp/models/ernie-tiny/vocab.txt
[2021-02-26 16:59:05,420] [    INFO] - Found /Users/rai/.paddlenlp/models/ernie-tiny/spm_cased_simp_sampled.model
[2021-02-26 16:59:05,422] [    INFO] - Found /Users/rai/.paddlenlp/models/ernie-tiny/dict.wordseg.pickle
[2021-02-26 16:59:42,962] [ WARNING] - PaddleHub model checkpoint not found, start from scratch...
WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/Users/rai/PycharmProjects/med_entity/PaddleHub-release-v2.0/demo/sequence_labeling/train.py", line 66, in <module>
    trainer.train(
  File "/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlehub/finetune/trainer.py", line 197, in train
    for batch_idx, batch in enumerate(loader):
  File "/Users/rai/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 365, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/reader/blocking_queue.h:158)


Process finished with exit code 1

```

**Comment by KPatr1ck** [comment]
你好，请问下你是用了自定义的数据集吗？

```
paddlehub                     2.0.0
paddlepaddle                  2.0.0
```
刚测试了在MacOS中，以上的环境`PaddleHub/demo/sequence_labeling/train.py`是可以正常执行训练的。

**Comment by Ryan906k9** [comment]
> 你好，请问下你是用了自定义的数据集吗？
> 
> ```
> paddlehub                     2.0.0
> paddlepaddle                  2.0.0
> ```
> 
> 刚测试了在MacOS中，以上的环境`PaddleHub/demo/sequence_labeling/train.py`是可以正常执行训练的。

下载了PaddleHub-release-v2.0后运行/demo/sequence_labeling/train.py 发生的报错，由于用的是MacBook，所以没有GPU，会是这个原因吗？

**Comment by KPatr1ck** [comment]
> 下载了PaddleHub-release-v2.0后运行/demo/sequence_labeling/train.py 发生的报错，由于用的是MacBook，所以没有GPU，会是这个原因吗？

跟gpu没关系，只有cpu也可以跑的。
试一下`pip install paddlenlp==2.0.0rc2`后再执行

**Comment by Ryan906k9** [comment]
> > 下载了PaddleHub-release-v2.0后运行/demo/sequence_labeling/train.py 发生的报错，由于用的是MacBook，所以没有GPU，会是这个原因吗？
> 
> 根gpu没关系，只有cpu也可以跑的。
> 试一下`pip install paddlenlp==2.0.0rc2`后再执行

安装后 paddlenlp==2.0.0rc2 可以运行了，非常感谢！感觉Paddle各个模块版本太多，常常出现这种不兼容但不知道哪里出错的情况啊～～

**Comment by jeffzhengye** [comment]
DataLoader reader thread raised an exception.
这种错误非常恶心，无法调试。

用tf 很少遇到自己无法解决的问题
