### ISSUE TITLE
paddlehub 1.8.3 句子相似度demo报错 是否是模型接口变化了？

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleFormers#1284]
运行代码为PaddleHub/demo/sentence_similarity/sensim.py

[2021-03-05 19:19:01,593] [    INFO] - Installing word2vec_skipgram module
[2021-03-05 19:19:01,599] [    INFO] - Module word2vec_skipgram already installed in C:\Users\Mao Xueyu\.paddlehub\modules\word2vec_skipgram
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/tmp/tmp3.py", line 27, in <module>
    word_ids = inputs["word_ids"]
KeyError: 'word_ids'

**Comment by Macxy2018** [comment]
模型加载为1.0.0版本的模型
hub install word2vec_skipgram==1.0.0
