### ISSUE TITLE
paddlehub-2.0.4 文本生成 ernie_tiny_couplet模型无法使用，报错AttributeError: 'ErnieTiny' object has no attribute 'context'

### ISSUE THREAD

**Issue by iloveopenworld** [PaddlePaddle/PaddleFormers#1302]
环境：
pip show paddlepaddle
Name: paddlepaddle
Version: 2.0.1
paddlehub-2.0.4
ubunt18.04.5 LTS (Bionic Beaver) Python 3.7.10

步骤：
按照这个链接里的操作：https://www.paddlepaddle.org.cn/hubdetail?name=ernie_tiny_couplet&en_category=TextGeneration
提示  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieTiny' object has no attribute 'context'

详细步骤和报错如下：
hub install ernie_tiny_couplet==1.0.0
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
2021-03-10 14:19:20,300 - INFO - Lock 140531860536144 acquired on /root/.paddlehub/tmp/ernie_tiny_couplet
[INFO 2021-03-10 14:19:20,300 filelock.py:274] Lock 140531860536144 acquired on /root/.paddlehub/tmp/ernie_tiny_couplet
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/ernie_tiny_couplet_1.0.0.tar.gz
[##################################################] 100.00%
Decompress /root/.paddlehub/tmp/tmpgh7ldn0k/ernie_tiny_couplet_1.0.0.tar.gz
[##################################################] 100.00%
[2021-03-10 14:19:47,414] [    INFO] - Successfully installed ernie_tiny_couplet-1.0.0
2021-03-10 14:19:47,578 - INFO - Lock 140531860536144 released on /root/.paddlehub/tmp/ernie_tiny_couplet
[INFO 2021-03-10 14:19:47,578 filelock.py:318] Lock 140531860536144 released on /root/.paddlehub/tmp/ernie_tiny_couplet
(paddle) root@7fbaa7b5c0cd:/workdir/paddle/�ı����# 
(paddle) root@7fbaa7b5c0cd:/workdir/paddle/�ı����# 
(paddle) root@7fbaa7b5c0cd:/workdir/paddle/�ı����# 
(paddle) root@7fbaa7b5c0cd:/workdir/paddle/�ı����# cd ..
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# hub run ernie_tiny_couplet --input_text '风吹云乱天垂泪'
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-03-10 14:20:05,175] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
2021-03-10 14:20:05,176 - INFO - Lock 139730637311696 acquired on /root/.paddlehub/tmp/ernie_tiny
[INFO 2021-03-10 14:20:05,176 filelock.py:274] Lock 139730637311696 acquired on /root/.paddlehub/tmp/ernie_tiny
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/ernie_tiny_2.0.1.tar.gz
[##################################################] 100.00%
Decompress /root/.paddlehub/tmp/tmpggv7d1um/ernie_tiny_2.0.1.tar.gz
[##################################################] 100.00%
[2021-03-10 14:20:05,892] [    INFO] - Successfully installed ernie_tiny-2.0.1
2021-03-10 14:20:05,893 - INFO - Lock 139730637311696 released on /root/.paddlehub/tmp/ernie_tiny
[INFO 2021-03-10 14:20:05,893 filelock.py:318] Lock 139730637311696 released on /root/.paddlehub/tmp/ernie_tiny
[2021-03-10 14:20:05,894] [    INFO] - Downloading https://paddlenlp.bj.bcebos.com/models/transformers/ernie_tiny/ernie_tiny.pdparams and saved to /root/.paddlenlp/models/ernie-tiny
[2021-03-10 14:20:05,894] [    INFO] - Downloading ernie_tiny.pdparams from https://paddlenlp.bj.bcebos.com/models/transformers/ernie_tiny/ernie_tiny.pdparams
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 354158/354158 [00:14<00:00, 23840.59it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 47, in execute
    module = Module(name=module_name)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 172, in __new__
    name=name, version=version, source=source, update=update, branch=branch, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 274, in init_with_name
    user_module._initialize(**kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/root/.paddlehub/modules/ernie_tiny_couplet/module.py", line 36, in _initialize
    inputs, outputs, program = self.module.context(
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieTiny' object has no attribute 'context'
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# import paddlehub as hub
bash: import: command not found
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# 
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# # Load ernie pretrained model
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# module = hub.Module(name="ernie_tiny_couplet", use_gpu=True)
bash: syntax error near unexpected token `('
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# results = module.generate(["风吹云乱天垂泪", "若有经心风过耳"])
bash: syntax error near unexpected token `('
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# for result in results:
>     print(result)^C
(paddle) root@7fbaa7b5c0cd:/workdir/paddle# python
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub as hub
# Load ernie pretrained model
module = hub.Module(name="ernie_tiny_couplet", use_gpu=True)
results = module.generate(["风吹云乱天垂泪", "若有经心风过耳"])
for result in results:
    print(result)

/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
>>> 
>>> # Load ernie pretrained model
>>> module = hub.Module(name="ernie_tiny_couplet", use_gpu=True)
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/root/miniconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-03-10 14:20:48,782] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2021-03-10 14:20:48,785] [    INFO] - Already cached /root/.paddlenlp/models/ernie-tiny/ernie_tiny.pdparams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 172, in __new__
    name=name, version=version, source=source, update=update, branch=branch, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 274, in init_with_name
    user_module._initialize(**kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/root/.paddlehub/modules/ernie_tiny_couplet/module.py", line 36, in _initialize
    inputs, outputs, program = self.module.context(
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieTiny' object has no attribute 'context'
>>> results = module.generate(["风吹云乱天垂泪", "若有经心风过耳"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'module' is not defined
>>> for result in results:
...     print(result)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'results' is not defined
>>> 
>>> 
>>> print()
KeyboardInterrupt
>>> import paddlehub as hub
>>> module = hub.Module(name="ernie_tiny_couplet", use_gpu=True)
[2021-03-10 14:21:01,775] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2021-03-10 14:21:01,776] [    INFO] - Already cached /root/.paddlenlp/models/ernie-tiny/ernie_tiny.pdparams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 172, in __new__
    name=name, version=version, source=source, update=update, branch=branch, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 274, in init_with_name
    user_module._initialize(**kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/root/.paddlehub/modules/ernie_tiny_couplet/module.py", line 36, in _initialize
    inputs, outputs, program = self.module.context(
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieTiny' object has no attribute 'context'
>>> module = hub.Module(name="ernie_tiny_couplet")              
[2021-03-10 14:21:07,832] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2021-03-10 14:21:07,833] [    INFO] - Already cached /root/.paddlenlp/models/ernie-tiny/ernie_tiny.pdparams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 172, in __new__
    name=name, version=version, source=source, update=update, branch=branch, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 274, in init_with_name
    user_module._initialize(**kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/root/.paddlehub/modules/ernie_tiny_couplet/module.py", line 36, in _initialize
    inputs, outputs, program = self.module.context(
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieTiny' object has no attribute 'context'

**Comment by KPatr1ck** [comment]
![image](https://user-images.githubusercontent.com/22954146/110588577-2af72800-81b0-11eb-8f10-52047550d55d.png)

你好，建议同步到以下环境，再尝试安装使用ernie_tiny_couplet

paddlehub 1.8.0
paddlepaddle-gpu 1.8.4.post97
