### ISSUE TITLE
paddlehub-2.0.4 词法分析 LAC服务部署运行时报错

### ISSUE THREAD

**Issue by iloveopenworld** [PaddlePaddle/PaddleFormers#1303]
环境：
pip show paddlepaddle
Name: paddlepaddle
Version: 2.0.1
paddlehub-2.0.4
ubunt18.04.5 LTS (Bionic Beaver) Python 3.7.10

步骤：
按照这个链接里的操作：https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis
配置文件lac_serving_config：{
  "modules_info": {
    "lac": {
      "init_args": {
        "version": "2.2.0"
      }
    }
  },
  "port": 8866,
  "use_singleprocess": false,
  "workers": 2
}
执行：hub serving start -c lac_serving_config.json
[2021-03-10 14:28:28,428] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0310 14:28:28.459650 19432 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
 * Serving Flask app "paddlehub.serving.app_compat" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2021-03-10 14:28:28,516 - INFO -  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
[INFO 2021-03-10 14:28:28,516 _internal.py:113]  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)

执行发送预测请求，代码如下：
# hub serving start -c lac_serving_config.json
def 发送预测请求():
    import requests
    import json

    # 待预测数据
    text = ["今天是个好日子", "天气预报说今天要下雨"]

    # 设置运行配置
    # 对应本地预测lac.cut(text=text, batch_size=1)
    data = {"text": text, "batch_size": 1}

    # 指定预测方法为lac并发送post请求，content-type类型应指定json方式
    # HOST_IP为服务器IP
    url = "http://127.0.0.1:8866/predict/lac"
    headers = {"Content-Type": "application/json"}
    r = requests.post(url=url, headers=headers, data=json.dumps(data))

    # 打印预测结果
    print(json.dumps(r.json(), indent=4, ensure_ascii=False))

if __name__ == '__main__':
    发送预测请求()

报错：
Traceback (most recent call last):
  File "C:/workspace/quantway/python_test/paddle_test/词法分析.py", line 53, in <module>
    发送预测请求()
  File "C:/workspace/quantway/python_test/paddle_test/词法分析.py", line 50, in 发送预测请求
    print(json.dumps(r.json(), indent=4, ensure_ascii=False))
  File "C:\Anaconda3-5.2.0-64\envs\baiduAI3.7.4\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Anaconda3-5.2.0-64\envs\baiduAI3.7.4\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3-5.2.0-64\envs\baiduAI3.7.4\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3-5.2.0-64\envs\baiduAI3.7.4\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

服务器端同时报错：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3-5.2.0-64\envs\baiduai3.7.4\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "c:\anaconda3-5.2.0-64\envs\baiduai3.7.4\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "c:\anaconda3-5.2.0-64\envs\baiduai3.7.4\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\anaconda3-5.2.0-64\envs\baiduai3.7.4\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "c:\anaconda3-5.2.0-64\envs\baiduai3.7.4\lib\site-packages\flask\app.py", line 1871, in handle_exception
    self.log_exception((exc_type, exc_value, tb))
  File "c:\anaconda3-5.2.0-64\envs\baiduai3.7.4\lib\site-packages\flask\app.py", line 1892, in log_exception
    "Exception on %s [%s]" % (request.path, request.method), exc_info=exc_info
TypeError: __call__() got an unexpected keyword argument 'exc_info'

**Comment by KPatr1ck** [comment]
```json
{
  "modules_info": {
    "lac": {
      "init_args": {
        "version": "2.2.0"
      },
      "predict_args": {}
    }
  },
  "port": 8866,
  "use_singleprocess": false,
  "workers": 2
}
```

用这个json配置文件试一下
