### ISSUE TITLE
paddlehub-2.0.4 语音合成 hub run transformer_tts_ljspeech --input_text="Life was like a box of chocolates, you never know what you're gonna get." --use_gpu True --vocoder griffin-lim 执行报错

### ISSUE THREAD

**Issue by iloveopenworld** [PaddlePaddle/PaddleFormers#1304]
环境：
pip show paddlepaddle
Name: paddlepaddle
Version: 2.0.1
paddlehub-2.0.4
ubunt18.04.5 LTS (Bionic Beaver) Python 3.7.10
以及：
pip list|grep paddle                       
paddlehub          1.8.0
paddlenlp          2.0.0rc10
paddlepaddle       1.8.4
以及：
paddlehub          1.8.2
都做了尝试，都报错，如下：

hub run transformer_tts_ljspeech --input_text="Life was like a box of chocolates, you never know what you're gonna get." --use_gpu True --vocoder griffin-lim
Install Module transformer_tts_ljspeech
Downloading transformer_tts_ljspeech
[==================================================] 100.00%
Uncompress /root/.paddlehub/tmp/tmpfv0nryzk/transformer_tts_ljspeech
[==================================================] 100.00%
Successfully installed transformer_tts_ljspeech-1.0.0
Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 232, in execute
    self.module = self.find_module(module_name)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 71, in find_module
    return hub.Module(directory=module_dir[0])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "/root/miniconda3/envs/paddle/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/transformer_tts_ljspeech/module.py", line 68, in <module>
    % ", ".join(lack_dependency))
ImportError: The module requires additional dependencies: ruamel, parakeet, soundfile, librosa. You can install parakeet via 'git clone https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .' and others via pip install

**Comment by KPatr1ck** [comment]
```
ImportError: The module requires additional dependencies: ruamel, parakeet, soundfile, librosa. You can install parakeet via 'git clone https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .' and others via pip install
```

你好，根据提示，需要额外手动安装以下几个依赖库：
ruamel, parakeet, soundfile, librosa

**Comment by iloveopenworld** [comment]
> ```
> ImportError: The module requires additional dependencies: ruamel, parakeet, soundfile, librosa. You can install parakeet via 'git clone https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .' and others via pip install
> ```
> 
> 你好，根据提示，需要额外手动安装以下几个依赖库：
> ruamel, parakeet, soundfile, librosa

其他三个都能顺利安装好，目前最新的parakeet 0.24（https://pypi.org/project/parakeet/0.24/#files）好像是py2的。把setpy.py里的改了，能顺利安装上parakeet 。
但是执行命令还是报错 ：hub run transformer_tts_ljspeech --input_text="Life was like a box of chocolates, you never know what you're gonna get." --use_gpu True --vocoder griffin-lim
GE3DCNJTHE2DQNRYFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.V6X3JNZUXIX27FZYHS000.f67c6b0.testpcurl.com
GE3DCNJTHE2DQNZZFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.XSYLNNQXV6X3JNZUXIX27FZYHS000.9306460.testpcurl.com
Install Module transformer_tts_ljspeech
Downloading transformer_tts_ljspeech
[==================================================] 100.00%
Uncompress /root/.paddlehub/tmp/tmp7xsu7jyt/transformer_tts_ljspeech
[==================================================] 100.00%
Successfully installed transformer_tts_ljspeech-1.0.0
Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 232, in execute
    self.module = self.find_module(module_name)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 71, in find_module
    return hub.Module(directory=module_dir[0])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "/root/miniconda3/envs/paddle/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/transformer_tts_ljspeech/module.py", line 59, in <module>
    from parakeet.g2p.en import text_to_sequence
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/parakeet-0.24-py3.7.egg/parakeet/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'config'

**Comment by iloveopenworld** [comment]
pip freeze|grep paddle
paddlehub==1.8.0
paddlenlp==2.0.0rc10
paddlepaddle==1.8.4

这个语音模型 fastspeech_ljspeech 也有这个问题
https://www.paddlepaddle.org.cn/hubdetail?name=fastspeech_ljspeech&en_category=TextToSpeech
详细问题如下：
hub install fastspeech_ljspeech==1.0.0
GE3DCNJTHE3DSMJWFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.V6X3JNZUXIX27FZYHS000.6064680.testpcurl.com
GE3DCNJTHE3DSMRXFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.XSYLNNQXV6X3JNZUXIX27FZYHS000.8f0b3f0.testpcurl.com
Downloading fastspeech_ljspeech
[==================================================] 100.00%
Uncompress /root/.paddlehub/tmp/tmpmrwdu_7f/fastspeech_ljspeech
[==================================================] 100.00%
Successfully installed fastspeech_ljspeech-1.0.0
(paddle) root@7fbaa7b5c0cd:/workdir/paddle/yuyinhecheng# hub run fastspeech_ljspeech --input_text='Simple as this proposition is, it is necessary to be stated'
GE3DCNJTHE3DSOBYFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.V6X3JNZUXIX27FZYHS000.c149170.testpcurl.com
GE3DCNJTHE3DSOJYFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.XSYLNNQXV6X3JNZUXIX27FZYHS000.010e990.testpcurl.com
Install Module fastspeech_ljspeech
Downloading fastspeech_ljspeech
[==================================================] 100.00%
Uncompress /root/.paddlehub/tmp/tmphgl3iulp/fastspeech_ljspeech
[==================================================] 100.00%
Successfully installed fastspeech_ljspeech-1.0.0
Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 232, in execute
    self.module = self.find_module(module_name)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 71, in find_module
    return hub.Module(directory=module_dir[0])
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "/root/miniconda3/envs/paddle/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/fastspeech_ljspeech/module.py", line 58, in <module>
    from parakeet.models.fastspeech.fastspeech import FastSpeech as FastSpeechModel
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/parakeet-0.24-py3.7.egg/parakeet/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'config'

**Comment by KPatr1ck** [comment]
> > ```
> > ImportError: The module requires additional dependencies: ruamel, parakeet, soundfile, librosa. You can install parakeet via 'git clone https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .' and others via pip install
> > ```
> > 
> > 
> > 你好，根据提示，需要额外手动安装以下几个依赖库：
> > ruamel, parakeet, soundfile, librosa
> 
> 其他三个都能顺利安装好，目前最新的parakeet 0.24（[https://pypi.org/project/parakeet/0.24/#files）好像是py2的。把setpy.py里的改了，能顺利安装上parakeet](https://pypi.org/project/parakeet/0.24/#files%EF%BC%89%E5%A5%BD%E5%83%8F%E6%98%AFpy2%E7%9A%84%E3%80%82%E6%8A%8Asetpy.py%E9%87%8C%E7%9A%84%E6%94%B9%E4%BA%86%EF%BC%8C%E8%83%BD%E9%A1%BA%E5%88%A9%E5%AE%89%E8%A3%85%E4%B8%8Aparakeet) 。
> 但是执行命令还是报错 ：hub run transformer_tts_ljspeech --input_text="Life was like a box of chocolates, you never know what you're gonna get." --use_gpu True --vocoder griffin-lim
> GE3DCNJTHE2DQNRYFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.V6X3JNZUXIX27FZYHS000.f67c6b0.testpcurl.com
> GE3DCNJTHE2DQNZZFQ3WMYTBME3WENLDGBRWILDSN5XXILBRGE4C4MJRG.YXDCNJOGQ3CYL3SN5XXIL3NNFXGSY3PNZSGCMZPMVXHM4ZPOBQWIZDMMU.XWY2LCF5YHS5DIN5XDGLRXF5ZWS5DFFVYGCY3LMFTWK4ZPOJ2WC3LFNQX.XSYLNNQXV6X3JNZUXIX27FZYHS000.9306460.testpcurl.com
> Install Module transformer_tts_ljspeech
> Downloading transformer_tts_ljspeech
> [==================================================] 100.00%
> Uncompress /root/.paddlehub/tmp/tmp7xsu7jyt/transformer_tts_ljspeech
> [==================================================] 100.00%
> Successfully installed transformer_tts_ljspeech-1.0.0
> Traceback (most recent call last):
> File "/root/miniconda3/envs/paddle/bin/hub", line 8, in
> sys.exit(main())
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
> command.execute(argv[1:])
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
> return command.execute(argv[1:])
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 232, in execute
> self.module = self.find_module(module_name)
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/commands/run.py", line 71, in find_module
> return hub.Module(directory=module_dir[0])
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in **new**
> module = cls.init_with_directory(directory=directory, **kwargs)
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/module/module.py", line 193, in init_with_directory
> _module = importlib.import_module("{}.module".format(basename))
> File "/root/miniconda3/envs/paddle/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/root/.paddlehub/modules/transformer_tts_ljspeech/module.py", line 59, in
> from parakeet.g2p.en import text_to_sequence
> File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/parakeet-0.24-py3.7.egg/parakeet/**init**.py", line 1, in
> ModuleNotFoundError: No module named 'config'

Parakeet用0.1分支，安装后再执行
```
git clone -b release/v0.1 https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .
```
