### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 6: invalid start byte

### ISSUE THREAD

**Issue by claudehotline** [PaddlePaddle/PaddleFormers#1341]
PaddlePaddle 2.0.0
PaddleHub 2.0.4
系统环境 window10， python 3.7.10

cmd窗口运行命令hub serving start -m yolov3_darknet53_coco2017报错：

(paddlepaddle) C:\Users\chaisen>hub serving start -m yolov3_darknet53_coco2017
c:\anaconda3\envs\paddlepaddle\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
c:\anaconda3\envs\paddlepaddle\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
c:\anaconda3\envs\paddlepaddle\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-03-25 22:25:01,035] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0325 22:25:01.036675 22920 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
 \* Serving Flask app "paddlehub.serving.app_compat" (lazy loading)
\* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 \* Debug mode: off
Traceback (most recent call last):
  File "c:\anaconda3\envs\paddlepaddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\paddlepaddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\anaconda3\envs\paddlepaddle\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\paddlehub\commands\serving.py", line 352, in execute
    self.start_serving()
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\paddlehub\commands\serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\paddlehub\commands\serving.py", line 223, in start_single_app_with_args
    app.run(configs=self.modules_info, port=port)
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\paddlehub\serving\app_compat.py", line 209, in run
    my_app.run(host="0.0.0.0", port=port, debug=False, threaded=False)
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\werkzeug\serving.py", line 1052, in run_simple
    inner()
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\werkzeug\serving.py", line 1005, in inner
    fd=fd,
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\werkzeug\serving.py", line 863, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "c:\anaconda3\envs\paddlepaddle\lib\site-packages\werkzeug\serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "c:\anaconda3\envs\paddlepaddle\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "c:\anaconda3\envs\paddlepaddle\lib\http\server.py", line 139, in server_bind
    self.server_name = socket.getfqdn(host)
  File "c:\anaconda3\envs\paddlepaddle\lib\socket.py", line 687, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 6: invalid start byte

**Comment by ShenYuhan** [comment]
尝试把你的主机名改成英文再试一下

**Comment by claudehotline** [comment]
谢谢问题解决了
