### ISSUE TITLE
This is a development server. Do not use it in a production deployment

### ISSUE THREAD

**Issue by AP-Kai** [PaddlePaddle/PaddleFormers#1367]
paddlepaddle    1.8.5
paddlehub       1.8.3
python         3.8
ubuntu  18.04

您好，我使用这个[链接](https://www.paddlepaddle.org.cn/hubdetail?name=deeplabv3p_xception65_humanseg&en_category=ImageSegmentation)
提供的服务端部署出现了问题。

当我run了下面的代码之后，
![2](https://user-images.githubusercontent.com/77101860/115133657-808ae400-a03c-11eb-9a6e-6593a565dfcc.png)
服务器端不知道为啥中止了，
![1](https://user-images.githubusercontent.com/77101860/115133633-67823300-a03c-11eb-9dad-570d073d7d36.png)

我想用paddlehub部署人像分割，并获取人像前景图，希望可以解答一下疑惑

**Comment by KPatr1ck** [comment]
`This is a development server. Do not use it in a production deployment.`
这句是warning，不会影响正常的服务。

看你图里的服务应该是正常启动了，没看到有报错的堆栈信息。
你是进行预测之后进程退出吗？有没有更多的报错信息？
方便的话提供一下你的paddlepaddle和paddlehub的版本号。

**Comment by AP-Kai** [comment]
> `This is a development server. Do not use it in a production deployment.`
> 这句话是warning，不会影响正常的服务。
> 
> 看你图里的服务应该是正常启动了，没看到有报错的替代信息。
> 你是进行预测之后进程退出吗？有没有更多的报错信息？
> 方便的话提供一下你的paddlepaddle和paddlehub的版本号。

paddlehub       2.0.4
paddlepaddle    2.0.2
服务器可以正常启动服务，在本地进行预测的时候会报错并且服务会关闭

这是服务端的界面
![1](https://user-images.githubusercontent.com/77101860/115181760-33c20e80-a10b-11eb-8faa-6ca5c56be61e.png)


这是python代码
`import requests
import json
import cv2
import base64

import numpy as np


def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')


def base64_to_cv2(b64str):
    data = base64.b64decode(b64str.encode('utf8'))
    data = np.fromstring(data, np.uint8)
    data = cv2.imdecode(data, cv2.IMREAD_COLOR)
    return data

data = {'images':[cv2_to_base64(cv2.imread("./example1.png"))]}
headers = {"Content-type": "application/json"}
url = "http://115.29.192.231:8866/predict/deeplabv3p_xception65_humanseg"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

print(base64_to_cv2(r.json()["results"][0]['data']))`


这是python的报错
`C:\Python\Python37\python.exe "E:/Python Project/photomaster/test.py"
E:/Python Project/photomaster/test.py:11: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return base64.b64encode(data.tostring()).decode('utf8')
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\Python37\lib\http\client.py", line 1354, in getresponse
    response.begin()
  File "C:\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Python\Python37\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\Python37\lib\http\client.py", line 1354, in getresponse
    response.begin()
  File "C:\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Python\Python37\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Python Project/photomaster/test.py", line 25, in <module>
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "C:\Python\Python37\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Process finished with exit code 1
`
