### ISSUE TITLE
在使用PaddleHub Serving时出现cannot be use for predicting 错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleFormers#1373]
- PaddlePaddle   2.0.1
 - paddlehub       2.0.4

```
e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-04-19 17:26:57,557] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2021-04-19 17:26:57,644] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0419 17:26:57.644044 15676 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
Traceback (most recent call last):
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle2.0\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\paddlehub\commands\serving.py", line 352, in execute
    self.start_serving()
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\paddlehub\commands\serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\paddlehub\commands\serving.py", line 221, in start_single_app_with_args
    self.preinstall_modules()
  File "e:\programdata\anaconda3\envs\paddlepaddle2.0\lib\site-packages\paddlehub\commands\serving.py", line 155, in preinstall_modules
    raise RuntimeError("{} cannot be use for " "predicting".format(key))
RuntimeError: Photo2Cartoon cannot be use for predicting


```

**Comment by ShenYuhan** [comment]
您好，是因为此模型的贡献者没有添加serving方法，我们会尽快升级。
