### ISSUE TITLE
windos  加载  ernie_gen失败  PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by xrzlizheng** [PaddlePaddle/PaddleFormers#1393]
runfile('D:/lz/ERNIE-GEN：汽车大师问答摘要与推理/qichedashi.py', wdir='D:/lz/ERNIE-GEN：汽车大师问答摘要与推理')
[2021-04-27 17:34:03,205] [    INFO] - Installing ernie_gen module
[2021-04-27 17:34:03,304] [    INFO] - Module ernie_gen already installed in C:\Users\lizheng\.paddlehub\modules\ernie_gen
2021-04-27 17:34:03,306-INFO: get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
[INFO 2021-04-27 17:34:03,306 tokenizing_ernie.py:89] get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
downloading https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz: 788478KB [01:35, 8278.39KB/s]                             
Traceback (most recent call last):

  File "D:\lz\ERNIE-GEN：汽车大师问答摘要与推理\qichedashi.py", line 158, in <module>
    **module = hub.Module(name="ernie_gen")**

  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)

  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)

  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)

  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 146, in __init__
    self._initialize(**kwargs)

  File "C:\Users\lizheng\.paddlehub\modules\ernie_gen\module.py", line 55, in _initialize
    "ernie-1.0", mask_token=None)

  File "D:\Anaconda3\lib\site-packages\ernie\tokenizing_ernie.py", line 90, in from_pretrained
    pretrain_dir = _fetch_from_remote(url, force_download=force_download)

  File "D:\Anaconda3\lib\site-packages\ernie\file_utils.py", line 39, in _fetch_from_remote
    with tarfile.open(f.name)  as tf:

  File "D:\Anaconda3\lib\tarfile.py", line 1573, in open
    return func(name, "r", fileobj, **kwargs)

  File "D:\Anaconda3\lib\tarfile.py", line 1638, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)

  File "D:\Anaconda3\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\lizheng\\AppData\\Local\\Temp\\tmpr0fymflz'
![image](https://user-images.githubusercontent.com/33617203/116221024-cdc72e00-a77f-11eb-92e2-dbb933b8d609.png)

相同的环境在 aistudio正常运行，，，，windows版本报错

**Comment by KPatr1ck** [comment]
> 2021-04-27 17:34:03,306-INFO: get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
> [INFO 2021-04-27 17:34:03,306 tokenizing_ernie.py:89] get pretrain dir from https://ernie- github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
> downloading https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz: 788478KB [01:35, 8278.39KB/s]

> File "D:\Anaconda3\lib\gzip.py", line 163, in init
> fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
>
> PermissionError: [Errno 13] Permission denied: 'C:\Users\lizheng\AppData\Local\Temp\tmpr0fymflz'

看起来像预训练模型的文件想要下载存放在`C:\Users\lizheng\AppData\Local\Temp\tmpr0fymflz`，但是这个目录没法写入。
