### ISSUE TITLE
报错：ModuleNotFoundError: No module named 'ernie.module'

### ISSUE THREAD

**Issue by JoeLiaoCHN** [PaddlePaddle/PaddleFormers#1394]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddle-ernie 0.1.0.dev1，paddlehub 2.0.4，paddlenlp 2.0.0rc18，paddlepaddle 2.0.2
2）系统环境：Windows 10，python3.6
- 复现信息：
- 报错：ModuleNotFoundError: No module named 'ernie.module'
- 复现环境：已修改系统变量 HUB_HOME=D:\paddleModule\paddlehub  PPNLP_HOME=D:\paddleModule\paddlenlp

- 代码：
- `import paddlehub as hub

data = [
    ['这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般'],
    ['怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片'],
    ['作为老的四星酒店，房间依然很整洁，相当不错。机场接机服务很好，可以在车上办理入住手续，节省时间。'],
]
label_map = {0: 'negative', 1: 'positive'}

model = hub.Module(
    name='ernie',
    version='2.0.1',
    task='seq-cls',
    load_checkpoint='/path/to/parameters',
    label_map=label_map)
results = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False)
for idx, text in enumerate(data):
    print('Data: {} \t Lable: {}'.format(text, results[idx]))`

- 报错：
- [2021-04-27 18:24:55,856] [ WARNING] - An error was encountered while loading ernie. Detailed error information can be found in the D:\paddleModule\paddlehub\log\20210427.log.
2021-04-27 18:24:55,857 - INFO - Lock 1605758886296 acquired on D:\paddleModule\paddlehub\tmp\ernie
[INFO 2021-04-27 18:24:55,857 filelock.py:274] Lock 1605758886296 acquired on D:\paddleModule\paddlehub\tmp\ernie
[2021-04-27 18:24:55,862] [ WARNING] - An error was encountered while loading ernie. Detailed error information can be found in the D:\paddleModule\paddlehub\log\20210427.log.
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/ernie_2.0.1.tar.gz
[##################################################] 100.00%
Decompress D:\paddleModule\paddlehub\tmp\tmp44jmj_5u\ernie_2.0.1.tar.gz
[##################################################] 100.00%[2021-04-27 18:24:56,889] [    INFO] - Successfully uninstalled ernie
2021-04-27 18:24:56,904 - INFO - Lock 1605758886296 released on D:\paddleModule\paddlehub\tmp\ernie
[INFO 2021-04-27 18:24:56,904 filelock.py:318] Lock 1605758886296 released on D:\paddleModule\paddlehub\tmp\ernie

Traceback (most recent call last):

  File "<ipython-input-31-271d65a1f7aa>", line 1, in <module>
    runfile('E:/ERNIE/ERNIE.py', wdir='E:/ERNIE')

  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/ERNIE/ERNIE.py", line 24, in <module>
    label_map=label_map)

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 172, in __new__
    name=name, version=version, source=source, update=update, branch=branch, **kwargs)

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 263, in init_with_name
    user_module_cls = manager.install(name=name, version=version, source=source, update=update, branch=branch)

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\manager.py", line 188, in install
    return self._install_from_name(name, version)

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\manager.py", line 263, in _install_from_name
    return self._install_from_url(item['url'])

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\manager.py", line 256, in _install_from_url
    return self._install_from_archive(file)

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\manager.py", line 361, in _install_from_archive
    return self._install_from_directory(directory)

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\manager.py", line 345, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))

  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\utils\utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)

  File "D:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 994, in _gcd_import

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'ernie.module'

log文件记录的错误：
==================================================
Record at 2021-04-27 18:24:55
==================================================
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\manager.py", line 222, in search
    module = self._local_modules[name] = HubModule.load(module_dir)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlehub\utils\utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "D:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ernie.module'

**Comment by KPatr1ck** [comment]
你好，paddlehub中的模型ernie在运行过程中会以模型名字加载为模块，`ernie`的模块名与paddle-ernie中的重复了，导致该报错。

建议执行下面命令卸载paddle-ernie后再测试运行。
`pip uninstall paddle-ernie==0.1.0.dev1`

**Comment by JoeLiaoCHN** [comment]
确实是这个问题，问题解决了，谢谢你！
