### ISSUE TITLE
PaddleDetection模型导入无法使用

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleFormers#1407]
PaddleDetection2.02模型导出->hub convert 转换 ->hub install模型部署，三个步骤都正常

hub serving start -m xxxxx出错

(base) D:\paddlex\hub>hub serving start -m xxxxx
[2021-05-11 16:24:14,468] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\hub.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "c:\anaconda3\lib\site-packages\paddlehub\commands\serving.py", line 352, in execute
    self.start_serving()
  File "c:\anaconda3\lib\site-packages\paddlehub\commands\serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "c:\anaconda3\lib\site-packages\paddlehub\commands\serving.py", line 221, in start_single_app_with_args
    self.preinstall_modules()
  File "c:\anaconda3\lib\site-packages\paddlehub\commands\serving.py", line 152, in preinstall_modules
    m = hub.Module(**init_args)
  File "c:\anaconda3\lib\site-packages\paddlehub\module\module.py", line 395, in __new__
    **kwargs)
  File "c:\anaconda3\lib\site-packages\paddlehub\module\module.py", line 504, in init_with_name
    user_module._initialize(**kwargs)
  File "c:\anaconda3\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\dell\.paddlehub\modules\cloud\module.py", line 47, in _initialize
    **kwargs)
  File "c:\anaconda3\lib\site-packages\paddlex\deploy.py", line 60, in __init__
    self.status = self.info['status']
KeyError: 'status'

1）PaddleHub和PaddlePaddle版本：PaddlePaddle2.0.2，paddlehub-2.1.0
2）系统环境：Windows 10，python3.6.8

**Comment by ShenYuhan** [comment]
这个问题可以在[paddlex](https://github.com/PaddlePaddle/PaddleX) issue上进行提问

**Comment by FlyingQianMM** [comment]
这是用paddlex训练的模型还是用paddledetection训练的模型？

**Comment by ShenYuhan** [comment]
hub convert命令只适用paddlex的模型的

**Comment by abanger** [comment]
> hub convert命令只适用paddlex的模型的
没再研究，应是这个原因，谢谢。

按个人想法，模型应要有统一标准。

**Comment by FlyingQianMM** [comment]
> > hub convert命令只适用paddlex的模型的
> > 没再研究，应是这个原因，谢谢。
> 
> 按个人想法，模型应要有统一标准。

嗯嗯，我们现在正在做对各套件统一部署的工作
