### ISSUE TITLE
在win10下安装服务模块 hub install deploy\hubserving\ocr_det\ 报错

### ISSUE THREAD

**Issue by qinyou10621** [PaddlePaddle/PaddleFormers#1408]
win10环境
基于PaddleHub Serving的服务部署
执行到第三步 安装服务模块 hub install deploy\hubserving\ocr_det\ 报错

错误如下
PS D:\PaddleOCR> hub install deploy\hubserving\ocr_det\
d:\program files\python\python37\lib\site-packages\setuptools\depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "d:\program files\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Python37\Scripts\hub.exe\__main__.py", line 5, in <module>
  File "d:\program files\python\python37\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "d:\program files\python\python37\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "d:\program files\python\python37\lib\site-packages\paddlehub\module\module.py", line 31, in <module>
    from paddlehub.common import utils
  File "d:\program files\python\python37\lib\site-packages\paddlehub\common\__init__.py", line 16, in <module>
    from . import utils
  File "d:\program files\python\python37\lib\site-packages\paddlehub\common\utils.py", line 33, in <module>
    from paddlehub.common.logger import logger
  File "d:\program files\python\python37\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "d:\program files\python\python37\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "d:\program files\python\python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "d:\program files\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "d:\program files\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShenYuhan** [comment]
使用的版本是paddlehub哪个版本呢

**Comment by qinyou10621** [comment]
pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple 执行的这个命令

**Comment by qinyou10621** [comment]
> 使用的版本是paddlehub哪个版本呢

执行的 pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple 这个命令

**Comment by ShenYuhan** [comment]
这个问题应该是使用的旧版本的paddlehub，您可以尝试升级到2.1.0再试试
