### ISSUE TITLE
TypeError: the 'package' argument is required to perform a relative import for '.module'

### ISSUE THREAD

**Issue by poopit** [PaddlePaddle/PaddleFormers#1413]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddlePaddle版本为1.7.2，Paddlehub版本为1.6.2
2）系统环境：Windows，python3.7
- 复现信息：做cv模型的迁移学习
-代码如下： import paddlehub as hub
test_dir = './database/img.jpg'
model = hub.Module(directory='finetuned_model_to_module/')
prediction = model.predict(test_dir)
print(prediction)
-报错信息如下：Traceback (most recent call last):
  File "E:/Data/AppData/firefox/demo2.py", line 4, in <module>
    model = hub.Module(directory='finetuned_model_to_module/',use_gpu=False)
  File "E:\miniconda3\lib\site-packages\paddlehub\module\module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "E:\miniconda3\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "E:\miniconda3\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.module'

文件夹下包含

1. finetuned_model_to_module
      -module.py
      -__init__.py
      -model_finetune
2. demo2.py

**Comment by poopit** [comment]
hub install之后改成model = hub.Module(name='se-resnext_finetune')之后，也会出现问题

[2021-05-14 21:14:50,407] [    INFO] - Try loading checkpoint from C:\Users\creper\.paddlehub\modules\se_resnext_finetuned\se_resnext\ckpt.meta
[2021-05-14 21:14:50,407] [    INFO] - PaddleHub model checkpoint not found, start from scratch...

但是同样的代码放在Aistudio上就运行正常，在报错信息的文件夹下best_model和ckpt.meta文件都有，相对路径和绝对路径都尝试过，最后还是会报checkpoint not found的警告，还望回答

**Comment by thgpddl** [comment]
你好，我也遇到了同样的问题，请问你是怎么解决的？
同时遗憾的是看到官方依然没有解决该问题
