### ISSUE TITLE
import paddlehub as hub 在win10环境下失败，发生TypeError: stat错误

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleFormers#1419]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
paddlepaddle: 2.1.0
paddlehub: 2.1.0
2）系统环境：
os: windows 10
python: 3.9.5

- 复现信息：如为报错，请给出复现环境、复现步骤
1 在PyCharm中创建虚拟环境， 然后在Terminal中安装paddlepaddle以及paddlehub

pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
安装好paddlepaddle后，验证成功。接着开始安装paddlehub,

pip install paddlehub -i https://mirror.baidu.com/pypi/simple
安装好paddlehub后，切到Python Console中，验证paddlehub

2 在Python Console中输入import paddlehub as hub，结果出现如下错误，而且复现多次，

import paddlehub as hub
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlehub\__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlehub\datasets\__init__.py", line 16, in <module>
    from paddlehub.datasets.chnsenticorp import ChnSentiCorp
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlehub\datasets\chnsenticorp.py", line 19, in <module>
    from paddlehub.datasets.base_nlp_dataset import TextClassificationDataset
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlehub\datasets\base_nlp_dataset.py", line 21, in <module>
    import paddlenlp
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlenlp\__init__.py", line 20, in <module>
    from . import ops
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlenlp\ops\__init__.py", line 15, in <module>
    from .transformer.decoding import *
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlenlp\ops\transformer\decoding.py", line 24, in <module>
    from paddlenlp.ops.ext_utils import load
  File "D:\JetBrains\PyCharmCE202111\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\sentaProject\venv\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in <module>
    if not os.path.exists(CUDA_HOME):
  File "D:\Python\Python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

请Team能够确认一下这个问题，非常感谢！

**Comment by LangDaoAI** [comment]
刚刚在python 3.8.10环境上验证，也是出现这个错误。

**Comment by LangDaoAI** [comment]
刚刚切换到paddlehub 1.8.3, paddlepaddle 1.8.5, python 3.8.10,  错误消失了！

Requirement already satisfied: chardet<5,>=3.0.2 in d:\python\python38\lib\site-packages (from requests->visualdl->paddlehub==1.8.3) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python\python38\lib\site-packages (from requests->visualdl->paddlehub==1.8.3) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\python38\lib\site-packages (from requests->visualdl->paddlehub==1.8.3) (2020.12.5)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
Installing collected packages: yapf, sentencepiece, pandas, nltk, cma, paddlehub
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
Successfully installed cma-3.0.3 nltk-3.6.2 paddlehub-1.8.3 pandas-1.2.4 sentencepiece-0.1.95 yapf-0.26.0
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -addlepaddle (d:\python\python38\lib\site-packages)

![paddlehub导入](https://user-images.githubusercontent.com/83859417/118906484-7700de80-b950-11eb-9c60-03c7b003cf41.png)

**Comment by LangDaoAI** [comment]
paddlehub 2.0.0, paddlepaddle 2.0.0, python 3.8.10, 错误也消失了！

![paddlehub导入—2 0 0](https://user-images.githubusercontent.com/83859417/118907084-7d438a80-b951-11eb-9aed-7acb016e416f.png)

**Comment by abanger** [comment]
windows 10 python 3.7.0 paddlehub: 2.1.0 CPU环境同样问题

运行部署 ：hub install xxxx.tar.gz 出现


   from . import ops
 File "d:\anaconda3\lib\site-packages\paddlenlp\ops\__init__.py", line 15, in <
odule>
   from .transformer.decoding import *
 File "d:\anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", l
ne 24, in <module>
   from paddlenlp.ops.ext_utils import load
 File "d:\anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in
module>
   if not os.path.exists(CUDA_HOME):
 File "d:\anaconda3\lib\genericpath.py", line 19, in exists
   os.stat(path)
ypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
pe

**Comment by abanger** [comment]
> windows 10 python 3.7.0 paddlehub: 2.1.0 CPU环境同样问题
> 
> 运行部署 ：hub install xxxx.tar.gz 出现
> 
> from . import ops
> File "d:\anaconda3\lib\site-packages\paddlenlp\ops__init__.py", line 15, in <
> odule>
> from .transformer.decoding import *
> File "d:\anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", l
> ne 24, in
> from paddlenlp.ops.ext_utils import load
> File "d:\anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in
> module>
> if not os.path.exists(CUDA_HOME):
> File "d:\anaconda3\lib\genericpath.py", line 19, in exists
> os.stat(path)
> ypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
> pe

paddlenlp 退回2.0.0rc21可以用

pip install paddlenlp==2.0.0rc21

**Comment by KPatr1ck** [comment]
> > windows 10 python 3.7.0 paddlehub: 2.1.0 CPU环境同样问题
> > 运行部署 ：hub install xxxx.tar.gz 出现
> > from . import ops
> > File "d:\anaconda3\lib\site-packages\paddlenlp\ops__init__.py", line 15, in <
> > odule>
> > from .transformer.decoding import *
> > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", l
> > ne 24, in
> > from paddlenlp.ops.ext_utils import load
> > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in
> > module>
> > if not os.path.exists(CUDA_HOME):
> > File "d:\anaconda3\lib\genericpath.py", line 19, in exists
> > os.stat(path)
> > ypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
> > pe
> 
> paddlenlp 退回2.0.0rc21可以用
> 
> pip install paddlenlp==2.0.0rc21

你好paddlenlp最新发布了2.0.0，可以使用`pip install paddlenlp -U`安装。
请问下遇到问题的环境是哪个版本？方便的话提供一下有问题时的环境信息：`pip list | grep paddle`

**Comment by LangDaoAI** [comment]
> > windows 10 python 3.7.0 paddlehub: 2.1.0 CPU环境同样问题
> > 运行部署 ：hub install xxxx.tar.gz 出现
> > from . import ops
> > File "d:\anaconda3\lib\site-packages\paddlenlp\ops__init__.py", line 15, in <
> > odule>
> > from .transformer.decoding import *
> > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", l
> > ne 24, in
> > from paddlenlp.ops.ext_utils import load
> > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in
> > module>
> > if not os.path.exists(CUDA_HOME):
> > File "d:\anaconda3\lib\genericpath.py", line 19, in exists
> > os.stat(path)
> > ypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
> > pe
> 
> paddlenlp 退回2.0.0rc21可以用
> 
> pip install paddlenlp==2.0.0rc21

感谢提示，确实是这样，我卸载了paddlenlp 2.0.0rc25，然后重新安装2.0.0rc21，然后senta_demo运行成功了！

![senta_demo](https://user-images.githubusercontent.com/83859417/118990903-dc3aeb00-b9b5-11eb-93f5-98f61f957858.png)

**Comment by LangDaoAI** [comment]
> > > windows 10 python 3.7.0 paddlehub: 2.1.0 CPU环境同样问题
> > > 运行部署 ：hub install xxxx.tar.gz 出现
> > > from . import ops
> > > File "d:\anaconda3\lib\site-packages\paddlenlp\ops__init__.py", line 15, in <
> > > odule>
> > > from .transformer.decoding import *
> > > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", l
> > > ne 24, in
> > > from paddlenlp.ops.ext_utils import load
> > > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in
> > > module>
> > > if not os.path.exists(CUDA_HOME):
> > > File "d:\anaconda3\lib\genericpath.py", line 19, in exists
> > > os.stat(path)
> > > ypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
> > > pe
> > 
> > 
> > paddlenlp 退回2.0.0rc21可以用
> > pip install paddlenlp==2.0.0rc21
> 
> 你好paddlenlp最新发布了2.0.0，可以使用`pip install paddlenlp -U`安装。
> 请问下遇到问题的环境是哪个版本？方便的话提供一下有问题时的环境信息：`pip list | grep paddle`

感谢提示paddlenlp 最新发布，我遇到的问题的paddle版本是2.0.2, 2.1.0,其他版本未能有时间逐一确认，我再试一下最新的paddlenlp，如果OK的话，那么paddlenlp最新版本需要在paddle中更新依赖了。

**Comment by LangDaoAI** [comment]
![image](https://user-images.githubusercontent.com/83859417/118991876-b19d6200-b9b6-11eb-8df0-e14bbdd4c7ab.png)

@KPatr1ck 请看一下，最新的paddlenlp 2.0.0没有fix这个问题，还是要回退到rc21.

**Comment by LeeWlving** [comment]
我在ubuntu20.04上也有相同的问题

**Comment by ccc008** [comment]
修改 paddlenlp\ops\ext_utils.py第19行 
if not os.path.exists(CUDA_HOME):
为
if (CUDA_HOME!=None) and (not os.path.exists(CUDA_HOME)):

可以解决

**Comment by abanger** [comment]
> > > windows 10 python 3.7.0 paddlehub: 2.1.0 CPU环境同样问题
> > > 运行部署 ：hub install xxxx.tar.gz 出现
> > > from . import ops
> > > File "d:\anaconda3\lib\site-packages\paddlenlp\ops__init__.py", line 15, in <
> > > odule>
> > > from .transformer.decoding import *
> > > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", l
> > > ne 24, in
> > > from paddlenlp.ops.ext_utils import load
> > > File "d:\anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 19, in
> > > module>
> > > if not os.path.exists(CUDA_HOME):
> > > File "d:\anaconda3\lib\genericpath.py", line 19, in exists
> > > os.stat(path)
> > > ypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
> > > pe
> > 
> > 
> > paddlenlp 退回2.0.0rc21可以用
> > pip install paddlenlp==2.0.0rc21
> 
> 你好paddlenlp最新发布了2.0.0，可以使用`pip install paddlenlp -U`安装。
> 请问下遇到问题的环境是哪个版本？方便的话提供一下有问题时的环境信息：`pip list | grep paddle`
与paddle版本无关试了2.1,2.02都存这个问题。
paddlenlp 2.0.0rc25 存在这个bug
