### ISSUE TITLE
senta = hub.Module(name="senta_bilstm") 报错：info['version'])   KeyError: 'version'

### ISSUE THREAD

**Issue by xinaiwunai** [PaddlePaddle/PaddleFormers#144]
在我的win10本地电脑跑同一个脚本，没有问题，在我的阿里云服务器上，centos跑就报错
错误如下:

`[root@wyh webpy]# python main.py 789`
`[2019-09-10 12:22:38,531] [    INFO] - Installing senta_bilstm module`
`Traceback (most recent call last):`
`  File "main.py", line 8, in <module>`
`    from myhub import Myhub`
`  File "/root/webpy/myhub.py", line 21, in <module>`
`    class Myhub(object):`
`  File "/root/webpy/myhub.py", line 22, in Myhub`
`    senta = hub.Module(name="senta_bilstm")`
`  File "/root/anaconda3/lib/python3.7/site-packages/paddlehub/module/module.py", line 122, in __init__`
`    self._init_with_name(name=name, version=version)`
`  File "/root/anaconda3/lib/python3.7/site-packages/paddlehub/module/module.py", line 147, in _init_with_name`
`    module_name=name, module_version=version)`
`  File "/root/anaconda3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 76, in install_module`
`    self.all_modules(update=True)`
`  File "/root/anaconda3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 68, in all_modules`
`    info['version'])`
`KeyError: 'version'`

**Comment by xinaiwunai** [comment]
我自己解决了问题。
原有大概是因为模型文件本身发送了错误。
把模型文件删除后，重新下载就OK了。

大概是因为我第一次写代码得时候，把这个代码放在一个网络服务中。结果有3个请求，就导致多线程同时在下载和解压缩模型。
可能就是这个原因导致模型文件损坏得把。
