### ISSUE TITLE
hub serving start -m plato-mini 运行成功，但是调用失败

### ISSUE THREAD

**Issue by arkerwu** [PaddlePaddle/PaddleFormers#1463]
版本：
PaddleHub2.1.0
paddlepaddle-gpu==2.1.0.post101
plato-mini 1.0.0

WIN10，python3.8

安装plato-mini：
hub install plato-mini==1.0.0

代码（官方文档里的）：
```
import paddlehub as hub

model = hub.Module(name='plato-mini')
data = [["你是谁？"], ["你好啊。", "吃饭了吗？",]]
result = model.predict(data)
```

报错：
Traceback (most recent call last):
  File "D:/pyspace/Knover/test.py", line 6, in <module>
    result = model.predict(data)
  File "E:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 63, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\.paddlehub\modules\plato_mini\module.py", line 172, in predict
    ids, scores = self(input_ids, token_type_ids, position_ids, attention_mask, **kwargs)
  File "E:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\.paddlehub\modules\plato_mini\module.py", line 130, in forward
    ids, scores = self.model.generate(input_ids=input_ids,
  File "<decorator-gen-269>", line 2, in generate
  File "E:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 316, in _decorate_function
    return func(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 618, in generate
    return self.sample(input_ids, logits_processors, max_length,
  File "E:\Anaconda3\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 793, in sample
    input_ids = paddle.concat([input_ids, next_tokens], axis=1)
  File "E:\Anaconda3\lib\site-packages\paddle\tensor\manipulation.py", line 121, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "E:\Anaconda3\lib\site-packages\paddle\fluid\layers\tensor.py", line 307, in concat
    return core.ops.concat(input, 'axis', axis)
**ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/tensor_impl.h:33)
  [operator < concat > error]**

**Comment by LazyBoy-KK** [comment]
我也碰到了同样的问题，python版本3.7，PaddleHub2.1.0，PaddlePaddle-gpu2.1.0，windows系统，plato-mini1.0.0，官方文档报错

**Comment by KPatr1ck** [comment]
@arkerwu @LazyBoy-KK 

看了报错的提示，猜测可能是windows系统里numpy整数序列默认数据类型的问题。
尝试将`C:\Users\Administrator.paddlehub\modules\plato_mini\module.py`第170行修改如下，再尝试执行。
之后将加入兼容性代码修复。

https://github.com/PaddlePaddle/PaddleHub/blob/a7e44e88508ae2e06afc4116cce923c600e76071/modules/text/text_generation/plato-mini/module.py#L170

```python
input_ids, token_type_ids, position_ids, attention_mask = map(paddle.to_tensor, batch, ['int64']*3 + ['float32'])
```

**Comment by arkerwu** [comment]
@KPatr1ck  感谢回复

确实有效
