### ISSUE TITLE
使用超分模型出错 ModuleNotFoundError: No module named 'realsr.module'; 'realsr' is not a package

### ISSUE THREAD

**Issue by KingsleyYau** [PaddlePaddle/PaddleFormers#1467]
使用超分模型出错 ModuleNotFoundError: No module named 'realsr.module'; 'realsr' is not a package
也试过手动删除缓存目录，和更新paddlehub版本，还是不行

- 代码
```
'''
realsr.py 
'''

import paddle
import os
import argparse
import cv2

import paddlehub as hub
def main(args):
    image_path = 'input.png'
    image = cv2.imread(image_path)
    module = hub.Module(name="realsr")
    res = module.run_image(image)
    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    args = parser.parse_args()
    main(args)
    print('exit')
```
- 系统环境 MaxOS
- python版本              Python 3.8.10
- paddlehub               2.1.0               /Users/max/Documents/Project/Demo/python/pd/PaddleHub
- paddlepaddle          2.0.0

- 详细日志
```
(pd) MaxdeMac-mini:pd max$ python realsr.py 
/Users/max/Documents/tools/miniconda3/envs/pd/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/Users/max/Documents/tools/miniconda3/envs/pd/lib/python3.8/site-packages/paddle2onnx/onnx_helper/mapping.py:42: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/Users/max/Documents/tools/miniconda3/envs/pd/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:43: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/Users/max/Documents/tools/miniconda3/envs/pd/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:44: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/Users/max/Documents/tools/miniconda3/envs/pd/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:49: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
[2021-06-08 17:23:52,521] [ WARNING] - An error was encountered while loading realsr. Detailed error information can be found in the /Users/max/.paddlehub/log/20210608.log.
[2021-06-08 17:23:52,525] [ WARNING] - An error was encountered while loading realsr. Detailed error information can be found in the /Users/max/.paddlehub/log/20210608.log.
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/realsr.tar.gz
[##################################################] 100.00%
Decompress /Users/max/.paddlehub/tmp/tmpq_d8ji2h/realsr.tar.gz
[##################################################] 100.00%
[2021-06-08 17:25:35,841] [    INFO] - Successfully uninstalled realsr
Traceback (most recent call last):
  File "realsr.py", line 32, in <module>
    main(args)
  File "realsr.py", line 25, in main
    module = hub.Module(name="realsr")
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/module.py", line 388, in __new__
    module = cls.init_with_name(
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/module.py", line 487, in init_with_name
    user_module_cls = manager.install(
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/manager.py", line 265, in _install_from_name
    return self._install_from_url(item['url'])
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/manager.py", line 258, in _install_from_url
    return self._install_from_archive(file)
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/manager.py", line 380, in _install_from_archive
    return self._install_from_directory(directory)
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/manager.py", line 364, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/module/module.py", line 418, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/Users/max/Documents/Project/Demo/python/pd/PaddleHub/paddlehub/utils/utils.py", line 250, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/Users/max/Documents/tools/miniconda3/envs/pd/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'realsr.module'; 'realsr' is not a package
```

**Comment by haoyuying** [comment]
您好，使用的脚本命名不能和模型的名字是同一个，建议将realsr.py换一个别的名字，比如predict.py等

**Comment by KingsleyYau** [comment]
的确是这个问题，可以了
