### ISSUE TITLE
在运行paddlehub2.1.0中的plato-mini模型时出现ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int.

### ISSUE THREAD

**Issue by LazyBoy-KK** [PaddlePaddle/PaddleFormers#1470]
- PaddleHub: 2.1.0
- PaddlePaddle: 2.1.0
- 系统环境: Windows  python3.7
- 在尝试运行PaddleHub中plato-mini模型的predict函数时报错

- 代码：
import paddlehub as hub
model = hub.Module(name='plato-mini')
data = ['你好啊', '吃了吗']
result = model.predict(data, use_gpu=True)

- 报错:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    result = model.predict(data, use_gpu=True)
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddlehub\module\module.py", line 63, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\.paddlehub\modules\plato_mini\module.py", line 172, in predict
    ids, scores = self(input_ids, token_type_ids, position_ids, attention_mask, **kwargs)
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\.paddlehub\modules\plato_mini\module.py", line 143, in forward
    num_return_sequences=num_return_sequences)
  File "<decorator-gen-269>", line 2, in generate
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddle\fluid\dygraph\base.py", line 316, in _decorate_function
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 620, in generate
    temperature, **model_kwargs)
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 793, in sample
    input_ids = paddle.concat([input_ids, next_tokens], axis=1)
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddle\tensor\manipulation.py", line 121, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "D:\anaconda3\envs\VirtualIdol\lib\site-packages\paddle\fluid\layers\tensor.py", line 307, in concat
    return core.ops.concat(input, 'axis', axis)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/t
ensor_impl.h:33)
  [operator < concat > error]

**Comment by KPatr1ck** [comment]
同样问题可参考该issue

https://github.com/PaddlePaddle/PaddleHub/issues/1463#issuecomment-856702870

**Comment by LazyBoy-KK** [comment]
@KPatr1ck 感谢回复，问题已解决

**Comment by 80905949** [comment]
# 官方没有这句话必须加上否则报类型错误
encoded_input['input_ids'] = encoded_input['input_ids'].astype('int64')
