### ISSUE TITLE
paddlehub预训练模型ernie_gen进行finetune自定义的场景错误

### ISSUE THREAD

**Issue by M-Cavan** [PaddlePaddle/PaddleFormers#1505]
# 项目环境aistudio自带paddle 2.0.2 环境:
paddlehub==2.0.4
paddlenlp==2.0.0rc7
paddlepaddle-gpu==2.0.2.post101
tb-paddle==0.3.6

# 下载ernie_gen模型,进行自定数据训练

import paddlehub as hub

module = hub.Module(name="ernie_gen")

result = module.finetune(
    train_path='/home/aistudio/train.txt',
    # dev_path='/home/aistudio/dev.txt',
    save_dir="module_teacher",
    max_steps=600,
    max_encode_len=200,
    max_decode_len=200,
    noise_prob=0.2,
    batch_size=300,
    log_interval=20
)
# 导出自定数据模型
module.export(params_path=result['last_save_path'], module_name="my_teachers", author="自定义模型")

# 安装自定义模型
!hub install my_teachers

# 运行模型预测
import paddlehub as hub
import os

os.environ["CUDA_VISIBLE_DEVICES"] ="0"

module = hub.Module(name="my_teachers")

test_texts = ["老师"]

results = module.generate(texts=test_texts, use_gpu=True, beam_width=5)
for result in results:
    print(result)

# 模型错误信息
---------------------------------------------------------------------------ValueError Traceback (most recent call last)<ipython-input-6-515cef86addd> in <module> 2 3 ----> 4 senta_test = hub.Module(directory="/home/aistudio/data/my_teachers/") 5 # senta_test.sentiment_classify(texts=["老师"]) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, version, source, update, branch, **kwargs) 173 CacheUpdater("update_cache", module=name, version=version).start() 174 elif directory: --> 175 module = cls.init_with_directory(directory=directory, **kwargs) 176 CacheUpdater("update_cache", module=directory, version="0.0.0").start() 177 else: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_directory(cls, directory, **kwargs) 293 ) 294 user_module = user_module_cls(directory=directory) --> 295 user_module._initialize(**kwargs) 296 return user_module 297 /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py in runner(*args, **kwargs) 218 def runner(*args, **kwargs): 219 with static_mode_guard(): --> 220 return func(*args, **kwargs) 221 222 return runner ~/data/my_teachers/module.py in _initialize(self) 45 assets_path = os.path.join(self.directory, "assets") 46 gen_checkpoint_path = os.path.join(assets_path, "ernie_gen.pdparams") ---> 47 self.model = ErnieForGeneration.from_pretrained("ernie-1.0") 48 model_state = paddle.load(gen_checkpoint_path) 49 self.model.set_dict(model_state) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py in from_pretrained(cls, pretrained_model_name_or_path, *args, **kwargs) 370 k) 371 m[k] = v # FIXME: no need to do this in the future --> 372 model.set_state_dict(m) 373 else: 374 raise ValueError('weight file not found in pretrain dir: %s' % /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in wrapper(*args, **kwargs) 270 kwargs['state_dict'] = kwargs['stat_dict'] 271 kwargs.pop('stat_dict') --> 272 return func(*args, **kwargs) 273 274 return wrapper /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in set_state_dict(self, state_dict, include_sublayers, use_structured_name) 1331 global_scope(), executor) 1332 for param, state in matched_param_state: -> 1333 _set_var(param, state) 1334 1335 # [aliases] Compatible with old method names /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in _set_var(var, ndarray) 1323 p.set_place(t._place()) 1324 place = core.CUDAPlace(p.gpu_device_id()) -> 1325 t.set(ndarray, place) 1326 1327 executor = Executor(_get_device())._default_executor ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:355)

# 命令行运行:
!hub run my_teachers --input_text="老师" --use_gpu True --beam_width 5

#  错误信息:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 10, in <module>
    sys.exit(execute())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/run.py", line 56, in execute
    result = module._run_func(argv[1:])
TypeError: 'property' object is not callable

# 问题总结:
### paddle2.0版本 安装自定义训练模型 并导入模型 总是报错: 命令行---TypeError: 'property' object is not callable  , 模块运行---ValueError:(InvalidArgument) Input object type error or incompatible array data type.

**Comment by KPatr1ck** [comment]
你好，方便的化麻烦提供一下AIstudio项目的地址和ernie_gen的module版本。

关于ernie_gen模型的运行环境，可以参考此文档：
https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0/modules/text/text_generation/ernie_gen

**Comment by M-Cavan** [comment]
> 你好，方便的化麻烦提供一下AIstudio项目的地址和ernie_gen的module版本。
> 
> 关于ernie_gen模型的运行环境，可以参考此文档：
> https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0/modules/text/text_generation/ernie_gen

> 1 .创建自定义aistudio2.1.0的项目, 按照官方例子生成自定义模型,进行预测必定会报错:
> ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:390)
> 2 .Windows训练模型必定报错:
> ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/tensor_impl.h:33)
  [operator < softmax_with_cross_entropy > error]

**Comment by Tycoonman-ML** [comment]
我也出现相同的问题https://github.com/PaddlePaddle/PaddleHub/issues/1493

**Comment by KPatr1ck** [comment]
@M-Cavan @Tycoonman-ML 
感谢反馈，问题查证后已提交修复https://github.com/PaddlePaddle/PaddleHub/commit/78b34a325379db1ccc59d2e5577e3c4eda9def3a

卸载后重新安装应可解决：
```
hun uninstall ernie_gen
hub install ernie_gen
```

**Comment by Tycoonman-ML** [comment]
重新安装ernie_gen后，finetune训练模型过程中出现另一个问题：ValueError: Token index 17969 in the provided `indices` is invalid.


result = module.finetune(train_path='./input/big_train_dataset.txt',
                         dev_path='./input/big_valid_dataset.txt',
                         init_ckpt_path='./output/init2_ppl_1.82027.params',
                         max_steps=1000000,
                         batch_size=16,
                         max_encode_len=256,
                         max_decode_len=32,
                         use_gpu=True,
                         beam_width=10,
                         save_dir='output',
                         log_interval=1000, 
                         save_interval=10000)

/root/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
[2021-07-02 12:45:04,258] [    INFO] - loading checkpoint from ./output/init2_ppl_1.82027.params
[2021-07-02 12:45:07,723] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
[2021-07-02 12:45:07,724] [   DEBUG] - init ErnieModel with config: {'attention_probs_dropout_prob': 0.1, 'hidden_act': 'relu', 'hidden_dropout_prob': 0.1, 'hidden_size': 768, 'initializer_range': 0.02, 'max_position_embeddings': 513, 'num_attention_heads': 12, 'num_hidden_layers': 12, 'type_vocab_size': 2, 'vocab_size': 18000, 'pad_token_id': 0}
[2021-07-02 12:45:08,844] [    INFO] - loading pretrained model from /root/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
[2021-07-02 12:45:09,247] [    INFO] - param:mlm_bias not set in pretrained model, skip
[2021-07-02 12:45:09,248] [    INFO] - param:mlm.weight not set in pretrained model, skip
[2021-07-02 12:45:09,249] [    INFO] - param:mlm.bias not set in pretrained model, skip
[2021-07-02 12:45:09,250] [    INFO] - param:mlm_ln.weight not set in pretrained model, skip
[2021-07-02 12:45:09,251] [    INFO] - param:mlm_ln.bias not set in pretrained model, skip
[2021-07-02 12:55:01,920] [    INFO] - [step 1000 / 1000000]train loss 3.44633, ppl 31.38497, elr 5.000e-07
[2021-07-02 13:04:53,796] [    INFO] - [step 2000 / 1000000]train loss 2.82949, ppl 16.93674, elr 1.000e-06
[2021-07-02 13:14:45,865] [    INFO] - [step 3000 / 1000000]train loss 2.49936, ppl 12.17470, elr 1.500e-06
[2021-07-02 13:24:38,014] [    INFO] - [step 4000 / 1000000]train loss 3.15208, ppl 23.38459, elr 2.000e-06
[2021-07-02 13:34:23,041] [    INFO] - [step 5000 / 1000000]train loss 2.49517, ppl 12.12381, elr 2.500e-06
[2021-07-02 13:44:10,656] [    INFO] - [step 6000 / 1000000]train loss 1.72089, ppl 5.58951, elr 3.000e-06
[2021-07-02 13:54:03,185] [    INFO] - [step 7000 / 1000000]train loss 2.28538, ppl 9.82938, elr 3.500e-06
[2021-07-02 14:03:50,987] [    INFO] - [step 8000 / 1000000]train loss 2.70090, ppl 14.89309, elr 4.000e-06
[2021-07-02 14:13:44,311] [    INFO] - [step 9000 / 1000000]train loss 2.20825, ppl 9.09980, elr 4.500e-06
[2021-07-02 14:23:37,578] [    INFO] - [step 10000 / 1000000]train loss 2.19891, ppl 9.01519, elr 5.000e-06
[2021-07-02 14:23:37,580] [    INFO] - save the model in output/step_10000_ppl_9.01519.params
[2021-07-02 14:23:41,280] [    INFO] - Evaluating...
[2021-07-02 15:02:23,841] [    INFO] - Rouge-1: 16.31103 ,Rouge-2: 10.39445
/root/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/paddlenlp/data/vocab.py:217: UserWarning: The type of `to_tokens()`'s input `indices` is not `int` which will be forcibly transfered to `int`. 
  "The type of `to_tokens()`'s input `indices` is not `int` which will be forcibly transfered to `int`. "
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-1476ad6ea042> in <module>
     10                          save_dir='output',
     11                          log_interval=1000,
---> 12                          save_interval=10000)

~/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py in runner(*args, **kwargs)
    218     def runner(*args, **kwargs):
    219         with static_mode_guard():
--> 220             return func(*args, **kwargs)
    221 
    222     return runner

~/.paddlehub/modules/ernie_gen/module.py in finetune(self, train_path, dev_path, save_dir, init_ckpt_path, use_gpu, max_steps, batch_size, max_encode_len, max_decode_len, learning_rate, warmup_proportion, weight_decay, noise_prob, label_smooth, beam_width, length_penalty, log_interval, save_interval)
    203                     if dev_path:
    204                         self._evaluate(self.model, dev_data_loader, self.tokenizer, rouge1, rouge2, attn_id,
--> 205                                        max_decode_len, max_encode_len, beam_width, length_penalty)
    206 
    207                 if global_step >= max_steps:

~/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py in runner(*args, **kwargs)
    218     def runner(*args, **kwargs):
    219         with static_mode_guard():
--> 220             return func(*args, **kwargs)
    221 
    222     return runner

~/.paddlehub/modules/ernie_gen/module.py in _evaluate(self, model, data_loader, tokenizer, rouge1, rouge2, attn_id, max_decode_len, max_encode_len, beam_width, length_penalty)
    341             reference_sentences.append(''.join(map(post_process, vocab.to_tokens(ids))))
    342         for ids in evaluated_sentences_ids[:3]:
--> 343             evaluated_sentences.append(''.join(map(post_process, vocab.to_tokens(ids))))
    344         logger.debug(reference_sentences)
    345         logger.debug(evaluated_sentences)

~/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/paddlenlp/data/vocab.py in to_tokens(self, indices)
    221                 raise ValueError(
    222                     'Token index {} in the provided `indices` is invalid.'.
--> 223                     format(idx))
    224             tokens.append(self._idx_to_token[idx])
    225 

ValueError: Token index 17969 in the provided `indices` is invalid.
