### ISSUE TITLE
运行deepvoice3_ljspeech示例代码时报错No module named 'paddle.io'

### ISSUE THREAD

**Issue by chenkun1029** [PaddlePaddle/PaddleFormers#1520]
Windows10 系统
python 3.8.7
PaddlePaddle 1.8.5
PaddleHub 1.8.0
按照其他issue中的回答，parakeet安装的是v0.1分支

运行代码就是deepvoice3_ljspeech中给出的示例代码
**错误信息：**
Traceback (most recent call last):
  File "C:/Users/辰昆/PycharmProjects/time/test.py", line 5, in <module>
    module = hub.Module(name="deepvoice3_ljspeech")
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\module.py", line 101, in __new__
    module = cls.init_with_name(
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\module.py", line 193, in init_with_directory
    _module = importlib.import_module("{}.module".format(basename))
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\辰昆\.paddlehub\modules\deepvoice3_ljspeech\module.py", line 59, in <module>
    from parakeet.utils import io
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\site-packages\parakeet\__init__.py", line 17, in <module>
    from parakeet import audio, data, datasets, frontend, models, modules, training, utils
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\site-packages\parakeet\data\__init__.py", line 30, in <module>
    from parakeet.data.dataset import *
  File "C:\Users\辰昆\AppData\Local\Programs\Python\Python38\lib\site-packages\parakeet\data\dataset.py", line 17, in <module>
    from paddle.io import Dataset
ModuleNotFoundError: No module named 'paddle.io'

**Comment by chenkun1029** [comment]
问题已解决，具体原因是新版本的parakeet没有卸载干净导致程序调用了新版本的parakeet包，删除源文件后重新安装parakeet v0.1，程序能够正常运行。
