### ISSUE TITLE
@runnable和@serving时遇到的ERROR

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/PaddleFormers#1544]
1）PaddleHub和PaddlePaddle版本：PaddleHub 2.1.0，PaddlePaddle 2.1.0
2）系统环境：AI Studio高级版

## 命令行预测时遇到的问题
安装好模型后运行 `hub run mnist_predict --input_img "./5.png"` 报错
```
W0721 22:48:51.535526 20136 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0721 22:48:51.540257 20136 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 10, in <module>
    sys.exit(execute())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/run.py", line 56, in execute
    result = module._run_func(argv[1:])
TypeError: 'property' object is not callable
```
这个问题貌似和参数没有关系，因为当我修改 `--input_img` 的内容时报了同样的错误。这个情况也适用于后面图片的路径。

## 服务部署时遇到的问题
在AI Studio通过 `hub serving start -m mnist_predict` 可以正确部署模型，但是在Python代码发送POST请求预测时出现问题，返回的JSON数据如下
```
{'msg': "[Errno 36] File name too long: 'iVBORw0KGgoAAAANSUhEUgAAAH0AAACACAIAAACp7vG1AAAaeklEQVR4Ae3Bf2jU9/0H8Of7/fl997nc1cvuLopBrSUh6nRdjDBWpmNbJ9YpRehfgoj0H8G5sn/8Q0GRgf/4l6Rah4QJKshAxmIVh1bdomH+qE1iqdGYpImZ+XHJJXefu/v8en3hDW8QvpamtTmTkseDERHmVRwjIsyrOEZEmFdxjIgwr+IYEWFexTEiwryKY0SEeRXHiAjzKo4REeZVHCMizKs4RkSYV3GMiDCv4hgRYV7FMSLCvIpjRIR5FceICPMqjhER5lUcIyLMqzhGRJitwjDECzzPC8MQ36ZcLnd2dgZBAIGIfN+HFATBxMQEEUGwLOudd97RNA1CsVi8deuW7/sQisXi48ePITHGFEWBFI1Gf/azn0HIZDL19fWYNkZEmK2CIMALCoWC7/v4NpOTk+fOnXNdF0IYhqVSCZLneb29vWEYQliwYMG+ffsikQiEbDZ79OjRUqkEYXx8/NKlS5AYY4ZhQEqlUjt37oSwevXqrVu3YtoYEWG2CoIALygUCr7v49tMTk6eO3fOdV0IYRiWSiVInuf19vaGYQhhwYIF+/bti0QiELLZ7NGjR0ulEoTx8fFLly5BYowZhgEplUrt3LkTwurVq7du3YppY0SE2SoIArygUCj4vo9vMzk5ee7cOdd1IYRhWCqVIHme19vbG4YhhAULFuzbty8SiUDIZrNHjx4tlUoQxsfHL126BIkxZhgGpFQqtXPnTgirV6/eunUrpo0REWarIAjwgkKh4Ps+vs3k5OS5c+dc14UQhmGpVILkeV5vb28YhhAWLFiwb9++SCQCIZvNHj16tFQqQRgfH7906RIkxphhGJBSqdTOnTshrF69euvWrZg2RkSYSY7jeJ4HKQxDIoI0NjbmOA6kkZGRYrEIqVwuB0EAqaenJ5fL4duUy+XOzs4gCCAQke/7kIjI931Itm2///77uq5DmJycPHPmjOu6EEqlUl9fHyRN09LpNKR0Ov3hhx9CWL58+S9/+UtMGyMizKSxsbFCoQDJ9/0wDCF1d3ePjIxAevjwYTabhVQoFDzPg9TW1vbs2TO8GkVRMpkM5xyCrusNDQ2qqkIoFArXrl3zPA8C5zwSiUAyTbOurg5SJpPZvXs3hEwmU19fj2ljRISZNDY2VigUIPm+H4YhpO7u7pGREUgPHz7MZrOQCoWC53mQ2tranj17hlejKEomk+GcQ9B1vaGhQVVVCIVC4dq1a57nQeCcRyIRSKZp1tXVQcpkMrt374aQyWTq6+sxbYyIMJPGxsYKhQIk3/fDMITU3d09MjIC6eHDh9lsFlKhUPA8D1JbW9uzZ8/wahRFyWQynHMIuq43NDSoqgqhUChcu3bN8zwInPNIJALJNM26ujpImUxm9+7dEDKZTH19PaaNERFm0tjYWKFQgOT7fhiGkLq7u0dGRiA9fPgwm81CKhQKnudBamtre/bsGV6NoiiZTIZzDkHX9YaGBlVVIRQKhWvXrnmeB4FzHolEIJmmWVdXBymTyezevRtCJpOpr6/HtDEiwg9qYmKiWCxCunLlypdffgmpXC4HQQBpbGzMcRxIIyMjxWIRkuu6YRhC+vrrr6empvDdMcYg2bb93nvv6boOQVGUhQsXcs4heJ739OnTMAwhKIqSSCQg6bq+cOFCSPF4/He/+x0E27arq6sxbYyI8IPq6+vLZrOQjhw5cvnyZUiO43ieh8rinDPGICSTyYMHD0YiEQiMMcuyGGN4GVVVU6kUJEVRqqqqIBmGsWTJEnwvjIjwg+rr68tms5COHDly+fJlSI7jeJ6HyuKcM8YgJJPJgwcPRiIRCIwxy7IYY3gZVVVTqRQkRVGqqqogGYaxZMkSfC+MiPCD6uvry2azkI4cOXL58mVIjuN4nofK4pwzxiAkk8mDBw9GIhEIjDHLshhjeBlVVVOpFCRFUaqqqiAZhrFkyRJ8L4yI8IPq6+vLZrOQjhw5cvnyZUiO43ieh8rinDPGICSTyYMHD0YiEQiMMcuyGGN4GVVVU6kUJEVRqqqqIBmGsWTJEnwvjIjwgxoZGZmamoL0l7/85dNPP4U0MTFRLBbxahhj6XRaURQIjDFd1znnEDzPe/bsWRiGEBhjiqIwxiBkMpnTp0/btg2BMaaqKmMML8M5j0ajkBhjhmFAUlU1kUjge2FEhB9UPp93XRfSoUOHWltbIQ0PD09NTeHVKIqyatUqwzAgcM5t21YUBUKxWLxz547v+5A0TWOMQaitrb1582YikcBrxYgIP6h8Pu+6LqRDhw61trZCGh4enpqawqtRFGXVqlWGYUDgnNu2rSgKhGKxeOfOHd/3IWmaxhiDUFtbe/PmzUQigdeKERF+UPl83nVdSIcOHWptbYU0PDw8NTWFV6MoyqpVqwzDgMA5t21bURQIxWLxzp07vu9D0jSNMQahtrb25s2biUQCrxUjIvyg8vm867qQDh061NraCml4eHhqagqvRlGUVatWGYYBgXNu27aiKBCKxeKdO3d834ekaRpjDEJtbe3NmzcTiQReK0ZE+EG5rhsEAaRz587997//hfTkyZORkRFI8Xg8EolAunv37vDwML5BIpEwTROAYRgffvhhIpGAwBiLRqOccwjlcrmjoyMIAgiu63Z1dQVBAKGmpqalpSUWi+G1YkSEmXTv3r3+/n5I9+/fHxgYgFRbW5tMJiGdPHmyo6MD32Dp0qXxeByAbdunTp2qqamBwBgzTZNzDsF13cePH4dhCGFycvLMmTOu60JIJpP79++PRCJ4rRgRYSbdu3evv78f0v379wcGBiDV1tYmk0lIJ0+e7OjowDdYunRpPB4HYNv2qVOnampqIDDGTNPknENwXffx48dhGEKYnJw8c+aM67oQksnk/v37I5EIXitGRJhJ9+7d6+/vh3T//v2BgQFItbW1yWQS0smTJzs6OvANli5dGo/HAdi2ferUqZqaGgiMMdM0OecQXNd9/PhxGIYQJicnz5w547ouhGQyuX///kgkgteKERFm0r179/r7+yHdv39/YGAAUm1tbTKZhHTy5MmOjg58g6VLl8bjcQC2bZ86daqmpgYCY8w0Tc45BNd1Hz9+HIYhhMnJyTNnzriuCyGZTO7fvz8SieC1YkSEmTQ0NJTL5SB9/fXX4+PjkJLJpG3bkE6cOPHFF19AevLkSS6Xg/T73/9+2bJlAEzT/POf/7xgwQIIjDFVVRljEIIgyGazRAShXC53dHQEQQDBsqxf/epXmqbhtWJEhAoqFoue50EyTVPTNEjNzc0PHjyAdOXKlb6+Pkh79+5tbGwEoGnaxo0bbdvGnMWICBVULBY9z4NkmqamaZCam5sfPHgA6cqVK319fZD27t3b2NgIQNO0jRs32raNOYsRESqoWCx6ngfJNE1N0yA1Nzc/ePAA0pUrV/r6+iDt3bu3sbERgKZpGzdutG0bcxYjIlRQsVj0PA+SaZqapkFqbm5+8OABpCtXrvT19UHau3dvY2MjAE3TNm7caNs25ixGRKggz/PCMISkqirnHNJf//rXL774AtLFixefPn0K6Q9/+MPy5csBmKb5pz/9acGCBXgBYwxzByMizBotLS1dXV2QLly48OTJE0grV66srq4GEI1GT5w4kclkIDEBcwcjIswaLS0tXV1dkC5cuPDkyRNIK1eurK6uBhCNRk+cOJHJZCAxAXMHIyLMGi0tLV1dXZAuXLjw5MkTSCtXrqyurgYQjUZPnDiRyWQgMQFzByMizBotLS1dXV2QLly48OTJE0grV66srq4GEI1GT5w4kclkIDEBcwcjIswad+7cef78OaRPPvmko6MD/080Gv34448zmQwEVVUXLVqkaRrmDkZEmDVKpVIQBJAOHz7c3t4OqbOzc3R0FEA0Gm1ubk6n0xBM01y7dq1lWZg7GBFh1iiVSkEQQDp8+HB7ezukzs7O0dFRANFotLm5OZ1OQzBNc+3atZZlYe5gRIRZo1QqBUEA6fDhw+3t7ZA6OztHR0cBRKPR5ubmdDoNwTTNtWvXWpaFuYMREWaNUqkUBAGkw4cPt7e3Q+rs7BwdHQUQjUabm5vT6TQE0zTXrl1rWRbmDkZEmDV83w/DENLFixefPn0K6fTp0w8fPgSg6/r7779v2zYE0zR//vOfW5YFQVGUn/zkJ5xzCLqur1y5UlEUvIAxhteKERFmq6GhIcdxIH300UefffYZAMZYLBbjnEMwTXPNmjWWZUHQdb2hoUFVVQixWOyDDz4wDAMvYIzhtWJEhNlqaGjIcRxIH3300WeffQaAMRaLxTjnEEzTXLNmjWVZEHRdb2hoUFUVQiwW++CDDwzDwAsYY3itGBFhthoaGnIcB9JHH3302WefAWCMxWIxzjkE0zTXrFljWRYEXdcbGhpUVYUQi8U++OADwzDwAsYYXitGRJitSqVSEASQ/v73v3d3dwMol8vnz5+fmpqCwDk3TZMxBoFzHovFGGMQEonEhx9+aJomBNM0165dq6oqBM55VVUV5xyVxYgIc8Tt27eHhoYAOI5z4MCBsbExCGEYFgoFIsLLJBKJPXv2WJYFIRqNbt68Wdd1CIqiVFdXc85RWYyIMEfcvn17aGgIgOM4Bw4cGBsbgxCGYaFQICK8TCKR2LNnj2VZEKLR6ObNm3Vdh6AoSnV1NecclcWICHPE7du3h4aGADiOc+DAgbGxMQhhGBYKBSLCyyQSiT179liWBSEajW7evFnXdQiKolRXV3POUVmMiDBH3L59e2hoCIDjOAcOHBgbG4MQhmGhUCAivEwikdizZ49lWRCi0ejmzZt1XYegKEp1dTXnHJXFiAhzRDabLZVKADzPu3btmuM4EKampv75z39OTU1BcF330aNHYRhC0DRt2bJliqJAsG37/fffNwwDQjQa3bRpk67rEDjn8Xicc44ZxogIc00QBN3d3Z7nQchms83NzePj4xCKxWJ7e7vv+3iZWCy2bds2wzAgxOPxXbt2maYJQVGUVCrFOccMY0SEuSYIgu7ubs/zIGSz2ebm5vHxcQjFYrG9vd33fbxMLBbbtm2bYRgQ4vH4rl27TNOEoChKKpXinGOGMSLCXBMEQXd3t+d5ELLZbHNz8/j4OIRisdje3u77Pl4mFott27bNMAwI8Xh8165dpmlCUBQllUpxzjHDGBFhrgmCoLu72/M8CNlstrm5eXx8HEKxWGxvb/d9Hy8Ti8W2bdtmGAaEeDy+a9cu0zQhKIqSSqU455hhjIgw1xBRPp8PwxCC67oPHz4sl8sQisXiv//9b8/zIExOTp49e7ZcLkNQVXXhwoWccwjRaPQ3v/mNrusQ3njjjT/+8Y+WZWGGMSLCHBeGYT6fD8MQguM4169f930fwujo6IEDBxzHgUBEeIFpmk1NTZqmQUin08ePH7dtGzOMERHmuDAM8/l8GIYQHMe5fv267/sQRkdHDxw44DgOBCLCC0zTbGpq0jQNQjqdPn78uG3bmGGMiDDHhWGYz+fDMITgOM7169d934cwOjp64MABx3EgEBFeYJpmU1OTpmkQ0un08ePHbdvGDGNEhDkuDMN8Ph+GIQTHca5fv+77PoTR0dEDBw44jgOBiPAC0zSbmpo0TYOQTqePHz9u2zZmGCMizHFE5Ps+JN/3x8bGwjCEMDg4+N57701OTkIKggCSoijJZJJzDiGdTn/88ce2bUMwTXP58uWYAYyI8KPW29vb1NSUy+UgEJHv+3iBqqqMMQjpdLq5udm2bQi2bTc2NmIGMCLCj1pvb29TU1Mul4NARL7v4wWqqjLGIKTT6ebmZtu2Idi23djYiBnAiAg/ar29vU1NTblcDgIR+b6PF6iqyhiDkE6nm5ubbduGYNt2Y2MjZgAjIvyo9fb2NjU15XI5CETk+z5eoKoqYwxCOp1ubm62bRuCbduNjY2YAYyIMNeEYfjs2TPf9yGUy+XOzs5yuQzB9/3+/v4wDCFMTEycOHGiVCpBIiJIqqouWrSIcw6hpqbmb3/7m23bEFRVXbBgAWYAIyLMNUEQPHr0yPM8CIVC4fr1647jQCiXy11dXUEQQCgWi21tbb7v42U0Taurq1MUBUJNTc3Zs2djsRgkzjlmACMizDVBEDx69MjzPAiFQuH69euO40Aol8tdXV1BEEAoFottbW2+7+NlNE2rq6tTFAVCTU3N2bNnY7EYJM45ZgAjIsw1QRA8evTI8zwIhULh+vXrjuNAKJfLXV1dQRBAKBaLbW1tvu/jZTRNq6urUxQFQk1NzdmzZ2OxGCTOOWYAIyLMNUEQPHr0yPM8CIVC4fr1647jQCiXy11dXUEQQCgWi21tbb7v42U0Taurq1MUBUJNTc3Zs2djsRgkzjlmACMizFZjY2OlUgnSnTt3nj9/DsDzvFu3bhWLRQie5/X29rquCyEMw6mpKSKCEARBNpslIkicc0imab799tuqqkJIp9OffPKJbduQGGOYAYyIMFsNDg7m83lIra2tPT09AFzXvXr1quM4EIIgyGazQRBgehRFYYxBME1z3bp1mqZBSKVSx44ds20bM4wREWarwcHBfD4PqbW1taenB4DrulevXnUcB0IQBNlsNggCTI+iKIwxCKZprlu3TtM0CKlU6tixY7ZtY4YxIsJsNTg4mM/nIbW2tvb09ABwXffq1auO40AIgiCbzQZBgOlRFIUxBsE0zXXr1mmaBiGVSh07dsy2bcwwRkSYrQYHB/P5PKTW1taenh4ArutevXrVcRwIQRBks9kgCDA9iqIwxiCYprlu3TpN0yCkUqljx47Zto0ZxogIr0+hUHBdF1JXV9fY2Bik//znP4ODg5C++uqr8fFxAGEYjoyMBEEAgYhc18U3UFW1traWcw4hGo3+9re/1XUdgmVZ77zzjqZpEAzD+OlPf6qqKmYYIyK8PrlcrlgsQrpx48bAwACk1tbWp0+fQhoeHnYcB9+RrusrVqxQVRVCPB7ftWuXaZoQLMtav369pmmoLEZEeH1yuVyxWIR048aNgYEBSK2trU+fPoU0PDzsOA6+I13XV6xYoaoqhHg8vmvXLtM0IViWtX79ek3TUFmMiPD65HK5YrEI6caNGwMDA5BaW1ufPn0KaXh42HEcfEe6rq9YsUJVVQjxeHzXrl2maUKwLGv9+vWapqGyGBHh9cnlcsViEdKNGzcGBgYgtba2Pn36FNLw8LDjOPiOdF1fsWKFqqoQ4vH4rl27TNOEYFnW+vXrNU1DZTEiwkxyHMd1XUhjY2OFQgHSv/71ry+//BLSo0ePstkspOfPnzuOA6lcLgdBgP9HVdXFixerqgohEon8+te/1jQNgmVZv/jFL1RVhaBp2tKlSznnEBRFqa6u5pyjshgRYSblcrlSqQRpcHBwYmIC0unTp9vb2yENDAzk83l8R7quNzQ0GIYBoaqqaseOHaZpQrAsa8OGDZqmQWICXitGRJhJuVyuVCpBGhwcnJiYgHT69On29nZIAwMD+Xwe35Gu6w0NDYZhQKiqqtqxY4dpmhAsy9qwYYOmaZCYgNeKERFmUi6XK5VKkAYHBycmJiCdPn26vb0d0sDAQD6fx3ek63pDQ4NhGBCqqqp27NhhmiYEy7I2bNigaRokJuC1YkSEmZTL5UqlEqTBwcGJiQlIp0+fbm9vhzQwMJDP5/Ed6bre0NBgGAaEqqqqHTt2mKYJwbKsDRs2aJoGiQl4rRgR4dWUSiXP8yBdvXr1q6++gjQ0NJTL5SD973//m5ychPT111+Pj49DKhaLQRDgGyxatCgWiwHQNG39+vWRSASCaZpvv/22aZoQdF1ftmyZoigQFEWprq7mnOMFjDG8VoyI8Gry+bzrupBaWlpu3boFqb+/P5vNQhoeHp6amsL3Ul9fn0wmARiGsX379ng8DsE0zaamJsuyIDDGDMNgjGEWY0SEV5PP513XhdTS0nLr1i1I/f392WwW0vDw8NTUFL6X+vr6ZDIJwDCM7du3x+NxCKZpNjU1WZYFgTFmGAZjDLMYIyK8mnw+77oupJaWllu3bkHq7+/PZrOQhoeHp6am8L3U19cnk0kAhmFs3749Ho9DME2zqanJsiwIjDHDMBhjmMUYEeHV5PN513UhtbS03Lp1C1J/f382m4U0PDw8NTWF76W+vj6ZTAIwDGP79u3xeByCaZpNTU2WZUFgjBmGwRjDLMaICNOQy+WeP38O4e7du/39/ZAGBwdzuRykhw8fPnv2DFKxWHRdF5Lrur7v4xuoqso5h9TY2JjJZCC9++67S5YsAaAoyptvvqnrOgTO+RtvvKEoCiTOOWMMsxgjIkzDyMhIT08PhIsXL3Z2dkLq6ekZGxuDlM1mHcfB96LruqqqkDZt2vTmm29C2rZtW11dHQTLsjjnmLMYEWEaRkZGenp6IFy8eLGzsxNST0/P2NgYpGw26zgOvhdd11VVhbRp06Y333wT0rZt2+rq6iBYlsU5x5zFiAjT8Pz580ePHkH49NNPOzo6IPX19WWzWUjj4+PFYhESEyApisI5xzewbVvTNEjvvvvu0qVLIW3ZsmX58uUAGGOmaXLOMWcxIsI0fP755//4xz8gXLx4sbOzE5LneWEYQgrDkIggpVKpqqoqSA0NDQsXLoTEBEjvvvvukiVLICWTScuyIEUiEU3TIDABcxYjIkzD3bt3z58/D+HixYudnZ2YnoULFyYSCUhr1qxZvHgxJMYY5xzSli1b3nrrLUjRaFTTNPwYMSLCNNy9e/f8+fMQLl682NnZielZuHBhIpGAtGbNmsWLF0NijHHOIW3ZsuWtt96CFI1GNU3DjxEjIkzD3bt3z58/D+HixYudnZ2YnoULFyYSCUhr1qxZvHgxJMYY5xzSli1b3nrrLUjRaFTTNPwYMSLCNHz++ecXLlyAcOXKlYcPH2J6ampq4vE4pFWrVi1atAgS55wxBmnTpk3Lli2DFIlENE3DjxEjIkxDuVx2HAeC4zie52F6FEXhnEPSdV1VVXyDSCSiaRokJuDHiBER5lUcIyLMqzhGRJhXcYyIMK/iGBFhXsUxIsK8imNEhHkVx4gI8yqOERHmVRwjIsyrOEZEmFdx/weupQi1+tZrfwAAAABJRU5ErkJggg=='", 'results': '', 'status': '101'}
```
而终端却返回了200响应值
```
W0721 22:23:22.847523 17715 device_context.cc:422] device: 0, cuDNN Version: 7.6.
 * Serving Flask app "paddlehub.serving.app_compat" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Jul/2021 22:34:01] "POST /predict/mnist_predict HTTP/1.1" 200 -
```

## module.py代码
```python
import paddle
from paddle.nn import Linear
import numpy as np
import argparse
import os
from PIL import Image

import paddlehub as hub
from paddlehub.module.module import runnable, moduleinfo, serving


# 读取一张本地的样例图片，转变成模型输入的格式
def load_image(img_path):
    # 从img_path中读取图像，并转为灰度图
    im = Image.open(img_path).convert('L')
    im = im.resize((28, 28), Image.ANTIALIAS)
    im = np.array(im).reshape(1, -1).astype(np.float32)
    # 图像归一化，保持和数据集的数据范围一致
    im = 1 - im / 255
    return im


# 预测网络结构
class MNIST(paddle.nn.Layer):
    def __init__(self):
        super(MNIST, self).__init__()
        self.fc = paddle.nn.Linear(in_features=784, out_features=1)

    def forward(self, inputs):
        outputs = self.fc(inputs)
        return outputs


@moduleinfo(
    name="mnist_predict",
    version="1.0.0",
    summary="This is a PaddleHub Module. Just for test.",
    author="7hinc",
    author_email="",
    type="cv/my_mnist",
)
class MnistPredict:
    def __init__(self):
        self.parser = argparse.ArgumentParser(
            description="Run the mnist_predict module.",
            prog='hub run mnist_predict',
            usage='%(prog)s',
            add_help=True)
        self.parser.add_argument(
            '--input_img', type=str, default=None, help="img to predict")
        

    def mnist_predict(self, img_path):
        model.eval()
        tensor_img = load_image(img_path)
        paddle.disable_static()
        result = model(paddle.to_tensor(tensor_img))
        
        return result.numpy().astype('int32')
    
    @runnable
    def run_cmd(self, argvs):
        args = self.parser.parse_args(argvs)
        img_path = [args.input_img]

        return self.mnist_predict(img_path)

    @serving
    def mnist_predict(self, img_path):
        model.eval()
        tensor_img = load_image(img_path)
        paddle.disable_static()
        result = model(paddle.to_tensor(tensor_img))

        return result.numpy().astype('int32')

# 代码应该放到全局
model = MNIST()
params_file_path = '/home/aistudio/mnist.pdparams'
param_dict = paddle.load(params_file_path)
model.load_dict(param_dict)

my_mnist = MnistPredict()
```

**Comment by KPatr1ck** [comment]
> Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 10, in <module>
    sys.exit(execute())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/run.py", line 56, in execute
    result = module._run_func(argv[1:])
TypeError: 'property' object is not callable

根据以往issue，出现这个报错可能是因为你当前目录下有`mnist_predict`这个目录，建议换一个目录再执行`hub run mnist_predict --input_img "./5.png"`

> 在AI Studio通过 hub serving start -m mnist_predict 可以正确部署模型，但是在Python代码发送POST请求预测时出现问题，返回的JSON数据如下

能否提供一下post请求的脚本，`[Errno 36] File name too long`看着像是解析文件路径参数时的问题。

**Comment by shaunhurryup** [comment]
## TypeError: 'property' object is not callable
这个错误的原因通过换目录执行**已经解决**。

## POST脚本
```python
import requests
import json
import cv2
import base64

def cv2_to_base64(image):
    data = cv2.imencode('.png', image)[1]
    return base64.b64encode(data.tobytes()).decode('utf-8')

# 发送HTTP请求
data = {'img_path':cv2_to_base64(cv2.imread("5.png"))}
headers = {"Content-type": "application/json"}
url = "http://0.0.0.0:8866/predict/mnist_predict"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
# print(r)
print(r.json())
# print(r.json()["results"])
```

**Comment by KPatr1ck** [comment]
```python
 # 发送HTTP请求
 data = {'img_path':cv2_to_base64(cv2.imread("5.png"))}
```

```python
    @serving
    def mnist_predict(self, img_path):
        model.eval()
        tensor_img = load_image(img_path)
        paddle.disable_static()
        result = model(paddle.to_tensor(tensor_img))

        return result.numpy().astype('int32')
```

这里是有问题的。`img_path`是一个路径信息，你的`mnist_predict`用它作为文件路径加载图像，但是你这里直接把图像读成base64传了过去。

**Comment by shaunhurryup** [comment]
确实是数据格式的问题，发送和返回的数据都应该是JSON格式。修改后的 `module.py` 代码如下，希望对大家有借鉴意义，同时也感谢 @KPatr1ck 的解答！
```python
import paddle
from paddle.nn import Linear
import numpy as np
import argparse
import os
from PIL import Image
import base64
from io import BytesIO
import json

import paddlehub as hub
from paddlehub.module.module import runnable, moduleinfo, serving


# 读取一张本地的样例图片，转变成模型输入的格式
def load_image(img_path):
    # 从img_path中读取图像，并转为灰度图
    im = Image.open(img_path).convert('L')
    im = im.resize((28, 28), Image.ANTIALIAS)
    im = np.array(im).reshape(1, -1).astype(np.float32)
    # 图像归一化，保持和数据集的数据范围一致
    im = 1 - im / 255
    return im


# 预测网络结构
class MNIST(paddle.nn.Layer):
    def __init__(self):
        super(MNIST, self).__init__()
        self.fc = paddle.nn.Linear(in_features=784, out_features=1)

    def forward(self, inputs):
        outputs = self.fc(inputs)
        return outputs


@moduleinfo(
    name="mnist_predict",
    version="1.0.0",
    summary="This is a PaddleHub Module. Just for test.",
    author="7hinc",
    author_email="",
    type="cv/my_mnist",
)
class MnistPredict:
    def __init__(self):
        self.parser = argparse.ArgumentParser(
            description="Run the mnist_predict module.",
            prog='hub run mnist_predict',
            usage='%(prog)s',
            add_help=True)
        self.parser.add_argument(
            '--input_img', type=str, default=None, help="img to predict")
        

    def mnist_predict(self, img_path):
        print('forward')
        model.eval()
        tensor_img = load_image(img_path)
        paddle.disable_static()
        result = model(paddle.to_tensor(tensor_img))

        return result.numpy().astype('int32')
    
    @runnable
    def runnable(self, argvs):
        print('runnable')
        args = self.parser.parse_args(argvs)

        return self.mnist_predict(args.input_img)

    @serving
    def serving(self, img_b64):
        print('serving')
        model.eval()
        img_b = base64.b64decode(img_b64)
        tensor_img = load_image(BytesIO(img_b))
        paddle.disable_static()
        result = model(paddle.to_tensor(tensor_img))

        # 应该返回JSON格式数据
        # 从numpy读出的数据格式是 numpy.int32
        res = { 'res': int(result.numpy().astype('int32')[0][0]) }
        return json.dumps(res)

# 代码应该放到全局
model = MNIST()
params_file_path = '/home/aistudio/mnist.pdparams'
param_dict = paddle.load(params_file_path)
model.load_dict(param_dict)

my_mnist = MnistPredict()
```

### POST请求代码
```python
import requests
import json
import cv2
import base64

def cv2_to_base64(image):
    data = cv2.imencode('.png', image)[1]
    return base64.b64encode(data.tobytes()).decode('utf-8')

# 发送HTTP请求
data = {'img_b64': cv2_to_base64(cv2.imread("5.png"))}
headers = {"Content-type": "application/json"}
url = "http://0.0.0.0:8866/predict/mnist_predict"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r)
print(r.json())
```

### 返回数据
```
<Response [200]>
{'msg': '', 'results': '{"res": 5}', 'status': '000'}
```
