### ISSUE TITLE
Could not find a version that satisfies。。。。

### ISSUE THREAD

**Issue by jurimengs** [PaddlePaddle/PaddleFormers#1550]
win10 
![image](https://user-images.githubusercontent.com/10648133/126935011-dc4f14cc-c0bd-4b1c-bbac-6837ac02892a.png)

安装 gpu 版本报错
PS D:\Python\Python39-32> .\python.exe -m pip install paddlepaddle-gpu==1.8.5.post107 -f https://paddlepaddle.org.cn/whl/stable.html
Looking in links: https://paddlepaddle.org.cn/whl/stable.html
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.8.5.post107 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==1.8.5.post107

**Comment by KPatr1ck** [comment]
你好，请问你当前python的版本是多少？

**Comment by sliontc** [comment]
@KPatr1ck ，你好！我在安装hub的时候老是出错，下面是日志：
root@dev-System-Product-Name:~# python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
Requirement already satisfied: paddlepaddle in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: protobuf>=3.1.0 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: decorator==4.4.2 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: astor in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: numpy>=1.13; python_version >= "3.5" and platform_system != "Windows" in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: gast>=0.3.3; platform_system != "Windows" in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: Pillow in /usr/local/lib/python3.6/dist-packages (from paddlepaddle)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->paddlepaddle)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->paddlepaddle)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->paddlepaddle)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->paddlepaddle)
root@dev-System-Product-Name:~# python3 -m pip install paddlehub -i https://mirror.baidu.com/pypi/simple
Collecting paddlehub
  Downloading https://mirror.baidu.com/pypi/packages/7a/29/3bd0ca43c787181e9c22fe44b944b64d7fcb14ce66d3bf4602d9ad2ac76c/paddlehub-2.1.0-py3-none-any.whl (211kB)
    100% |████████████████████████████████| 215kB 6.1MB/s 
Collecting matplotlib (from paddlehub)
  Downloading https://mirror.baidu.com/pypi/packages/09/03/b7b30fa81cb687d1178e085d0f01111ceaea3bf81f9330c937fb6f6c8ca0/matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5MB)
    100% |████████████████████████████████| 11.5MB 210kB/s 
Collecting pyzmq (from paddlehub)
  Downloading https://mirror.baidu.com/pypi/packages/4b/87/88a87fa6f8a711dc4b56600d9e9ab61e0283607fd3b97376819059b3a9cb/pyzmq-22.1.0-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 2.2MB/s 
Collecting paddle2onnx>=0.5.1 (from paddlehub)
  Downloading https://mirror.baidu.com/pypi/packages/37/80/aa6134b5f36aea45dc1b363e7af941dccabe4d7e167ac391ff046f34baf1/paddle2onnx-0.7-py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 10.3MB/s 
Collecting gitpython (from paddlehub)
  Downloading https://mirror.baidu.com/pypi/packages/55/60/f884f01eef2a7255875862ec1b12d57d74113ec6e8d9e16c4d254cd6aa3c/GitPython-3.1.20-py3-none-any.whl (178kB)
    100% |████████████████████████████████| 184kB 3.1MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from paddlehub)
Collecting opencv-python (from paddlehub)
  Downloading https://mirror.baidu.com/pypi/packages/01/9b/be08992293fb21faf35ab98e06924d7407fcfca89d89c5de65442631556a/opencv-python-4.5.3.56.tar.gz (89.2MB)
    100% |████████████████████████████████| 89.2MB 27kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-msra2r4t/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-msra2r4t/opencv-python/

**Comment by sliontc** [comment]
Python 3.6.9
Paddlepaddle 2.1

**Comment by KPatr1ck** [comment]
> Python 3.6.9
> Paddlepaddle 2.1

目前是已经安装了paddlepaddle 2.1，但是paddlehub安装失败吗？

```sh
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-msra2r4t/opencv-python/setup.py", line 10, in
import skbuild
ModuleNotFoundError: No module named 'skbuild'
```

这个错误建议升级一下pip然后再重试：
```
pip install --upgrade pip
```
