### ISSUE TITLE
使用plato2_en_base模型预测时报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleFormers#1552]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
版本：paddlepaddle-gpu       2.1.1.post112
paddlehub      2.1
环境：windows10
python版本：3.7

使用plato2_en_base命令行预测

hub run plato2_en_base --input_text="Hello, how are you"

报如下错误：
it__() to handle the initialization of the object
Traceback (most recent call last):
  File "d:\programme\anaconda\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programme\anaconda\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\programme\Anaconda\envs\paddle\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\programme\anaconda\envs\paddle\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "d:\programme\anaconda\envs\paddle\lib\site-packages\paddlehub\commands\run.py", line 47, in execute
    module = Module(name=module_name)
  File "d:\programme\anaconda\envs\paddle\lib\site-packages\paddlehub\module\module.py", line 395, in __new__
    **kwargs)
  File "d:\programme\anaconda\envs\paddle\lib\site-packages\paddlehub\module\module.py", line 504, in init_with_name
    user_module._initialize(**kwargs)
  File "d:\programme\anaconda\envs\paddle\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\yx200\.paddlehub\modules\plato2_en_base\module.py", line 56, in _initialize
    self.task = DialogGeneration(args)
  File "C:\Users\yx200\.paddlehub\modules\plato2_en_base\tasks\dialog_generation.py", line 193, in __init__
    self.reader = PlatoReader(args)
  File "C:\Users\yx200\.paddlehub\modules\plato2_en_base\readers\plato_reader.py", line 27, in __init__
    super(PlatoReader, self).__init__(args)
  File "C:\Users\yx200\.paddlehub\modules\plato2_en_base\readers\dialog_reader.py", line 69, in __init__
    self.tokenizer = tokenizer_cls(args)
  File "C:\Users\yx200\.paddlehub\modules\plato2_en_base\utils\tokenization.py", line 138, in __init__
    self.vocab = load_vocab(args.vocab_path)
  File "C:\Users\yx200\.paddlehub\modules\plato2_en_base\utils\tokenization.py", line 104, in load_vocab
    for num, line in enumerate(fin):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 1795: illegal multibyte sequence

**Comment by KPatr1ck** [comment]
你好，plato2_en_base模型暂不支持`hub run`的命令运行，具体的使用方式可以参考：
https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/modules/text/text_generation/plato2_en_base

**Comment by thomas-yanxin** [comment]
![image](https://user-images.githubusercontent.com/58030051/127127818-5f2532b4-97d6-4c60-a48b-5176f8c73ab5.png)
emmm那文档这里可能有点问题欸~~

**Comment by KPatr1ck** [comment]
> ![image](https://user-images.githubusercontent.com/58030051/127127818-5f2532b4-97d6-4c60-a48b-5176f8c73ab5.png)
> emmm那文档这里可能有点问题欸~~

我查证一下

**Comment by KPatr1ck** [comment]
> 复现信息：如为报错，请给出复现环境、复现步骤
版本：paddlepaddle-gpu 2.1.1.post112
paddlehub 2.1
环境：windows10
python版本：3.7

plato2_en_base的[适用环境](https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/modules/text/text_generation/plato2_en_base#%E4%BE%9D%E8%B5%96)：
```
1.8.2 <= paddlepaddle < 2.0.0
1.7.0 <= paddlehub < 2.0.0
```

建议把环境同步到上述的适用环境后再测试一下～
