### ISSUE TITLE
安装paddle-hub报错

### ISSUE THREAD

**Issue by huangcao008** [PaddlePaddle/PaddleFormers#1569]
Traceback (most recent call last):
  File "/usr/local/python3.7.0/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/__init__.py", line 35, in <module>
    from paddlehub.utils.paddlex import download, ResourceNotFoundError
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/utils/paddlex.py", line 19, in <module>
    from paddlehub.server.server import module_server, CacheUpdater
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/server/__init__.py", line 17, in <module>
    from paddlehub.server.git_source import GitSource
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlehub/server/git_source.py", line 27, in <module>
    import git
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/git/__init__.py", line 42, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/git/config.py", line 48, in <module>
    from typing import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing' (/usr/local/python3.7.0/lib/python3.7/typing.py)

**Comment by KPatr1ck** [comment]
你好，这个错误应该是GitPython这个包的更新引起的：
https://github.com/gitpython-developers/GitPython/blob/5b3669e24a8ce7f3f482de86fcf95620db643467/git/config.py#L45

解决的办法如下，选择其中一个即可：
1. 【推荐】安装上一版本的GitPython，`pip install gitpython==3.1.18`
2. 更新Python环境到3.7.2以上
