### ISSUE TITLE
python3.5安装paddlehub提示成功，import时失败

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/PaddleFormers#157]
python3.5安装paddlehub提示成功，默认安装1.1.1版本，import时失败

[root@73b49b2ec016 sentiment_classification]# python
Python 3.5.1 (default, Nov 24 2018, 08:56:52)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/paddlehub/__init__.py", line 48, in <module>
    from .finetune.task import ClassifierTask
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/paddlehub/finetune/task.py", line 29, in <module>
    from visualdl import LogWriter
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/visualdl/__init__.py", line 20, in <module>
    from .python.storage import *  # noqa: F401,F403
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/visualdl/python/storage.py", line 18, in <module>
    from visualdl import core
ImportError: /opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/visualdl/core.so: undefined symbol: _PyThreadState_UncheckedGet

**Comment by Steffy-zxf** [comment]
感谢反馈！根据以上堆栈调用信息，像是visualdl没有安装正确，试试先卸载visualdl，后重装visualdl。
```shell
$ pip uninstall visualdl
$ pip install visualdl
```

**Comment by kinghuin** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
