### ISSUE TITLE
在使用paddlehub2.1版本 进行分类预测，根据示例进行predict，结果报错不包含return_prob

### ISSUE THREAD

**Issue by Jiangbiyu** [PaddlePaddle/PaddleFormers#1575]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by haoyuying** [comment]
具体使用的什么模型，预测脚本是怎样的呢

**Comment by Jiangbiyu** [comment]
> 具体使用的什么模型，预测脚本是怎样的呢

用的是roberta-wwm-ext，预测脚本用的是https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/demo/text_classification/predict.py

**Comment by Zeref996** [comment]
你好，能否提供一下具体的PaddleHub版本？系统类型例如Linux/Windows/MacOS？以及paddlenlp的版本，这样能方便我们进行定位。

**Comment by Jiangbiyu** [comment]
> 你好，能否提供一下具体的PaddleHub版本？系统类型例如Linux/Windows/MacOS？以及paddlenlp的版本，这样能方便我们进行定位。
系统：linux
版本：
paddlehub           2.1.0          
paddlenlp           2.0.7          
paddlepaddle-gpu    2.1.1.post112

**Comment by Jiangbiyu** [comment]
> 你好，能否提供一下具体的PaddleHub版本？系统类型例如Linux/Windows/MacOS？以及paddlenlp的版本，这样能方便我们进行定位。

系统：linux
版本：
paddlehub 2.1.0
paddlenlp 2.0.7
paddlepaddle-gpu 2.1.1.post112

**Comment by linjieccc** [comment]
你好，我用以下这个环境是可以跑的，
paddlehub           2.1.0          
paddlenlp           2.0.7          
paddlepaddle-gpu    2.1.1
请尝试重装下paddlehub

**Comment by Jiangbiyu** [comment]
> 你好，我用以下这个环境是可以跑的，
> paddlehub 2.1.0
> paddlenlp 2.0.7
> paddlepaddle-gpu 2.1.1
> 请尝试重装下paddlehub

results, probs = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False, return_prob=True)
我如果删除了return_prob这个参数 是可以正常运行的，但是按照predict.py 中的包含return_prob，就会报错
重装过paddlehub，但是还是没法解决return_prob报错

**Comment by linjieccc** [comment]
麻烦提供下报错信息

**Comment by Jiangbiyu** [comment]
> 麻烦提供下报错信息

Traceback (most recent call last):
  File "predict.py", line 18, in <module>
    results, probs = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False, return_prob=True)
TypeError: predict() got an unexpected keyword argument 'return_prob'

**Comment by linjieccc** [comment]
> > 麻烦提供下报错信息
> 
> Traceback (most recent call last):
> File "predict.py", line 18, in
> results, probs = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False, return_prob=True)
> TypeError: predict() got an unexpected keyword argument 'return_prob'

卸载重装paddlehub到最新版本即可，return_prob是新版本paddlehub新增的一个参数

**Comment by coderchuan** [comment]
> > > 麻烦提供下报错信息
> > 
> > 
> > Traceback (most recent call last):
> > File "predict.py", line 18, in
> > results, probs = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False, return_prob=True)
> > TypeError: predict() got an unexpected keyword argument 'return_prob'
> 
> 卸载重装paddlehub到最新版本即可，return_prob是新版本paddlehub新增的一个参数

我也遇到这个问题了，同样报错 TypeError: predict() got an unexpected keyword argument 'return_prob'，
经过调查在develo分支中的nlp_module.py中有对return_prob相关参数的修改,而在release分支中没有这样的修改
如果使用的是release分支的demo就会报错。

使用release分支的demo报TypeError: predict() got an unexpected keyword argument 'return_prob'错误应该不是预期结果
@linjieccc

**Comment by linjieccc** [comment]
> > > > 麻烦提供下报错信息
> > > 
> > > 
> > > Traceback (most recent call last):
> > > File "predict.py", line 18, in
> > > results, probs = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False, return_prob=True)
> > > TypeError: predict() got an unexpected keyword argument 'return_prob'
> > 
> > 
> > 卸载重装paddlehub到最新版本即可，return_prob是新版本paddlehub新增的一个参数
> 
> 我也遇到这个问题了，同样报错 TypeError: predict() got an unexpected keyword argument 'return_prob'，
> 经过调查在develo分支中的nlp_module.py中有对return_prob相关参数的修改,而在release分支中没有这样的修改
> 如果使用的是release分支的demo就会报错。
> 
> 使用release分支的demo报TypeError: predict() got an unexpected keyword argument 'return_prob'错误应该不是预期结果
> @linjieccc

Hi, release/v2.1版本和develop分支都有包含新增return_prob参数的更改哈

**Comment by coderchuan** [comment]
> > > > > 麻烦提供下报错信息
> > > > 
> > > > 
> > > > Traceback (most recent call last):
> > > > File "predict.py", line 18, in
> > > > results, probs = model.predict(data, max_seq_len=50, batch_size=1, use_gpu=False, return_prob=True)
> > > > TypeError: predict() got an unexpected keyword argument 'return_prob'
> > > 
> > > 
> > > 卸载重装paddlehub到最新版本即可，return_prob是新版本paddlehub新增的一个参数
> > 
> > 
> > 我也遇到这个问题了，同样报错 TypeError: predict() got an unexpected keyword argument 'return_prob'，
> > 经过调查在develo分支中的nlp_module.py中有对return_prob相关参数的修改,而在release分支中没有这样的修改
> > 如果使用的是release分支的demo就会报错。
> > 使用release分支的demo报TypeError: predict() got an unexpected keyword argument 'return_prob'错误应该不是预期结果
> > @linjieccc
> 
> Hi, release/v2.1版本和develop分支都有包含新增return_prob参数的更改哈

通过命令 pip3 install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple 安装后,查看paddlehub目录,其中的 
 paddlehub/module/nlp_module.py 确实没有 return_prod 相关的内容，并且使用 pip3 list | grep paddlehub 查看版本确实也为2.1.0。实在很迷惑啊

**Comment by linjieccc** [comment]
@coderchuan  你好，可以clone PaddleHub的代码后，执行python setup.py install 进行升级

**Comment by coderchuan** [comment]
> @coderchuan 你好，可以clone PaddleHub的代码后，执行python setup.py install 进行升级

感谢
