### ISSUE TITLE
cannot import name 'calculate_f1_np' from 'paddlehub.finetune.evaluate'

### ISSUE THREAD

**Issue by yisampi** [PaddlePaddle/PaddleFormers#158]
# python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub as hub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/optanaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddlehub/__init__.py", line 48, in <module>
    from .finetune.task import ClassifierTask
  File "/optanaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddlehub/finetune/task/__init__.py", line 17, in <module>
    from .classifier_task import ClassifierTask, ImageClassifierTask, TextClassifierTask, MultiLabelClassifierTask
  File "/optanaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py", line 25, in <module>
    from paddlehub.finetune.evaluate import calculate_f1_np, matthews_corrcoef
ImportError: cannot import name 'calculate_f1_np' from 'paddlehub.finetune.evaluate' (/optanaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddlehub/finetune/evaluate.py)

**Comment by Steffy-zxf** [comment]
感谢反馈！paddlehub版本是多少？可以尝试升级paddlehub至最新版本1.1.3

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
