### ISSUE TITLE
使用pyramidbox_face_detection模型预测时，一些图片推测报错

### ISSUE THREAD

**Issue by gitzhang** [PaddlePaddle/PaddleFormers#1627]
- 版本、环境信息  
1) PaddlePaddle 2.1.3 & PaddleHub 2.1
2) 系统环境：MacOS，python3.8
- 复现信息：
```python
import cv2
import paddlehub as hub


module = hub.Module(name="pyramidbox_face_detection")

test_img = cv2.imread("data/cropped-0-3.JPG")

results = module.face_detection(images=[test_img], visualization=True, use_gpu=False, score_thresh=0.15)

for result in results:
    print('result=', result)
```

- 错误信息
```shell
Traceback (most recent call last):
  File "/Users/jger/work/python/paddle_study/paddlehub_examples/paddlehub_face_detector.py", line 28, in <module>
    results = module.face_detection(images=[test_img], visualization=True, use_gpu=False, score_thresh=0.15)
  File "/Users/jger/opt/anaconda3/envs/paddle_env2/lib/python3.8/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/Users/jger/.paddlehub/modules/pyramidbox_face_detection/module.py", line 105, in face_detection
    out = postprocess(
  File "/Users/jger/.paddlehub/modules/pyramidbox_face_detection/processor.py", line 107, in postprocess
    det_conf = data_out[:, 1]
IndexError: index 1 is out of bounds for axis 1 with size 1
```
![cropped-0-3](https://user-images.githubusercontent.com/2832192/134796897-c48e9975-a2f7-4ac9-8deb-f3ace4beccc4.JPG)

**Comment by haoyuying** [comment]
请问pyramidbox_face_detection用的什么版本呢

**Comment by gitzhang** [comment]
> 请问pyramidbox_face_detection用的什么版本呢

1.1.0

**Comment by haoyuying** [comment]
您好，可以把您报错的107行改成
```
if data_out.shape[1]!=6:
```
我们将会尽快修复该模型，感谢您的反馈

**Comment by gitzhang** [comment]
> 您好，可以把您报错的107行改成
> 
> ```
> if data_out.shape[1]!=6:
> ```
> 
> 我们将会尽快修复该模型，感谢您的反馈

我尝试了好像不行，我改成如下这样，现在不报错了：
```python
else:
    if data_out.shape[1] == 6:
        det_conf = data_out[:, 1]
        ...
```

**Comment by Yakuho** [comment]
你的图片没有人脸，paddlehub 后处理代码中没有做判断，直接取索引了... 你传一张有人脸的图片上去就不会报错——来自 paddlehub==2.3.1 的使用体验
