### ISSUE TITLE
UnboundLocalError: local variable 'downsample_ratios' referenced before assignment

### ISSUE THREAD

**Issue by careylipu** [PaddlePaddle/PaddleFormers#1651]
版本、环境信息
1）PaddleHub和PaddlePaddle版本：

Name: paddlepaddle Version: 2.1.2
Name: paddlex Version: 2.0.0
Name: paddlehub Version: 2.1.1

2）系统环境：Linux
python版本:Python 3.7.4

安全帽识别项目训练的yolov3模型通过!hub serving start -m larva运行，可以启动API。但是 pp-yolo模型 通过运行!hub serving start -m larva报错。

报错信息如下：

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
[10-13 16:38:50 MainThread @logger.py:242] Argv: /opt/conda/envs/python35-paddle120-env/bin/hub serving start -m larva
[10-13 16:38:50 MainThread @utils.py:79] WRN paddlepaddle version: 2.1.2. The dynamic graph version of PARL is under development, not fully tested and supported
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/remote/communication.py:38: DeprecationWarning: 'pyarrow.default_serialization_context' is deprecated as of 2.0.0 and will be removed in a future version. Use pickle or the pyarrow IPC functionality instead.
  context = pyarrow.default_serialization_context()
[2021-10-13 16:38:51,710] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 10, in <module>
    sys.exit(execute())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 352, in execute
    self.start_serving()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 221, in start_single_app_with_args
    self.preinstall_modules()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 152, in preinstall_modules
    m = hub.Module(**init_args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 395, in __new__
    **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 504, in init_with_name
    user_module._initialize(**kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/home/aistudio/.paddlehub/modules/larva/module.py", line 60, in _initialize
    **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/deploy.py", line 52, in __init__
    self._model = load_model(model_dir, with_net=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 86, in load_model
    **model_info['_init_params'])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 1504, in __init__
    self.downsample_ratios = downsample_ratios
UnboundLocalError: local variable 'downsample_ratios' referenced before assignment

**Comment by haoyuying** [comment]
local variable 'downsample_ratios' referenced before assignment 报错信息显示的是downsample_ratios没有定义，可以看下padddlex的使用定义

**Comment by careylipu** [comment]
!hub convert --model_dir predict/ppyolov2_r50vd_dcn/inference_model \
              --module_name zzzz\
              --module_version 1.0 

这是用hub convert自动生成的，为什么会缺少downsample_ratios定义呢，是bug吧？

**Comment by FlyingQianMM** [comment]
> local variable 'downsample_ratios' referenced before assignment 报错信息显示的是downsample_ratios没有定义，可以看下padddlex的使用定义

抱歉，这是paddlex的已知bug，问题已经修复，需要使用paddlex develop可正常导出，paddlex develop安装方法见文档 https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85

安装前记得先卸载 `pip uninstall paddlex`

**Comment by careylipu** [comment]
谢谢！
