### ISSUE TITLE
验证出错

### ISSUE THREAD

**Issue by qwertyuiop194** [PaddlePaddle/PaddleFormers#166]
在自己训练集上训练；按照给定数据集格式制作的，训练的时候可以读取到，验证时读不到图像，提示一下错误，望解答，谢谢

Traceback (most recent call last):
  File "img_classifier.py", line 97, in <module>
    finetune(args)
  File "img_classifier.py", line 87, in finetune
    task.finetune_and_eval()
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 506, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 516, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 557, in _run
    return self._run_with_data_feeder(do_eval=do_eval)
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 596, in _run_with_data_feeder
    self._eval_interval_event()
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 454, in _eval_interval_event
    self.eval(phase="dev")
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 535, in eval
    run_states = self._run()
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 557, in _run
    return self._run_with_data_feeder(do_eval=do_eval)
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/finetune/task.py", line 567, in _run_with_data_feeder
    for run_step, batch in enumerate(self.reader(), start=1):
  File "/home/zlw/.local/lib/python2.7/site-packages/paddle/batch.py", line 35, in batch_reader
    for instance in r:
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/reader/cv_reader.py", line 121, in _data_reader
    image = preprocess(image_path)
  File "/home/zlw/.local/lib/python2.7/site-packages/paddlehub/reader/cv_reader.py", line 91, in preprocess
    image = Image.open(image_path)
  File "/home/zlw/.local/lib/python2.7/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 21] Is a directory: '/home/zlw/Github/PaddleHub/demo/image-classification/Data/OCT_Filtered/'

**Comment by Steffy-zxf** [comment]
根据以上的错误提示，打开的'/home/zlw/Github/PaddleHub/demo/image-classification/Data/OCT_Filtered/'是一个文件夹，而不是一个文件。确定下数据存放的路径是否正确。

**Comment by qwertyuiop194** [comment]
路径存放没有错误

应该是paddle读数据的问题，可能需要自己修改内部函数，-_-||

**Comment by Steffy-zxf** [comment]
已和用户得到沟通，该问题已解决。
