### ISSUE TITLE
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.

### ISSUE THREAD

**Issue by oliwang** [PaddlePaddle/PaddleFormers#168]
操作系统是CentOS 7，python版本是3.6。
安装了paddlepaddle和paddlehub以后，我在命令行运行

`hub run senta_bilstm --input_text "今天天气真好。"`

结果报错

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/python3.6/bin/hub", line 10, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/hub.py", line 69, in main
    command.execute(argv[1:])
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/hub.py", line 56, in execute
    return command.execute(argv[1:])
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/run.py", line 211, in execute
    self.module = self.find_module(module_name)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/run.py", line 71, in find_module
    return hub.Module(module_dir=module_dir)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/module/module.py", line 124, in __init__
    self._init_with_module_file(module_dir=module_dir[0])
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/module/module.py", line 212, in _init_with_module_file
    self.helper.model_path(), executor=exe)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 1207, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 755, in load_persistables
    filename=filename)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 619, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 656, in load_vars
    executor.run(load_prog)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/executor.py", line 657, in run
    use_program_cache=use_program_cache)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/executor.py", line 755, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Call stacks: 
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1774, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 641, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 619, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 755, in load_persistables
    filename=filename)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 1207, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/module/module.py", line 212, in _init_with_module_file
    self.helper.model_path(), executor=exe)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/module/module.py", line 124, in __init__
    self._init_with_module_file(module_dir=module_dir[0])
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/run.py", line 71, in find_module
    return hub.Module(module_dir=module_dir)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/run.py", line 211, in execute
    self.module = self.find_module(module_name)
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/hub.py", line 56, in execute
    return command.execute(argv[1:])
  File "/root/anaconda3/envs/python3.6/lib/python3.6/site-packages/paddlehub/commands/hub.py", line 69, in main
    command.execute(argv[1:])
  File "/root/anaconda3/envs/python3.6/bin/hub", line 10, in <module>
    sys.exit(main())
C++ Call stacks: 
Enforce failed. Expected posix_memalign(&p, alignment, size) == 0, but received posix_memalign(&p, alignment, size):12 != 0:0.
Alloc 643383296 error! at [/paddle/paddle/fluid/memory/detail/system_allocator.cc:57]
PaddlePaddle Call Stacks: 
0       0x7f9d5671f798p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f9d57aed317p paddle::memory::detail::AlignedMalloc(unsigned long) + 295
2       0x7f9d57aed5d7p paddle::memory::detail::CPUAllocator::Alloc(unsigned long*, unsigned long) + 39
3       0x7f9d57aea0c9p paddle::memory::detail::BuddyAllocator::SystemAlloc(unsigned long) + 57
4       0x7f9d57aeb07cp paddle::memory::detail::BuddyAllocator::Alloc(unsigned long) + 332
5       0x7f9d57add415p void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long) + 181
6       0x7f9d57ade145p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long) + 405
7       0x7f9d57ad9973p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 227
8       0x7f9d57ad9b6ep paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 30
9       0x7f9d57abdabcp paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 44
10      0x7f9d57ab69a4p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, unsigned long) + 148
11      0x7f9d57abce78p void paddle::framework::VisitDataType<paddle::framework::DeserializedDataFunctor>(paddle::framework::proto::VarType_Type, paddle::framework::DeserializedDataFunctor) + 408
12      0x7f9d57abbe9bp paddle::framework::TensorFromStream(std::istream&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&) + 523
13      0x7f9d577421aep paddle::framework::DeserializeFromStream(std::istream&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 382
14      0x7f9d56e3bf34p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::LoadLodTensor(std::istream&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*, paddle::framework::ExecutionContext const&) const + 100
15      0x7f9d56e3c380p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 432
16      0x7f9d56e3c743p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
17      0x7f9d57a7cae7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
18      0x7f9d57a7d251p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
19      0x7f9d57a781f4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 260
20      0x7f9d5689f2aep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 590
21      0x7f9d568a21bfp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
22      0x7f9d56711a4dp
23      0x7f9d5674ec36p
24      0x56401470d744p _PyCFunction_FastCallDict + 340
25      0x56401479457ep
26      0x5640147b938ap _PyEval_EvalFrameDefault + 778
27      0x56401478d8e4p
28      0x56401478e771p
29      0x564014794505p
30      0x5640147ba147p _PyEval_EvalFrameDefault + 4295
31      0x56401478d8e4p
32      0x56401478e771p
33      0x564014794505p
34      0x5640147b938ap _PyEval_EvalFrameDefault + 778
35      0x56401478d8e4p
36      0x56401478e771p
37      0x564014794505p
38      0x5640147ba147p _PyEval_EvalFrameDefault + 4295
39      0x56401478d8e4p
40      0x56401478e771p
41      0x564014794505p
42      0x5640147ba147p _PyEval_EvalFrameDefault + 4295
43      0x56401478d8e4p
44      0x56401478e771p
45      0x564014794505p
46      0x5640147b938ap _PyEval_EvalFrameDefault + 778
47      0x56401478dbfep
48      0x56401478e771p
49      0x564014794505p
50      0x5640147ba147p _PyEval_EvalFrameDefault + 4295
51      0x56401478d8e4p
52      0x56401478e771p
53      0x564014794505p
54      0x5640147ba147p _PyEval_EvalFrameDefault + 4295
55      0x56401478d8e4p
56      0x56401478ee6ap _PyFunction_FastCallDict + 986
57      0x56401470db0fp _PyObject_FastCallDict + 623
58      0x5640147126a3p _PyObject_Call_Prepend + 99
59      0x56401470d54ep PyObject_Call + 62
60      0x5640147670fbp
61      0x564014794767p
62      0x56401470d92bp _PyObject_FastCallDict + 139
63      0x56401478ea5ap _PyObject_FastCallKeywords + 170
64      0x56401479457ep
65      0x5640147ba147p _PyEval_EvalFrameDefault + 4295
66      0x56401478e53bp
67      0x564014794505p
68      0x5640147b938ap _PyEval_EvalFrameDefault + 778
69      0x56401478e53bp
70      0x564014794505p
71      0x5640147b938ap _PyEval_EvalFrameDefault + 778
72      0x56401478e53bp
73      0x564014794505p
74      0x5640147b938ap _PyEval_EvalFrameDefault + 778
75      0x56401478e53bp
76      0x564014794505p
77      0x5640147b938ap _PyEval_EvalFrameDefault + 778
78      0x56401478f289p PyEval_EvalCodeEx + 809
79      0x56401479001cp PyEval_EvalCode + 28
80      0x5640148123c4p
81      0x5640148127c1p PyRun_FileExFlags + 161
82      0x5640148129c3p PyRun_SimpleFileExFlags + 451
83      0x5640148164b3p Py_Main + 1555
84      0x5640146df02ep main + 238
85      0x7f9d7f4f63d5p __libc_start_main + 245
86      0x5640147bfe0ep
```

**Comment by Steffy-zxf** [comment]
感谢反馈！这个错误每次都是必现的吗？PaddlePaddle和PaddleHub版本是多少呢？

**Comment by oliwang** [comment]
paddlehub==1.1.3
paddlepaddle==1.5.2

我是在云服务器上会出现这个错误，复制demo作为python文件运行也会报这个错，目前还没有成功运行过。我又新建了一个environment安装还是报一样的错。

我用同样的方式在本地Mac电脑上安装运行时没问题的。

**Comment by ZeyuChen** [comment]
@oliwang 是否方便提供下云服务器上的CPU信息？安装的是CPU版本还是GPU版本？

**Comment by oliwang** [comment]
是阿里云的服务器，安装的是CPU版本。

我用`lscpu`看了一下

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
Stepping:              1
CPU MHz:               2499.996
BogoMIPS:              4999.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt spec_ctrl intel_stibp
```

是因为硬件不够吗？

**Comment by ZeyuChen** [comment]
我们在百度云CPU服务器上测试过paddlehub的可用性，是可以正常执行的hub run命令的。
这一错误可能跟你的硬件有关，
建议在新的云服务器上测试，
或者重新创建干净的conda环境后重新安装paddlepaddle与paddlehub后使用。

**Comment by oliwang** [comment]
创建干净的conda环境这个我试过了，还是会报错。那大概就是硬件的关系了。

**Comment by nepeplwu** [comment]
@oliwang，从报错日志来看，应该是内存不足导致的crash，是否方便给下你的机器内存？

使用`cat /proc/meminfo`看下MemFree这个字段

**Comment by qianshuifanzhou** [comment]
我也遇到了这个问题，下面是cat /proc/meminfo的返回结果，感觉像是内存不够MemFree只有149M，但是不大确定是不是这个问题：
MemTotal:        1883844 kB
MemFree:          149160 kB
MemAvailable:    1578452 kB
Buffers:          176464 kB
Cached:          1292496 kB
SwapCached:            0 kB
Active:           770452 kB
Inactive:         771920 kB
Active(anon):      73616 kB
Inactive(anon):      164 kB
Active(file):     696836 kB
Inactive(file):   771756 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               512 kB
Writeback:             0 kB
AnonPages:         73432 kB
Mapped:            27904 kB
Shmem:               368 kB
Slab:             160852 kB
SReclaimable:     148188 kB
SUnreclaim:        12664 kB
KernelStack:        1456 kB
PageTables:         3656 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      941920 kB
Committed_AS:     293808 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       10500 kB
VmallocChunk:   34359719676 kB
HardwareCorrupted:     0 kB
AnonHugePages:      6144 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       47096 kB
DirectMap2M:     2050048 kB

**Comment by oliwang** [comment]
@nepeplwu 

```
MemTotal:        1014904 kB
MemFree:           76812 kB
MemAvailable:     236996 kB
Buffers:           17444 kB
Cached:           260208 kB
SwapCached:            0 kB
Active:           736184 kB
Inactive:         135972 kB
Active(anon):     594768 kB
Inactive(anon):      240 kB
Active(file):     141416 kB
Inactive(file):   135732 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                40 kB
Writeback:             0 kB
AnonPages:        594544 kB
Mapped:            49836 kB
Shmem:               496 kB
Slab:              35716 kB
SReclaimable:      21624 kB
SUnreclaim:        14092 kB
KernelStack:        2368 kB
PageTables:         8536 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      507452 kB
Committed_AS:    1420552 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        8812 kB
VmallocChunk:   34359719676 kB
HardwareCorrupted:     0 kB
AnonHugePages:     40960 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       61312 kB
DirectMap2M:      987136 kB
DirectMap1G:           0 kB
```

**Comment by kinghuin** [comment]
@oliwang 您好，从MemFree字段来看应该是剩余内存太小了。由于模型参数较多，建议剩余内存>1.4GB，可以尝试一下百度云CPU服务器

**Comment by oliwang** [comment]
@kinghuin 好的，谢谢
