### ISSUE TITLE
Fine-tune时极端时报OverflowError: timeout value is too large错误

### ISSUE THREAD

**Issue by yangchanglin324** [PaddlePaddle/PaddleFormers#1701]
paddle 2.2
paddlehub 2.1
windows10

Exception in thread Thread-8:
Traceback (most recent call last):
  File "***\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "***\Anaconda3\lib\site-packages\visualdl\writer\record_writer.py", line 198, in run
    data = self._queue.get(True, queue_wait_duration)
  File "***\Anaconda3\lib\queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "***\Anaconda3\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

使用erni_tiny进行文本分类Fine-tune时报的错误，应该与可视化训练过程的visualdl有关

**Comment by linjieccc** [comment]
您好，麻烦提供一下最小复现代码，我们先尝试复现一下
