### ISSUE TITLE
u2_conformer_aishell 模块在windows下安装出错

### ISSUE THREAD

**Issue by applepieiris** [PaddlePaddle/PaddleFormers#1706]
我看到官方教程中，在语音辨识task上只有两个模型可以使用了，其中支持中文的u2_conformer_aishell模型，官方文档为https://www.paddlepaddle.org.cn/hubdetail?name=u2_conformer_aishell&en_category=AutomaticSpeechRecognition，在windows系统下，用`hub install u2_conformer_aishell`命令会报错。一直在循环下载模型的tar文件

**Comment by KPatr1ck** [comment]
你好，详细的报错信息可以粘贴出来吗？
因为存在系统依赖，目前ASR的模型`u2_conformer_aishell`仅在linux和macos上测试，windows系统上可能无法运行该模型。

**Comment by applepieiris** [comment]
错误信息为：
`Some errors occurred while installing dependent packages. Detailed error information can be found in the C:\Users\320150117\.paddlehub\log\20211203.log.
Traceback (most recent call last):
  File "D:\condaenvs\autotag\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\condaenvs\autotag\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\condaenvs\autotag\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\commands\install.py", line 49, in execute
    manager.install(archive=_arg)
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\module\manager.py", line 194, in install
    return self._install_from_archive(archive)
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\module\manager.py", line 380, in _install_from_archive
    return self._install_from_directory(directory)
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\module\manager.py", line 364, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\module\module.py", line 418, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "D:\condaenvs\autotag\lib\site-packages\paddlehub\utils\utils.py", line 248, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "D:\condaenvs\autotag\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\320150117\.paddlehub\modules\u2_conformer_aishell\module.py", line 29, in <module>
    from deepspeech.exps.u2.config import get_cfg_defaults
  File "C:\Users\320150117\.paddlehub\modules\u2_conformer_aishell\deepspeech\exps\u2\config.py", line 16, in <module>
    from deepspeech.exps.u2.model import U2Tester
  File "C:\Users\320150117\.paddlehub\modules\u2_conformer_aishell\deepspeech\exps\u2\model.py", line 30, in <module>
    from deepspeech.io.collator import SpeechCollator
  File "C:\Users\320150117\.paddlehub\modules\u2_conformer_aishell\deepspeech\io\collator.py", line 22, in <module>
    from deepspeech.frontend.normalizer import FeatureNormalizer
  File "C:\Users\320150117\.paddlehub\modules\u2_conformer_aishell\deepspeech\frontend\normalizer.py", line 22, in <module>
    from deepspeech.frontend.audio import AudioSegment
  File "C:\Users\320150117\.paddlehub\modules\u2_conformer_aishell\deepspeech\frontend\audio.py", line 24, in <module>
    import soxbindings as sox
ModuleNotFoundError: No module named 'soxbindings'
`
是模块未安装的错误，然后我查了一下windows不支持pip安装soxblings

**Comment by applepieiris** [comment]
`PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\320150117\\.paddlehub\\modules\\u2_conformer_aishell\\deepspeech\\decoders\\sw
ig\\kenlm\\.git\\objects\\pack\\._pack-79c7e12e084d7a04574bf3376ebea9fbbd0d770c.idx'`还有访问受限的问题，我是管理员权限，所以按理说不应该出现文件访问无权限的问题。

**Comment by applepieiris** [comment]
请问windows系统上还有其他方式运行该模型吗？比如通过load 参数值的方式

**Comment by applepieiris** [comment]
终于在linux上安装成功了，然后又遇到了新的问题。
![image](https://user-images.githubusercontent.com/36785462/144983782-38200990-1baf-4961-8f9d-a912ab01c6b7.png)

请问输入的视频如何将采样率转化为16000呢？
![image](https://user-images.githubusercontent.com/36785462/144984150-9fd13905-14ae-4fe4-866f-43df91b44e3e.png)

**Comment by KPatr1ck** [comment]
> 终于在linux上安装成功了，然后又遇到了新的问题。 ![image](https://user-images.githubusercontent.com/36785462/144983782-38200990-1baf-4961-8f9d-a912ab01c6b7.png)
> 
> 请问输入的视频如何将采样率转化为16000呢？ ![image](https://user-images.githubusercontent.com/36785462/144984150-9fd13905-14ae-4fe4-866f-43df91b44e3e.png)

你好，可以在命令行中尝试使用sox工具转换采样率：
```shell
sox input.wav -r 16000 output.wav
```

**Comment by applepieiris** [comment]
> > 终于在linux上安装成功了，然后又遇到了新的问题。 ![image](https://user-images.githubusercontent.com/36785462/144983782-38200990-1baf-4961-8f9d-a912ab01c6b7.png)
> > 请问输入的视频如何将采样率转化为16000呢？ ![image](https://user-images.githubusercontent.com/36785462/144984150-9fd13905-14ae-4fe4-866f-43df91b44e3e.png)
> 
> 你好，可以在命令行中尝试使用sox工具转换采样率：
> 
> ```shell
> sox input.wav -r 16000 output.wav
> ```

嗯嗯，我用soundfile和librosa两个库解决了这个采样率问题，此处贴代码，希望能对其他人有些帮助：
```python
def wav_file_resample(src, dst, dst_sample):
    """
    对目标文件进行降采样，采样率为dst_sample
    :param src:源文件路径
    :param dst:降采样后文件保存路径
    :param dst_sample:降采样后的采样率
    :return:
    """
    src_sig, sr = sf.read(src)
    src_sig = src_sig.T
    dst_sig = librosa.resample(src_sig, sr, dst_sample)
    dst_sig = dst_sig.T
    sf.write(dst, dst_sig, dst_sample)
```
其中src和dst是.wav文件的路径。
