### ISSUE TITLE
model = hub.Module(name='plato-mini') 模型加载错误

### ISSUE THREAD

**Issue by Siriuscy** [PaddlePaddle/PaddleFormers#1729]
python :3.8.3
paddlepaddle:-2.2.1
paddlehub:2.1.1

代码：
import paddlehub as hub

model = hub.Module(name='plato-mini')
data = [["你是谁？"], ["你好啊。", "吃饭了吗？",]]
result = model.predict(data)
print(result)
报错：

Traceback (most recent call last):
  File "/Users/chenyu/Desktop/Rasa/plato/plato_main.py", line 4, in <module>
    model = hub.Module(name='plato-mini')
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/paddlehub/module/module.py", line 388, in __new__
    module = cls.init_with_name(
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/paddlehub/module/module.py", line 511, in init_with_name
    return user_module_cls(**kwargs)
  File "/Users/chenyu/.paddlehub/modules/plato_mini/module.py", line 41, in __init__
    self.model = UnifiedTransformerLMHeadModel.from_pretrained('plato-mini')
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 145, in from_pretrained
    raise ValueError(
ValueError: Calling UnifiedTransformerLMHeadModel.from_pretrained() with a model identifier or the path to a directory instead. The supported model identifiers are as follows: dict_keys(['unified_transformer-12L-cn', 'unified_transformer-12L-cn-luge'])

**Comment by Siriuscy** [comment]
重装环境可以了
