### ISSUE TITLE
 执行hub,就报错cannot import name '_convert_attention_mask' from 'paddle.nn.layer.transformer

### ISSUE THREAD

**Issue by yz4322gly** [PaddlePaddle/PaddleFormers#1758]
系统: windows server 2012 r2 
gpu: CUDA10.0 M60显卡
paddle版本: 
    paddlehub          2.0.2
    paddlenlp          2.2.3
    paddlepaddle-gpu   2.0.2.post100
paddle检查正常运行

执行hub 就报错cannot import name '_convert_attention_mask' from 'paddle.nn.layer.transformer

日志如下
C:\Users\Administrator>activate paddle_env

(paddle_env) C:\Users\Administrator>hub
C:\Miniconda\envs\paddle_env\lib\site-packages\paddle\fluid\layers\utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself.
Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check
the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "C:\Miniconda\envs\paddle_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Miniconda\envs\paddle_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\envs\paddle_env\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlehub\__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlehub\datasets\__init__.py", line 18, in <module>
    from paddlehub.datasets.chnsenticorp import ChnSentiCorp
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlehub\datasets\chnsenticorp.py", line 19, in <module>
    from paddlehub.datasets.base_nlp_dataset import TextClassificationDataset
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlehub\datasets\base_nlp_dataset.py", line 23, in <module>
    from paddlenlp.transformers import PretrainedTokenizer
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlenlp\__init__.py", line 20, in <module>
    from . import ops
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlenlp\ops\__init__.py", line 16, in <module>
    from .faster_transformer.transformer.faster_transformer import *
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlenlp\ops\faster_transformer\transformer\faster_transformer.py", line 22, in <module>
    from paddlenlp.transformers import (TransformerModel, WordEmbedding,
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlenlp\transformers\__init__.py", line 61, in <module>
    from .blenderbot.modeling import *
  File "C:\Miniconda\envs\paddle_env\lib\site-packages\paddlenlp\transformers\blenderbot\modeling.py", line 23, in <module>
    from paddle.nn.layer.transformer import _convert_attention_mask
ImportError: cannot import name '_convert_attention_mask' from 'paddle.nn.layer.transformer' (C:\Miniconda\envs\paddle_env\lib\site-packages\paddle\nn\layer\transformer.py)

**Comment by yz4322gly** [comment]
PaddleNLP 版本太高了,降到2.0.2就可以了,paddlenlp 2.2.3最低paddlepaddle版本要2.2
