### ISSUE TITLE
paddlehub 运行提示 UnicodeEncodeError

### ISSUE THREAD

**Issue by shinoi2** [PaddlePaddle/PaddleFormers#1783]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：

版本、环境信息
1）PaddleHub和PaddlePaddle版本：2.2.0
2）系统环境：Ubuntu 18.04，python3.6
报错信息：
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/server/server.py", line 183, in run
    self.update_resource_list_file(self.command, self.module, self.version, self.addition)
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/server/server.py", line 164, in update_resource_list_file
    if os.path.exists(cache_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\uff5e' in position 0: ordinal not in range(128)
```
根据报错信息定位到应该是这里`~`写成了中文的`～`
https://github.com/PaddlePaddle/PaddleHub/blob/1b99b419e6d477c197f1f5ac38328fc67865ca7e/paddlehub/server/server.py#L162

**Comment by KPatr1ck** [comment]
你好，想问下是在运行什么脚本时抛出的错误。
这个符号应该是有问题的

**Comment by shinoi2** [comment]
运行环境基于 docker 镜像 nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04 构建
在这个环境内执行 hub 命令都会报错
