### ISSUE TITLE
运行hub命令 报json.decoder.JSONDecodeError: Excepting value: line 1 column 1 (char 0)错误

### ISSUE THREAD

**Issue by upcdz** [PaddlePaddle/PaddleFormers#1785]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

（1）PaddlePaddle版本为2.2.1， PaddleHub 2.2.0
（2）系统环境： linux ，  python版本：3.7.10

<img width="515" alt="clipboard" src="https://user-images.githubusercontent.com/45310743/153362303-69c1ccaf-1932-4ab7-9882-b671890802a0.png">

**Comment by KPatr1ck** [comment]
你好，开发环境的网络连接状况是正常的吗？
先试一下 hub install lac 安装lac模型

**Comment by javadoge** [comment]
hub install lac 也不行，

(paddle_env) D:\dev-soft\anaconda3\condabin>hub install lac
D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\dev-soft\anaconda3\envs\paddle_env\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\commands\install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\manager.py", line 262, in _install_from_name
    result = module_server.search_module(name=name, version=version)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\server\server.py", line 87, in search_module
    return self.search_resource(
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\server\server.py", line 113, in search_resource
    result = source.search_resource(name=name, type=type, version=version)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\server\server_source.py", line 77, in search_resource
    result = self.request(path='search', params=params)
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\server\server_source.py", line 118, in request
    return result.json()
  File "D:\dev-soft\anaconda3\envs\paddle_env\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><html lang="zh-cmn-Hans-CN"><head><meta charset="utf-8"/><meta http-equiv="refresh" content="4;url=/"><link rel="icon" href="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/favicon-48.png" sizes="48x48"><link rel="icon" href="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/favicon-64.png" sizes="64x64"><link rel="icon" href="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/favicon-128.png" sizes="128x128"><meta name="viewport" content="width=device-width"/><meta name="theme-color" content="#fff"/><link rel="manifest" href="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/manifest.json"/><title> 飞桨PaddlePaddle-源于产业实践的开源深度学习平台</title><meta name="keywords" content="飞桨PaddlePaddle"/><meta name="description" content="飞桨PaddlePaddle-源于产业实践的开源深度学习平台"/><script>if(void 0===_historyPolyfill){var _historyPolyfill=function(t){var n=history[t];function e(t){var n;return"function"==typeof Event?n=new Event(t):(n=document.createEvent("Event")).initEvent(t,!0,!0),n}return function(){var i=n.apply(this,arguments),o=t.toLowerCase(),r="on"+o,a=e(o);return a.arguments=arguments,window.dispatchEvent(a),"function"==typeof window[r]&&window[r].apply(this,arguments),i}};history.pushState=_historyPolyfill("pushState"),history.replaceState=_historyPolyfill("replaceState")}</script><script>var _hmt=_hmt||{};!function(){var e=function(){_hmt=_hmt||{};var e=document.getElementById("baidu-tj");e&&e.parentNode.removeChild(e);var t=document.createElement("script");t.id="baidu-tj",t.src="https://hm.baidu.com/hm.js?89be97848720f62fa00a07b1e0d83ae6";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n),setTimeout((function(){"function"!=typeof _hmt.push&&(_hmt=void 0)}),0)};e(),window.addEventListener("popstate",e),window.addEventListener("pushstate",e),window.addEventListener("replacestate",e)}()</script><script>!function(){var t=function(){var t=document.getElementById("baidu-push");t&&t.parentNode.removeChild(t);var e=document.createElement("script");e.id="baidu-push";var n=window.location.protocol.split(":")[0];e.src="https"===n?"https://zz.bdstatic.com/linksubmit/push.js":"http://push.zhanzhang.baidu.com/push.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(e,a)};t(),window.addEventListener("popstate",t),window.addEventListener("pushstate",t),window.addEventListener("replacestate",t)}()</script><style>.paddle-s-e-o{position:absolute;overflow:hidden;height:0;width:0}</style><link href="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/static/css/common.e8f70c71.chunk.css" rel="stylesheet"><link href="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/static/css/404.4a3f11e8.chunk.css" rel="stylesheet"></head><body><style>.paddle-logo{position:absolute;overflow:hidden;height:0;width:0}</style><div class="paddle-logo"><img src="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/static/media/paddlelogo.0b483fa7.png"/></div><noscript>You need to enable JavaScript to run this app.</noscript><div style="height:0;overflow:hidden">\u200E</div><div id="root"></div><div class="paddle-s-e-o"><div class="header"></div></div><script src="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/static/js/runtime.393fb9ff.js"></script><script src="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/static/js/common.d9c2232f.chunk.js"></script><script src="https://paddlepaddle-org-cn.cdn.bcebos.com/paddle-site-front/static/js/404.d28ca1b8.chunk.js"></script></body></html>: 0

**Comment by GreatLandmark** [comment]
同样问题。
环境：
- Python 3.7.15 (conda 4.10.3),  
- paddlehub/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2.3.1
- PaddlePaddle 2.4.1, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
- Description:    Ubuntu 16.04.6 LTS.    
在jupyter notebook 里，运行（readme中的）lac案例报错:
File "/home/name/anaconda3/envs/paddlehub/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
