### ISSUE TITLE
cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc'

### ISSUE THREAD

**Issue by tangkai521** [PaddlePaddle/PaddleFormers#1792]
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub2.0.4，PaddlePaddle2.0.2
2）系统环境：官网算力，python3.7
#安装预训练模型
!hub install vgg19_imagenet==1.0.0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 6, in <module>
    from paddlehub.commands.utils import execute
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/__init__.py", line 24, in <module>
    import paddlehub.commands.install
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/install.py", line 21, in <module>
    from paddlehub.module.manager import LocalModuleManager
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py", line 28, in <module>
    from paddlehub.utils import xarfile, log, utils, pypi
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/utils/pypi.py", line 18, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pip/_internal/utils/misc.py)

**Comment by thgpddl** [comment]
我也遇到了，是paddlehub版本问题，我使用`pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple`升级后就成功运行了

**Comment by Berlinbenilo** [comment]
Probably this issue is based on pip version. You must downgrade the pip version to 21.2
`pip install pip==21.2`
or
`python -m pip install pip==21.2`

**Comment by Alvaro8317** [comment]
Hi @Berlinbenilo , how did you know that was the pip version? Thanks to you I could resolve my issue, but I'd to know how to identify something so specific. Thanks in advance!
