### ISSUE TITLE
使用paddlehub1.8预训练报错：task.finetune_and_eval()

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleFormers#1794]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddle-gpu=2.2.0  paddlehub=1.8.0
2）系统环境：win10，Anconda环境，python=3.6.13
- 复现信息：
- 根据：[PaddleHub 图像分类-开始Fine-tune](https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/demo/image_classification)编写的一样的代码，我的代码如下：
```python
import paddle
paddle.enable_static()
import paddlehub as hub
# from data import DemoDataset

module = hub.Module(name='resnet_v2_50_imagenet')
# dataset = DemoDataset()
dataset = hub.dataset.Flowers()
data_reader = hub.reader.ImageClassificationReader(
    image_width=module.get_expected_image_width(),
    image_height=module.get_expected_image_height(),
    images_mean=module.get_pretrained_images_mean(),
    images_std=module.get_pretrained_images_std(),
    dataset=dataset
)

config = hub.RunConfig(
    use_cuda=True,
    num_epoch=1,
    checkpoint_dir='output/',
    batch_size=32,
    eval_interval=50,
    strategy=hub.finetune.strategy.DefaultFinetuneStrategy()
)

input_dict, output_dict, program = module.context(trainable=True)

feature_map = output_dict['feature_map']
feed_list = [input_dict['image'].name]

task = hub.ImageClassifierTask(
    data_reader=data_reader,
    feed_list=feed_list,
    feature=feature_map,
    num_classes=dataset.num_labels,
    config=config
)

run_states = task.finetune_and_eval()

```

运行后报错，报错信息如下：
```python
[2022-02-18 11:11:52,576] [    INFO] - PaddleHub finetune start
Traceback (most recent call last):
  File "D:/WorkSpace/PeachClassify/main.py", line 39, in <module>
    run_states = task.finetune_and_eval()
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 945, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 966, in finetune
    run_states = self._run(do_eval=do_eval)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1212, in _run
    return_numpy=self.return_numpy)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\executor.py", line 1246, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\executor.py", line 1244, in run
    return_merged=return_merged)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\executor.py", line 1387, in _run_impl
    return_merged=return_merged)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\executor.py", line 1049, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
RuntimeError: In user code:

    File "D:/WorkSpace/PeachClassify/main.py", line 39, in <module>
      run_states = task.finetune_and_eval()
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 945, in finetune_and_eval
      return self.finetune(do_eval=True)
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 960, in finetune
      self.init_if_necessary()
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 384, in init_if_necessary
      if not self.load_checkpoint():
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 911, in load_checkpoint
      main_program=self.main_program)
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 545, in main_program
      self._build_env()
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\finetune\task\base_task.py", line 413, in _build_env
      self._base_main_program, for_test=False)
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\common\paddle_helper.py", line 299, in clone_program
      dest_program.global_block())
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlehub\common\paddle_helper.py", line 191, in _copy_vars_and_ops_in_blocks
      to_block.append_op(**op_info)
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    NotFoundError: The argument ReserveSpace of batch_norm op is not found.
      [Hint: reserve_space should not be null.] (at ../paddle/fluid/operators/batch_norm_op.cu:426)
      [operator < batch_norm > error]

Process finished with exit code 1
```

**Comment by KPatr1ck** [comment]
你好，建议将paddlepaddle和paddlehub的大版本对齐后再使用。
可以尝试安装paddlepaddle 1.8版本：
```
python3 -m pip install paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple
```
