### ISSUE TITLE
python3.6安装成功 import报错

### ISSUE THREAD

**Issue by thousfeet** [PaddlePaddle/PaddleFormers#180]
已安装了paddlepaddle和paddlehub
```
paddlehub=1.2.0      
paddlepaddle-gpu=1.5.2.post87 
```
但import时出错：
```
>>> import paddlehub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/paddlehub/__init__.py", line 48, in <module>
    from .finetune.task import ClassifierTask
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/paddlehub/finetune/task/__init__.py", line 16, in <module>
    from .basic_task import BasicTask, RunEnv, RunState
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/paddlehub/finetune/task/basic_task.py", line 26, in <module>
    from tb_paddle import SummaryWriter
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/__init__.py", line 4, in <module>
    from .writer import FileWriter, SummaryWriter
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/writer.py", line 16, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/proto/event_pb2.py", line 16, in <module>
    from tb_paddle.proto import summary_pb2 as tb__paddle_dot_proto_dot_summary__pb2
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/proto/summary_pb2.py", line 16, in <module>
    from tb_paddle.proto import tensor_pb2 as tb__paddle_dot_proto_dot_tensor__pb2
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/proto/tensor_pb2.py", line 16, in <module>
    from tb_paddle.proto import resource_handle_pb2 as tb__paddle_dot_proto_dot_resource__handle__pb2
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tb_paddle/proto/resource_handle_pb2.py", line 23, in <module>
    serialized_pb=_b('\n%tb_paddle/proto/resource_handle.proto\x12\ttb_paddle\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

```

请问要怎么解决，非常感谢

**Comment by nepeplwu** [comment]
@thousfeet ，感谢反馈，从堆栈来看应该是protobuf的版本太低导致，建议升级到最新版本试试看
`pip install --upgrade protobuf`

**Comment by thousfeet** [comment]
> 
> 
> @thousfeet ，感谢反馈，从堆栈来看应该是protobuf的版本太低导致，建议升级到最新版本试试看
> `pip install --upgrade protobuf`

解决了 非常感谢！
