### ISSUE TITLE
自定义datasets，执行finetune_and_eval()报这个错

### ISSUE THREAD

**Issue by wshzd** [PaddlePaddle/PaddleFormers#182]
Traceback (most recent call last):
  File "E:/Pycharm/NER/ERNIE_NER/sequence_label.py", line 123, in <module>
    seq_label_task.finetune_and_eval()
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 506, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 516, in finetune
    run_states = self._run(do_eval=do_eval)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 557, in _run
    return self._run_with_data_feeder(do_eval=do_eval)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 567, in _run_with_data_feeder
    for run_step, batch in enumerate(self.reader(), start=1):
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\reader\nlp_reader.py", line 286, in wrapper
    examples, batch_size, phase=phase):
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\reader\nlp_reader.py", line 213, in _prepare_batch_data
    self.tokenizer, phase)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\reader\nlp_reader.py", line 464, in _convert_example_to_record
    for label in labels] + [no_entity_id]
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\reader\nlp_reader.py", line 464, in <listcomp>
    for label in labels] + [no_entity_id]
KeyError: 'O O O B-时间点 I-时间点 I-时间点 O B-否定

**Comment by wshzd** [comment]
我按照hub.dataset.MSRA_NER()的格式定义的，train.tsv、test.tsv和dev.tsv的格式是text_a的每个char使用空格分隔，text_a和label使用\t分隔，然后运行sequence_label.py结果报上述错了，说是KeyError:，可是我打印label_map是可以正常输出值的

**Comment by Steffy-zxf** [comment]
感谢反馈！利用Ernie完成序列标注任务时，标签是针对每一个字的，所以text_a的每一个字是以空格分开，对应每个字的label也需要以空格分开。

**Comment by wshzd** [comment]
是的，我的数据text_a就是使用python脚本的时候使用write(' ')的方式写入空格的，后来查看hub.dataset.MSRA_NER()的数据格式，发现是text_a是以分隔的，使用notepad++打开，显示是分隔符是STX，所以我替换了，那么数据格式的问题就好了，不过有报新的错误了：
C:\Users\user\paddlepaddle\Scripts\python.exe E:/Pycharm/demo/NER/baidu/sequence_label.py
[2019-09-30 10:53:45,069] [    INFO] - Installing ernie module-1.0.2
[2019-09-30 10:53:45,514] [    INFO] - Module ernie-1.0.2 already installed in C:\Users\user\.paddlehub\modules\ernie
[2019-09-30 10:53:46,416] [    INFO] - Set maximum sequence length of input tensor to 128
[2019-09-30 10:53:46,416] [ WARNING] - ernie-stable has no task_id, the arguement use_taskid of Reader class must be False.
[2019-09-30 10:53:46,416] [    INFO] - The shape of input tensor[input_ids] set to [-1, 128, 1]
[2019-09-30 10:53:46,416] [    INFO] - The shape of input tensor[position_ids] set to [-1, 128, 1]
[2019-09-30 10:53:46,416] [    INFO] - The shape of input tensor[segment_ids] set to [-1, 128, 1]
[2019-09-30 10:53:46,416] [    INFO] - The shape of input tensor[input_mask] set to [-1, 128, 1]
[2019-09-30 10:53:46,417] [    INFO] - 199 pretrained paramaters loaded by PaddleHub
Downloading msra_ner.tar.gz
[==================================================] 100.00%
Uncompress C:\Users\user\.paddlehub\dataset\msra_ner.tar.gz
[==================================================] 100.00%
[2019-09-30 10:53:48,702] [    INFO] - Dataset label map = {'B-PER': 0, 'I-PER': 1, 'B-ORG': 2, 'I-ORG': 3, 'B-LOC': 4, 'I-LOC': 5, 'O': 6}
[2019-09-30 10:53:48,702] [    INFO] - Checkpoint dir: ernie_seq_label_turtorial_demo
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=6 # for example, set CPU_NUM as number of physical CPU core which is 6.

!!! The default number of CPU_NUM=1.
[2019-09-30 10:53:53,578] [    INFO] - Try loading checkpoint from ernie_seq_label_turtorial_demo\ckpt.meta
[2019-09-30 10:53:53,579] [    INFO] - PaddleHub model checkpoint not found, start training from scratch...
[2019-09-30 10:53:53,935] [    INFO] - PaddleHub finetune start
Traceback (most recent call last):
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddle\fluid\data_feeder.py", line 89, in done
    arr = arr.reshape(self.shape)
ValueError: cannot reshape array of size 128 into shape (10000,1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Pycharm/demo/NER/baidu/sequence_label.py", line 119, in <module>
    seq_label_task.finetune_and_eval()
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 506, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 516, in finetune
    run_states = self._run(do_eval=do_eval)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 557, in _run
    return self._run_with_data_feeder(do_eval=do_eval)
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddlehub\finetune\task.py", line 577, in _run_with_data_feeder
    feed=data_feeder.feed(batch),
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddle\fluid\data_feeder.py", line 289, in feed
    ret_dict[each_name] = each_converter.done()
  File "C:\Users\user\paddlepaddle\lib\site-packages\paddle\fluid\data_feeder.py", line 93, in done
    .format(self.shape, arr.shape))
ValueError: Reshape error. What is defined in data layer is (-1, 10000, 1), but receive (1, 1, 128, 1)

Process finished with exit code 1

**Comment by Steffy-zxf** [comment]
从以上报错信息来看，无法进行shape转换。
```python
module = hub.Module(name="ernie")
inputs, outputs, program = module.context(trainable=True, max_seq_len=128)
```
context接口的max_seq_len 必须与SequenceLabelReader接口参数max_seq_len保持一致。
参考序列标注任务的说明
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.2/demo/sequence-labeling

**Comment by kinghuin** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天关闭。关闭后您可重新开启此issue继续跟进问题。
