### ISSUE TITLE
PaddleHub 口罩检测示例 Please set another path through the set HUB_HOME command怎么解决

### ISSUE THREAD

**Issue by 123456bfb** [PaddlePaddle/PaddleFormers#1824]
代码：
# 一、定义待预测数据

# 待预测图片
test_img_path = ["./test_mask_detection.jpg"]

import matplotlib.pyplot as plt 
import matplotlib.image as mpimg 

img = mpimg.imread(test_img_path[0]) 

# 展示待预测图片
plt.figure(figsize=(10,10))
plt.imshow(img) 
plt.axis('off') 
plt.show()

# 二、加载预训练模型

import paddlehub as hub

module = hub.Module(name="pyramidbox_lite_mobile_mask")
# module = hub.Module(name="pyramidbox_lite_server_mask")

# 三、预测

import os

import cv2

imgs = [cv2.imread(test_img_path[0])]

# 口罩检测预测
# visualization=True 将预测结果保存图片可视化
# output_dir='detection_result' 预测结果图片保存在当前运行路径下detection_result文件夹下
results = module.face_detection(images=imgs, use_multi_scale=True, shrink=0.6, visualization=True, output_dir='detection_result')
for result in results:
    print(result)

# 预测结果展示

path = os.path.join('detection_result', 'test_img.jpg')
img = mpimg.imread(path)
plt.figure(figsize=(10,10))
plt.imshow(img) 
plt.axis('off') 
plt.show()

运行结果：
[2022-03-30 23:50:21,463] [ WARNING] - The home directory contains Chinese characters which may cause unknown exceptions in the execution                     of some modules. Please set another path through the set HUB_HOME command.
[2022-03-30 23:50:21,631] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2022-03-30 23:50:21,778] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0330 23:50:21.781178 24160 analysis_predictor.cc:1350] Deprecated. Please use CreatePredictor instead.
(NotFound) Cannot open file C:\Users\澶╁疂\.paddlehub\modules\pyramidbox_lite_mobile\pyramidbox_lite_mobile_face_detection/__model__, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:1116)

Traceback (most recent call last):
  File "mask_detection.py", line 22, in <module>
    module = hub.Module(name="pyramidbox_lite_mobile_mask")
  File "D:\Python37\lib\site-packages\paddlehub\module\module.py", line 395, in __new__
    **kwargs)
  File "D:\Python37\lib\site-packages\paddlehub\module\module.py", line 504, in init_with_name
    user_module._initialize(**kwargs)
  File "D:\Python37\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\天宝\.paddlehub\modules\pyramidbox_lite_mobile_mask\module.py", line 36, in _initialize
    self.face_detector = hub.Module(name='pyramidbox_lite_mobile')
  File "D:\Python37\lib\site-packages\paddlehub\module\module.py", line 395, in __new__
    **kwargs)
  File "D:\Python37\lib\site-packages\paddlehub\module\module.py", line 504, in init_with_name
    user_module._initialize(**kwargs)
  File "D:\Python37\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\天宝\.paddlehub\modules\pyramidbox_lite_mobile\module.py", line 30, in _initialize
    self._set_config()
  File "D:\Python37\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\天宝\.paddlehub\modules\pyramidbox_lite_mobile\module.py", line 40, in _set_config
    self.cpu_predictor = create_paddle_predictor(cpu_config)
RuntimeError: Unknown exception

**Comment by KPatr1ck** [comment]
> 运行结果：
[2022-03-30 23:50:21,463] [ WARNING] - The home directory contains Chinese characters which may cause unknown exceptions in the execution of some modules. Please set another path through the set HUB_HOME command.

这里提示的是你的用户目录下包含中文字符，建议换成没有中文字符的路径。
可以将HUB_HOME配置在环境变量中，也要确保不包括中文字符。

**Comment by 123456bfb** [comment]
我已经安装了paddlehub,要怎么将HUB_HOME配置在环境变量里？要重新安装吗？能不能详细讲一下怎么弄，谢谢！

**Comment by 123456bfb** [comment]
> > 运行结果：
> > [2022-03-30 23:50:21,463] [ WARNING] - The home directory contains Chinese characters which may cause unknown exceptions in the execution of some modules. Please set another path through the set HUB_HOME command.
> 
> 这里提示的是你的用户目录下包含中文字符，建议换成没有中文字符的路径。 可以将HUB_HOME配置在环境变量中，也要确保不包括中文字符。

我已经安装了paddlehub,要怎么将HUB_HOME配置在环境变量里？要重新安装吗？能不能详细讲一下怎么弄，谢谢！

**Comment by KPatr1ck** [comment]
> 怎么将HUB_HOME配置在环境变量里

不需要重新安装，配置环境变量的方法可参考：
https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

**Comment by 123456bfb** [comment]
> > 怎么将HUB_HOME配置在环境变量里
> 
> 不需要重新安装，配置环境变量的方法可参考： https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

![image](https://user-images.githubusercontent.com/68626928/162109631-a14f9718-233f-4eeb-9f8c-4b1a22064644.png)
这个怎么添加呀？把paddlehub改到D盘吗？还是重新写一个？
