### ISSUE TITLE
导入paddlehub即报错

### ISSUE THREAD

**Issue by lightbordwin** [PaddlePaddle/PaddleFormers#1830]
paddlehub==2.2.0 paddlepaddle==2.2.2  Pillow==9.1.0
python3.8 win10系统

使用如下代码
import paddlehub as hub
import paddle

model = hub.Module(name='ernie', version='2.0.2', task='text-matching')

model.get_tokenizer()

报错如下
Traceback (most recent call last):

  File "C:\Users\dengyn\Documents\caiwubaobiao\baobiaoimage\src\untitled0.py", line 7, in <module>
    import paddlehub as hub

  File "D:\anaconda\lib\site-packages\paddlehub\__init__.py", line 31, in <module>
    from paddlehub import datasets

  File "D:\anaconda\lib\site-packages\paddlehub\datasets\__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas

  File "D:\anaconda\lib\site-packages\paddlehub\datasets\canvas.py", line 23, in <module>
    from paddlehub.vision.utils import get_img_file

  File "D:\anaconda\lib\site-packages\paddlehub\vision\utils.py", line 224, in <module>
    def get_pseudo_color_map(pred: np.ndarray) -> PIL.Image.Image:

AttributeError: module 'PIL' has no attribute 'Image'

**Comment by rainyfly** [comment]
已收到相关报错，我们将进行修复，你可以尝试在D:\anaconda\lib\site-packages\paddlehub\vision\utils.py开头加上import PIL.Image
