### ISSUE TITLE
fine-tune模型转为module时报错

### ISSUE THREAD

**Issue by lightbordwin** [PaddlePaddle/PaddleFormers#1859]
我使用ernie2.0 通过fine-tuneAPI迁移训练了导出了一个新模型，任务是text-matching。我在使用 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/finetuned_model_to_module.md
中的教程将model转为module时出现了错误，下面是完整的错误信息
runfile('D:/paddle_workspace/ernie_demo/src/test.py', wdir='D:/paddle_workspace/ernie_demo/src')
Reloaded modules: ernie.module, finetuned_model_to_module.module
[2022-05-06 09:36:26,650] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2022-05-06 09:36:26,652] [    INFO] - Already cached C:\Users\dengyn\.paddlenlp\models\ernie-1.0\ernie_v1_chn_base.pdparams
[2022-05-06 09:36:27,419] [    INFO] - Weights from pretrained model not used in ErnieModel: ['cls.predictions.layer_norm.weight', 'cls.predictions.decoder_bias', 'cls.predictions.transform.bias', 'cls.predictions.transform.weight', 'cls.predictions.layer_norm.bias']
Traceback (most recent call last):

  File "D:\paddle_workspace\ernie_demo\src\test.py", line 13, in <module>
    module = hub.Module(

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 398, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 525, in init_with_directory
    user_module._initialize(**kwargs)

  File "D:\anaconda\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)

  File "D:\paddle_workspace\ernie_demo\src\finetuned_model_to_module\module.py", line 33, in _initialize
    self.module = hub.Module(name="ernie",version="2.0.2",task="text-matching")

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 388, in __new__
    module = cls.init_with_name(

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 511, in init_with_name
    return user_module_cls(**kwargs)

  File "C:\Users\dengyn\.paddlehub\modules\ernie\module.py", line 76, in __init__
    self.model = ErnieModel.from_pretrained(pretrained_model_name_or_path='ernie-1.0', **kwargs)

  File "C:\Users\dengyn\AppData\Roaming\Python\Python38\site-packages\paddlenlp\transformers\model_utils.py", line 376, in from_pretrained
    state_to_load[k] = state_to_load[k].astype(dtype)

AttributeError: 'paddle.fluid.core_avx.LoDTensor' object has no attribute 'astype'

我使用的调用方法是直接通过Hub.Module(directory=...)加载，请问这种情况怎么处理？

**Comment by KPatr1ck** [comment]
你好，建议将paddlepaddle和paddlehub升级到最新版，根据下面教程导出模型：
https://github.com/PaddlePaddle/PaddleHub/blob/develop/docs/docs_ch/tutorial/custom_module.rst
