### ISSUE TITLE
fine-tuneAPI导出模型转换module时报错

### ISSUE THREAD

**Issue by lightbordwin** [PaddlePaddle/PaddleFormers#1860]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlehub2.2.0 paddlepaddle2.2.2 win10 python3.8.8
使用ernie2.0 通过finetuneAPI导出的迁移训练模型，任务为text_matching，通过
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/finetuned_model_to_module.md
中教程进行model to module的转换，转换使用的module.py代码如下

import os

import numpy as np
from paddlehub.common.logger import logger
from paddlehub.module.module import moduleinfo, serving
import paddlehub as hub

@moduleinfo(
    name="ernie_2.0_finetuned",
    version="1.0.0",
    summary="ERNIE 2.0 which was fine-tuned on the st-cbs dataset.",
    author="dyn",
    author_email="",
    type="nlp/text-matching")
class ERNIE2Finetuned(hub.Module):
    def _initialize(self,
                ckpt_dir="./ckpt",
                num_class=2,
                max_seq_len=128,
                use_gpu=False,
                batch_size=1):
        self.ckpt_dir=os.path.join(self.directory, ckpt_dir)
        self.num_class = num_class
        self.MAX_SEQ_LEN = max_seq_len

        self.params_path = os.path.join(self.ckpt_dir, 'best_model')
        if not os.path.exists(self.params_path):
            logger.error(
                "%s doesn't contain the best_model file which saves the best parameters as fietuning."
                )
            exit()
            
        # Load Paddlehub ERNIE 2.0 pretrained model
        self.module = hub.Module(name="ernie",version="2.0")
        inputs, outputs, program = self.module.context(
            trainable=True, max_seq_len=max_seq_len)
        
        self.vocab_path = self.module.get_vocab_path()
        
        # metric should be acc, f1 or matthews
        metrics_choices = ["acc"]
        
        reader = hub.reader.ClassifyReader(
        vocab_path=self.module.get_vocab_path(),
        max_seq_len=max_seq_len,
        sp_model_path=None,
        word_dict_path=None)
        
        pooled_output = outputs["pooled_output"]
        
        feed_list = [
            inputs["input_ids"].name,
            inputs["position_ids"].name,
            inputs["segment_ids"].name,
            inputs["input_mask"].name,
        ]
        
        # Setup runing config for PaddleHub Finetune API
        config = hub.RunConfig(
            use_data_parallel=False,
            use_cuda=False,
            batch_size=batch_size,
            checkpoint_dir=self.ckpt_dir,
            strategy=hub.AdamWeightDecayStrategy())
        self.cls_task = hub.TextClassifierTask(
            data_reader=reader,
            feature=pooled_output,
            feed_list=feed_list,
            num_classes=self.num_class,
            config=config,
            metrics_choices=metrics_choices)
        
        
    @serving
    def predict(self, data, return_result=False, accelerate_mode=True):
        """
        Get prediction results
        """
        run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,
            accelerate_mode=accelerate_mode)
        results = [run_state.run_results for run_state in run_states]
        prediction = []
        for batch_result in results:
            # get predict index
            batch_result = np.argmax(batch_result, axis=2)[0]
            batch_result = batch_result.tolist()
            prediction += batch_result
        return prediction

调用代码如下
import paddlehub as hub
import numpy as np

data = [
    ['这个表情叫什么', '这个猫的表情叫什么'],
    ['什么是智能手环', '智能手环有什么用'],
    ['介绍几本好看的都市异能小说，要完结的！', '求一本好看点的都市异能小说，要完结的'],
    ['一只蜜蜂落在日历上（打一成语）', '一只蜜蜂停在日历上（猜一成语）'],
    ['一盒香烟不拆开能存放多久？', '一条没拆封的香烟能存放多久。'],
]
label_map = {1: 'similar', 0: 'dissimilar'}

module = hub.Module(
    directory="D:\\paddle_workspace\\ernie_demo\\src\\finetuned_model_to_module\\")
predictions = module.predict(data=data,max_seq_len=128, batch_size=1, use_gpu=False)
for idx, texts in enumerate(data):
    print('TextA: {}\tTextB: {}\t Label: {}'.format(texts[0], texts[1], predictions[idx]))

报错完整信息如下
runfile('D:/paddle_workspace/ernie_demo/src/test.py', wdir='D:/paddle_workspace/ernie_demo/src')
Reloaded modules: ernie.module, finetuned_model_to_module.module
[2022-05-06 11:10:58,885] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
Traceback (most recent call last):

  File "D:\paddle_workspace\ernie_demo\src\test.py", line 13, in <module>
    module = hub.Module(

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 398, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 525, in init_with_directory
    user_module._initialize(**kwargs)

  File "D:\anaconda\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)

  File "D:\paddle_workspace\ernie_demo\src\finetuned_model_to_module\module.py", line 34, in _initialize
    self.module = hub.Module(name="ernie",version="2.0")

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 388, in __new__
    module = cls.init_with_name(

  File "D:\anaconda\lib\site-packages\paddlehub\module\module.py", line 487, in init_with_name
    user_module_cls = manager.install(

  File "D:\anaconda\lib\site-packages\paddlehub\module\manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)

  File "D:\anaconda\lib\site-packages\paddlehub\module\manager.py", line 283, in _install_from_name
    raise EnvironmentMismatchError(name=name, info=valid_infos, version=version)

EnvironmentMismatchError: ernie-2.0 cannot be installed because some conditions are not met:
+---------------+----------+-----------------------------------+-----------------------------------+
|     Name          | Version   |  PaddlePaddle Version Required |    PaddleHub Version Required   |
+---------------+----------+-----------------------------------+-----------------------------------+
|     ernie           |  2.0.0       |              >=2.0.0                          |              >=2.0.0                           |
+---------------+----------+-----------------------------------+-----------------------------------+
我很确定我的paddlepaddle版本和paddlehub版本满足要求，因此不知道这个问题该如何解决

**Comment by KPatr1ck** [comment]
https://github.com/PaddlePaddle/PaddleHub/issues/1859#issuecomment-1119519406
