### ISSUE TITLE
paddlehub-系统找不到指定的文件

### ISSUE THREAD

**Issue by Arthurlyf** [PaddlePaddle/PaddleFormers#1872]
- 版本、环境信息
1）paddlehub==2.2.0,paddlepaddle==2.3.0
2）win10系统，python3.8.5

在命令窗口输入hub，hub config，hub install deeplabv3p_xception65_humanseg==1.1.2，等命令，都会提示如下。

> Traceback (most recent call last):
  File "c:\users\yi\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yi\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\YI\AppData\Local\Programs\Python\Python38\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "c:\users\yi\appdata\local\programs\python\python38\lib\site-packages\paddlehub\__init__.py", line 18, in <module>
    import paddle
  File "c:\users\yi\appdata\local\programs\python\python38\lib\site-packages\paddle\__init__.py", line 71, in <module>
    import paddle.dataset  # noqa: F401
  File "c:\users\yi\appdata\local\programs\python\python38\lib\site-packages\paddle\dataset\__init__.py", line 27, in <module>
    import paddle.dataset.flowers  # noqa: F401
  File "c:\users\yi\appdata\local\programs\python\python38\lib\site-packages\paddle\dataset\flowers.py", line 39, in <module>
    from paddle.dataset.image import load_image_bytes
  File "c:\users\yi\appdata\local\programs\python\python38\lib\site-packages\paddle\dataset\image.py", line 48, in <module>
    import_cv2_proc = subprocess.Popen(
  File "c:\users\yi\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\yi\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

是安装不成功吗？有尝试过卸载重新部署。

**Comment by Arthurlyf** [comment]
百度到了。。最后一句话。FileNotFoundError: [WinError 2] 系统找不到指定的文件。
在lib文件夹中找到subprocess.py

1、搜索class Popen(object):

2、将__init__中的shell=False修改为shell=True

不知道为什么，但是可以了。

**Comment by dingqiaolin** [comment]
我改了shell=True还是报 FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by dingqiaolin** [comment]
> 百度到了。。最后一句话。FileNotFoundError: [WinError 2] 系统找不到指定的文件。 在lib文件夹中找到subprocess.py
> 
> 1、搜索class Popen(object):
> 
> 2、将__init__中的shell=False修改为shell=True
> 
> 不知道为什么，但是可以了。


我改了shell=True还是报 FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by sshimii** [comment]
> 百度到了。。最后一句话。FileNotFoundError: [WinError 2] 系统找不到指定的文件。 在lib文件夹中找到subprocess.py
> 
> 1、搜索class Popen(object):
> 
> 2、将__init__中的shell=False修改为shell=True
> 
> 不知道为什么，但是可以了。

感谢，用了这种方法，好了。。。
