### ISSUE TITLE
photo_restoration , Out of memory error on GPU

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleFormers#1897]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
paddlehub          2.2.0
paddlenlp          2.2.6
paddlepaddle-gpu   0.0.0.post112
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
WIN11 anaconda python3.7
cuda11.6 cudnn 8.2
3080TI

- 复现信息：如为报错，请给出复现环境、复现步骤

看着 3080Ti   16G显存  一直上升 
直接爆了

导入图片尺寸
1080*1440 

```

W0620 20:40:24.009438 24484 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0620 20:40:24.027439 24484 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
load pretrained checkpoint success
load pretrained checkpoint success

 Colorization model proccess start..

 SuperResolution model proccess start..
Traceback (most recent call last):
  File "f:/lao.py", line 6, in <module>
    res = model.run_image(im,save_path="F:/2222222.jpg")
  File "C:\Users\Huang\.paddlehub\modules\photo_restoration\module.py", line 59, in run_image
    output = model.run_image(input)
  File "C:\Users\Huang\.paddlehub\modules\realsr\module.py", line 78, in run_image
    out = self.model(x)
  File "D:\anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Huang\.paddlehub\modules\realsr\rrdb.py", line 134, in forward
    self.upconv2(F.interpolate(fea, scale_factor=2, mode='nearest')))
  File "D:\anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\anaconda3\envs\paddlehub\lib\site-packages\paddle\nn\layer\conv.py", line 678, in forward
    use_cudnn=self._use_cudnn)
  File "D:\anaconda3\envs\paddlehub\lib\site-packages\paddle\nn\functional\conv.py", line 144, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 5.932617GB memory on GPU 0, 13.486816GB memory has been allocated and available memory is only 2.512695GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:87)
. (at ..\paddle\fluid\imperative\tracer.cc:311)
```

**Comment by monkeycc** [comment]
图片尺寸输入太大
改小一点 解决了
