### ISSUE TITLE
您好！我是Windows10，然后paddlepaddle版本是1.7.2，paddlehub版本是1.6.0，在使用hub命令以及用Python代码安装口罩检测模型时，会提示一个JSONDecode的错误

### ISSUE THREAD

**Issue by H-elloMyCode** [PaddlePaddle/PaddleFormers#1898]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by H-elloMyCode** [comment]
(Paddlehub) D:\DingJiaxiong\PycharmProjects\PaddleHub>hub install pyramidbox_lite_mobile_mask==1.1.0
Traceback (most recent call last):
  File "E:\anaconda\envs\Paddlehub\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\anaconda\envs\Paddlehub\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\anaconda\envs\Paddlehub\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "E:\anaconda\envs\Paddlehub\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "E:\anaconda\envs\Paddlehub\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
  File "E:\anaconda\envs\Paddlehub\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "E:\anaconda\envs\Paddlehub\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "E:\anaconda\envs\Paddlehub\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\anaconda\envs\Paddlehub\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(Paddlehub) D:\DingJiaxiong\PycharmProjects\PaddleHub>hub install deeplabv3p_xception65_humanseg
Traceback (most recent call last):
    from paddlehub.common.logger import logger
  File "E:\anaconda\envs\Paddlehub\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "E:\anaconda\envs\Paddlehub\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "E:\anaconda\envs\Paddlehub\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "E:\anaconda\envs\Paddlehub\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "E:\anaconda\envs\Paddlehub\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\anaconda\envs\Paddlehub\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by H-elloMyCode** [comment]
import paddlehub as hub
humanseg = hub.Module(name="deeplabv3p_xception_humanseg")

运行这个也会出现相同的错误
