### ISSUE TITLE
安装deeplabv3p_xception65_humanseg出现错误

### ISSUE THREAD

**Issue by boxiyang** [PaddlePaddle/PaddleFormers#1904]
PaddleHub版本号2.2.0，paddleaddle版本号2.3.0
windows server 2019，python 3.9.13 64位
安装deeplabv3p_xception65_humanseg时出现错误，如下所示

C:\Users\Administrator>hub install deeplabv3p_xception65_humanseg
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/deeplabv3p_xception65_humanseg.tar.gz
[##################################################] 100.00%
Decompress C:\Users\Administrator\.paddlehub\tmp\tmp7lvh3i9f\deeplabv3p_xception65_humanseg.tar.gz
<traceback object at 0x0000022C8026BA40>

Traceback (most recent call last):
  File "E:\dev\python\lib\site-packages\paddlehub\utils\xarfile.py", line 228, in unarchive_with_progress
    total_size += file.getxarinfo(filename).size
  File "E:\dev\python\lib\site-packages\paddlehub\utils\xarfile.py", line 153, in getxarinfo
    return XarInfo(self._archive_fp.getmember(name), self.arctype)
  File "E:\dev\python\lib\tarfile.py", line 1799, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'deeplabv3p_xception65_humanseg/deeplabv3p_xception65_humanseg_model/decoder/separable_conv2/pointwise/' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dev\python\lib\site-packages\paddlehub\utils\utils.py", line 185, in generate_tempdir
    yield _dir
  File "E:\dev\python\lib\site-packages\paddlehub\module\manager.py", line 258, in _install_from_url
    return self._install_from_archive(file)
  File "E:\dev\python\lib\site-packages\paddlehub\module\manager.py", line 374, in _install_from_archive
    for path, ds, ts in xarfile.unarchive_with_progress(archive, _tdir):
  File "E:\dev\python\lib\site-packages\paddlehub\utils\xarfile.py", line 233, in unarchive_with_progress
    yield filename, extract_size, total_size
  File "E:\dev\python\lib\site-packages\paddlehub\utils\xarfile.py", line 109, in __exit__
    raise exit_exception(exit_value)
KeyError: KeyError("filename 'deeplabv3p_xception65_humanseg/deeplabv3p_xception65_humanseg_model/decoder/separable_conv2/pointwise/' not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dev\python\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Administrator\\.paddlehub\\tmp\\tmp7lvh3i9f\\deeplabv3p_xception65_humanseg.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dev\python\lib\tempfile.py", line 805, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Administrator\\.paddlehub\\tmp\\tmp7lvh3i9f\\deeplabv3p_xception65_humanseg.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dev\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\dev\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\dev\python\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "E:\dev\python\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "E:\dev\python\lib\site-packages\paddlehub\commands\install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "E:\dev\python\lib\site-packages\paddlehub\module\manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "E:\dev\python\lib\site-packages\paddlehub\module\manager.py", line 265, in _install_from_name
    return self._install_from_url(item['url'])
  File "E:\dev\python\lib\site-packages\paddlehub\module\manager.py", line 258, in _install_from_url
    return self._install_from_archive(file)
  File "E:\dev\python\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\dev\python\lib\site-packages\paddlehub\utils\utils.py", line 185, in generate_tempdir
    yield _dir
  File "E:\dev\python\lib\tempfile.py", line 830, in __exit__
    self.cleanup()
  File "E:\dev\python\lib\tempfile.py", line 834, in cleanup
    self._rmtree(self.name)
  File "E:\dev\python\lib\tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "E:\dev\python\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\dev\python\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "E:\dev\python\lib\tempfile.py", line 808, in onerror
    cls._rmtree(path)
  File "E:\dev\python\lib\tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "E:\dev\python\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\dev\python\lib\shutil.py", line 610, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "E:\dev\python\lib\shutil.py", line 607, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\Administrator\\.paddlehub\\tmp\\tmp7lvh3i9f\\deeplabv3p_xception65_humanseg.tar.gz'

**Comment by mrvegazhou** [comment]
兄弟解决了吗？

**Comment by huanheaha** [comment]
https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/get_start/windows_quickstart.md
照着这个过程安装，得创建一个新的环境

**Comment by LeChaPatteImpitoyable** [comment]
我也遇到这个问题，重装都不行，这个模型有问题

**Comment by LeChaPatteImpitoyable** [comment]
我已经解决了！
找到你install下来得文件：C:\Users\yings\\.paddlehub\tmp\tmp1mo7m038\deeplabv3p_xception65_humanseg_1.1.2.tar.gz
tmp1mo7m038是随机生成的，yings是用户目录。
直接将deeplabv3p_xception65_humanseg_1.1.2.tar.gz解压到：C:\Users\yings\.paddlehub\modules 即可！
