### ISSUE TITLE
安装风格迁移，在最后一步运行代码的时候报错

### ISSUE THREAD

**Issue by fuyaochangge** [PaddlePaddle/PaddleFormers#1982]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
------------------------------------------------------------------------------------------------------------------------
win10，Anaconda  python版本为3.8的可执行环境，paddle使用的百度源。风格迁移模型：stylepro_artistic==1.0.1

代码内容：
import paddlehub as hub
import cv2

# 待转换图片的绝对地址
picture = 'D:\\style_transfer\\pic.jpg'  # 注意代码中此处为双反斜杠
# 风格图片的绝对地址
style_image = 'D:\\style_transfer\\fangao.jpg'

# 创建风格转移网络并加载参数
stylepro_artistic = hub.Module(name="stylepro_artistic")

# 读入图片并开始风格转换
result = stylepro_artistic.style_transfer(
                    images=[{'content': cv2.imread(picture),
                             'styles': [cv2.imread(style_image)]}],
                    visualization=True
)

报错图片
![image](https://user-images.githubusercontent.com/90813017/188051383-703733f9-c26b-4d32-a8b8-47aa9c412e48.png)

如果看不到报错截图，下面给出报错代码：
(paddle_env) D:\style_transfer>python style_transfer.py
[2022-09-02 10:45:00,343] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0902 10:45:00.345582 17180 analysis_predictor.cc:1736] Deprecated. Please use CreatePredictor instead.
[ WARN:0@2.744] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('D:\style_transfer\pic.jpg'): can't open/read file: check file path/integrity
[ WARN:0@2.748] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('D:\style_transfer\fangao.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "style_transfer.py", line 10, in <module>
    result = stylepro_artistic.style_transfer(
  File "D:\Users\fy\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "C:\Users\fy\.paddlehub\modules\stylepro_artistic\module.py", line 111, in style_transfer
    for component, w, h in reader(images, paths):
  File "C:\Users\fy\.paddlehub\modules\stylepro_artistic\data_feed.py", line 36, in reader
    each_res['content_arr'], w, h = _handle_single(
  File "C:\Users\fy\.paddlehub\modules\stylepro_artistic\data_feed.py", line 80, in _handle_single
    w, h = im.shape[1], im.shape[0]
UnboundLocalError: local variable 'im' referenced before assignment

**Comment by jm12138** [comment]
> 欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
>   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> * 复现信息：如为报错，请给出复现环境、复现步骤
> 
> win10，Anaconda python版本为3.8的可执行环境，paddle使用的百度源。风格迁移模型：stylepro_artistic==1.0.1
> 
> 代码内容： import paddlehub as hub import cv2
> 
> # 待转换图片的绝对地址
> picture = 'D:\style_transfer\pic.jpg' # 注意代码中此处为双反斜杠
> 
> # 风格图片的绝对地址
> style_image = 'D:\style_transfer\fangao.jpg'
> 
> # 创建风格转移网络并加载参数
> stylepro_artistic = hub.Module(name="stylepro_artistic")
> 
> # 读入图片并开始风格转换
> result = stylepro_artistic.style_transfer( images=[{'content': cv2.imread(picture), 'styles': [cv2.imread(style_image)]}], visualization=True )
> 
> 报错图片 ![image](https://user-images.githubusercontent.com/90813017/188051383-703733f9-c26b-4d32-a8b8-47aa9c412e48.png)
> 
> 如果看不到报错截图，下面给出报错代码： (paddle_env) D:\style_transfer>python style_transfer.py [2022-09-02 10:45:00,343] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the **init**() to handle the initialization of the object W0902 10:45:00.345582 17180 analysis_predictor.cc:1736] Deprecated. Please use CreatePredictor instead. [ WARN:0@2.744] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('D:\style_transfer\pic.jpg'): can't open/read file: check file path/integrity [ WARN:0@2.748] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('D:\style_transfer\fangao.jpg'): can't open/read file: check file path/integrity Traceback (most recent call last): File "style_transfer.py", line 10, in result = stylepro_artistic.style_transfer( File "D:\Users\fy\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner return func(*args, **kwargs) File "C:\Users\fy.paddlehub\modules\stylepro_artistic\module.py", line 111, in style_transfer for component, w, h in reader(images, paths): File "C:\Users\fy.paddlehub\modules\stylepro_artistic\data_feed.py", line 36, in reader each_res['content_arr'], w, h = _handle_single( File "C:\Users\fy.paddlehub\modules\stylepro_artistic\data_feed.py", line 80, in _handle_single w, h = im.shape[1], im.shape[0] UnboundLocalError: local variable 'im' referenced before assignment

请尝试更新一下 stylepro_artistic 模块的版本至 1.0.3
