### ISSUE TITLE
Meet an error when installing paddlehub

### ISSUE THREAD

**Issue by Kunlun-Zhu** [PaddlePaddle/PaddleFormers#2026]
Hi developer,

When I use the latest pip to install paddlehub as follow
`!pip install --upgrade paddlehub`

I meet the following problem,

```
Installing collected packages: visualdl, rarfile, easydict, paddlehub
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 413, in run
    pycompile=options.compile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 81, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 810, in install
    requested=self.user_supplied,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/wheel.py", line 737, in install_wheel
    requested=requested,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
    file.save()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/wheel.py", line 383, in save
    if os.path.exists(self.dest_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u53f3' in position 81: ordinal not in range(128)
```
the system is Ubuntu 18.04.5 LTS

**Comment by rainyfly** [comment]
Hi，I think maybe some files in wheel have chinese characters in their filenames. What if you execute 'pip install visualdl' ? If you can install this package successfully, try 'pip install --upgrade paddlehub' again.

**Comment by Kunlun-Zhu** [comment]
> Hi，I think maybe some files in wheel have chinese characters in their filenames. What if you execute 'pip install visualdl' ? If you can install this package successfully, try 'pip install --upgrade paddlehub' again.

Thanks for the response, I meet the similar error installing that package.
I tried the following method searched from internet, but still not working, the same error occur.
```
!export PYTHONIOENCODING=utf8
!export LC_ALL=C
!pip install --upgrade setuptools
```

**Comment by rainyfly** [comment]
Is there any chinese character in your path ? If you can not install any package, maybe some problems happen in your environment. Check something like your username, etc.
