### ISSUE TITLE
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv)

### ISSUE THREAD

**Issue by imohuan** [PaddlePaddle/PaddleFormers#2047]
# Qustion
links: https://www.paddlepaddle.org.cn/hubdetail?name=animegan_v2_hayao_99&en_category=GANs
I imitated the link to re engage, but there was an error, and the online query was unsuccessful
I don’t know where there is a problem

# animegan_v3 already updated, How do I import a local model? (onnx model)

# Program
* `win11`
* `Python 3.9.6`
* `paddlepaddle==2.3.2`
* `paddlehub==2.3.0`

# Code
``` python
import cv2
import paddlehub as hub

model = hub.Module(name='animegan_v2_hayao_99')

result = model.style_transfer(
    images=[cv2.imread('./data/2.jpg')],
    output_dir='output',
    visualization=True
)
```

# Error
``` log
E:\PythonEnv\paddle\lib\site-packages\paddlenlp\transformers\image_utils.py:213: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  resample=Image.BILINEAR,
E:\PythonEnv\paddle\lib\site-packages\paddlenlp\transformers\image_utils.py:379: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  resample=Image.NEAREST,
E:\PythonEnv\paddle\lib\site-packages\paddlenlp\transformers\ernie_vil\feature_extraction.py:65: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  resample=Image.BICUBIC,
E:\PythonEnv\paddle\lib\site-packages\paddlenlp\transformers\clip\feature_extraction.py:64: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  resample=Image.BICUBIC,
Traceback (most recent call last):
  File "G:\level-2\Python\PaddleHub\demo.py", line 6, in <module>
    result = model.style_transfer(
  File "E:\PythonEnv\paddle\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "C:\Users\26522\.paddlehub\modules\animegan_v2_hayao_99\module.py", line 40, in style_transfer
    outputs = self.model.predict(processor.input_datas)
  File "C:\Users\26522\.paddlehub\modules\animegan_v2_hayao_99\model.py", line 68, in predict
    self.predictor.run()
ValueError: In user code:

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\site-packages\paddle\fluid\layers\nn.py", line 2938, in conv2d
    "data_format": data_format,

    File "Hayao-99\model_with_code\x2paddle_model.py", line 86, in x2paddle_net
    generator_G_MODEL_A_Conv_Conv2D = fluid.layers.conv2d(input=conv2d_transpose_0, bias_attr=False, param_attr='generator_G_MODEL_A_Conv_weights', num_filters=32, filter_size=[7, 7], stride=[1, 1], dilation=[1, 1], padding='VALID')

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\site-packages\x2paddle\core\program.py", line 290, in gen_model
    inputs, outputs = x2paddle_model.x2paddle_net()

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\site-packages\x2paddle\convert.py", line 137, in tf2paddle
    program.gen_model(save_dir)

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\site-packages\x2paddle\convert.py", line 291, in main
    define_input_shape, params_merge)

    File "C:\Users\Xpk22\AppData\Local\Programs\Python\Python37\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
    sys.exit(main())

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)

    File "c:\users\xpk22\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)


    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 1030, the input's shape is [1, 1030, 582, 3]; the filter's channels is 3, the filter's shape is [32, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1030 != filter_dims[1] * groups:3.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/conv_op.cc:116)
      [operator < conv2d > error]
```

**Comment by imohuan** [comment]
Anything about the image style conversion model library, I will have the current error

**Comment by jm12138** [comment]
> # animegan_v3 already updated, How do I import a local model? (onnx model)
AnimeGAN v3  has not been officially released yet. We will consider updating and accessing the new model after waiting for its official open source code and model.

**Comment by jm12138** [comment]
> Anything about the image style conversion model library, I will have the current error

I can't reproduce this problem on my environment. You can try to uninstall and reinstall PaddlePaddle and PaddleHub packages.

**Comment by imohuan** [comment]
# Test
I have tried to create a new virtual environment for testing, and my steps are
1. `mkvirtualenv test`
2. `pip install paddlepaddle paddlehub`
3. Execute the code
``` python
import cv2
import paddlehub as hub

model = hub.Module(name='animegan_v2_hayao_99')

result = model.style_transfer(
    images=[cv2.imread('./data/2.jpg')],
    output_dir='output',
    visualization=True
)
```

# Error 
Failed unexpectedly, and the error prompt is the same.

**Comment by imohuan** [comment]
Execute the code when you reinstall the virtual environment, and he doesn't download the model again.

**Comment by rainyfly** [comment]
PaddleHub modules are stored in path ~/.paddlehub/modules .  If module has exists, it will not be downloaded again. And the error message shows that input format is wrong, format NCHW expected but actually got NHWC. We will find out why this happens.
