### ISSUE TITLE
是文档没更新吗？

### ISSUE THREAD

**Issue by wuxiang666** [PaddlePaddle/PaddleFormers#2119]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

系统是macos最新版本
paddlepaddle的版本信息：
paddle-bfloat         0.1.7
paddle-serving-app    0.9.0
paddle-serving-client 0.9.0
paddle-serving-server 0.9.0
paddle2onnx           1.0.1
paddlefsl             1.1.0
paddlehub             2.3.0
paddlenlp             2.4.2
paddlepaddle          2.3.2

执行官方文档命令：hub serving start -m lac        

报错信息：
  Traceback (most recent call last):
  File "/Users/arno/anaconda3/envs/videoEnh/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 352, in execute
    self.start_serving()
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 221, in start_single_app_with_args
    self.preinstall_modules()
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 152, in preinstall_modules
    m = hub.Module(**init_args)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/module/module.py", line 396, in __new__
    **kwargs)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/module/module.py", line 508, in init_with_name
    return user_module_cls(directory=directory, **kwargs)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/compat/module/module_v1.py", line 50, in __init__
    self._load_model()
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddlehub/compat/module/module_v1.py", line 115, in _load_model
    self.program, _, _ = paddle.static.load_inference_model(model_path, executor=exe)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddle/fluid/framework.py", line 443, in __impl__
    return func(*args, **kwargs)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddle/static/io.py", line 799, in load_inference_model
    program_bytes = load_from_file(model_path)
  File "/Users/arno/anaconda3/envs/videoEnh/lib/python3.7/site-packages/paddle/static/io.py", line 675, in load_from_file
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/arno/.paddlehub/modules/lac/model.pdmodel'

**Comment by wuxiang666** [comment]
之前paddlehub2.3.0报错，降低版本至：

paddlehub             2.2.0
paddlenlp             2.4.2
paddlepaddle          2.3.2

后执行命令：
hub serving start -m lac  
显示这个错误：
AttributeError: 'ModuleV1_c85d69d8336c934efb938740c46c899c' object has no attribute 'serving_func_name'

**Comment by jm12138** [comment]
* 可能是 lac 的版本问题
* 建议升级至最新版本
```shell
$ hub install lac==2.2.0
```

**Comment by wuxiang666** [comment]
@jm12138 
感谢 模型使用2.2.0后正常

**Comment by wuxiang666** [comment]
> * 可能是 lac 的版本问题
> * 建议升级至最新版本
> 
> ```shell
> $ hub install lac==2.2.0
> ```

感谢  lac模型使用2.2.0后正常
