### ISSUE TITLE
安装resnet_v2_50_imagenet模型报错

### ISSUE THREAD

**Issue by AdTomato** [PaddlePaddle/PaddleFormers#2124]
python版本：3.7.4
paddlepaddle版本：1.7.2（安装命令：pip install paddlepaddle==1.7.2 -i https://mirror.baidu.com/pypi/simple）
paddlehub版本：1.6.0（安装命令：pip install paddlehub==1.6.0 -i https://mirror.baidu.com/pypi/simple）
resent_v2_50_imagenet版本：1.0.1（安装命令：hub install resnet_v2_50_imagenet==1.0.1）
安装报错信息
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddle_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\paddle_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\paddle_env\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\module\module.py", line 31, in <module>
    from paddlehub.common import utils
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\common\__init__.py", line 16, in <module>
    from . import utils
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\common\utils.py", line 33, in <module>
    from paddlehub.common.logger import logger
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "D:\anaconda3\envs\paddle_env\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\anaconda3\envs\paddle_env\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda3\envs\paddle_env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda3\envs\paddle_env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jm12138** [comment]
建议更新 paddlepaddle 和 paddlehub 的版本后使用
