### ISSUE TITLE
PaddleHub一键OCR中文识别-五、部署服务器

### ISSUE THREAD

**Issue by MaxokDavid** [PaddlePaddle/PaddleFormers#2144]
Sir, thanks for your guidance. I have completed online image recognition according the article
https://aistudio.baidu.com/aistudio/projectdetail/5121515
While, I am unable to know how to deploy the server through the notebook.I will appreciate it ,if you give me detail steps about deploying the server -"五、部署服务器" by this notebook.
Thanks for your reading.

**Comment by jm12138** [comment]
> Sir, thanks for your guidance. I have completed online image recognition according the article
> https://aistudio.baidu.com/aistudio/projectdetail/5121515
> While, I am unable to know how to deploy the server through the notebook.I will appreciate it ,if you give me detail steps about deploying the server -"五、部署服务器" by this notebook.
> Thanks for your reading.

Execute the command `hub serving start -m chinese_ocr_db_crnn_mobile -p 8866` in the terminal or execute the command `!hub serving start -m chinese_ocr_db_crnn_mobile -p 8866` in the notebook code that you can then start a server .

**Comment by MaxokDavid** [comment]
follow your advice, this bug turn up. but my PaddleHub and PaddlePaddle both 2.1.1


***@***.***:~$ hub serving start -m chinese_ocr_db_crnn_mobile -p 8866

Traceback (most recent call last):

  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 6, in <module>

    from paddlehub.commands.utils import execute

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/__init__.py", line 23, in <module>

    'Version mismatch in PaddleHub and PaddlePaddle, you need to upgrade PaddlePaddle to version 2.0.0 or above.')

RuntimeError: Version mismatch in PaddleHub and PaddlePaddle, you need to upgrade PaddlePaddle to version 2.0.0 or above.













At 2022-11-29 14:39:30, "jm12138" ***@***.***> wrote:

Sir, thanks for your guidance. I have completed online image recognition according the article
https://aistudio.baidu.com/aistudio/projectdetail/5121515
While, I am unable to know how to deploy the server through the notebook.I will appreciate it ,if you give me detail steps about deploying the server -"五、部署服务器" by this notebook.
Thanks for your reading.

Execute the command hub serving start -m chinese_ocr_db_crnn_mobile -p 8866 in the terminal or execute the command !hub serving start -m chinese_ocr_db_crnn_mobile -p 8866 in the notebook code that you can then start a server .

**Comment by MaxokDavid** [comment]
hello sir ,finally I get this
WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)


what  these code meaning and what should I do next?













At 2022-11-29 14:39:30, "jm12138" ***@***.***> wrote:

Sir, thanks for your guidance. I have completed online image recognition according the article
https://aistudio.baidu.com/aistudio/projectdetail/5121515
While, I am unable to know how to deploy the server through the notebook.I will appreciate it ,if you give me detail steps about deploying the server -"五、部署服务器" by this notebook.
Thanks for your reading.

Execute the command hub serving start -m chinese_ocr_db_crnn_mobile -p 8866 in the terminal or execute the command !hub serving start -m chinese_ocr_db_crnn_mobile -p 8866 in the notebook code that you can then start a server .

**Comment by jm12138** [comment]
> hello sir ,finally I get this WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead. * Debug mode: off * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit) what these code meaning and what should I do next? 

* Next, you can write web request code to send images and get text recognition results in python or JS/TS etc. 
* Here is a python code example.

  ```python
  import requests
  import json
  import cv2
  import base64
  
  def cv2_to_base64(image):
      data = cv2.imencode('.jpg', image)[1]
      return base64.b64encode(data.tostring()).decode('utf8')
  
  # 发送HTTP请求
  data = {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}
  headers = {"Content-type": "application/json"}
  url = "http://127.0.0.1:8866/predict/chinese_ocr_db_crnn_mobile"
  r = requests.post(url=url, headers=headers, data=json.dumps(data))
  
  # 打印预测结果
  print(r.json()["results"])
  ```

**Comment by MaxokDavid** [comment]
sir, I add these code given ,while some error turn up. what should I do next?
[ ***@***.*** global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/PATH/TO/IMAGE'): can't open/read file: check file path/integrity

---------------------------------------------------------------------------error                                     Traceback (most recent call last)/tmp/ipykernel_93/1545546450.py in <module>     10     11# 发送HTTP请求---> 12data ={'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}     13 headers ={"Content-type":"application/json"}     14 url ="http://127.0.0.1:8866/predict/chinese_ocr_db_crnn_mobile"/tmp/ipykernel_93/1545546450.py in cv2_to_base64(image)      6      7def cv2_to_base64(image):----> 8data = cv2.imencode('.jpg', image)[1]      9return base64.b64encode(data.tostring()).decode('utf8')     10error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:976: error: (-215:Assertion failed) !image.empty() in function 'imencode'













At 2022-11-30 10:33:56, "jm12138" ***@***.***> wrote:

hello sir ,finally I get this WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead. * Debug mode: off * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit) what these code meaning and what should I do next?

Next, you can write web request code to send images and get text recognition results in python or JS/TS etc.

Here is a python code example.

importrequestsimportjsonimportcv2importbase64defcv2_to_base64(image):

    data=cv2.imencode('.jpg', image)[1]

    returnbase64.b64encode(data.tostring()).decode('utf8')



# 发送HTTP请求data= {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}

headers= {"Content-type": "application/json"}

url="http://127.0.0.1:8866/predict/chinese_ocr_db_crnn_mobile"r=requests.post(url=url, headers=headers, data=json.dumps(data))



# 打印预测结果print(r.json()["results"])

**Comment by jm12138** [comment]
> sir, I add these code given ,while some error turn up. what should I do next? [ ***@***.*** global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/PATH/TO/IMAGE'): can't open/read file: check file path/integrity
> […](#)

You need to send an image to the server, /PATH/TO/IMAGE means the path to the image on your local computer, you need to replace /PATH/TO/IMAGE in the code with the path to the image on your local computer

**Comment by MaxokDavid** [comment]
I modify the path  ,but I  don't know whether it is right.
<>:12: DeprecationWarning: invalid escape sequence \s
<>:12: DeprecationWarning: invalid escape sequence \s
<>:12: DeprecationWarning: invalid escape sequence \s
/tmp/ipykernel_93/618996580.py:12: DeprecationWarning: invalid escape sequence \s
  data = {'images':[cv2_to_base64(cv2.imread("D:\storage\png\1.jpg"))]}
[ ***@***.*** global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('D:\storage\png.jpg'): can't open/read file: check file path/integrity

---------------------------------------------------------------------------error                                     Traceback (most recent call last)/tmp/ipykernel_93/618996580.py in <module>     10     11# 发送HTTP请求---> 12data ={'images':[cv2_to_base64(cv2.imread("D:\storage\png\1.jpg"))]}     13 headers ={"Content-type":"application/json"}     14 url ="http://127.0.0.1:8866/predict/chinese_ocr_db_crnn_mobile"/tmp/ipykernel_93/618996580.py in cv2_to_base64(image)      6      7def cv2_to_base64(image):----> 8data = cv2.imencode('.jpg', image)[1]      9return base64.b64encode(data.tostring()).decode('utf8')     10error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:976: error: (-215:Assertion failed) !image.empty() in function 'imencode'
















At 2022-11-30 10:54:43, "jm12138" ***@***.***> wrote:

sir, I add these code given ,while some error turn up. what should I do next? [ @.*** global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/PATH/TO/IMAGE'): can't open/read file: check file path/integrity
…

You need to send an image to the server, /PATH/TO/IMAGE means the path to the image on your local computer, you need to replace /PATH/TO/IMAGE in the code with the path to the image on your local computer

**Comment by jm12138** [comment]
> I modify the path ,but I don't know whether it is right. <>:12: DeprecationWarning: invalid escape sequence \s <>:12: DeprecationWarning: invalid escape sequence \s <>:12: DeprecationWarning: invalid escape sequence \s /tmp/ipykernel_93/618996580.py:12: DeprecationWarning: invalid escape sequence \s data = {'images':[cv2_to_base64(cv2.imread("D:\storage\png\1.jpg"))]} [ ***@***.*** global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('D:\storage\png.jpg'): can't open/read file: check file path/integrity
> […](#)

* This is not a PaddleHub problem, in Python code, if the path contains "\\", you need to process it, change it to "\\\\" or use the format r"xxx\xxx\xxx" or "xxx/xxx/xxx"
* Please search through the search engine first and try to solve the problem if you encounter a problem not related to Paddle or PaddleHub, rather than asking here.

**Comment by MaxokDavid** [comment]
Thanks for your professional guidance, I  have completed this project. Best wishes for you.
















At 2022-11-30 16:37:33, "jm12138" ***@***.***> wrote:

I modify the path ,but I don't know whether it is right. <>:12: DeprecationWarning: invalid escape sequence \s <>:12: DeprecationWarning: invalid escape sequence \s <>:12: DeprecationWarning: invalid escape sequence \s /tmp/ipykernel_93/618996580.py:12: DeprecationWarning: invalid escape sequence \s data = {'images':[cv2_to_base64(cv2.imread("D:\storage\png\1.jpg"))]} [ @.*** global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('D:\storage\png.jpg'): can't open/read file: check file path/integrity
…

This is not a PaddleHub problem, in Python code, if the path contains "", you need to process it, change it to "\" or use the format r "xxx\xxx\xxx" or "xxx/xxx/xxx"
Please search through the search engine first and try to solve the problem if you encounter a problem not related to Paddle or PaddleHub, rather than asking here.
