### ISSUE TITLE
ImportError: cannot import name 'save_wav' from 'paddleaudio'

### ISSUE THREAD

**Issue by panusocom** [PaddlePaddle/PaddleFormers#2153]
hub serving start -m u2_conformer_wenetspeech

[2022-12-02 11:01:50,688] [    INFO] - Successfully uninstalled u2_conformer_wenetspeech
[2022-12-02 11:02:06,662] [ WARNING] - Some errors occurred while installing dependent packages. Detailed error information can be found in the /root/.paddlehub/log/20221202.log.
Traceback (most recent call last):
  File "/root/anaconda3/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 352, in execute
    self.start_serving()
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 245, in start_serving
    self.start_single_app_with_args()
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 221, in start_single_app_with_args
    self.preinstall_modules()
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 152, in preinstall_modules
    m = hub.Module(**init_args)
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/module.py", line 393, in __new__
    module = cls.init_with_name(
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/module.py", line 492, in init_with_name
    user_module_cls = manager.install(
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/manager.py", line 265, in _install_from_name
    return self._install_from_url(item['url'])
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/manager.py", line 258, in _install_from_url
    return self._install_from_archive(file)
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/manager.py", line 380, in _install_from_archive
    return self._install_from_directory(directory)
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/manager.py", line 364, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/module/module.py", line 423, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/root/anaconda3/lib/python3.9/site-packages/paddlehub/utils/utils.py", line 250, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/root/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.paddlehub/modules/u2_conformer_wenetspeech/module.py", line 18, in <module>
    from paddleaudio import load, save_wav
ImportError: cannot import name 'save_wav' from 'paddleaudio' (/root/anaconda3/lib/python3.9/site-packages/paddleaudio/__init__.py)

**Comment by jm12138** [comment]
* The module currently requires a specified version of PaddleSpeech to be available, and is installed using the following command.

  ```shell
  $ pip install paddlespeech==0.1.0a9
  ```
