### ISSUE TITLE
paddlehub.module.manager.HubModuleNotFoundError

### ISSUE THREAD

**Issue by yier2333** [PaddlePaddle/PaddleFormers#2163]
1）
PaddleHub是这样安装的：pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple
paddle是这样安装的：python38 -m pip install paddlepaddle-gpu==2.4.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

2）系统环境：Linux，python3.8

执行：hub serving start -m ace2p use_gpu

报错信息：
Decompress /home/jovyan/.paddlehub/tmp/tmpk7p3h30i/ace2p_1_2_0.zip

[##################################################] 100.00%
[##################################################] 100.00%
[32m[2022-12-05 15:25:31,401] [ INFO][0m - Successfully installed ace2p-1.2.0[0m
Traceback (most recent call last):
File "/data/conda/envs/python38/bin/hub", line 8, in
sys.exit(execute())
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/commands/utils.py", line 78, in execute
status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/commands/serving.py", line 352, in execute
self.start_serving()
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/commands/serving.py", line 245, in start_serving
self.start_single_app_with_args()
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/commands/serving.py", line 221, in start_single_app_with_args
self.preinstall_modules()
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/commands/serving.py", line 152, in preinstall_modules
m = hub.Module(**init_args)
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/module/module.py", line 393, in __new__
module = cls.init_with_name(
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/module/module.py", line 492, in init_with_name
user_module_cls = manager.install(
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/module/manager.py", line 190, in install
return self._install_from_name(name, version, ignore_env_mismatch)
File "/data/conda/envs/python38/lib/python3.8/site-packages/paddlehub/module/manager.py", line 270, in _install_from_name
raise HubModuleNotFoundError(name=name, version=version)
paddlehub.module.manager.HubModuleNotFoundError: No HubModule named [31muse[39m was found

**Comment by jm12138** [comment]
看这个log，`Successfully installed ace2p-1.2.0` 应该是已经成功安装了
