### ISSUE TITLE
执行模型是报错“Out of memory error on GPU”但系统可用显存还有还多

### ISSUE THREAD

**Issue by ZanePoe** [PaddlePaddle/PaddleFormers#2175]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddlehub2.3.1，paddlepaddle-gpu2.4.0.post117
2）系统环境：Windows 10，python3.9.15
- 报错：
```File "C:\Users\Administrator\.paddlehub\modules\animegan_v2_shinkai_53\model.py", line 35, in __call__
    return self.forward(*input_datas, batch_size=batch_size)
  File "C:\Users\Administrator\.paddlehub\modules\animegan_v2_shinkai_53\model.py", line 143, in forward
    self.predictor.run()
RuntimeError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
resourceexhaustederror:

Out of memory error on GPU 0. Cannot allocate 72.000000MB memory on GPU 0, 7.999390GB memory has been allocated and available memory is only 0.000000B.`
```
- 报错时系统状态：
1)GPU状态：
```
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:81:00.0  On |                  N/A |
|  0%   33C    P8    11W / 200W |   1102MiB /  8192MiB |     23%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4844    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      5332    C+G   ...e6\promecefpluginhost.exe    N/A      |
|    0   N/A  N/A      6016    C+G   ...wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A      6420    C+G   ...418.62\msedgewebview2.exe    N/A      |
|    0   N/A  N/A      7660    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     13136    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     16244    C+G   ...nputApp\TextInputHost.exe    N/A      |
|    0   N/A  N/A     16568    C+G   ...C Manager\MSPCManager.exe    N/A      |
|    0   N/A  N/A     16832    C+G   ...ge\Application\msedge.exe    N/A      |
|    0   N/A  N/A     18204    C+G   ...les\Feishu\app\Feishu.exe    N/A      |
|    0   N/A  N/A     23240    C+G   ...bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A     26984    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     27972    C+G   ...e6\promecefpluginhost.exe    N/A      |
|    0   N/A  N/A     28416    C+G   ...icrosoft VS Code\Code.exe    N/A      |
|    0   N/A  N/A     37084    C+G   ...m-windows-x64\trilium.exe    N/A      |
+-----------------------------------------------------------------------------+
```
2)windows 任务管理 性能监视器中没有看到模型运行过程中GPU有太大的显存占用的波动，占用率在1-6%徘徊。
- 尝试过的解决的方式
1)尝试更换模型，由animegan_v2_hayao_99更换为animegan_v2_shinkai_53同样失败；
2)尝试修改batch_size,未找到具体修改位置，查看模型源码“C:\Users\Administrator\.paddlehub\modules\animegan_v2_shinkai_53\model.py”处，发现默认batch_size为1，未发现有其它地方修改batch size,如果有其它地方修改batch_size，请不吝赐教;
`    # 类调用函数
    def __call__(self, *input_datas, batch_size=1):
        '''
        call function
        '''
        return self.forward(*input_datas, batch_size=batch_size)`
- 未尝试的解决方案
1) 减小图像分辨率。
经过资料查询，图片过大也可能造成Out of memory error。但是我发现我的报错一次申请显存为72.000000MB，并不大，而且系统报错“7.999390GB memory has been allocated and available memory is only 0.000000B”的时候，我的windows 性能监视器中并无任何内存波动。
2)排查GPU被其它进程占用
我的电脑只有一块显卡，windows有其它进程使用GPU非常正常，而且空闲显存接近8GB，模型不应该没有空闲内存可分配。根据报错提示：“Please check whether there is any other process using GPU 0”，如果paddlehub要求独占GPU，请请教独占方式。

**Comment by jm12138** [comment]
应该就是显存不足，随着图片的分辨率放大，需要的显存需要成倍提高，我记得1280x720 就需要占用差不多15g+，报错显示的需要多少显存并不是实际只需要的。

**Comment by ZanePoe** [comment]
确实是显存不足，将图片分辨率降低之后就可以了。

**Comment by Sunshine-hero** [comment]
不是显存的问题，是因为docker
