### ISSUE TITLE
stable_diffusion模型报错

### ISSUE THREAD

**Issue by metaire** [PaddlePaddle/PaddleFormers#2176]
1）PaddleHub2.1.0，PaddlePaddle2.1.2.post112
2）系统环境：Windows。python版本：3.7
- 复现信息：如为报错，请给出复现环境、复现步骤
- 运行出错，运行方式：
- module = hub.Module(name="stable_diffusion_img2img")
    text_prompts = ["A fantasy landscape, trending on artstation"]
    da = module.generate_image(text_prompts=text_prompts, init_image='./image/img.png', batch_size=2,
                               output_dir='./stable_diffusion_img2img_out/')
    da[0].chunks[-1].chunks.plot_image_sprites(skip_empty=True, show_index=True, keep_aspect_ratio=True)
    da[0].chunks[-1].chunks.save_gif('stable_diffusion_img2img_out-merged-result.gif')
    da[0].chunks[0].chunks.plot_image_sprites(skip_empty=True, show_index=True, keep_aspect_ratio=True)
    da[0].chunks[0].chunks.save_gif('stable_diffusion_img2img-image-0-result.gif')
错误：
Traceback (most recent call last):
  File "D:/metaire/stable_diffusion/imgtoimg.py", line 12, in <module>
    output_dir='./stable_diffusion_img2img_out/')
  File "D:\Anaconda3\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\.paddlehub\modules\stable_diffusion_img2img\module.py", line 205, in generate_image
    init_latents = self.scheduler.add_noise(init_latents, noise, timesteps)
  File "C:\Users\Administrator\.paddlehub\modules\stable_diffusion_img2img\diffusers\schedulers\scheduling_pndm.py", line 255, in add_noise
    sqrt_alpha_prod = self.match_shape(sqrt_alpha_prod, original_samples)
  File "C:\Users\Administrator\.paddlehub\modules\stable_diffusion_img2img\diffusers\schedulers\scheduling_utils.py", line 73, in match_shape
    values = values[..., None]
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 569, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) too many indices (2) for tensor of dimension 1
  [Hint: Expected size <= rank == true, but received size <= rank:0 != true:1.] (at C:\home\workspace\Paddle_release2\paddle\fluid\pybind\imperative.cc:421)

**Comment by jm12138** [comment]
可以尝试升级至最新版本的 PaddlePaddle 和 PaddleHub，还有检查一下图片文件，我这边测试是能够正常运行的

**Comment by VVsxmja** [comment]
可以把 [`modules/image/text_to_image/stable_diffusion/README.md`](https://github.com/PaddlePaddle/PaddleHub/blob/b402610a6f0b382a978e82473b541ea1fc6cf09a/modules/image/text_to_image/stable_diffusion/README.md) 中的环境依赖改为 `paddlepaddle>=2.2` 吗？

我用 2.1 版本会报一样的错，升级到 2.2 及以上就可以用了。

问题应该出在 [`modules/image/text_to_image/stable_diffusion/module.py` 第179行](https://github.com/PaddlePaddle/PaddleHub/blob/b402610a6f0b382a978e82473b541ea1fc6cf09a/modules/image/text_to_image/stable_diffusion/module.py#L179)

```py3
paddle.amp.auto_cast(enable=enable_fp16, level='O2')
```

这里 `level` 这个参数是 `paddlepaddle 2.2` 之后才有的

**Comment by hjj-lmx** [comment]
stable_diffusion_img2img需要多大的显存，我现在24g的都会报显存不足
