### ISSUE TITLE
PaddleHub引入报错

### ISSUE THREAD

**Issue by Gray-web** [PaddlePaddle/PaddleFormers#2194]
硬件：Jetson Nano 2G
cuda：10.2
cudnn：8.0.0
paddlepaddle-gpu：2.0.2
paddlehub：2.0.0
paddlenlp：2.3.3

在Python终端中输入import paddlehub后输出以下报错

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlehub/__init__.py", line 24, in <module>
    from paddlehub import datasets
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlehub/datasets/__init__.py", line 18, in <module>
    from paddlehub.datasets.chnsenticorp import ChnSentiCorp
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlehub/datasets/chnsenticorp.py", line 19, in <module>
    from paddlehub.datasets.base_nlp_dataset import TextClassificationDataset
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlehub/datasets/base_nlp_dataset.py", line 23, in <module>
    from paddlenlp.transformers import PretrainedTokenizer
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlenlp/__init__.py", line 24, in <module>
    from . import data
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlenlp/data/data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlenlp/transformers/__init__.py", line 26, in <module>
    from .electra.modeling import *
  File "/home/tringai/.local/lib/python3.6/site-packages/paddlenlp/transformers/electra/modeling.py", line 20, in <module>
    from paddle.nn.layer.transformer import _convert_attention_mask
ImportError: cannot import name '_convert_attention_mask'

求解答

**Comment by rainyfly** [comment]
看报错应该是版本的问题，试试升级一下paddle的版本看看

**Comment by Gray-web** [comment]
> 看报错应该是版本的问题，试试升级一下paddle的版本看看

nano的paddle版本最高就是2.0.2
