### ISSUE TITLE
paddlehub 引用sklearn 报 cannot load any more object with static TLS 错误

### ISSUE THREAD

**Issue by hnlslyp** [PaddlePaddle/PaddleFormers#2195]
系统环境
paddle.__version__  2.4.0-rc0

####    具体代码
!/usr/bin/env python
#-*- coding=utf8 -*-
import os
import sys
import paddlehub as hub

module = hub.Module(name="lac")
test_text = '小明硕士毕业于中国科学院计算所，后在日本京都大学深造'
results = module.lexical_analysis(texts=test_text)
###############

Traceback (most recent call last):
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_lac.py", line 5, in <module>
    import paddlehub as hub
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlehub/__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlehub/datasets/__init__.py", line 16, in <module>
    from paddlehub.datasets.chnsenticorp import ChnSentiCorp
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlehub/datasets/chnsenticorp.py", line 19, in <module>
    from paddlehub.datasets.base_nlp_dataset import TextClassificationDataset
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlehub/datasets/base_nlp_dataset.py", line 21, in <module>
    import paddlenlp
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlenlp/__init__.py", line 29, in <module>
    from . import metrics
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlenlp/metrics/__init__.py", line 16, in <module>
    from .chunk import ChunkEvaluator
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/paddlenlp/metrics/chunk.py", line 6, in <module>
    from seqeval.metrics.sequence_labeling import get_entities
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/seqeval/metrics/__init__.py", line 1, in <module>
    from seqeval.metrics.sequence_labeling import (accuracy_score,
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py", line 14, in <module>
    from seqeval.metrics.v1 import SCORES, _precision_recall_fscore_support
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/seqeval/metrics/v1.py", line 5, in <module>
    from sklearn.exceptions import UndefinedMetricWarning
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/sklearn/__init__.py", line 79, in <module>
    from . import __check_build  # noqa: F401
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/ssd4/liuyaping/python38/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /ssd4/liuyaping/python38/lib/python3.8/site-packages/sklearn/__check_build:
_check_build.cpython-38-x86_64-linux-gnu.sosetup.py                  __pycache__
__init__.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

**Comment by rainyfly** [comment]
可能是你环境的问题，要不你用anaconda创建一个python3.7的环境安装paddlehub重新试试。另外
results = module.lexical_analysis(texts=[test_text])
