### ISSUE TITLE
Error: Can not import paddle core while this file exists: D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\libpaddle.pyd

### ISSUE THREAD

**Issue by water-2022** [PaddlePaddle/PaddleFormers#2208]
1.平台环境：
Win10
conda 4.11.0
Python 3.7.12
paddlehub            2.3.1
paddlenlp            2.5.1
paddlepaddle         2.4.2

2.官网参考文档：
[①](https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis)
[②](https://www.paddlepaddle.org.cn/hub)

3.实际操作：
```
(lac) D:\PycharmProjects\lac>python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub as hub
Error: Can not import paddle core while this file exists: D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddlehub\__init__.py", line 18, in <module>
    import paddle
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\core.py", line 338, in <module>
    raise e
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\core.py", line 274, in <module>
    from . import libpaddle
ImportError: DLL load failed: The specified module could not be found.
```

当我移动libpaddle.pyd文件后：
```
(lac) D:\PycharmProjects\lac>python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub as hub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddlehub\__init__.py", line 18, in <module>
    import paddle
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\core.py", line 338, in <module>
    raise e
  File "D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\core.py", line 274, in <module>
    from . import libpaddle
ImportError: cannot import name 'libpaddle' from 'paddle.fluid' (D:\Program Files\miniconda3\envs\lac\lib\site-packages\paddle\fluid\__init__.py)
>>>
```

**Comment by rainyfly** [comment]
看报错应该是导入paddle出错了，你可以打开python后，直接import paddle看看会不会报错。如果导入paddle有问题的话，要不用conda重新创建一个环境，然后再安装paddle试试看。

**Comment by water-2022** [comment]
> 
没找到原因，我试着安装高版本Python 3.9+后没有问题了。
