### ISSUE TITLE
wav2lip FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleFormers#2216]
```
import paddlehub as hub
import os


# 获取当前文件夹路径
parent = os.path.dirname(os.path.abspath(__file__)) + "/"


module = hub.Module(name="wav2lip")
face_input_path = parent + "1.jpg"
audio_input_path = parent +  "334292423-1-208.wav"

print(face_input_path)
print(audio_input_path)
print( parent + '/transfer_result/')

module.wav2lip_transfer(face=face_input_path, audio=audio_input_path, output_dir= parent + '/transfer_result/', use_gpu=True)  


```

D:\anaconda31114\envs\paddHUB\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[02/28 17:47:46] ppgan INFO: Found C:\Users\monke\.cache\ppgan\GPEN-512.pdparams
W0228 17:47:47.090358 14692 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W0228 17:47:47.096369 14692 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.

f:/HUB/1.jpg
f:/HUB/334292423-1-208.wav
f:/HUB//transfer_result/

Number of frames available for inference: 1
Length of mel chunks: 2346
Model loaded
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/it] 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [03:04<00:00,  9.72s/it] 
Traceback (most recent call last):
  File "f:/qian_HUB/wav2lip2.py", line 16, in <module>
  File "D:\anaconda31114\envs\paddHUB\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "C:\Users\monke\.paddlehub\modules\wav2lip\module.py", line 70, in wav2lip_transfer
    self.network.run(face, audio, output_dir, visualization)
  File "C:\Users\monke\.paddlehub\modules\wav2lip\model.py", line 290, in run
    subprocess.call(command, shell=platform.system() != 'Windows')
  File "D:\anaconda31114\envs\paddHUB\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\anaconda31114\envs\paddHUB\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\anaconda31114\envs\paddHUB\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

```

-------------------- -------------
aiofiles             23.1.0
aiohttp              3.8.4
aiosignal            1.3.1
altair               4.2.2
anyio                3.6.2
astor                0.8.1
async-timeout        4.0.2
attrs                22.2.0
audioread            3.0.0
Babel                2.11.0
bce-python-sdk       0.8.79
Bottleneck           1.3.6
certifi              2022.12.7
cffi                 1.15.1
charset-normalizer   3.0.1
click                8.1.3
colorama             0.4.6
colorlog             6.7.0
contourpy            1.0.7
cycler               0.11.0
Cython               0.29.33
datasets             2.10.0
decorator            4.4.2
dill                 0.3.4
Distance             0.1.3
easydict             1.10
editdistance         0.6.2
entrypoints          0.4
fastapi              0.92.0
ffmpeg               1.4
ffmpy                0.3.0
filelock             3.9.0
Flask                2.2.3
Flask-Babel          2.0.0
fonttools            4.38.0
frozenlist           1.3.3
fsspec               2023.1.0
future               0.18.3
g2p-en               2.1.0
g2pM                 0.1.2.5
gradio               3.19.1
h11                  0.14.0
h5py                 3.8.0
httpcore             0.16.3
httpx                0.23.3
huggingface-hub      0.12.1
idna                 3.4
imageio              2.26.0
imageio-ffmpeg       0.4.8
importlib-metadata   6.0.0
importlib-resources  5.12.0
inflect              6.0.2
itsdangerous         2.1.2
jieba                0.42.1
Jinja2               3.1.2
joblib               1.2.0
jsonlines            3.1.0
jsonschema           4.17.3
kaldiio              2.17.2
kiwisolver           1.4.4
librosa              0.8.1
linkify-it-py        2.0.0
llvmlite             0.39.1
loguru               0.6.0
lxml                 4.9.2
markdown-it-py       2.2.0
MarkupSafe           2.1.2
matplotlib           3.7.0
mdit-py-plugins      0.3.3
mdurl                0.1.1
mock                 5.0.1
moviepy              1.0.3
multidict            6.0.4
multiprocess         0.70.12.2
nara-wpe             0.0.9
nltk                 3.8.1
numba                0.56.4
numpy                1.23.5
opencv-python        4.7.0.72
opt-einsum           3.3.0
orjson               3.8.6
packaging            23.0
paddle-bfloat        0.1.7
paddle2onnx          1.0.5
paddleaudio          1.1.0
paddlefsl            1.1.0
paddlehub            2.3.1
paddlenlp            2.5.1
paddlepaddle-gpu     2.4.1.post116
paddlespeech         0.1.0a13
paddlespeech-feat    0.1.0
pandas               1.5.3
parameterized        0.8.1
pathos               0.2.8
Pillow               9.4.0
pip                  22.3.1
pkgutil_resolve_name 1.3.10
platformdirs         3.0.0
pooch                1.7.0
portalocker          2.7.0
pox                  0.3.2
ppft                 1.7.6.6
praatio              4.4.0
proglog              0.1.10
protobuf             3.20.0
pyarrow              11.0.0
pybind11             2.10.3
pycparser            2.21
pycryptodome         3.17
pydantic             1.10.5
pydub                0.25.1
pyglet               2.0.3
Pygments             2.14.0
pyparsing            3.0.9
pypinyin             0.48.0
pyrsistent           0.19.3
python-dateutil      2.8.2
python-multipart     0.0.5
pytz                 2022.7.1
pywin32              305
pyworld              0.3.2
PyYAML               6.0
pyzmq                25.0.0
rarfile              4.0
regex                2022.10.31
requests             2.28.2
resampy              0.2.2
responses            0.18.0
rfc3986              1.5.0
rich                 13.3.1
sacrebleu            2.3.1
scikit-learn         1.2.1
scipy                1.10.1
sentencepiece        0.1.96
seqeval              1.2.2
setuptools           65.6.3
six                  1.16.0
sniffio              1.3.0
soundfile            0.12.1
starlette            0.25.0
tabulate             0.9.0
TextGrid             1.5
threadpoolctl        3.1.0
timer                0.2.2
toolz                0.12.0
tqdm                 4.64.1
typeguard            2.13.3
typer                0.7.0
typing_extensions    4.5.0
uc-micro-py          1.0.1
urllib3              1.26.14
uvicorn              0.20.0
visualdl             2.4.2
webrtcvad            2.0.10
websockets           10.4
Werkzeug             2.2.3
wheel                0.38.4
win32-setctime       1.1.0
wincertstore         0.2
xxhash               3.2.0
yacs                 0.1.8
yarl                 1.8.2
zipp                 3.15.0
```

**Comment by yapianwan** [comment]
安装ffmepg

**Comment by yapianwan** [comment]
安装ffmpeg

**Comment by mmhzlrj** [comment]
> 安装ffmpeg

解决方式：
conda install ffmpeg
