### ISSUE TITLE
official project BUG

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/PaddleFormers#2226]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
地址：https://aistudio.baidu.com/aistudio/projectdetail/4445054?channelType=0&channel=0
bug复现：
```
!hub run ernie_zeus \
    --task text_cloze \
    --text "她有着一双[MASK]的眼眸。"
```
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/commands/run.py", line 47, in execute
    module = Module(name=module_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 396, in __new__
    **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 511, in init_with_name
    return user_module_cls(**kwargs)
  File "/home/aistudio/.paddlehub/modules/ernie_zeus/module.py", line 54, in __init__
    self.access_token = get_access_token(ak, sk)
  File "/home/aistudio/.paddlehub/modules/ernie_zeus/module.py", line 27, in get_access_token
    'Please go to the wenxin official website to apply for AK and SK and set the parameters “ak” and “sk” correctly, or set the environment variables “WENXIN_AK” and “WENXIN_SK”.'
AssertionError: Please go to the wenxin official website to apply for AK and SK and set the parameters “ak” and “sk” correctly, or set the environment variables “WENXIN_AK” and “WENXIN_SK”.
问题：现在收费了？还是我来晚了？

**Comment by rainyfly** [comment]
需要自己去文心官网申请ak和sk进行使用
