### ISSUE TITLE
PaddleHub serving启动以后， Gradio APP页面无法访问

### ISSUE THREAD

**Issue by xwdreamer** [PaddlePaddle/PaddleFormers#2235]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
```
% pip list | grep paddle
paddle-bfloat        0.1.7
paddle2onnx          1.0.6
paddlefsl            1.1.0
paddlehub            2.3.1
paddlenlp            2.5.2
paddlepaddle         2.4.2
```
2）系统环境：
操作系统版本：macos
设备：macbook pro m2
python版本
```
% python --version
Python 3.8.16
% pip --version
pip 23.0.1
```
3）复现信息：如为报错，请给出复现环境、复现步骤

### 模型1：chinese_ocr_db_crnn_server

参考文档：https://www.paddlepaddle.org.cn/hubdetail?name=chinese_ocr_db_crnn_server

文档反馈：**从 PaddleHub 2.3.1 开始支持使用链接 http://127.0.0.1:8866/gradio/chinese_ocr_db_crnn_server 在浏览器中访问 chinese_ocr_db_crnn_server 的 Gradio App。**

实际操作，hub serving可以正常运行，但是访问，http://127.0.0.1:8866/gradio/chinese_ocr_db_crnn_server ，报错。

```

127.0.0.1 - - [10/Apr/2023 20:40:19] "GET /gradio/chinese_ocr_db_crnn_server HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 229, in gradio_app
    create_gradio_app(module_info)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 101, in create_gradio_app
    process.start()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/werkzeug/serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/werkzeug/serving.py", line 320, in execute
    application_iter = app(environ, start_response)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1721, in handle_exception
    self.log_exception(exc_info)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1744, in log_exception
    self.logger.error(
TypeError: __call__() got an unexpected keyword argument 'exc_info'


```

### 模型2：lac——已解决

参考文档：https://www.paddlepaddle.org.cn/hubdetail?name=lac

hub run可以正常运行，运行如下

```
%  hub run lac --input_text "今天是个好日子"
/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[{'word': ['今天', '是', '个', '好日子'], 'tag': ['TIME', 'v', 'q', 'n']}]
```
hub serving可以正常运行，运行如下：

```
hub serving start -c serving_config.json
/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-04-11 08:41:17,408] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0411 08:41:17.421156 3862870656 analysis_predictor.cc:2166] Deprecated. Please use CreatePredictor instead.
 * Serving Flask app 'paddlehub.serving.app_compat'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8866
 * Running on http://198.18.0.1:8866
Press CTRL+C to quit

```

**但是按照教程访问gradio app，失败。访问地址： http://127.0.0.1:8866/gradio/lac** 

错误信息：
```
127.0.0.1 - - [11/Apr/2023 08:41:29] "GET /gradio/lac HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 86, in create_gradio_app
    serving_method = getattr(module_info["module"], 'create_gradio_app')
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/module/module.py", line 95, in __getattribute__
    _attr = object.__getattribute__(self, attr)
AttributeError: 'LAC' object has no attribute 'create_gradio_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 229, in gradio_app
    create_gradio_app(module_info)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 88, in create_gradio_app
    raise RuntimeError('Module {} is not supported for gradio app.'.format(module_name))
RuntimeError: Module lac is not supported for gradio app.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/werkzeug/serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/werkzeug/serving.py", line 320, in execute
    application_iter = app(environ, start_response)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1721, in handle_exception
    self.log_exception(exc_info)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1744, in log_exception
    self.logger.error(
TypeError: __call__() got an unexpected keyword argument 'exc_info'
```

**Comment by rainyfly** [comment]
会不会是下载的模型版本不对，可以看一下你hub install得到的lac模块里（路径： ~/.paddlehub/modules/lac/module.py） 里有没有create_gradio_app这个函数。

**Comment by xwdreamer** [comment]
> 会不会是下载的模型版本不对，可以看一下你hub install得到的lac模块里（路径： ~/.paddlehub/modules/lac/module.py） 里有没有create_gradio_app这个函数。

查了，情况如下：
- chinese_ocr_db_crnn_server：有create_gradio_app
- lac：没有create_gradio_app

检查lac版本发现确实不是文档里面要求的2.4.0版本，而是2.1.0版本。lac没有create_gradio_app问题解决了。
请问chinese_ocr_db_crnn_server有什么解决思路吗？

**Comment by xwdreamer** [comment]
持续更新，修改lac版本为2.4.0版本以后，报错内容跟chinese_ocr_db_crnn_server一样了。

```
% hub serving start -c serving_config.json
/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
 * Serving Flask app 'paddlehub.serving.app_compat'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8866
 * Running on http://198.18.0.1:8866
Press CTRL+C to quit
127.0.0.1 - - [12/Apr/2023 09:31:33] "GET /gradio/lac HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 229, in gradio_app
    create_gradio_app(module_info)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddlehub/serving/app_compat.py", line 101, in create_gradio_app
    process.start()
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/werkzeug/serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/werkzeug/serving.py", line 320, in execute
    application_iter = app(environ, start_response)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1721, in handle_exception
    self.log_exception(exc_info)
  File "/Users/xxx/anaconda3/envs/paddle_env/lib/python3.8/site-packages/flask/app.py", line 1744, in log_exception
    self.logger.error(
TypeError: __call__() got an unexpected keyword argument 'exc_info'
```

**Comment by xwdreamer** [comment]
python 版本换成3.7

访问： http://127.0.0.1:8866/gradio/lac 。提示一直Loading
<img width="763" alt="image" src="https://user-images.githubusercontent.com/1173919/231932647-3a9e24ec-aac6-4d4a-8a3b-8f4d5a84df5d.png">

查看后台日志，如下
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/1173919/231932678-e6793a6a-4412-49c9-9ac3-e342c78c476b.png">

**Comment by rainyfly** [comment]
pip install gradio==3.11.0 呢

**Comment by xwdreamer** [comment]
> pip install gradio==3.11.0 呢

改成这个版本搞定了。


<img width="1311" alt="a960e9a73568a8dbf705f0172aafa631" src="https://user-images.githubusercontent.com/1173919/231934786-348c2f16-74fe-4c42-9920-1d1b64659b77.png">
