### ISSUE TITLE
hub serving部署成功一段时间后，会出现post请求超时错误

### ISSUE THREAD

**Issue by waizao** [PaddlePaddle/PaddleFormers#2256]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
paddle-bfloat             0.1.7
paddle-serving-app        0.9.0
paddle-serving-client     0.9.0
paddle-serving-server     0.9.0
paddle-serving-server-gpu 0.9.0.post1028
paddle2onnx               1.0.0
paddlefsl                 1.1.0
paddlehub                 2.3.0
paddlenlp                 2.4.0
paddlepaddle              2.3.2
tb-paddle                 0.4.0

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
Linux系统，Python 3.6.8 
- 复现信息：如为报错，请给出复现环境、复现步骤
hub serving部署OCR成功后，可以通过post正常请求。
但是一般正常运行几天后，则通过post请求一直提示超时，客户端(客户端和hub serving部署一台机器上，是本地调用)
在linux上通过 ps | grep  serving 查看进程后，发现进程仍在，是正常的，但是post请求会一直超时。
已经发生多次这个情况了，不是一两次。
客户端调用异常信息如下：

2023-05-20 20:14:31.303 [http-nio-9030-exec-762] ERROR c.y.r.controller.ai.image.ImageOcr - Failed to post request.models=2001
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://127.0.0.1:8867/predict/paddle_ch_ocr_system": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:468)

**Comment by waizao** [comment]
**问题又复现了，并且一旦出现调用失败，后面每次调用都会失败：**
**1、调用本地http接口识别OCR识别**
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://127.0.0.1:8867/predict/captcha_one": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:468)

**2、hub serving 进程还存在**
[root@iZ8vbihe2iddpwdi621lqeZ ~]# ps -ef|grep ocr
root      1714   644  0 18:24 pts/4    00:00:00 grep --color=auto ocr
root     19211     1  0 May20 ?        00:03:13 /usr/bin/python3.6 /usr/local/bin/hub serving start -c /root/service/waizao/humanai/ocr_start_config.json

hub serving启动http服务这个是否有日志打印？怎么开启日志？现在都找不到哪里出问题了
这个问题能麻烦看下么？感觉是通用性问题呢 ,麻烦各位大佬看下，非常感谢 @rainyfly  @jm12138

**Comment by waizao** [comment]
麻烦各位大佬看下，非常感谢 @rainyfly @jm12138

**Comment by waizao** [comment]
项目还有人在维护了吗？

**Comment by 736048546** [comment]
我也遇到这个问题，并且运行内存会越来越大

**Comment by 736048546** [comment]
并且无法杀掉进程只能重启服务器后才可以正常使用
