### ISSUE TITLE
ImportError: cannot import name 'RNNCell' from 'paddle.fluid.layers' (D:\software\lib\site-packages\paddle\fluid\layers\__init__.py)

### ISSUE THREAD

**Issue by dididiskq** [PaddlePaddle/PaddleFormers#2283]
How to solve it

**Comment by TTyb** [comment]
同样的问题

**Comment by hcx1002** [comment]
用paddle2.4版本就可以

**Comment by PhilanthropistBright** [comment]
同样的问题  试了2.4.0 和2.4.2的版本  一样不行

**Comment by fuzhao123232** [comment]
卡了一下午，百度在干嘛啊，bug也不修复

**Comment by qq545622333** [comment]
我也试了2.4.0，有其他报错
Traceback (most recent call last):
  File "d:/Work/Paddle/Test1/tesst.py", line 1, in <module>
    import paddlehub
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlehub\__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlehub\datasets\__init__.py", line 16, in <module>
    from paddlehub.datasets.chnsenticorp import ChnSentiCorp
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlehub\datasets\chnsenticorp.py", line 19, in <module>
    from paddlehub.datasets.base_nlp_dataset import TextClassificationDataset
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlehub\datasets\base_nlp_dataset.py", line 21, in <module>
    import paddlenlp
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlenlp\__init__.py", line 35, in <module>
    from . import (
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlenlp\data\__init__.py", line 16, in <module>
    from .data_collator import *
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlenlp\data\data_collator.py", line 26, in <module>
    from ..transformers import BertTokenizer
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlenlp\transformers\__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlenlp\transformers\model_utils.py", line 63, in <module>
    from .generation_utils import GenerationMixin
  File "D:\ProgramData\anaconda3\envs\PaddleTest\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 29, in <module>
    from paddle.nn.layer.layers import in_declarative_mode
ModuleNotFoundError: No module named 'paddle.nn.layer.layers'

**Comment by whisky-12** [comment]
同样的错误 感觉像python版本的冲突 或者paddle的 
好几个环境 有的可以有的不可以

**Comment by GuanghuiMin** [comment]
同样的问题，希望官方能解决

**Comment by monkeycc** [comment]
`pip install paddlenlp==2.5.2`

**Comment by rainyfly** [comment]
现阶段有效版本可按如下方式安装（以anaconda作为环境管理工具为例）：

conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
