### ISSUE TITLE
运行代码时报错：生成图片超限，如何解决？

### ISSUE THREAD

**Issue by wm-95** [PaddlePaddle/PaddleFormers#2314]
PaddleHub2.4.0，PaddlePaddle2.5.2
系统环境：Windows
python版本：3.9.18
报错：在进行预测代码示例中，运行images = module.generate_image(text_prompts=text_prompts, style='油画', output_dir='./ernie_vilg_out/')后报错
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\k\anaconda3\envs\wm\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "C:\Users\k\.paddlehub\modules\ernie_vilg\module.py", line 121, in generate_image
    raise RuntimeError(res['msg'])
RuntimeError: 生成图片超限

**Comment by michaelowenliu** [comment]
能在res['msg']前面打印下内容吗？
