### ISSUE TITLE
hub install 命令 或 search 命令 报错

### ISSUE THREAD

**Issue by CodeEthanLucas** [PaddlePaddle/PaddleFormers#2319]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub 2.4.0，python3.8 conda 23.7.4 
2）系统环境：Windows
根据 https://github.com/PaddlePaddle/PaddleHub/blob/develop/docs/docs_ch/get_start/windows_quickstart.md 文档 进行安装后，输入  hub install 模型  或  hub search 模型 时 会报josn error 

```python
placing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\Scripts\hub.exe\__main__.py", line 7, in <module>
    sys.exit(execute())
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\paddlehub\commands\utils.py", line 84, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\paddlehub\commands\search.py", line 36, in execute
    results = module_server.search_module(name=argv)
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\paddlehub\server\server.py", line 87, in search_module
    return self.search_resource(
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\paddlehub\server\server.py", line 113, in search_resource
    result = source.search_resource(name=name, type=type, version=version)
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\paddlehub\server\server_source.py", line 87, in search_resource
    result = self.request(path='search', params=params)
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\paddlehub\server\server_source.py", line 131, in request
    return result.json()
  File "C:\Users\YanJinTao\.conda\envs\paddle_env\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

``` 
/

**Comment by w5688414** [comment]
您好，可能是网络的原因，如果怕出错，可以参考我的paddle配置，然后检查一下网络是否通。

```
paddle-bfloat==0.1.7
paddle2onnx==1.1.0
paddleaudio==1.1.0
paddlefsl==1.1.0
paddlehub==2.3.1
paddlenlp==2.5.2
paddlepaddle-gpu==2.4.2.post117
paddlesde==0.2.5
paddleslim==2.6.0
paddlespeech==1.4.1
paddlespeech-ctcdecoders==0.2.1
paddlespeech-feat==0.1.0
```
<img width="1063" alt="image" src="https://github.com/PaddlePaddle/PaddleHub/assets/12107462/b18fe73c-b1c9-4aed-b47f-f1c3cc8eef8e">
