### ISSUE TITLE
序列标注自定义数据集报keyerror

### ISSUE THREAD

**Issue by Stephen-L-Woo** [PaddlePaddle/PaddleFormers#339]
平台：aistudio
paddlehub版本：1.5.0
使用模型版本：ernie-1.1.0

我参照的项目：
《PaddleHub实战——使用语义预训练模型ERNIE优化信息抽取》
https://aistudio.baidu.com/aistudio/projectdetail/184200

我的数据集格式不同是中间没有分隔符‘’，和官方例子中的MSRA_NER()的格式是一样
但一直报错，而且相似的还报好几个，这是什么原因？
`2020-02-06 14:58:53,414-WARNING: Your decorated reader has raised an exception!
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 474, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 455, in __provider_thread__
    for tensors in func():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 506, in __tensor_provider__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/nlp_reader.py", line 257, in wrapper
    examples, batch_size, phase=phase):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/nlp_reader.py", line 187, in _prepare_batch_data
    self.tokenizer, phase)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/nlp_reader.py", line 463, in _convert_example_to_record
    for label in labels] + [no_entity_id]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/nlp_reader.py", line 463, in <listcomp>
    for label in labels] + [no_entity_id]
KeyError: 'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'`

**Comment by Steffy-zxf** [comment]
感谢反馈！由于ERNIE对于文本处理粒度是以汉字为单位。PaddleHub预置MSRA_NER数据集也是以不可见字符"\002"分隔汉字和数字的。建议你的数据（文本、label）也以不可见字符"\002"分隔每个汉字、数字等。

**Comment by Stephen-L-Woo** [comment]
> 感谢反馈！由于ERNIE对于文本处理粒度是以汉字为单位。PaddleHub预置MSRA_NER数据集也是以不可见字符"\002"分隔汉字和数字的。建议你的数据（文本、label）也以不可见字符"\002"分隔每个汉字、数字等。

明白了，非常感谢！

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
