### ISSUE TITLE
运行task.finetune_and_eval()报错，提示我创建一个issues 

### ISSUE THREAD

**Issue by sdjkxhb2016** [PaddlePaddle/PaddleFormers#344]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

代码如下：
#!/usr/bin/env python
# coding: utf-8

# # 如何使用PaddleHub进行图像分类
# 

get_ipython().system('pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple')

# -*- coding: utf8 -*-
import paddlehub as hub

#module = hub.Module(name="resnet_v2_50_imagenet")
get_ipython().system('hub install mobilenet_v2_imagenet==1.0.1')

module = hub.Module(name="mobilenet_v2_imagenet")

# PaddleHub 还有着许多的图像分类预训练模型，更多信息参见[PaddleHub官方网站](https://www.paddlepaddle.org.cn/hub)

# ## 三、数据准备

# 解压数据
get_ipython().system('cd data/data20782/ && unzip -qo train.zip ')

# 直接用PaddleHub提供的数据集
# dataset = hub.dataset.DogCat()

from paddlehub.dataset.base_cv_dataset import BaseCVDataset
   
class DemoDataset(BaseCVDataset):	
  def __init__(self):	
      # 数据集存放位置
      self.dataset_dir = "data/data20782/train"
      super(DemoDataset, self).__init__(
          base_path=self.dataset_dir,
          train_list_file="train_list.txt",
          validate_list_file="validate_list.txt",
          test_list_file="test_list.txt",
          label_list_file="label_list.txt"
          )
dataset = DemoDataset()

print("自定义数据集")

# ## 四、生成Reader

data_reader = hub.reader.ImageClassificationReader(
    image_width=module.get_expected_image_width(),
    image_height=module.get_expected_image_height(),
    images_mean=module.get_pretrained_images_mean(),
    images_std=module.get_pretrained_images_std(),
    dataset=dataset)

print(data_reader)

# ## 五、选择运行时配置

config = hub.RunConfig(
    use_data_parallel = True,
    use_cuda=True,
    num_epoch=1,
    checkpoint_dir="work/cv_train_checkpoint",
    batch_size=32,
    eval_interval=50,
    strategy=hub.finetune.strategy.DefaultFinetuneStrategy())

# ## 六、组建Finetune Task

input_dict, output_dict, program = module.context(trainable=True)

# Setup feed list for data feeder
feed_list = [input_dict["image"].name]
img = input_dict["image"]
feed_list = [img.name]

feature_map = output_dict["feature_map"]

print(dataset.num_labels)

task = hub.ImageClassifierTask(
    data_reader=data_reader,
    feed_list=feed_list,
    feature=feature_map,
    num_classes=dataset.num_labels,
    config=config)

# ## 七、开始Finetune

task.finetune_and_eval()

# 报错如下 
[2020-02-12 00:54:42,952] [    INFO] - Try loading checkpoint from work/cv_train_checkpoint/ckpt.meta
[2020-02-12 00:54:42,954] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-02-12 00:54:42,955] [    INFO] - PaddleHub finetune start
2020-02-12 00:54:42,957-WARNING: Your decorated reader has raised an exception!
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 474, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 455, in __provider_thread__
    for tensors in func():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 506, in __tensor_provider__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/batch.py", line 58, in batch_reader
    for instance in r:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/cv_reader.py", line 145, in _data_reader
    image = preprocess(image_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/cv_reader.py", line 112, in preprocess
    image = Image.open(image_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/data20782/train/InRoom_Yes/IMG_20200210_084729.jpg\t0'

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-61-117cac863186> in <module>
----> 1 task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    761 
    762     def finetune_and_eval(self):
--> 763         return self.finetune(do_eval=True)
    764 
    765     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    773                 while self.current_epoch <= self.config.num_epoch:
    774                     self.config.strategy.step()
--> 775                     run_states = self._run(do_eval=do_eval)
    776                     self.env.current_epoch += 1
    777 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
    826         with fluid.program_guard(self.main_program, self.startup_program):
    827             if self.config.use_pyreader:
--> 828                 return self._run_with_py_reader(do_eval=do_eval)
    829             return self._run_with_data_feeder(do_eval=do_eval)
    830 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run_with_py_reader(self, do_eval)
    904                         fetch_result = self.exe.run(
    905                             self.main_program_to_be_run,
--> 906                             fetch_list=self.fetch_list)
    907                     else:
    908                         fetch_result = self.exe.run(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    778                 warnings.warn(
    779                     "The following exception is not an EOF exception.")
--> 780             six.reraise(*sys.exc_info())
    781 
    782     def _run_impl(self, program, feed, fetch_list, feed_var_name,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    773                 scope=scope,
    774                 return_numpy=return_numpy,
--> 775                 use_program_cache=use_program_cache)
    776         except Exception as e:
    777             if not isinstance(e, core.EOFException):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    820                 scope=scope,
    821                 return_numpy=return_numpy,
--> 822                 use_program_cache=use_program_cache)
    823 
    824         program._compile(scope, self.place)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    897         if not use_program_cache:
    898             self._default_executor.run(program.desc, scope, 0, True, True,
--> 899                                        fetch_var_name)
    900         else:
    901             self._default_executor.run_cached_prepared_ctx(ctx, scope, False,
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ReadOp::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
4   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
5   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 872, in read_file
    type='read', inputs={'Reader': [reader]}, outputs={'Out': out})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 352, in _build_env
    py_vars = fluid.layers.read_file(self.env.py_reader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 474, in main_program
    self._build_env()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 732, in load_checkpoint
    main_program=self.main_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 297, in init_if_necessary
    if not self.load_checkpoint():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 769, in finetune
    self.init_if_necessary()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 763, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "<ipython-input-60-035a73d4265a>", line 1, in <module>
    run_states = task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle._run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

----------------------
Error Message Summary:
----------------------
Error: Paddle internal Check failed. (Please help us create a new issue, here we need to find the developer to add a user friendly error message)
  [Hint: reader_ should not be null.] at (/paddle/paddle/fluid/framework/reader.h:110)
  [operator < read > error]

**Comment by Steffy-zxf** [comment]
感谢反馈！更具以上错误信息显示：
`FileNotFoundError: [Errno 2] No such file or directory: 'data/data20782/train/InRoom_Yes/IMG_20200210_084729.jpg\t0'`
确认下数据是否正确，是否存在。

**Comment by sdjkxhb2016** [comment]
多谢回复，我知道这个原因，是因为我的图片路径和后面的索引之间用tab键分隔的，用空格才可以
