### ISSUE TITLE
执行python语句下载模型报错

### ISSUE THREAD

**Issue by SaintyLiu** [PaddlePaddle/PaddleFormers#388]
PaddleHub1.5.3，PaddlePaddle1.7.0.post107
系统环境Windows 10 python 3.7.6
- 复现信息：如为报错，请给出复现环境、复现步骤
执行python export_model.py报错
(paddlehub) C:\Users\小胖Sainty>C:/ProgramData/Anaconda3/envs/paddlehub/python.exe d:/code/PaddleHub/demo/mask_detection/python/export_model.py
[2020-02-25 21:43:48,389] [    INFO] - Installing pyramidbox_lite_server_mask module-1.1.0
[2020-02-25 21:43:48,516] [    INFO] - Module pyramidbox_lite_server_mask-1.1.0 already installed in C:\Users\小胖Sainty\.paddlehub\modules\pyramidbox_lite_server_mask
C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "d:/code/PaddleHub/demo/mask_detection/python/export_model.py", line 17, in <module>
    module = hub.Module(name="pyramidbox_lite_server_mask", version='1.1.0')
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 144, in __new__
    module = cls.init_with_name(name=name, version=version)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 217, in init_with_name
    return cls.init_with_directory(directory=module_dir[0])
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 232, in init_with_directory
    return ModuleV1(directory=directory)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 326, in __init__
    self.helper.model_path(), executor=exe)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 1377, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 917, in load_persistables
    filename=filename)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 742, in load_vars
    filename=filename)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 794, in load_vars
    executor.run(load_prog)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 774, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 742, in load_vars
    filename=filename)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 917, in load_persistables
    filename=filename)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddle\fluid\io.py", line 1377, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 326, in __init__
    self.helper.model_path(), executor=exe)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 232, in init_with_directory
    return ModuleV1(directory=directory)
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 217, in init_with_name
    return cls.init_with_directory(directory=module_dir[0])
  File "C:\ProgramData\Anaconda3\envs\paddlehub\lib\site-packages\paddlehub\module\module.py", line 144, in __new__
    module = cls.init_with_name(name=name, version=version)
  File "d:/code/PaddleHub/demo/mask_detection/python/export_model.py", line 17, in <module>
    module = hub.Module(name="pyramidbox_lite_server_mask", version='1.1.0')

----------------------
Error Message Summary:
----------------------
Error: Cannot open file C:\Users\小胖Sainty\.paddlehub\modules\pyramidbox_lite_server_mask\model\@HUB_pyramidbox_lite_server_mask@age_block2_1.w_0 for load op at (D:\1.7.0\paddle\paddle/fluid/operators/load_op.h:38)
  [operator < load > error]

**Comment by ZeyuChen** [comment]
@SaintyLiu 
C:\Users\小胖Sainty.paddlehub\modules\pyramidbox_lite_server_mask\model@HUB_pyramidbox_lite_server_mask@age_block2_1.w_0 for load op

原因是因为路径中有中文目录导致文件加载出错
请尝试通过设置环境变量HUB_HOME至D:\xxx等其他不包含中文路径的目录后重新运行试试。

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
