### ISSUE TITLE
识别多帧之后报错 HUB_pyramidbox_lite_mobile

### ISSUE THREAD

**Issue by oeandn** [PaddlePaddle/PaddleFormers#416]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如
paddlehub            1.5.2     
paddlepaddle         1.6.3     
2）系统环境：centos7请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：
如为报错，请给出复现环境、复现步骤
复现环境，python调用摄像头不断读帧，将图像进行图像检测face_detection
input_dict={"data":[frame]}
错误追踪：
var @HUB_pyramidbox_lite_mobile@image not in this blockNone
Traceback (most recent call last):
  File "/root/oeworkspace/kouzhao/kzvideo5.py", line 155, in startpushstream
    results = module.face_detection(data=input_dict)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 537, in __call__
    reader, feeder = _get_reader_and_feeder(data_format, data, place)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 510, in _get_reader_and_feeder
    feeder = fluid.DataFeeder(feed_list=feed_name_list, place=place)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 262, in __init__
    each_var = program.block(0).var(each_var)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2263, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var @HUB_pyramidbox_lite_mobile_mask@image not in this block

**Comment by nepeplwu** [comment]
@oeandn ，感谢反馈，请问大概跑了多久出现的问题？

**Comment by taingload** [comment]
> @oeandn ，感谢反馈，请问大概跑了多久出现的问题？

大概是10到12个小时

**Comment by taingload** [comment]
> @oeandn ，感谢反馈，请问大概跑了多久出现的问题？

我用两个线程不断的进行图像识别，每个线程间隔是0.5S/张

**Comment by nepeplwu** [comment]
了解，我们先复现下问题看看

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
