### ISSUE TITLE
使用config.json启动hub serving方式报错

### ISSUE THREAD

**Issue by DeIn221** [PaddlePaddle/PaddleFormers#448]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.5.4，PaddlePaddle1.5.2
2）系统环境：Windows10，python3.6.4

- 复现信息：
使用`hub serving start -c config.json`
- 报错信息：
```
Traceback (most recent call last):
  File "d:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python36\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\python36\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "d:\python36\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "d:\python36\lib\site-packages\paddlehub\commands\serving.py", line 432, in execute
    self.start_serving()
  File "d:\python36\lib\site-packages\paddlehub\commands\serving.py", line 357, in start_serving
    ServingCommand.start_single_app_with_file(configs)
TypeError: start_single_app_with_file() missing 1 required positional argument: 'configs'
```
- config.json内容
```
{  
  "modules_info": [  
    {  
       "module": "ernie_tiny",
       "version": "1.0.0",
       "batch_size": "1"
    }
  ],  
  "port": 8866,
  "use_gpu": false,  
  "use_multiprocess": false
}
```

**Comment by Steffy-zxf** [comment]
感谢反馈！ernie_tiny不支持直接部署预测使用。了解下，你想用ernie_tiny做什么任务呢？

**Comment by DeIn221** [comment]
> 感谢反馈！ernie_tiny不支持直接部署预测使用。了解下，你想用ernie_tiny做什么任务呢？

文本情感分类任务

**Comment by Steffy-zxf** [comment]
你可以先用ernie_tiny完成情感分类任务Fine-tune ，参考 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/demo/text_classification/text_classifier.py 
之后将Fine-tune保存的best_model转化成module。fine-tune模型如何转化为module，参考  #444 回复。之后就可以用Hub Serving部署预测了。

**Comment by DeIn221** [comment]
> 你可以先用ernie_tiny完成情感分类任务Fine-tune ，参考 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/demo/text_classification/text_classifier.py
> 之后将Fine-tune保存的best_model转化成module。fine-tune模型如何转化为module，参考 #444 回复。之后就可以用Hub Serving部署预测了。

明白了，非常感谢您的回复！

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
