### ISSUE TITLE
你好，我安装的PaddlePaddle1.7.1和PaddleHub1.5.4，win10系统，python3.6，导入paddlehub就直接报错了，想请求帮助解决下问题。

### ISSUE THREAD

**Issue by AIman6** [PaddlePaddle/PaddleFormers#462]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
下面是错误信息：
 File "D:/FaceMask Detection/detect.py", line 8, in <module>
    import paddlehub
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\module\module.py", line 33, in <module>
    from paddlehub.common import utils
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\__init__.py", line 16, in <module>
    from . import utils
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\utils.py", line 33, in <module>
    from paddlehub.common.logger import logger
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by takumijash** [comment]
hub clean 之後再試試看

**Comment by 784228565** [comment]
收到，谢谢您的解答，，have a good day




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "takumijash"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 下午5:01
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;; 
抄送: "784228565"<784228565@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleHub] 你好，我安装的PaddlePaddle1.7.1和PaddleHub1.5.4，win10系统，python3.6，导入paddlehub就直接报错了，想请求帮助解决下问题。 (#462)





 
hub clean 之後再試試看

**Comment by AIman6** [comment]
@takumijash 你好，我输入hub clean后还是一样的问题，包括卸载重装PaddleHub还是原来的问题

**Comment by ShenYuhan** [comment]
您试试下面的步骤
1 卸载干净paddlehub
2 手动删除 .paddlehub 文件夹**【如果您在此文件夹下没有重要数据的话】**，windows环境的话您可以在电脑上搜索一下
3 重新安装paddlehub

**Comment by AIman6** [comment]
@ShenYuhan 谢谢 ，照着做原来问题解决了，但是又出现了新的错误，并且重新运行后又变成原来的错误了，这是测试连接代码：
import paddlehub
paddlehub.server_check()
下面是新的报错信息： 
File "D:/FaceMask Detection/detect.py", line 2, in <module>
    paddlehub.server_check()
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\hub_server.py", line 342, in server_check
    HubServer().server_check()
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\decorator_utils.py", line 24, in synced_func
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\decorator_utils.py", line 35, in _get_instance
    _instance[cls] = cls(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\paddlepaddle1.7.1\lib\site-packages\paddlehub\common\hub_server.py", line 52, in __init__
    fp.write(json.dumps(default_server_config))
ValueError: I/O operation on closed file.

**Comment by tiesanguaixia** [comment]
您好，我也遇到了一样的问题，求解答，仅仅import paddlehub 就会报错

**Comment by 784228565** [comment]
我也是

**Comment by Gs-Zhang** [comment]
`我也遇到了一样的问题，win10下显示安装成功了，但是导入就出现同样的问题。已经卸载重装过了``>>> import paddlehub as hub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\module\module.py", line 31, in <module>
    from paddlehub.common import utils
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\common\__init__.py", line 16, in <module>
    from . import utils
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\common\utils.py", line 33, in <module>
    from paddlehub.common.logger import logger
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "C:\Users\12971\Miniconda3\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "C:\Users\12971\Miniconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\12971\Miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\12971\Miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\12971\Miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Gs-Zhang** [comment]
{
    "server_url": [
        "http://paddlepaddle.org.cn/paddlehub"
    ],
    "resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
    "debug": false,
    "log_level": "DEBUG"
}

把这个拷到 .paddlehub/conf/config.json下
亲测可解决我之前的问题，感谢热心大佬

**Comment by tiesanguaixia** [comment]
> {
> "server_url": [
> "http://paddlepaddle.org.cn/paddlehub"
> ],
> "resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
> "debug": false,
> "log_level": "DEBUG"
> }
> 
> 把这个拷到 .paddlehub/conf/config.json下
> 亲测可解决我之前的问题，感谢热心大佬

解决了，谢谢大佬！

**Comment by AIman6** [comment]
> {
> "server_url": [
> "http://paddlepaddle.org.cn/paddlehub"
> ],
> "resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
> "debug": false,
> "log_level": "DEBUG"
> }
> 
> 把这个拷到 .paddlehub/conf/config.json下
> 亲测可解决我之前的问题，感谢热心大佬

非常感谢！亲测问题已解决，谢谢大佬

**Comment by ShenYuhan** [comment]
此问题在1.6.1的版本中已经修复

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
