### ISSUE TITLE
你好，请问这个问题该怎么解决？ValueError: The target variable must have an associated operator that generates it.

### ISSUE THREAD

**Issue by SDUwn** [PaddlePaddle/PaddleFormers#473]
请问这个问题该怎么解决？ValueError: The target variable must have an associated operator that generates it.

Traceback (most recent call last):
  File "reading_comprehension.py", line 461, in <module>
    reading_comprehension_task.finetune_and_eval()
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 884, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 1097, in _run
    self._eval_interval_event()
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 630, in hook_function
    func(*args)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 782, in _default_eval_interval_event
    self.eval(phase="dev")
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 922, in eval
    self._eval_end_event(run_states)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 630, in hook_function
    func(*args)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 753, in _default_eval_end_event
    self.save_inference_model(dirname=model_saved_dir)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/finetune/task/base_task.py", line 860, in save_inference_model
    params_filename=params_filename)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 1218, in save_inference_model
    feeded_var_names=feeded_var_names, targets=target_vars)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/framework.py", line 4122, in _prune_with_input
    "The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.

**Comment by Steffy-zxf** [comment]
感谢反馈！你的paddlepaddle版本和paddlehub版本各是多少？

**Comment by SDUwn** [comment]
> 感谢反馈！你的paddlepaddle版本和paddlehub版本各是多少？

paddlehub                          1.6.0          
paddlepaddle-gpu                   1.7.0.post97

**Comment by kinghuin** [comment]
@wangdanana hi，请问您是否有修改过组网部分呢？ 可以贴下代码吗？

**Comment by SDUwn** [comment]
> @wangdanana hi，请问您是否有修改过组网部分呢？ 可以贴下代码吗？

我直接在百度 AI Studio上运行的，用的python版本是2.7,
只改过这里：!pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by kinghuin** [comment]
麻烦公开一下项目并贴一下项目链接，我复现一下这个错误

**Comment by SDUwn** [comment]
> 麻烦公开一下项目并贴一下项目链接，我复现一下这个错误

https://aistudio.baidu.com/aistudio/projectdetail/332910

**Comment by kinghuin** [comment]
> > 麻烦公开一下项目并贴一下项目链接，我复现一下这个错误
> 
> https://aistudio.baidu.com/aistudio/projectdetail/332910

您好，感谢您的错误报告，请尝试执行以下命令降级paddlepaddle至1.6.2：
!pip install paddlepaddle-gpu==1.6.2.post97

**Comment by ZYsayoulala** [comment]
请问问题解决了吗，我也碰到了相同的问题，py3，其他都是最新版

**Comment by kinghuin** [comment]
@ZYsayoulala Hi，尝试过降级paddlepaddle至1.6.2吗？

**Comment by ZYsayoulala** [comment]
@kinghuin 降级已解决，谢谢

**Comment by SDUwn** [comment]
降级已解决，谢谢！
