### ISSUE TITLE
paddlehub的bert的sequence_output后如何加入lstm??

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#476]
这是我想要实现的代码：

```
`import paddlehub as hub
max_seq_len=128
# dataset = MyDataset()
module = hub.Module(name="bert_chinese_L-12_H-768_A-12")
inputs, outputs, program = module.context(
trainable=True, max_seq_len=max_seq_len)
print(outputs)
# Use "pooled_output" for classification tasks on an entire sentence.
pooled_output = outputs["pooled_output"]
seq_output=outputs['sequence_output']
print(seq_output)
hidden_units=[128]
cls_feats = fluid.layers.dropout(
            x=seq_output,
            dropout_prob=0,
            dropout_implementation="upscale_in_train")
print(cls_feats)
if hidden_units is not None:
    for n_hidden in hidden_units:
        # cls_feats = fluid.layers.fc(
        #     input=cls_feats, size=n_hidden, act=None)
        # print(cls_feats)
        cls_feats = fluid.layers.fc(input=cls_feats, size=n_hidden,
                    act=None, bias_attr=None)
        print(cls_feats)
        lstm_h, c = fluid.layers.dynamic_lstm(
            input=cls_feats, size=n_hidden, is_reverse=False)
        print(lstm_h)
        # # 最大池化
        lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
        print(lstm_max)
        # # 激活函数
        cls_feats = fluid.layers.tanh(lstm_max)
        print(cls_feats)

logits = fluid.layers.fc(
    input=cls_feats,
    size=3,
    param_attr=fluid.ParamAttr(
        name="cls_out_w",
        initializer=fluid.initializer.TruncatedNormal(scale=0.02)),
    bias_attr=fluid.ParamAttr(
        name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
    act="softmax")

ret_infers = fluid.layers.reshape(
    x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])
----------------------
Error Message Summary:
----------------------
Error: Size of target LoD should be greater than 1.
  [Hint: Expected level0.size() > 1UL, but received level0.size():1 <= 1UL:1.] at (/paddle/paddle/fluid/operators/lod_reset_op.h:60)
  [operator < lod_reset > error]
```

**Comment by wxl1351641822** [comment]
我考虑了layers的lod_append,但他并不能改变我的seq_output
考虑使用lod_reset:
他在一般的variable上可以用，但在sequence_output上用不了
set_lod也不管用
```
import paddle.fluid as fluid
seq_feature=fluid.layers.lod_reset(seq_output, target_lod=[1]*128)
print(seq_feature)
name: "@HUB_bert_chinese_L-12_H-768_A-12@@HUB_bert_chinese_L-12_H-768_A-12@layer_norm_24.tmp_2"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false
```

```
 
import paddle.fluid as fluid
x = fluid.layers.data(name='x1', shape=[128,768], lod_level=0)
print(x)
out = fluid.layers.lod_reset(x, target_lod=[128])
print(out)


name: "x1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false

name: "lod_reset_1.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 1
  }
}
persistable: false
```

**Comment by Steffy-zxf** [comment]
你好！你需要自定义一个task，自定义task教程 参考 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/how_to_define_task.md
在自定义Task的_build_net方法里搭建你想要组建的lstm网络，参考 https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/shared_modules/models/classification/nets.py#L269
其中ernie_bilstm_net方法中的token_embeddings即为outputs['sequence_output']。

**Comment by wxl1351641822** [comment]
您好，这两个我都看过了，build_net我也已经重载过了，上述代码就是在buildnet里的，也用的sequence_output,但就是报错。
```

----------------------
Error Message Summary:
----------------------
Error: Size of target LoD should be greater than 1.
  [Hint: Expected level0.size() > 1UL, but received level0.size():1 <= 1UL:1.] at (/paddle/paddle/fluid/operators/lod_reset_op.h:60)
  [operator < lod_reset > error]
```
我以为是lod没有改变，然后用了lod_reset,但也不管用，一样的错误。
buildnet里代码如下：
```
def _bilstm_layer(self, hidden_dim):
        input_fwd_proj = fluid.layers.fc(
            input=self.feature,
            param_attr=fluid.ParamAttr(name='_fw_gate_w'),
            size=hidden_dim * 4,
            act=None,
            bias_attr=False)
        input_bwd_proj = fluid.layers.fc(
            input=self.feature,
            param_attr=fluid.ParamAttr(name='_bw_gate_w'),
            size=hidden_dim * 4,
            act=None,
            bias_attr=False)
        fwd, _ = fluid.layers.dynamic_lstm(
            input=input_fwd_proj,
            size=hidden_dim * 4,
            use_peepholes=False,
            param_attr=fluid.ParamAttr(name='_fw_lstm_w'),
            bias_attr=fluid.ParamAttr(name='_fw_lstm_b'))
        bwd, _ = fluid.layers.dynamic_lstm(
            input=input_bwd_proj,
            param_attr=fluid.ParamAttr(name='_bw_lstm_w'),
            bias_attr=fluid.ParamAttr(name='_bw_lstm_b'),
            size=hidden_dim * 4,
            is_reverse=True,
            use_peepholes=False)
        outputs = fluid.layers.concat(input=[fwd, bwd], axis=1)
        return outputs
def _build_net(self):
        # self.feature = fluid.layers.lod_reset(self.feature, target_lod=[128])
        cls_feats = fluid.layers.dropout(
            x=self.feature,
            dropout_prob=0.1,
            dropout_implementation="upscale_in_train",
            seed=seed)

        if hidden_units is not None:
            for n_hidden in hidden_units:
                cls_feats=self._bilstm_layer(n_hidden)

        logits = fluid.layers.fc(
            input=cls_feats,
            size=self.num_classes,
            param_attr=fluid.ParamAttr(
                name="cls_out_w",
                initializer=fluid.initializer.TruncatedNormal(scale=0.02, seed=seed)),
            bias_attr=fluid.ParamAttr(
                name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
            act="softmax")

        self.ret_infers = fluid.layers.reshape(
            x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])

        return [logits]
```

**Comment by wxl1351641822** [comment]
从dynamic_lstm换成lstm也不管用orz……求问这是什么情况？？？
不用lstm的时候就一切正常
```
    def _build_net(self):
        # self.feature = fluid.layers.lod_reset(self.feature, target_lod=[128])
        cls_feats = fluid.layers.dropout(
            x=self.feature,
            dropout_prob=0.1,
            dropout_implementation="upscale_in_train",
            seed=seed)

        # cls_feats=fluid.layers.lod_reset(self.feature, target_lod=[128])
        if hidden_units is not None:
            for n_hidden in hidden_units:
                num_layers=1
                init_h = fluid.layers.fill_constant([num_layers*2, batch_size,n_hidden], 'float32', 0.0)
                init_c = fluid.layers.fill_constant([num_layers*2, batch_size, n_hidden], 'float32', 0.0)
                cls_feats, last_h, last_c = fluid.layers.lstm(cls_feats, init_h, init_c, max_seq_len,n_hidden, num_layers,is_bidirec=True,seed=seed)
                print(cls_feats)

        logits = fluid.layers.fc(
                input=cls_feats,
                size=self.num_classes,
                param_attr=fluid.ParamAttr(
                    name="cls_out_w",
                    initializer=fluid.initializer.TruncatedNormal(scale=0.02, seed=seed)),
                bias_attr=fluid.ParamAttr(
                    name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
                act="softmax")

        self.ret_infers = fluid.layers.reshape(
            x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])

        return [logits]
```

```
[2020-03-26 16:50:18,650] [    INFO] - Installing bert_chinese_L-12_H-768_A-12 module
[2020-03-26 16:50:18,653] [    INFO] - Module bert_chinese_L-12_H-768_A-12 already installed in /home/aistudio/.paddlehub/modules/bert_chinese_L_12_H_768_A_12
[2020-03-26 16:50:18,654] [    INFO] - Dataset label map = {'-1': 0, '0': 1, '1': 2}
[2020-03-26 16:50:18,682] [ WARNING] - Both noam_decay and linear_decay have been set, only noam_decay will take effect
[2020-03-26 16:50:18,682] [    INFO] - Checkpoint dir: ./work/model4
[2020-03-26 16:50:22,556] [    INFO] - Load pretraining parameters from /home/aistudio/.paddlehub/modules/bert_chinese_L_12_H_768_A_12/assets/params.
[2020-03-26 16:50:22,723] [    INFO] - Delete hook eval_end_event:default successfully
[2020-03-26 16:50:22,723] [    INFO] - Add hook eval_end_event:new_eval_end_event successfully
[2020-03-26 16:50:22,723] [    INFO] - Add hook log_interval_event:new_log_interval_event successfully
[2020-03-26 16:50:24,008] [    INFO] - Strategy with warmup, noam decay, slanted triangle learning rate, weight decay regularization, 
W0326 16:50:25.047698   474 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0326 16:50:25.052628   474 device_context.cc:244] device: 0, cuDNN Version: 7.3.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:795: UserWarning: The current program is empty.
  warnings.warn(error_info)
[2020-03-26 16:50:26,302] [    INFO] - Try loading checkpoint from ./work/model4/ckpt.meta
[2020-03-26 16:50:26,303] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-03-26 16:50:26,357] [    INFO] - PaddleHub finetune start
I0326 16:50:26.698858   474 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0326 16:50:26.823554   474 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0326 16:50:27.010787   474 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0326 16:50:27.115900   474 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
4
name: "dropout_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false

name: "cudnn_lstm_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 32
    }
  }
}
persistable: false

Traceback (most recent call last):
  File "./work/change.py", line 766, in <module>
    run_states = cls_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 884, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1077, in _run
    return_numpy=self.return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::operators::CudnnRNNCache::init(cudnnContext*, paddle::platform::Place const&, unsigned long, int, int, int, int, float, bool, int, int)
3   paddle::operators::CudnnLSTMGPUKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CudnnLSTMGPUKernel<float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1018, in lstm
    'seed': seed,
  File "./work/change.py", line 441, in _build_net
    cls_feats, last_h, last_c = fluid.layers.lstm(cls_feats, init_h, init_c, max_seq_len,n_hidden, num_layers,is_bidirec=True,seed=seed)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 401, in _build_env
    self.env.outputs = self._build_net()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 507, in main_program
    self._build_env()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 832, in load_checkpoint
    main_program=self.main_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 366, in init_if_necessary
    if not self.load_checkpoint():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 878, in finetune
    self.init_if_necessary()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "./work/change.py", line 766, in <module>
    run_states = cls_task.finetune_and_eval()

----------------------
Error Message Summary:
----------------------
Error: CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/cudnn_rnn_cache.h:173)
  [operator < cudnn_lstm > error]
```

**Comment by Steffy-zxf** [comment]
@wxl1351641822 hi，抱歉回复晚了。使用`dynamic_lstm`出现错误`Error: Size of target LoD should be greater than 1.`，这是因为ERNIE/BERT module输出`seq_output=outputs['sequence_output']`是一个padding之后的Tensor，而dynamic_lstm要求使用的是LodTensor。所以你需要先去paddling化，之后接入lstm网络。

你可以尝试自已定义一个Task，继承自SequenceLabelTask，并改写其中build_net()方法。下方代码示例写了一个BiLSTM+CRF的网络，我试过用我们的[序列标注demo](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/sequence_labeling/sequence_label.py)是可以正常运行的。代码如下：

记得在创建SequenceLabelTask_BiLSTMCRF对象时把add_crf打开。

```python
class SequenceLabelTask_BiLSTMCRF(SequenceLabelTask):
    def _build_net(self):
        self.seq_len = fluid.layers.data(
            name="seq_len", shape=[1], dtype='int64', lod_level=0)

        if version_compare(paddle.__version__, "1.6"):
            self.seq_len_used = fluid.layers.squeeze(self.seq_len, axes=[1])
        else:
            self.seq_len_used = self.seq_len

        if self.add_crf:
            # drop padding
            unpad_feature = fluid.layers.sequence_unpad(
                self.feature, length=self.seq_len_used)

            hid_dim = 128
            # bilstm layer
            fc0 = fluid.layers.fc(input=unpad_feature, size=hid_dim * 4)
            rfc0 = fluid.layers.fc(input=unpad_feature, size=hid_dim * 4)
            lstm_h, c = fluid.layers.dynamic_lstm(
                input=fc0, size=hid_dim * 4, is_reverse=False)
            rlstm_h, c = fluid.layers.dynamic_lstm(
                input=rfc0, size=hid_dim * 4, is_reverse=True)
            # concat layer
            lstm_concat = fluid.layers.concat(input=[lstm_h, rlstm_h], axis=1)

            self.emission = fluid.layers.fc(
                size=self.num_classes,
                input=lstm_concat,
                param_attr=fluid.ParamAttr(
                    initializer=fluid.initializer.Uniform(low=-0.1, high=0.1),
                    regularizer=fluid.regularizer.L2DecayRegularizer(
                        regularization_coeff=1e-4)))
            size = self.emission.shape[1]
            fluid.layers.create_parameter(
                shape=[size + 2, size], dtype=self.emission.dtype, name='crfw')
            self.ret_infers = fluid.layers.crf_decoding(
                input=self.emission, param_attr=fluid.ParamAttr(name='crfw'))
            ret_infers = fluid.layers.assign(self.ret_infers)
            return [ret_infers]
        else:
            self.logits = fluid.layers.fc(
                input=self.feature,
                size=self.num_classes,
                num_flatten_dims=2,
                param_attr=fluid.ParamAttr(
                    name="cls_seq_label_out_w",
                    initializer=fluid.initializer.TruncatedNormal(scale=0.02)),
                bias_attr=fluid.ParamAttr(
                    name="cls_seq_label_out_b",
                    initializer=fluid.initializer.Constant(0.)))

            self.ret_infers = fluid.layers.reshape(
                x=fluid.layers.argmax(self.logits, axis=2), shape=[-1, 1])

            logits = self.logits
            logits = fluid.layers.flatten(logits, axis=2)
            logits = fluid.layers.softmax(logits)
            self.num_labels = logits.shape[1]
            return [logits]
```

**Comment by wxl1351641822** [comment]
哦哦，我看见他了，我试试，谢谢。

**Comment by Masterkmp** [comment]
> 
> 
> 这是我想要实现的代码：
> 
> ```
> `import paddlehub as hub
> max_seq_len=128
> # dataset = MyDataset()
> module = hub.Module(name="bert_chinese_L-12_H-768_A-12")
> inputs, outputs, program = module.context(
> trainable=True, max_seq_len=max_seq_len)
> print(outputs)
> # Use "pooled_output" for classification tasks on an entire sentence.
> pooled_output = outputs["pooled_output"]
> seq_output=outputs['sequence_output']
> print(seq_output)
> hidden_units=[128]
> cls_feats = fluid.layers.dropout(
>             x=seq_output,
>             dropout_prob=0,
>             dropout_implementation="upscale_in_train")
> print(cls_feats)
> if hidden_units is not None:
>     for n_hidden in hidden_units:
>         # cls_feats = fluid.layers.fc(
>         #     input=cls_feats, size=n_hidden, act=None)
>         # print(cls_feats)
>         cls_feats = fluid.layers.fc(input=cls_feats, size=n_hidden,
>                     act=None, bias_attr=None)
>         print(cls_feats)
>         lstm_h, c = fluid.layers.dynamic_lstm(
>             input=cls_feats, size=n_hidden, is_reverse=False)
>         print(lstm_h)
>         # # 最大池化
>         lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
>         print(lstm_max)
>         # # 激活函数
>         cls_feats = fluid.layers.tanh(lstm_max)
>         print(cls_feats)
> 
> logits = fluid.layers.fc(
>     input=cls_feats,
>     size=3,
>     param_attr=fluid.ParamAttr(
>         name="cls_out_w",
>         initializer=fluid.initializer.TruncatedNormal(scale=0.02)),
>     bias_attr=fluid.ParamAttr(
>         name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
>     act="softmax")
> 
> ret_infers = fluid.layers.reshape(
>     x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])
> ----------------------
> Error Message Summary:
> ----------------------
> Error: Size of target LoD should be greater than 1.
>   [Hint: Expected level0.size() > 1UL, but received level0.size():1 <= 1UL:1.] at (/paddle/paddle/fluid/operators/lod_reset_op.h:60)
>   [operator < lod_reset > error]
> ```

你好，大佬，请问这个问题你解决了吗，能否请教下？
