### ISSUE TITLE
使用预训练模型ERNIE时，加入额外的特征训练，保存模型检查点时报错，说变量不在block中

### ISSUE THREAD

**Issue by MiloHang** [PaddlePaddle/PaddleFormers#481]
使用ERNIE预训练模型做文本分类，需要额外加入自己的特征，目前已经继承扩展了自己的Reader、Task、Dataset，可以正常开启训练，但是在训练保存检查点时报错。

**具体步骤**

1.在输入变量列表中加入了自己的特征，已经对应扩展了dataset、reader

```python
feed_list = [
    inputs["input_ids"].name,
    inputs["position_ids"].name,
    inputs["segment_ids"].name,
    inputs["input_mask"].name,
    "concept_ids"
]
```

2.自定义了Task的组网事件

```python
def _build_net(self):
    ...
    concept_ids = fluid.data(name='concept_ids', 
                             shape=[-1, self.max_concept_sequence_len, 1],
                             dtype='int64')
    ...
```

3.开启微调

```python
run_states = cls_task.finetune()
```

4.控制台输入

```
[2020-03-26 22:57:38,500] [    INFO] - PaddleHub finetune start
[2020-03-26 22:57:38,925] [    INFO] - Saving model checkpoint to ernie_tity_single_intent_cls\step_1
2020-03-26 22:57:39,450-WARNING: paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Traceback (most recent call last):
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-18576bfe9166>", line 1, in <module>
    runfile('D:/dev/projects/local/python/research/user-intent-classification/models/conco_ernie/single_intent/single_intent_conco_ernie_tiny.py', wdir='D:/dev/projects/local/python/research/user-intent-classification/models/conco_ernie/single_intent')
  File "D:\Application\PyCharm 2019.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Application\PyCharm 2019.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/dev/projects/local/python/research/user-intent-classification/models/conco_ernie/single_intent/single_intent_conco_ernie_tiny.py", line 118, in <module>
    run_states = cls_task.finetune()
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\paddlehub\finetune\task\base_task.py", line 784, in finetune
    self.save_checkpoint()
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\paddlehub\finetune\task\base_task.py", line 719, in save_checkpoint
    self.save_inference_model(dirname=model_saved_dir)
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\paddlehub\finetune\task\base_task.py", line 760, in save_inference_model
    params_filename=params_filename)
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 1189, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 988, in prepend_feed_ops
    out = global_block.var(name)
  File "D:\dev\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2263, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var concept_ids not in this block
```

经过跟踪发现是`framework.py`的`prepend_feed_ops`函数中去获取全局block的变量，发现`concept_ids`不存在，是不是在`build_net`事件中使用`fluid.data`定义的数据不在全局变量中呢？那么我该在哪里定义？

**Comment by MiloHang** [comment]
抱歉，是我的问题，追踪代码到`save_inference_model`中发现原来是feed的变量，在模型训练中要使用算子进行操作，并跟最后的`fetch_list`列表中的任一变量有一条计算链路，这样`Program`中的对应`Variable`才不会被模型剪枝掉，当我完成全部代码后和最后的输出关联上，就不会报错了，跟垃圾回收的对象引用链很类似，不错的设计，还是希望能在`Variable`文档中提醒说明一下就更好了，自己调试太耗时间了，不过对Paddle设计的理解进一步加深了。
