### ISSUE TITLE
win10 运行quickstart 案例报错 ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by liuzengzhen1** [PaddlePaddle/PaddleFormers#482]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.6.1，PaddlePaddle1.7.0
2）系统环境：win10，python版本 3.7.4
- 复现信息：
cmd 输入：
$ hub run lac --input_text "今天是个好日子"
[{'word': ['今天', '是', '个', '好日子'], 'tag': ['TIME', 'v', 'q', 'n']}]
报错提示：
`Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\hub.exe\__main__.py", line 5, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "c:\programdata\anaconda3\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "c:\programdata\anaconda3\lib\site-packages\paddlehub\module\module.py", line 29, in <module>
    import paddle.fluid as fluid
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\__init__.py", line 57, in <module>
    from . import contrib
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\contrib\__init__.py", line 27, in <module>
    from . import slim
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
    from .core import *
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
    from . import config
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
    from ..prune import *
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
    from . import prune_strategy
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
    from scipy.optimize import leastsq
  File "c:\programdata\anaconda3\lib\site-packages\scipy\optimize\__init__.py", line 391, in <module>
    from ._minimize import *
  File "c:\programdata\anaconda3\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "c:\programdata\anaconda3\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "c:\programdata\anaconda3\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "c:\programdata\anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .eigen import *
  File "c:\programdata\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "c:\programdata\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "c:\programdata\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: 找不到指定的程序。`
![图片](https://user-images.githubusercontent.com/52186737/77719159-91c31600-701f-11ea-9198-32f50e3ca565.png)

**Comment by Steffy-zxf** [comment]
你好！根据错误提示，你安装的scipy不正确，请卸载了重新安装scipy 1.2.1版本试试。

**Comment by liuzengzhen1** [comment]
@Steffy-zxf  之前的scipy 是1.3.1，按照你的方法卸载安装1.2.1版本后，已经不报错了哈，非常感谢，给你点赞
