### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by cheerser** [PaddlePaddle/PaddleFormers#491]
1）PaddleHub和PaddlePaddle版本：`PaddleHub1.6.1`，`PaddlePaddle1.7.1`
2）系统环境：ubuntu18.04, python3.7.3

出现方式：初次配置，先后pip安装了PaddlePaddle和PaddleHub。然后，命令行输入 `hub`，报出以下错误。hub 其他命令依旧。

Traceback (most recent call last):
  File "${ANACONDA_HOME}/bin/hub", line 6, in <module>
    from paddlehub.commands.hub import main
  File "${ANACONDA_HOME}/lib/python3.7/site-packages/paddlehub/commands/__init__.py", line 26, in <module>
    from . import config
  File "${ANACONDA_HOME}/lib/python3.7/site-packages/paddlehub/commands/config.py", line 30, in <module>
    HubServer()
  File "${ANACONDA_HOME}/lib/python3.7/site-packages/paddlehub/common/decorator_utils.py", line 24, in synced_func
    return func(*args, **kwargs)
  File "${ANACONDA_HOME}/lib/python3.7/site-packages/paddlehub/common/decorator_utils.py", line 35, in _get_instance
    _instance[cls] = cls(*args, **kwargs)
  File "${ANACONDA_HOME}/lib/python3.7/site-packages/paddlehub/common/hub_server.py", line 59, in __init__
    lock.flock(fp_lock, lock.LOCK_EX)
  File "${ANACONDA_HOME}/lib/python3.7/site-packages/paddlehub/common/lock.py", line 38, in flock
    self.lock.flock(fp, cmd)
OSError: [Errno 9] Bad file descriptor

（${ANACONDA_HOME}为anaconda的主目录）

**Comment by ShenYuhan** [comment]
您确认一下 ~/.paddlehub/conf/文件夹中是否有一个 config.json的文件，其中是否有内容？

**Comment by cheerser** [comment]
多谢百忙中回复，我找到问题了，HubServer会调用`fcntl.flock`函数对config.json文件加EX锁，而NFS中不能用该方法对read模式文件进行EX锁（参见 [flock](https://manpages.debian.org/buster/manpages-dev/flock.2.en.html)），是否可以改为`fcntl.fcntl`函数进行加锁？

**Comment by ShenYuhan** [comment]
实际上如果你不使用autofinetune这个功能，可以把lock改成空的，在/commom/lock.py中有一个空的lock类，可以直接用那个，没有关系

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by Vickzhang** [comment]
使用NFS时，在paddlehub 1.8版本中遇到类似问题；似乎在2.0版解决了
