### ISSUE TITLE
使用config.json启动hub serving方式报错

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/PaddleFormers#495]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by mcl-stone** [comment]
Traceback (most recent call last):
  File "commands/hub.py", line 74, in <module>
    command.execute(argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/serving.py", line 432, in execute
    self.start_serving()
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/serving.py", line 363, in start_serving
    self.start_app_with_file(configs, 1)
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/serving.py", line 232, in start_app_with_file
    module = [str(i["module"]) + "==" + str(i["version"]) for i in modules]
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/serving.py", line 232, in <listcomp>
    module = [str(i["module"]) + "==" + str(i["version"]) for i in modules]
TypeError: string indices must be integers

**Comment by mcl-stone** [comment]
{
  "modules_info": {
    "lac": {
      "init_args": {
        "version": "1.1.0"
      },
      "predict_args": {
        "batch_size": 1,
        "use_gpu": false
      }
    }
  },
  "port": 8866,
  "use_multiprocess": false,
  "workers": 1
}
使用的这个config，使用hub serving start --config config.json这个命令部署出上面错误

**Comment by mcl-stone** [comment]
hub serving start --modules  --use_gpu 使用这个命令可以执行，但没有使用gpu，很奇怪

**Comment by mcl-stone** [comment]
版本信息PaddlePaddle1.7 ubuntu18.04 python3.7

**Comment by mcl-stone** [comment]
卸载后安装了新版本没有报错问题了，但还是没有使用gpu，一直使用的cpu

**Comment by ShenYuhan** [comment]
您本机直接预测的话有用到gpu吗？另外需要对应的paddlepaddle-gpu版本安装了吗

**Comment by mcl-stone** [comment]
安装了paddlepaddle-gpu最新版，本机预测时使用高性能口罩模型等都使用到了gpu，但paddlehub serving部署时，加了参数也没有使用gpu

**Comment by ShenYuhan** [comment]
在新版的serving中，调用模型时传递的参数统一放到config.json文件了，所以您可以试一下在config。json文件中指定use_gpu字段

**Comment by mcl-stone** [comment]
> 在新版的serving中，调用模型时传递的参数统一放到config.json文件了，所以您可以试一下在config。json文件中指定use_gpu字段

我也测过了，并没有使用gpu，eeee

**Comment by mcl-stone** [comment]
请问还有使用gpu方案吗，除了hubserving部署方式，就是自己直接调用模型，使用gpu处理。

**Comment by mcl-stone** [comment]
使用hub serving start --config 显示内容如下，能够正常预测，但没有使用gpu，下面显示正常吗？
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(hub:5921): Gdk-CRITICAL **: 16:32:05.708: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Downloading yolov3_darknet53_coco2017
[==================================================] 100.00%
Uncompress /root/.paddlehub/tmp/tmp1af2u98u/yolov3_darknet53_coco2017
[==================================================] 100.00%
yolov3_darknet53_coco2017 == 1.0.0
 * Serving Flask app "paddlehub.serving.app_single" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-04-05 16:34:10,309-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
2020-04-05 16:34:20,833-INFO: 192.169.0.2 - - [05/Apr/2020 16:34:20] "GET / HTTP/1.1" 200 -
2020-04-05 16:34:21,058-INFO: 192.169.0.2 - - [05/Apr/2020 16:34:21] "POST /get/modules HTTP/1.1" 200 -
image with bbox drawed saved as /home/skyinfor/Documents/detection_result/1ffa2516e2456b28ec235367a955dc42_57b57b7a3cc1eca76aed30ebf22111b4.jpeg
2020-04-05 16:34:36,887-INFO: 192.169.0.2 - - [05/Apr/2020 16:34:36] "POST /predict/image/yolov3_darknet53_coco2017 HTTP/1.1" 200 -

**Comment by mcl-stone** [comment]
已解决，感谢
