### ISSUE TITLE
本地win10安装paddlehub不管用

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#505]
```
D:\ruanjian\Miniconda3\envs\paddle_env\python.exe F:/比赛/情感分析数据集/code/bert_seq_lstm.py
Traceback (most recent call last):
  File "F:/比赛/情感分析数据集/code/bert_seq_lstm.py", line 21, in <module>
    import paddlehub as hub
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\module\module.py", line 31, in <module>
    from paddlehub.common import utils
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\common\__init__.py", line 16, in <module>
    from . import utils
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\common\utils.py", line 33, in <module>
    from paddlehub.common.logger import logger
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ruanjian\Miniconda3\envs\paddle_env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
请问这个是什么情况？

**Comment by nepeplwu** [comment]
@wxl1351641822 试试将paddlehub升级到1.6.1版本看看

**Comment by wxl1351641822** [comment]
![image](https://user-images.githubusercontent.com/42665925/78851689-05681880-7a4d-11ea-9f85-87e22036116e.png)
这是我的版本

**Comment by wxl1351641822** [comment]
paddle-gpu1.7.0.post97,paddlehub1.6.1,numpy1.18.2,python3.7,paddle改成cpu也是一样的错误

**Comment by Steffy-zxf** [comment]
@wxl1351641822 你好，可以参考这个issue https://github.com/PaddlePaddle/PaddleHub/issues/462 当中的解决方法

**Comment by wxl1351641822** [comment]
额……请问他所说的.paddle文件夹在哪里？我用的conda，打开了隐藏文件显示，但在paddle的环境目录下没有发现它？它具体是在哪里呢？

**Comment by Steffy-zxf** [comment]
你好！不是.paddle文件夹，是.paddlehub文件夹下， #462 已经更正。.paddlehub文件夹默认生成在用户目录下。PaddleHub 支持修改HUB_HOME，参考 https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7

**Comment by wxl1351641822** [comment]
妥了，感谢
