### ISSUE TITLE
Error KeyError: 6  for set strategy to ULMFiTStrategy

### ISSUE THREAD

**Issue by yisampi** [PaddlePaddle/PaddleFormers#527]
CUDA_VISIBLE_DEVICES=1  python img_classifier-ULMFiTStrategy.py 
[2020-04-17 22:26:24,264] [    INFO] - Installing efficientnetb7_imagenet module
[2020-04-17 22:26:24,408] [    INFO] - Module efficientnetb7_imagenet already installed in /home/sam.yi/.paddlehub/modules/efficientnetb7_imagenet
[2020-04-17 22:26:26,045] [    INFO] - 1037 pretrained paramaters loaded by PaddleHub
[2020-04-17 22:26:26,180] [    INFO] - Dataset label map = {'normal': 0, 'recaptured': 1}
[2020-04-17 22:26:26,180] [    INFO] - Checkpoint dir: cv_finetune_turtorial_demo_ULMFiTStrategy
Traceback (most recent call last):
  File "img_classifier-ULMFiTStrategy.py", line 118, in <module>
    finetune(args)
  File "img_classifier-ULMFiTStrategy.py", line 108, in finetune
    task.finetune_and_eval()
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 864, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 879, in finetune
    self.init_if_necessary()
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 367, in init_if_necessary
    if not self.load_checkpoint():
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 833, in load_checkpoint
    main_program=self.main_program)
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 508, in main_program
    self._build_env()
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 425, in _build_env
    self.device_count)
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/strategy.py", line 477, in execute
    self.depth_params_dict = get_depth_parameter(self.main_program)
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/strategy.py", line 112, in get_depth_parameter
    updated_depth_params_dict[depth].append(
KeyError: 6

set strategy to ULMFiTStrategy

    strategy_ULMFiTStrategy = hub.ULMFiTStrategy(
    learning_rate=1e-4,
    optimizer_name="adam",
    cut_fraction=0.1,
        ratio=32,
        dis_blocks=3,
        factor=2.6,
        frz_blocks=3)

config = hub.RunConfig(
        use_data_parallel=args.use_data_parallel,
        use_cuda=args.use_gpu,
        num_epoch=args.num_epoch,
        batch_size=args.batch_size,
        checkpoint_dir=args.checkpoint_dir,
        strategy=strategy_ULMFiTStrategy)

set --modul to efficientnetb7

**Comment by kinghuin** [comment]
@yisampi Hi, 请问您使用的PaddleHub，Paddle是什么版本呢

**Comment by yisampi** [comment]
paddlehub                          1.6.1

**Comment by yisampi** [comment]
@kinghuin 请问有解决办法不？谢谢。

**Comment by kinghuin** [comment]
@yisampi 请暂时在 File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/finetune/strategy.py", line 104后追加2行代码修复这一问题
```python
for index, depth in enumerate(depth_list):
    在此处追加2行代码
    for param in depth_params_dict[depth]:
```
修改后：
```python
for index, depth in enumerate(depth_list):
    if depth not in updated_depth_params_dict:
        continue
    for param in depth_params_dict[depth]:
```

感谢您反馈的问题！

**Comment by yisampi** [comment]
谢谢

**Comment by yisampi** [comment]
@kinghuin 这个问题在新版本中还是没修复

**Comment by yisampi** [comment]
paddlehub          1.8.2
paddlepaddle-gpu   1.8.4.post107

**Comment by kinghuin** [comment]
现在已经合入修复代码了，下次发版将会生效，感谢反馈~
