### ISSUE TITLE
在本地运行口罩识别demo时出现错误

### ISSUE THREAD

**Issue by pomeloyou** [PaddlePaddle/PaddleFormers#528]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.61，PaddlePaddle-gpu1.7.1
2）系统环境：请您描述系统类型，Windows10，python3.6.8
- 复现信息：如为报错，请给出复现环境、复现步骤
报错信息：
[2020-04-18 17:05:34,287] [    INFO] - Installing pyramidbox_lite_server_mask module-1.2.0
[2020-04-18 17:05:34,309] [    INFO] - Module pyramidbox_lite_server_mask-1.2.0 already installed in C:\Users\pomelo\.paddlehub\modules\pyramidbox_lite_server_mask
[2020-04-18 17:05:34,438] [    INFO] - Installing pyramidbox_lite_server module
[2020-04-18 17:05:34,453] [    INFO] - Module pyramidbox_lite_server already installed in C:\Users\pomelo\.paddlehub\modules\pyramidbox_lite_server
{'image': ['D:/code/mask_dataset/image_mask/0023.jpg']}
[2020-04-18 17:05:34,684] [    INFO] - 133 pretrained paramaters loaded by PaddleHub
[2020-04-18 17:05:34,729] [    INFO] - 143 pretrained paramaters loaded by PaddleHub
Traceback (most recent call last):
  File "D:/code/demo2.py", line 22, in <module>
    results = module.face_detection(data=input_dict, use_multi_scale=True, shrink=0.6,)
  File "E:\python3.6.8\lib\site-packages\paddlehub\module\module.py", line 558, in __call__
    sign_name=sign_name, data_dict=data)
  File "C:\Users\pomelo\.paddlehub\modules\pyramidbox_lite_server_mask\python\cf911a04badc2b77bcb61d0819cb814d.py", line 220, in preprocess
    _results = self.face_detector.face_detection(data=data_dict, visualization=False, use_gpu=use_gpu, batch_size=batch_size, shrink=scale)
  File "E:\python3.6.8\lib\site-packages\paddlehub\module\module.py", line 558, in __call__
    sign_name=sign_name, data_dict=data)
  File "C:\Users\pomelo\.paddlehub\modules\pyramidbox_lite_server\python\86a38616afd048f03c7e50c42700a511.py", line 100, in preprocess
    data, height, width = process_image(orig_image, shrink)
  File "C:\Users\pomelo\.paddlehub\modules\pyramidbox_lite_server\python\86a38616afd048f03c7e50c42700a511.py", line 73, in process_image
    image = Image.fromarray(orig_image[:,:,::-1])
TypeError: 'NoneType' object is not subscriptable

**Comment by nepeplwu** [comment]
@pomeloyou ，从报错日志来看，应该是图片不存在导致的

**Comment by pomeloyou** [comment]
> @pomeloyou ，从报错日志来看，应该是图片不存在导致的
但是前面的代码是可以调用展示出图片的，虽然报错信息是TypeError
，但是pycharm提示的有face_detection的相关问题：Unresolved attribute reference 'face_detection' for class 'Module' 
`results = module.face_detection(data=input_dict, use_multi_scale=True, shrink=0.6,)`

**Comment by nepeplwu** [comment]
@pomeloyou pycharm的提示可以忽略，这个提示可能和face_detection这个方法是动态生成的有关。你的完整调用代码是否可以贴下？

**Comment by pomeloyou** [comment]
> @pomeloyou pycharm的提示可以忽略，这个提示可能和face_detection这个方法是动态生成的有关。你的完整调用代码是否可以贴下？
代码就是你们的demo的代码，直接复制下来的
```import paddlehub as hub

# 待预测图片
test_img_path = ["D:/code/mask_dataset/image_mask/0023.jpg"]

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread(test_img_path[0])

# 展示待预测图片
plt.figure(figsize=(10,10))
plt.imshow(img)
plt.axis('off')
plt.show()

#加载预训练模型
module = hub.Module(name='pyramidbox_lite_server_mask', version='1.2.0')
input_dict = {"image": test_img_path}
#print(input_dict)

# 口罩检测预测
results = module.face_detection(data=input_dict, use_multi_scale=True, shrink=0.6,)
for result in results:
    print(result)

# 预测结果展示
img = mpimg.imread("detection_result/test_mask_detection.jpg")
plt.figure(figsize=(10,10))
plt.imshow(img)
plt.axis('off')
plt.show()
```

**Comment by nepeplwu** [comment]
@pomeloyou 代码应该是ok的，你试试以下代码，是不是返回了None
```python
import cv2
img = cv2.imread('D:/code/mask_dataset/image_mask/0023.jpg')
print(img)
```

**Comment by pomeloyou** [comment]
> @pomeloyou 代码应该是ok的，你试试以下代码，是不是返回了None
> 
> ```python
> import cv2
> img = cv2.imread('D:/code/mask_dataset/image_mask/0023.jpg')
> print(img)
> ```

确实是，问题出在哪里呢，是本地环境的问题吗，还是库的问题呢

**Comment by nepeplwu** [comment]
一般这种情况就是图片不存在，你试试用PIL读取看看有没有什么错误
```python
from PIL import Image
Image.open('D:/code/mask_dataset/image_mask/0023.jpg')
```

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
