### ISSUE TITLE
（已经升级到paddlehub1.6.1）win10 导入paddlehub失败

### ISSUE THREAD

**Issue by daniao2017** [PaddlePaddle/PaddleFormers#541]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
`PaddleHub1.6.1，PaddlePaddle1.7.1`
2）系统环境：请您描述系统类型，
`Windows，Python 3.7.7+vscode+conda`
- 复现信息：如为报错，请给出复现环境、复现步骤

导入hub
 ```
import paddlehub as hub
module = hub.Module(name="ultra_light_fast_generic_face_detector_1mb_640")
```

报错

```
(paddle) C:\Users\28681\Desktop\vscode-python>D:/776/envs/paddle/python.exe c:/Users/28681/Desktop/vscode-python/百度/baidu.py
Traceback (most recent call last):
  File "c:/Users/28681/Desktop/vscode-python/百度/baidu.py", line 1, in <module>
    import paddlehub as hub
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\__init__.py", line 25, in <module>
    from . import module
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\module\module.py", line 31, in <module>
    from paddlehub.common import utils
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\common\__init__.py", line 16, in <module>
    from . import utils
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\common\utils.py", line 33, in <module>
    from paddlehub.common.logger import logger
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\common\logger.py", line 155, in <module>
    logger = Logger()
  File "D:\776\envs\paddle\lib\site-packages\paddlehub\common\logger.py", line 67, in __init__
    level = json.load(fp).get("log_level", "DEBUG")
  File "D:\776\envs\paddle\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\776\envs\paddle\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\776\envs\paddle\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\776\envs\paddle\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by daniao2017** [comment]
参考#505 没有更新后没有用啊
```
Name: paddlehub
Version: 1.6.1
Summary: A toolkit for managing pretrained models of PaddlePaddle and helping user getting started with transfer learning more efficiently.
Home-page: https://github.com/PaddlePaddle/PaddleHub
Author: PaddlePaddle Author
Author-email: paddle-dev@baidu.com
License: Apache 2.0
Location: d:\776\envs\paddle\lib\site-packages
Requires: cma, flask, chardet, sentencepiece, flake8, protobuf, six, yapf, tensorboard, opencv-python, nltk, requests, pre-commit, colorlog, pandas, numpy, pyyaml, tb-paddle, Pillow
Required-by:
```

**Comment by ShenYuhan** [comment]
您看下.paddlehub/conf/config.json这个文件是否存在，以及其中的内容是什么

**Comment by daniao2017** [comment]
参考#462
没有config.json这个文件啊

**Comment by daniao2017** [comment]
![666](https://user-images.githubusercontent.com/34906591/80168501-95918a80-8615-11ea-9121-cf11aa05f48a.png)

**Comment by ShenYuhan** [comment]
如果您没有改过hub_home这个变量的话，这个文件夹大概率在您的user目录下，您可以搜下 .paddlehub这个文件夹，这个不是安装目录哈

**Comment by daniao2017** [comment]
> 
> 
> 如果您没有改过hub_home这个变量的话，这个文件夹大概率在您的user目录下，您可以搜下 .paddlehub这个文件夹，这个不是安装目录哈

嗯嗯，感谢，已经找到了，原先在conda的目录下去找了。
找完后，参考#462已经解决。
