### ISSUE TITLE
UnboundLocalError: local variable 'results' referenced before assignment

### ISSUE THREAD

**Issue by linux-devil** [PaddlePaddle/PaddleFormers#605]
Linux

hub serving start --modules pyramidbox_lite_server_mask --port 9292 --use_gpu --use_multiproces

```
Traceback (most recent call last):
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 420, in predict_image
    results = predict_func(module_info, file_name_list, req_id, extra_info)
  File "/home/harshit/miniconda3/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 233, in predict_mask
    results_pack = results
UnboundLocalError: local variable 'results' referenced before assignment
2020-05-18 02:07:45,345-INFO: 127.0.0.1 - - [18/May/2020 02:07:45] "POST /predict/image/pyramidbox_lite_server_mask HTTP/1.1" 500 -

```

service gives 500 response 
paddlepaddle-gpu-1.8.0.post107

**Comment by ShenYuhan** [comment]
Hello, Please upgrade to the latest version via the followed command:
```shell
pip install paddlehub == 1.6.2
```

**Comment by linux-devil** [comment]
Requirement already satisfied: paddlehub==1.6.2 in /home/harshit/miniconda3/lib/python3.7/site-packages (1.6.2)

**Comment by linux-devil** [comment]
hub version
1.6.2

**Comment by linux-devil** [comment]
```
hub show pyramidbox_lite_server_mask

+-----------------+----------------------------------------------------+
|   ModuleName    |pyramidbox_lite_server_mask                         |
+-----------------+----------------------------------------------------+
|     Version     |1.1.0                                               |
+-----------------+----------------------------------------------------+
|     Summary     |PyramidBox-Lite-Server-Mask is a high-performance   |
|                 |face detection model used to detect whether people  |
|                 | wear masks.                                        |
+-----------------+----------------------------------------------------+
|     Author      |baidu-vis                                           |
+-----------------+----------------------------------------------------+
|  Author-Email   |UNKNOWN                                             |
+-----------------+----------------------------------------------------+
|    Location     |/home/harshit/.paddlehub/modules/pyramidbox_lite_s  |
|                 |erver_mask                                          |
```

**Comment by ShenYuhan** [comment]
Please upgrade your module 'pyramidbox_lite_server_mask' to v1.3.0
by use
```shell
hub install pyramidbox_lite_server_mask==1.3.0
```

**Comment by linux-devil** [comment]
Works , i needed to install pyramidbox_lite_server==1.2.0
