### ISSUE TITLE
chinese_ocr_db_rcnn 运行错误

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleFormers#625]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.7.0，PaddlePaddle1.8.1
2）系统环境：
Docker version 19.03.8, 基础镜像Ubuntu 18.04, Python 3.6.9
- 复现信息：如为报错，请给出复现环境、复现步骤
运行命令
hub run chinese_ocr_db_rcnn --input_path /program/img/02.png
报错为
2020-05-25 17:00:42,138-INFO: generated new fontManager
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/commands/run.py", line 242, in execute
    results = self.module.run_func(argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/paddlehub/module/module.py", line 59, in _wrapper
    return func(*args, **kwargs)
  File "/root/.paddlehub/modules/chinese_ocr_db_rcnn/module.py", line 374, in run_cmd
    results = self.recognize_texts(
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 533, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ChineseOCRDBRCNN' object has no attribute 'recognize_texts'

**Comment by liweigu** [comment]
是不是模型版本跟代码版本不一致？

**Comment by Steffy-zxf** [comment]
你好！试试将chinese_ocr_db_rcnn 和 chinese_text_detection_db module都先卸载，之后重新安装，还会不会有问题？
```shell
$ hub uninstall chinese_ocr_db_rcnn
$ hub uninstall chinese_text_detection_db
$
$ hub install chinese_ocr_db_rcnn
$ hub install chinese_text_detection_db
$
$ hub run chinese_ocr_db_rcnn  --input_path ***
```

**Comment by liweigu** [comment]
操作有效。
卸载后安装模型，然后还需要 pip3 install shapely pyclipper ，就能识别出文字了。

**Comment by liweigu** [comment]
注意是 crnn
hub uninstall chinese_ocr_db_rcnn && hub uninstall chinese_text_detection_db && hub install chinese_ocr_db_crnn && hub install chinese_text_detection_db
