### ISSUE TITLE
paddlehub模型不能运行

### ISSUE THREAD

**Issue by xianbinzhang** [PaddlePaddle/PaddleFormers#630]
问题：安装hub yolov3_darknet53_pedestrian 和yolov3_darknet53_vehicles 模型都不能正常运行
本机环境： win10  64位  显卡 GTX1660 Ti   PaddleHub1.7.0，PaddlePaddle1.8  GPU 版本 

错误提示：

PS F:\aiCode\paddlehubCode\vehicles> python ./vehicles.py
Traceback (most recent call last):
  File "./vehicles.py", line 4, in <module>
    vehicles_detector = hub.Module(name=yolov3_darknet53_vehicles)
NameError: name 'yolov3_darknet53_vehicles' is not defined
PS F:\aiCode\paddlehubCode\vehicles> hub install yolov3_darknet53_vehicles
Module yolov3_darknet53_vehicles already installed in C:\Users\Acer\.paddlehub\modules\yolov3_darknet53_vehicles
PS F:\aiCode\paddlehubCode\vehicles> hub run yolov3_darknet53_vehicles --input_path "F://1201.jpg"
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\run.py", line 242, in execute
    results = self.module.run_func(argv[1:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\module\module.py", line 59, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\Acer\.paddlehub\modules\yolov3_darknet53_vehicles\module.py", line 283, in run_cmd
    results = self.face_detection(
  File "d:\programdata\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 533, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'YOLOv3DarkNet53Vehicles' object has no attribute 'face_detection'
PS F:\aiCode\paddlehubCode\vehicles> hub install yolov3_darknet53_pedestrian==1.0.0
Downloading yolov3_darknet53_pedestrian
[==================================================] 100.00%
Uncompress C:\Users\Acer\.paddlehub\tmp\tmpyqe38e6v\yolov3_darknet53_pedestrian
[==================================================] 100.00%
Successfully installed yolov3_darknet53_pedestrian-1.0.0
PS F:\aiCode\paddlehubCode\vehicles> hub run yolov3_darknet53_pedestrian --input_path "F://1201.jpg"
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\commands\run.py", line 242, in execute
    results = self.module.run_func(argv[1:])
  File "d:\programdata\anaconda3\lib\site-packages\paddlehub\module\module.py", line 59, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\Acer\.paddlehub\modules\yolov3_darknet53_pedestrian\module.py", line 283, in run_cmd
    results = self.face_detection(
  File "d:\programdata\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 533, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'YOLOv3DarkNet53Pedestrian' object has no attribute 'face_detection'
PS F:\aiCode\paddlehubCode\vehicles>

**Comment by Steffy-zxf** [comment]
你好！命令行的方式运行确实有问题，请先使用python脚本的运行方式
如
```python
import paddlehub as hub
import cv2

vehicles_detector = hub.Module(name="yolov3_darknet53_vehicles")
result = vehicles_detector.object_detection(images=[cv2.imread('/PATH/TO/IMAGE')])
# or
# result = vehicles_detector.object_detection((paths=['/PATH/TO/IMAGE'])
```

**Comment by xianbinzhang** [comment]
脚本昨天也试了，也是不行，忘记复制错误信息了



---原始邮件---
发件人: "Steffy-zxf"<notifications@github.com&gt;
发送时间: 2020年5月27日(周三) 上午10:08
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送: "xianbinzhang"<314687187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleHub] paddlehub模型不能运行 (#630)




 
你好！命令行的方式运行确实有问题，请先使用python脚本的运行方式
 如
 import paddlehub as hub import cv2 vehicles_detector = hub.Module(name="yolov3_darknet53_vehicles") result = vehicles_detector.object_detection(images=[cv2.imread('/PATH/TO/IMAGE')]) # or # result = vehicles_detector.object_detection((paths=['/PATH/TO/IMAGE'])

**Comment by Steffy-zxf** [comment]
> PS F:\aiCode\paddlehubCode\vehicles> python ./vehicles.py
Traceback (most recent call last):
File "./vehicles.py", line 4, in
vehicles_detector = hub.Module(name=yolov3_darknet53_vehicles)

你调用 yolov3_darknet53_vehicles module代码不对，name是一个str类型

请仔细参考文档API用法，或者 上述我写的代码示例：
https://www.paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_vehicles&en_category=ObjectDetection

**Comment by xianbinzhang** [comment]
好的，我再试试，我直接复制文档底部代码，确实没仔细看



---原始邮件---
发件人: "Steffy-zxf"<notifications@github.com&gt;
发送时间: 2020年5月27日(周三) 上午10:16
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送: "xianbinzhang"<314687187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleHub] paddlehub模型不能运行 (#630)




  
PS F:\aiCode\paddlehubCode\vehicles&gt; python ./vehicles.py
 Traceback (most recent call last):
 File "./vehicles.py", line 4, in
 vehicles_detector = hub.Module(name=yolov3_darknet53_vehicles)
  
你调用 yolov3_darknet53_vehicles module代码不对，name是一个str类型
 
请仔细参考文档API用法，或者 上述我写的代码示例：
 https://www.paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_vehicles&amp;en_category=ObjectDetection

**Comment by nepeplwu** [comment]
@xianbinzhang 命令行无法运行的问题已经解决，通过以下命令进行升级module就可以解决
```shell
hub install yolov3_darknet53_pedestrian==1.0.1
hub install yolov3_darknet53_vehicles ==1.0.1
```

**Comment by xianbinzhang** [comment]
升级后已经能正常运行，谢谢解答
