### ISSUE TITLE
pycharm打包python报错

### ISSUE THREAD

**Issue by sherklock** [PaddlePaddle/PaddleFormers#655]
AttributeError: type object 'Path' has no attribute 'home'
49010 INFO:   Matplotlib backend "template": ignored
    Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "D:\anaconda3\envs\paddle\lib\site-packages\matplotlib\backends\__init__.py", line 8, in <module>
    from matplotlib.backend_bases import _Backend
  File "D:\anaconda3\envs\paddle\lib\site-packages\matplotlib\backend_bases.py", line 49, in <module>
    from matplotlib import (
  File "D:\anaconda3\envs\paddle\lib\site-packages\matplotlib\textpath.py", line 8, in <module>
    from matplotlib import cbook, dviread, font_manager, rcParams
  File "D:\anaconda3\envs\paddle\lib\site-packages\matplotlib\font_manager.py", line 103, in <module>
    os.path.join(str(Path.home()), r'AppData\Local\Microsoft\Windows\Fonts'),
AttributeError: type object 'Path' has no attribute 'home'
49010 INFO: Loading module hook "hook-matplotlib.py"...
49330 INFO: Loading module hook "hook-nltk.py"...
Unable to find "C:\Users\lenovo\nltk_data" when adding binary and data files.

**Comment by Steffy-zxf** [comment]
你好！上述代码没有看到有关PaddleHub的信息。请问你是将什么工具进行打包？能将背景信息详细说说吗？

**Comment by dengmingD** [comment]
我也遇到了同样的问题，pyinstaller打包的时候
