### ISSUE TITLE
能否提供一个客户端请求新版模型的方式的image版本？

### ISSUE THREAD

**Issue by cqzhao** [PaddlePaddle/PaddleFormers#675]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
Python版本
python3.7
框架版本
PaddlePaddle 1.7.1
根据[例子](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/serving.md)写了以下版本：
```
import requests
import json
from base64 import b64encode
ENCODING = 'utf-8'
def imagetojson(imagepath):
    with open(imagepath,'rb') as f:
        byte_content = f.read()
        base64_bytes = b64encode(byte_content)
        base64_string = base64_bytes.decode(ENCODING)
        return base64_string

files = [("image", imagetojson(item)) for item in [input_path]]
url = "http://127.0.0.1:8866/predict/image/ace2p"
headers = {"Content-Type": "application/json"}
data = {"image":imagetojson(input_path),"id":1}
r = requests.post(url=url, headers=headers,data=json.dumps(data))
```
结果还是说
```{"msg":{"Warnning":"This usage is out of date, please use \'application/json\' as content-type to post to /predict/ace2p. See \'https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md\' for more details."},"results":"","status":"-1"}\n'```

请问能否给一个demo，或者更新一下库中的相关demo，现有的都是旧版本的，不能用了

**Comment by cqzhao** [comment]
参考了PaddleHub文档提供的[代码](https://www.paddlepaddle.org.cn/hubdetail?name=human_pose_estimation_resnet50_mpii&en_category=KeyPointDetection) 
结果提示：
```
2020-06-08 10:10:22,358-ERROR: Exception on /predict/human_pose_estimation_resnet50_mpii [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```
请问是怎么回事？

**Comment by ShenYuhan** [comment]
您这个错误是请求端报的还是服务端报的呢，另外您的请求脚本和您参考的官网一致吗

**Comment by cqzhao** [comment]
这个错误是服务端报的，请求端收到的是500 Internal Error。
请求端代码有例子中一致，是复制过来的。

**Comment by ShenYuhan** [comment]
您用的paddlehub的版本是多少，用的模型的版本是多少，我这边复现一下

**Comment by cqzhao** [comment]
hub: 1.6.0
ace2p: 1.1.0

**Comment by ShenYuhan** [comment]
您好 我运行同样的代码没有问题，环境是 
paddlepaddle 1.7.1
paddlehub 1.6.0
ace2p 1.1.0

请求代码是
```python
import requests
import json
import cv2
import base64

import numpy as np


def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')


def base64_to_cv2(b64str):
    data = base64.b64decode(b64str.encode('utf8'))
    data = np.fromstring(data, np.uint8)
    data = cv2.imdecode(data, cv2.IMREAD_COLOR)
    return data


# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("./girl_mask2.jpg"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/ace2p"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(base64_to_cv2(r.json()["results"][0]['data']))
```
您是linux环境吗

**Comment by cqzhao** [comment]
不好意思。我试了一下ace2p是可以的。我的那个错误是human_pose_estimation_resnet50_mpii的1.1.0版本
启动：$ hub serving start -m human_pose_estimation_resnet50_mpii
请求代码：
```
# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("./work/input/pic/trump2.jpg"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/human_pose_estimation_resnet50_mpii"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])
```
返回的错误代码就是[这里显示的](https://github.com/PaddlePaddle/PaddleHub/issues/675#issuecomment-640324016)

我的环境是AiStudio。

**Comment by ShenYuhan** [comment]
您确定是在aistuidio上使用吗，AS应该无法对外开放端口部署服务，您是本机调用本机吗？

**Comment by cqzhao** [comment]
对。本机调用本机。部署和调用都是在AIStudio上的。我是想先测试一下，没问题再放到其他地方

**Comment by ShenYuhan** [comment]
这个模型的serving使用上存在bug，我们今天会修复

**Comment by cqzhao** [comment]
好的

**Comment by cqzhao** [comment]
是否修复？@ShenYuhan

**Comment by ShenYuhan** [comment]
您好，您可以使用新版的模型 human_pose_estimation_resnet50_mpii==1.1.1
新模型已经修复serving使用的问题

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
