### ISSUE TITLE
RuntimeError: resnet50_vd_10w does not support dynamic graph mode yet.

### ISSUE THREAD

**Issue by zachary-zheng** [PaddlePaddle/PaddleFormers#686]
I tried the demo:
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/image_classification/img_classifier_dygraph.py

But the result and Error as following:
```
E:\Python\Python37-64\python.exe "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/PaddleHub-release-v1.7/demo/image_classification/img_classifier_dygraph.py"
[2020-06-10 22:40:34,848] [    INFO] - Installing resnet50_vd_10w module
[2020-06-10 22:40:34,868] [    INFO] - Module resnet50_vd_10w already installed in C:\Users\admin\.paddlehub\modules\resnet50_vd_10w
[2020-06-10 22:40:34,871] [    INFO] - Dataset C:\Users\admin\.paddlehub\dataset\flower_photos already cached.
[2020-06-10 22:40:36,859] [    INFO] - Dataset label map = {'roses': 0, 'tulips': 1, 'daisy': 2, 'sunflowers': 3, 'dandelion': 4}
Traceback (most recent call last):
  File "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/PaddleHub-release-v1.7/demo/image_classification/img_classifier_dygraph.py", line 89, in <module>
    finetune(args)
  File "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/PaddleHub-release-v1.7/demo/image_classification/img_classifier_dygraph.py", line 66, in finetune
    pred = resnet(imgs)
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\dygraph\layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/PaddleHub-release-v1.7/demo/image_classification/img_classifier_dygraph.py", line 29, in forward
    feature_map = self.backbone(imgs)
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\dygraph\layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Python\Python37-64\lib\site-packages\paddlehub\module\module.py", line 254, in forward
    self.name))
RuntimeError: resnet50_vd_10w does not support dynamic graph mode yet.
W0610 22:40:34.892999  3416 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 50, Driver API Version: 11.0, Runtime API Version: 10.0
W0610 22:40:34.904000  3416 device_context.cc:260] device: 0, cuDNN Version: 7.6.

Process finished with exit code 1
```
I just cannot believe that "RuntimeError: resnet50_vd_10w does not support dynamic graph mode yet."
Would you please take a look at it and help me?
Appreciate it.

**Comment by Steffy-zxf** [comment]
Hi, resnet50_vd_10w module now only works on the static graph, rather than dynamic graph. Please run the demo: https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/image_classification/img_classifier.py

PaddleHub will works on dynamic graph as soon as possible.

**Comment by zachary-zheng** [comment]
Thanks for your support.
would you please share the list of classification models which support dynamic graph mode ?
Also looking forward to more models for dynamic graph on PaddleHub.

**Comment by zachary-zheng** [comment]
Hi, Guys
I just wanna try to run dygraph on PaddleHub for image classification finetuning, after replace "resnet50_vd_10w" with "resnet_v2_50_imagenet", another wrong raised:
E:\Python\Python37-64\python.exe "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/peach_class/paddle_hub_study_dygraph_baidu.py"
[2020-06-12 21:41:19,201] [    INFO] - Installing resnet_v2_50_imagenet module
[2020-06-12 21:41:19,222] [    INFO] - Module resnet_v2_50_imagenet already installed in C:\Users\admin\.paddlehub\modules\resnet_v2_50_imagenet
Traceback (most recent call last):
  File "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/peach_class/paddle_hub_study_dygraph_baidu.py", line 89, in <module>
    finetune(args)
  File "E:/Python/Pycharm/my work/AI_study/Learning_from_Github/04 paddlepaddle-learn/03 Paddle_hub/peach_class/paddle_hub_study_dygraph_baidu.py", line 37, in finetune
    resnet_v2_50_imagenet = hub.Module(name="resnet_v2_50_imagenet")
  File "E:\Python\Python37-64\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "E:\Python\Python37-64\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)
  File "E:\Python\Python37-64\lib\site-packages\paddlehub\module\module.py", line 186, in init_with_directory
    return ModuleV1(directory=directory, **kwargs)
  File "E:\Python\Python37-64\lib\site-packages\paddlehub\module\module.py", line 321, in __init__
    self.helper.model_path(), executor=exe)
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\io.py", line 1396, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\framework.py", line 4357, in parse_from_string
    p._sync_with_cpp()
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\framework.py", line 4557, in _sync_with_cpp
    block._sync_with_cpp()
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\framework.py", line 2730, in _sync_with_cpp
    op = Operator(self, op_desc)
  File "E:\Python\Python37-64\lib\site-packages\paddle\fluid\framework.py", line 1832, in __init__
    "`type` to initialized an Operator can not be None.")
ValueError: `type` to initialized an Operator can not be None.

Process finished with exit code 1

The following shows my code.
```
#coding:utf-8
import argparse
import os

import numpy as np
import paddlehub as hub
import paddle.fluid as fluid
from paddle.fluid.dygraph import Linear
from paddle.fluid.dygraph.base import to_variable
from paddle.fluid.optimizer import AdamOptimizer

# yapf: disable
parser = argparse.ArgumentParser(__doc__)
parser.add_argument("--num_epoch",          type=int,               default=1,                                  help="Number of epoches for fine-tuning.")
parser.add_argument("--checkpoint_dir",     type=str,               default="paddlehub_finetune_ckpt_dygraph",  help="Path to save log data.")
parser.add_argument("--batch_size",         type=int,               default=16,                                 help="Total examples' number in batch for training.")
parser.add_argument("--log_interval",       type=int,               default=10,                                 help="log interval.")
parser.add_argument("--save_interval",      type=int,               default=10,                                 help="save interval.")
# yapf: enable.


class ResNet50(fluid.dygraph.Layer):
    def __init__(self, num_classes, backbone):
        super(ResNet50, self).__init__()
        self.fc = Linear(input_dim=2048, output_dim=num_classes)
        self.backbone = backbone

    def forward(self, imgs):
        feature_map = self.backbone(imgs)
        feature_map = fluid.layers.reshape(feature_map, shape=[-1, 2048])
        pred = self.fc(feature_map)
        return fluid.layers.softmax(pred)


def finetune(args):
    with fluid.dygraph.guard():
        resnet_v2_50_imagenet = hub.Module(name="resnet_v2_50_imagenet")
        dataset = hub.dataset.Flowers()
        resnet = ResNet50(
            num_classes=dataset.num_labels, backbone=resnet_v2_50_imagenet)
        adam = AdamOptimizer(
            learning_rate=0.001, parameter_list=resnet.parameters())
        state_dict_path = os.path.join(args.checkpoint_dir,
                                       'dygraph_state_dict')
        if os.path.exists(state_dict_path + '.pdparams'):
            state_dict, _ = fluid.load_dygraph(state_dict_path)
            resnet.load_dict(state_dict)

        reader = hub.reader.ImageClassificationReader(
            image_width=resnet_v2_50_imagenet.get_expected_image_width(),
            image_height=resnet_v2_50_imagenet.get_expected_image_height(),
            images_mean=resnet_v2_50_imagenet.get_pretrained_images_mean(),
            images_std=resnet_v2_50_imagenet.get_pretrained_images_std(),
            dataset=dataset)
        train_reader = reader.data_generator(
            batch_size=args.batch_size, phase='train')

        loss_sum = acc_sum = cnt = 0
        # 执行epoch_num次训练
        for epoch in range(args.num_epoch):
            # 读取训练数据进行训练
            for batch_id, data in enumerate(train_reader()):
                imgs = np.array(data[0][0])
                labels = np.array(data[0][1])

                pred = resnet(imgs)
                acc = fluid.layers.accuracy(pred, to_variable(labels))
                loss = fluid.layers.cross_entropy(pred, to_variable(labels))
                avg_loss = fluid.layers.mean(loss)
                avg_loss.backward()
                # 参数更新
                adam.minimize(avg_loss)

                loss_sum += avg_loss.numpy() * imgs.shape[0]
                acc_sum += acc.numpy() * imgs.shape[0]
                cnt += imgs.shape[0]
                if batch_id % args.log_interval == 0:
                    print('epoch {}: loss {}, acc {}'.format(
                        epoch, loss_sum / cnt, acc_sum / cnt))
                    loss_sum = acc_sum = cnt = 0

                if batch_id % args.save_interval == 0:
                    state_dict = resnet.state_dict()
                    fluid.save_dygraph(state_dict, state_dict_path)


if __name__ == "__main__":
    args = parser.parse_args()
    finetune(args)


```
Would you please take a look at my code or share a demo of dygraph for finetuning for image classification ?
Thanks a lot.

**Comment by nepeplwu** [comment]
@zachary-zheng thanks for feedback，the image classification module on paddlehub does not currently support the dynamic graph mode, we will support this feature in a recent version.
