### ISSUE TITLE
服务端命令行启用报错

### ISSUE THREAD

**Issue by Li-rr** [PaddlePaddle/PaddleFormers#764]
版本环境信息：
paddleHub 1.7.1
paddlepaddle-gpu 1.8.2
win10
python3.7

报错信息：
(paddle) C:\Users\DD\Pictures> hub run chinese_ocr_db_crnn_server --input_path "test.png"
Traceback (most recent call last):
  File "c:\users\dd\.conda\envs\paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dd\.conda\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DD\.conda\envs\paddle\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\paddlehub\commands\run.py", line 242, in execute
    results = self.module.run_func(argv[1:])
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\paddlehub\module\module.py", line 59, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\DD\.paddlehub\modules\chinese_ocr_db_crnn_server\module.py", line 392, in run_cmd
    visualization=args.visualization)
  File "C:\Users\DD\.paddlehub\modules\chinese_ocr_db_crnn_server\module.py", line 195, in recognize_text
    images=predicted_data, use_gpu=self.use_gpu, box_thresh=box_thresh)
  File "C:\Users\DD\.paddlehub\modules\chinese_text_detection_db_server\module.py", line 168, in detect_text
    from chinese_text_detection_db_server.processor import DBPreProcess, DBPostProcess, draw_boxes, get_image_ext
  File "C:\Users\DD\.paddlehub\modules\chinese_text_detection_db_server\processor.py", line 9, in <module>
    from shapely.geometry import Polygon
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "c:\users\dd\.conda\envs\paddle\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "c:\users\dd\.conda\envs\paddle\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by Steffy-zxf** [comment]
你好！根据上述错误提示，应该是shapely安装的问题，可以参考这个issue 解决方法 https://github.com/PaddlePaddle/PaddleHub/issues/642

**Comment by Li-rr** [comment]
可以了，谢谢老哥
