### ISSUE TITLE
当metrics_choices=["f1"]时报错。

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleFormers#795]
paddle and paddlehub are v1.8.

Traceback (most recent call last):
  File "train.py", line 70, in <module>
    cls_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 945, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 966, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1224, in _run
    self._log_interval_event(period_run_states)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 708, in hook_function
    func(*args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 851, in _default_log_interval_event
    step=self._envs['train'].current_step)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/visualdl/writer/writer.py", line 135, in add_scalar
    scalar(tag=tag, value=value, step=step, walltime=walltime))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/visualdl/component/base_component.py", line 33, in scalar
    value = float(value)
TypeError: float() argument must be a string or a number, not 'tuple'

**Comment by Steffy-zxf** [comment]
Thanks for your feedback. I would prefer your task and code.

**Comment by ghost** [comment]
official text classification demo.

**Comment by Steffy-zxf** [comment]
@illcat Thanks for your feedback! If you wanna use f1-score as metric, you can do as following steps:
1. Find the location of paddlehub package
```shell
$ pip show paddlehub
```

2. Modify the code, ****/site-packages/paddlehub/finetune/task/classifier_task.py:
Please replace the 128 line `f1 = calculate_f1_np(all_infers, all_labels)`  with `f1 = calculate_f1_np(all_infers, all_labels)[2]`.

**Comment by ghost** [comment]
Hope it can be fixed in a later version.

**Comment by Steffy-zxf** [comment]
Yes. It will be fixed in the next version.
