### ISSUE TITLE
bert 客户端无法远程访问到server

### ISSUE THREAD

**Issue by rickyhuw** [PaddlePaddle/PaddleFormers#846]
使用127.0.0.1这个IP是可以访问的，切换到本机IP就无法访问了。
报错日志：
Traceback (most recent call last):
  File "1.py", line 6, in <module>
    bc = bs_client.BSClient(module_name="ernie_tiny", server="10.19.141.148:8866")
  File "/home/work/.local/lib/python3.6/site-packages/paddlehub/serving/bert_serving/bs_client.py", line 18, in __init__
    self.bs.add_server(server=server)
  File "/home/work/.local/lib/python3.6/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 76, in add_server
    self.check_server()
  File "/home/work/.local/lib/python3.6/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 88, in check_server
    client.connect((server_ip, server_port))
ConnectionRefusedError: [Errno 111] Connection refused

demo 代码：
# coding: utf8
from paddlehub.serving.bert_serving import bs_client

if __name__ == "__main__":
    # 初始化bert_service客户端BSClient
    bc = bs_client.BSClient(module_name="ernie_tiny", server="10.19.141.148:8866")

    # 输入要做embedding的文本
    # 文本格式为[["文本1"], ["文本2"], ]
    input_text = [
        ["西风吹老洞庭波"],
        ["一夜湘君白发多"],
        ["醉后不知天在水"],
        ["满船清梦压星河"],
    ]

    # BSClient.get_result()获取结果
    result = bc.get_result(input_text=input_text)

    # 打印输入文本的embedding结果
    for item in result:
        print(item)

**Comment by livingbody** [comment]
那你得监测防火墙端口开了没？能不能telnet通，排除下



---原始邮件---
发件人: "rickyhuw"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 下午4:19
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PaddlePaddle/PaddleHub] bert 客户端无法远程访问到server (#846)




 
使用127.0.0.1这个IP是可以访问的，切换到本机IP就无法访问了。
 报错日志：
 Traceback (most recent call last):
 File "1.py", line 6, in 
 bc = bs_client.BSClient(module_name="ernie_tiny", server="10.19.141.148:8866")
 File "/home/work/.local/lib/python3.6/site-packages/paddlehub/serving/bert_serving/bs_client.py", line 18, in init
 self.bs.add_server(server=server)
 File "/home/work/.local/lib/python3.6/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 76, in add_server
 self.check_server()
 File "/home/work/.local/lib/python3.6/site-packages/paddlehub/serving/bert_serving/bert_service.py", line 88, in check_server
 client.connect((server_ip, server_port))
 ConnectionRefusedError: [Errno 111] Connection refused
 
demo 代码：
 
coding: utf8
 
from paddlehub.serving.bert_serving import bs_client
 
if name == "main":
 # 初始化bert_service客户端BSClient
 bc = bs_client.BSClient(module_name="ernie_tiny", server="10.19.141.148:8866")
 # 输入要做embedding的文本 # 文本格式为[["文本1"], ["文本2"], ] input_text = [     ["西风吹老洞庭波"],     ["一夜湘君白发多"],     ["醉后不知天在水"],     ["满船清梦压星河"], ] # BSClient.get_result()获取结果 result = bc.get_result(input_text=input_text) # 打印输入文本的embedding结果 for item in result:     print(item)

**Comment by rickyhuw** [comment]
我用netstat -tunlp 查看了监听接口，发现这个服务只是监听了127.0.0.1，所以没有办法通过本机IP访问，那这个配置在哪里修改呢？
![image](https://user-images.githubusercontent.com/38985786/91152559-b0722980-e6f1-11ea-8a1d-43286c90da76.png)

**Comment by ShenYuhan** [comment]
在启动的时候增加参数 `--host XX.XX.XX.XXX`

**Comment by rickyhuw** [comment]
是我的版本问题吗？，提示没有host这个参数，希望得到您的解答，谢谢。
![image](https://user-images.githubusercontent.com/38985786/91249678-eb27a080-e789-11ea-9776-7671c146becd.png)
![image](https://user-images.githubusercontent.com/38985786/91249782-1e6a2f80-e78a-11ea-85c0-45e6fce149ee.png)

**Comment by ultimatedaotu** [comment]
兄弟你解决了没有哇  ubuntu18.04  按照教程客户端访问不了 报错list index out of range  浏览器可以访问

**Comment by rickyhuw** [comment]
> 兄弟你解决了没有哇 ubuntu18.04 按照教程客户端访问不了 报错list index out of range 浏览器可以访问

没有解决，是他服务监听的问题，而且服务并没有提供相应的参数配置监听

**Comment by MRXLT** [comment]
不好意思，这个问题我们会尽快修复，可以先通过修改 $PYTHONROOT/lib/python3.6/site-packages/paddle_gpu_serving/run/__init__.py中的监听地址实现跨机器访问
![image](https://user-images.githubusercontent.com/16594411/92432060-b2e18280-f1cb-11ea-9761-5ea7ff9d14dd.png)

**Comment by bigpo** [comment]
> 不好意思，这个问题我们会尽快修复，可以先通过修改 $PYTHONROOT/lib/python3.6/site-packages/paddle_gpu_serving/run/**init**.py中的监听地址实现跨机器访问
> ![image](https://user-images.githubusercontent.com/16594411/92432060-b2e18280-f1cb-11ea-9761-5ea7ff9d14dd.png)

请问现在修复了吗？现在还是会遇到list index out of range的错误

**Comment by rickyhuw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已被接受，我将尽快回复您！
