### ISSUE TITLE
文本匹配Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xiaotaiyangsun** [PaddlePaddle/PaddleFormers#856]
PaddlePaddle 1.8.0/paddlehub 1.8.0
**aistudio运行**
!cd PaddleHub-release-v1.8/demo/pointwise_text_matching/ && sh run_ernie_pointwise_matching_predict.sh
**报错**
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Segmentation fault (core dumped)

**Comment by Steffy-zxf** [comment]
你好！文本匹配任务参考[教程](https://aistudio.baidu.com/aistudio/projectdetail/705526)：https://aistudio.baidu.com/aistudio/projectdetail/705526

**Comment by xiaotaiyangsun** [comment]
> 你好！文本匹配任务参考[教程](https://aistudio.baidu.com/aistudio/projectdetail/705526)：https://aistudio.baidu.com/aistudio/projectdetail/705526

您好，您给的链接之前尝试过不会报错，将paddlehub 更新到1.8.0会出现如上错误

**Comment by Steffy-zxf** [comment]
请更新paddlehub至最新版本

```shell
pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by xiaotaiyangsun** [comment]
> l



> 请更新paddlehub至最新版本
> 
> ```shell
> pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple
> ```

**Comment by xiaotaiyangsun** [comment]
> 请更新paddlehub至最新版本
> 
> ```shell
> pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple
> ```
您好，已安装1.8.2版本，用run_ernie_pointwise_matching.sh训练了一个epoch1的模型。运行如下命令，
!cd PaddleHub-release-v1.8/demo/pointwise_text_matching/ && sh run_ernie_pointwise_matching_predict.sh
**报错**
[2020-08-31 14:13:05,114] [    INFO] - Checkpoint dir: ./ckpt_ernie_pointwise_matching_epoch1
[2020-08-31 14:13:05,481] [    INFO] - PaddleHub predict start
[2020-08-31 14:13:05,481] [    INFO] - Load the best model from ./ckpt_ernie_pointwise_matching_epoch1/best_model
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Traceback (most recent call last):
  File "ernie_pointwise_matching_predict.py", line 92, in <module>
    accelerate_mode=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/matching_task.py", line 739, in predict
    self.init_if_load_best_model()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 395, in init_if_load_best_model
    self.load_parameters(best_model_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 924, in load_parameters
    self.exe, dirname, self.main_program, predicate=if_exist)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 819, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((2304, 2)), while the loaded parameter (namely [ matching_out_w ]) has a shape of  ((196608, 2)).
