### ISSUE TITLE
模型保存失败……

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#892]
除了输入数据改了，其他没有动，但它保存不了？？？paddlehub1.8.0，paddle1.7.2
```
Traceback (most recent call last):
  File "paddlehub_mrcrelation.py", line 136, in <module>
    testone(id)
  File "paddlehub_mrcrelation.py", line 94, in testone
    id=cross_validation(args, id)
  File "paddlehub_mrcrelation.py", line 110, in cross_validation
    one(args, schema_labels, predict_data, predict_sents, str(id))
  File "paddlehub_mrcrelation.py", line 26, in one
    seq_label_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 945, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 966, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1232, in _run
    self._eval_interval_event()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 708, in hook_function
    func(*args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 861, in _default_eval_interval_event
    self.eval(phase="dev")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1011, in eval
    self._eval_end_event(run_states)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 708, in hook_function
    func(*args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 832, in _default_eval_end_event
    self.save_inference_model(dirname=model_saved_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 942, in save_inference_model
    params_filename=params_filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1217, in save_inference_model
    feeded_var_names=feeded_var_names, targets=target_vars)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4122, in _prune_with_input
    "The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.
```

**Comment by Steffy-zxf** [comment]
你好！请升级paddle至 1.8.0以上版本。paddle安装指南：https://www.paddlepaddle.org.cn/install/quick

**Comment by Steffy-zxf** [comment]
你好好，此issue在近两月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
