### ISSUE TITLE
关于paddlehub可视化

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/PaddleFormers#910]
在使用paddlehub和可视化的时候**请问怎么样才能看到训练集的曲线和验证集的指标对比曲线都在一个图里呢**，hub默认的通过可视化打开log文件只有验证集的曲线。

**Comment by Steffy-zxf** [comment]
你好！关于训练过程效果可视化，可以参考相应demo的可视化说明。例如文本分类任务可视化说明：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/demo/text_classification#%E5%8F%AF%E8%A7%86%E5%8C%96

**Comment by Masterkmp** [comment]
> 
> 
> 你好！关于训练过程效果可视化，可以参考相应demo的可视化说明。例如文本分类任务可视化说明：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/demo/text_classification#%E5%8F%AF%E8%A7%86%E5%8C%96
**### 你好我按照文档运行了指令，报错了。结果如下：**
aistudio@jupyter-116545-931725:~$ visualdl --logdir $CKPT_DIR/visualization --host ${HOST_IP} --port ${PORT_NUM}usage: visualdl [-h] [--logdir LOGDIR [LOGDIR ...]] [-p PORT] [-t HOST] [--model MODEL]
                [--cache_timeout CACHE_TIMEOUT] [-L LANGUAGE] [-P PUBLIC_PATH] [-A]
**visualdl: error: argument -t/--host: expected one argument**

**Comment by Steffy-zxf** [comment]
你好！选项参数host 需要更换成运行程序的机器ip地址。

**Comment by Masterkmp** [comment]
> 
> 
> 你好！选项参数host 需要更换成运行程序的机器ip地址。

你好，还是报错。
`aistudio@jupyter-116545-931725:~$ visualdl --logdir $CKPT_DIR/visualization --host 219.216.65.116 --port 49675
[INFO 2020-09-21 12:18:48,667 app.py:141]  port=49675
 * Serving Flask app "visualdl" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/visualdl", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/visualdl/server/app.py", line 143, in main
    app.run(debug=False, host=args.host, port=args.port, threaded=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/werkzeug/serving.py", line 963, in inner
    fd=fd,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/werkzeug/serving.py", line 821, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/werkzeug/serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address`

**Comment by ShenYuhan** [comment]
aistudio与本地，在使用visualdl的方式上有些差别，您可以看下在aistudio上使用visualdl的文档
https://ai.baidu.com/forum/topic/show/960053

**Comment by Masterkmp** [comment]
> 
> 
> aistudio与本地，在使用visualdl的方式上有些差别，您可以看下在aistudio上使用visualdl的文档
> https://ai.baidu.com/forum/topic/show/960053

好的，谢谢解答

**Comment by dickobe** [comment]
> 你好！选项参数host 需要更换成运行程序的机器ip地址。


在linux下怎么看呢？

**Comment by EricJoung1997** [comment]
我用的命令是 'visualdl --logdir $CKPT_DIR/visualization --host localhost --port 2222' ，没有报错，但是浏览器localhost拒绝访问，请问什么原因？

**Comment by ShenYuhan** [comment]
您是本机启动，本机查看吗，可以试一下把localhost改成 0.0.0.0

**Comment by EricJoung1997** [comment]
> 您是本机启动，本机查看吗，可以试一下把localhost改成 0.0.0.0
我是在AIstudio上运行的，ip地址和端口需要改变吗？改成 0.0.0.0还是无法访问
