### ISSUE TITLE
predict，最多只能识别8个图片，多了会暴显存

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleFormers#937]
hub:1.82
code:
images = [cv2.imread(image_path) for image_path in test_image]
#就是下面这行代码报错
result = ocr.recognize_text(images=images,use_gpu=True,
                            output_dir='ocr_result',
                            visualization=True
                            # box_thresh=0.5,
                            # text_thresh=0.5
                            )
error:
[2020-09-30 15:49:30,097] [    INFO] - Installing chinese_ocr_db_crnn_server module
[2020-09-30 15:49:30,176] [    INFO] - Module chinese_ocr_db_crnn_server already installed in C:\Users\1\.paddlehub\modules\chinese_ocr_db_crnn_server
[2020-09-30 15:49:31,412] [    INFO] - Installing chinese_text_detection_db_server module-1.0.2
[2020-09-30 15:49:31,413] [    INFO] - Module chinese_text_detection_db_server-1.0.2 already installed in C:\Users\1\.paddlehub\modules\chinese_text_detection_db_server
Traceback (most recent call last):
  File "D:/project/new1/paddle/ocr_text.py", line 32, in <module>
    visualization=True
  File "C:\Users\1\.paddlehub\modules\chinese_ocr_db_crnn_server\module.py", line 271, in recognize_text
    rec_results = self._recognize_text(img_crop_list)
  File "C:\Users\1\.paddlehub\modules\chinese_ocr_db_crnn_server\module.py", line 407, in _recognize_text
    self.rec_predictor.zero_copy_run()
RuntimeError: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 183.047119MB memory on GPU 0, available memory is only 139.662499MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (D:\1.8.5\paddle\paddle\fluid\memory\allocation\cuda_allocator.cc:69)

gpu:2070 super
cpu:10700k
显存没有一直被占用

**Comment by LDOUBLEV** [comment]
参考： https://github.com/PaddlePaddle/PaddleHub/issues/682
paddle 2.0 版本会修复

**Comment by FD-Liekkas** [comment]
> 参考： #682
> paddle 2.0 版本会修复

您好，请问这个问题在paddle 2.0.0b0版本修复了吗？我在版本更新日志中没看到相关说明，还是说只有2.0正式版才会修复？麻烦您解答一下

**Comment by liweigu** [comment]
在 chinese_ocr_db_crnn_server 1.1.1 （paddlepaddle-gpu==2.0.0rc1.post110） 上测试还未解决。

**Comment by FD-Liekkas** [comment]
> 在 chinese_ocr_db_crnn_server 1.1.1 （paddlepaddle-gpu==2.0.0rc1.post110） 上测试还未解决。

我在python3.7.9+paddlepaddle-gpu==2.0.0rc1.post100-cp37上跑通了，没出现显存问题了

**Comment by SilenceBlue** [comment]
> > 在 chinese_ocr_db_crnn_server 1.1.1 （paddlepaddle-gpu==2.0.0rc1.post110） 上测试还未解决。
> 
> 我在python3.7.9+paddlepaddle-gpu==2.0.0rc1.post100-cp37上跑通了，没出现显存问题了

paddlepaddle==2.0.0rc1上测试还未解决
