### ISSUE TITLE
paddlehub安装成功之后，hub命令运行 一直等待状态

### ISSUE THREAD

**Issue by colinTmx** [PaddlePaddle/PaddleFormers#991]
环境redhat7，局域网（无法连接外网）

pip show paddlehub 结果如下：
Name: paddlehub
Version: 1.8.2
Summary: A toolkit for managing pretrained models of PaddlePaddle and helping user getting started with transfer learning more efficiently.
Home-page: https://github.com/PaddlePaddle/PaddleHub
Author: PaddlePaddle Author
Author-email: paddle-dev@baidu.com
License: Apache 2.0
Location: /qhapp/anaconda3/lib/python3.7/site-packages
Requires: pre-commit, colorlog, six, pandas, gunicorn, yapf, flake8, flask, tqdm, cma, nltk, visualdl, sentencepiece, protobuf
Required-by: 

但是 hub 的命令一直处于等待状态

hub version Crtl+c之后输出如下：

hub version
^CTraceback (most recent call last):
  File "/qhapp/anaconda3/bin/hub", line 5, in <module>
    from paddlehub.commands.hub import main
  File "/qhapp/anaconda3/lib/python3.7/site-packages/paddlehub/commands/__init__.py", line 26, in <module>
    from . import config
  File "/qhapp/anaconda3/lib/python3.7/site-packages/paddlehub/commands/config.py", line 30, in <module>
    HubServer()
  File "/qhapp/anaconda3/lib/python3.7/site-packages/paddlehub/common/decorator_utils.py", line 24, in synced_func
    return func(*args, **kwargs)
  File "/qhapp/anaconda3/lib/python3.7/site-packages/paddlehub/common/decorator_utils.py", line 35, in _get_instance
    _instance[cls] = cls(*args, **kwargs)
  File "/qhapp/anaconda3/lib/python3.7/site-packages/paddlehub/common/hub_server.py", line 60, in __init__
    lock.flock(fp_lock, lock.LOCK_EX)
  File "/qhapp/anaconda3/lib/python3.7/site-packages/paddlehub/common/lock.py", line 38, in flock
    self.lock.flock(fp, cmd)
KeyboardInterrupt

**Comment by haoyuying** [comment]
出现这个问题时候试下这个命令看看 rm ~/.paddlehub/conf/config.json
