### ISSUE TITLE
No such file or directory: 'model/my_model/round9/model-0/'

### ISSUE THREAD

**Issue by JKwanghao** [PaddlePaddle/PaddleFormers#999]
测试run_autofinetune.sh的时候，前面都能成功，到了后面就报这个错误，有人知道是啥问题么？
The final best eval score is 0.0.
The final best model parameters are saved as model/my_model/best_model .
Traceback (most recent call last):
  File "/root/miniconda3/envs/py37/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/paddlehub/commands/autofinetune.py", line 210, in execute
    shutil.copytree(best_hparams_dir, best_model_dir)
  File "/root/miniconda3/envs/py37/lib/python3.7/shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'model/my_model/round9/model-0/'

**Comment by haoyuying** [comment]
model/my_model/round9/model-0/ 这个路径不存在，是不是模型地址给错了，具体是哪个模型出现了这个问题呢？
